### ISSUE TITLE
Implement DiscreteLp with p != 2

### ISSUE THREAD

**Issue by odlgroup** [odlgroup/odl#1]
Beside the pure implementation, we need to review one design decision, namely where the discrete space functions are specified. Currently, this is completely done in the data space `Fn` by adding a weight to the inner product, norm and dist.
If we decide to keep it that way, we must add an `exponent` parameter to the weighting classes, and for `p != 2`, things become slightly more complicated:

- `inner` must be disabled
- `norm` must be re-implemented, e.g. in the matrix-weighted case, the matrix power `M^(1/p)` has to be (pre-)computed since the weighted norm is `|||x|||_p = ||M^(1/p)x||_p`. Probably this is not feasible for larger problems, we'll see. For vector- and constant-weighted spaces, it's easy though.

**Comment by Berzerka** [comment]
My suggestion is that we only support `norm` in the diagonal/constant case to begin with.

**Comment by Berzerka** [comment]
Further, the parameter should be called `ord` as in "order", since that is what [numpy does](http://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.norm.html).

**Comment by kohr-h** [comment]
I've never been happy with `ord` since it's the name of a [built-in function of the standard library](https://docs.python.org/3/library/functions.html#ord). This is one of the worse NumPy choices, even the longer term "order" is at least debatable, and I suggest that we consider not following it.

**Comment by adler-j** [comment]
If we decide to disallow it we need to fix this in [pspace](https://github.com/odlgroup/odl/blob/838d21f99d89ae4612e95ec52a33f567bda7b5e6/odl/set/pspace.py#L87-L92) and also in [domain](https://github.com/odlgroup/odl/blob/b6574a6496d3234a0c69a1f6120eb7664a7505ba/odl/set/domain.py#L273)
