### ISSUE TITLE
Add possibility to refresh same figure in DiscreteLp.Vector.show

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#10]
Currently the following gives you 50 figures:

```python
for i in range(50):
    #do stuff
    x.show()
```

a syntax like

```python
fig=None
for i in range(50):
    #do stuff
    fig=x.show(figure=fig)
```

or possibly something better, would be very nice.

**Comment by kohr-h** [comment]
I'll see what I can do. However, `matplotlib` has its quirks, not trivial to get this running smoothly.

**Comment by adler-j** [comment]
Don't waste to much time on it then, we can wait.

**Comment by moosmann** [comment]
The only thing that worked for me to refresh a figure was to use `matplotlib.pyplot.pause` instead of `matplotlib.pyplot.show`. However, it's an experimental function and probably won't work for all backends.
