### ISSUE TITLE
Make matplotlib an optional dependency

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#101]
It's minor, but keeping dependencies at a minimum is always good. I say we make it optional, with a check when it is imported in `graphics.py`.

**Comment by kohr-h** [comment]
Believe it or not, I had the same thought when I saw how nicely encapsulated the dependency now is.

We can also think of trying other backends, one quite promising is [GR](http://gr-framework.org/).

**Comment by adler-j** [comment]
Decent idea, but we should probably have matplotlib as the default, simply because most people have it installed. Perhaps allow some global option to change.
