### ISSUE TITLE
Make show(indices=something) behave like show(coords=something)

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#1015]
The `coords` argument to the `show` mehtod of discrete function space elements accepts `coords=[None, None, 1]`, but when using `indices` one still has to use the inconvenient `indices=[np.s_[:], np.s_[:], 1]` or `indices=[slice(None), slice(None), 1]` explicitly.
We should harmonize those two arguments.

**Comment by adler-j** [comment]
A big part of the reason is that one can also use `indices=np.s_[:, :, 1]` which hardly makes sense for coordinates (since slices only work on integers). So we would need to harmonize with that in mind as well.

**Comment by kohr-h** [comment]
Yes, that's true. My suggestion would be to just translate `None` to `slice(None)` in the `indices` case, which would do the trick. The original meaning of `None` in Numpy slicing, namely `newaxis`, wouldn't make any sense anyway.

**Comment by adler-j** [comment]
Agree with your comment, please go ahead
