### ISSUE TITLE
Add Figure Of Merits

### ISSUE THREAD

**Issue by zickert** [odlgroup/odl#1017]
Add implementation of figure of merits to quantitatively compare reconstructions with known ground truth. Separate branch with corresponding pull request in preparation.

**Comment by adler-j** [comment]
A general comment is that if we make a `odl.contrib.fom` package (which i think we should) then there are some sub-modules that should be kept separate (in my opinion). Some suggested such sub-modules would be (names are obviously preliminary):

* `unsupervised`: FOMs of the form `fom(reconstruction)` attempting to estimate features from a single image.
* `supervised`: FOMs of the form `fom(reconstruction, true)` computing some generalized distance
* `ensamble`: FOMs of the form `fom(reconstruction1, reconstruction2, ..., reconstructionn, [true])` computing some kind of batch statistic (e.g. noise sensitivity, etc)

**Comment by adler-j** [comment]
I was thinking about this when implementing some other stuff and I realized that there are some features that would be nice to have. These do NOT need to be implemented in the PR, but should be added shortly after.

* More FOM, in particular we want "signal to noise ratio" (SNR) and "peak signal to noise ratio" (PSNR)
* Utilities to normalize values, either as a parameter to the FOMs (e.g. normalization=...) or by external functions. Examples include [z-scores](https://docs.scipy.org/doc/scipy-0.18.1/reference/generated/scipy.stats.zscore.html) and rescaling into [0, 1].
* Unsupervised FOMs, in particular some type of noise estimation similar to [this one](https://github.com/odlgroup/odl/pull/972/files#diff-2802eb089e5c95578ebafe78e56ac907R107)

Anyway, would be great to get the main skeleton in so we can start building on top of it.

**Comment by adler-j** [comment]
Closed by #1018
