### ISSUE TITLE
Disallow broadcasting NTuples.element

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#103]
We currently allow this:

```python
>>> Rn(3).element(5)
Rn.element([5.0, 5.0, 5.0])
```

I suggest we disallow this (throw an error). If users want it they can do as they would in numpy:

```python
>>> Rn(3).one() * 5
Rn.element([5.0, 5.0, 5.0])
```

The reason is that this looks somewhat confusing (at least to me) and does not follow the numpy convention.

**Comment by kohr-h** [comment]
I agree, this is related to #100, where we end up with allowing `op(1)` to be interpreted as `op(op.domain.element(1))` which goes too far in my opinion. Better to be explicit.
