### ISSUE TITLE
Text phantom default font not available on all platforms

### ISSUE THREAD

**Issue by aringh** [odlgroup/odl#1037]
I get the following error using the text phantom (example taken from the PR #1009):
```python
import odl
space = odl.uniform_discr([-1, -1], [1, 1], [300, 300])
for font in ['arial', 'impact', 'calibri']: 
    odl.phantom.text(space, text='ODL', font=font).show(font)
```
```
Traceback (most recent call last):

  File "<ipython-input-1-b05f19fad3e2>", line 4, in <module>
    odl.phantom.text(space, text='ODL', font=font).show(font)

  File "/home/aringh/git/odl/odl/phantom/misc_phantoms.py", line 207, in text
    encoding="unic")

  File "/home/aringh/miniconda3/envs/odl-py35/lib/python3.5/site-packages/PIL/ImageFont.py", line 238, in truetype
    return FreeTypeFont(font, size, index, encoding)

  File "/home/aringh/miniconda3/envs/odl-py35/lib/python3.5/site-packages/PIL/ImageFont.py", line 127, in __init__
    self.font = core.getfont(font, size, index, encoding)

OSError: cannot open resource
```

I am running almost the newest version of `odl`, and I have `pillow: 4.1.1-py35_0` installed. Am I doing something wrong?

**Comment by aringh** [comment]
The error seems to be that `arial` was in fact not installed as a font. For anyone else how might encounter this problem later: it seems like `PIL`/`pillow` gets the fonts from `/usr/share/fonts/truetype`, and the font you specify need to have the exact same name as a `.tff` file in one of the subfolders.

**Comment by adler-j** [comment]
Well, if possible we should settle on a default font that everyone can degree on. Can you see what default fonts you had installed?

**Comment by aringh** [comment]
I am jumping back and forth between different computers... but on Tikhonov in the office we have [the following fonts](https://user-images.githubusercontent.com/15774494/27273996-c8fddd88-54d1-11e7-8c0b-3f654e574149.png). However, most folders contains a number of fonts, and I think that you really need to use the font name with the [same name as the `ttf` file](https://github.com/odlgroup/odl/blob/master/odl/phantom/misc_phantoms.py#L206). Do you want the complete list of all `ttf` files?

On Ubuntu you should always have the utbuntu-font-family, like `Ubuntu-L.ttf`, but I guess that will not be a good default for windows...

**Comment by kohr-h** [comment]
Seems like there is no safe default for all platforms and distributions. I guess it would make sense then to make the `font` parameter mandatory, even if it's a slight annoyance.

**Comment by adler-j** [comment]
Another option is to make the default platform dependent, which I'd prefer.

**Comment by kohr-h** [comment]
I can live with that, but then we at least need to make a quick round of font searching to determine which ones are available at least on *our* machines. 

### Windows
- `arial` should always be available

### Linux
Here are some fonts that I encounter very often, perhaps we can find a common denominator among all distributions we work with.

Font | @kohr-h Fedora | @kohr-h Gentoo | @aringh Ubuntu
------ | --------------------- | --------------------- | --------------------
`FreeSans` | ✔️ | |
`LiberationSans-Regular` | ✔️ | |
`DejaVuSans` | ✔️ | | 

If possible, we should take one with a short name :-)

For comparison:
`FreeSans`
![freesans](https://user-images.githubusercontent.com/5030250/27289220-714181de-5509-11e7-8cca-b0609b13e6cc.png)
`DejaVuSans`
![dejavusans](https://user-images.githubusercontent.com/5030250/27289237-798798a6-5509-11e7-9112-5e87f7e7bf22.png)
`LiberationSans-Regular`
![liberationsansregular](https://user-images.githubusercontent.com/5030250/27289247-82bb0598-5509-11e7-8049-81ba1cb3dcd5.png)

**Comment by kohr-h** [comment]
Looking at more high-resolution examples, I think `DejaVuSans` looks nicest, a bit more round and balanced than the others.

**Comment by aringh** [comment]
Should we check Mac as well for default fonts? I do not have one, but I think @hilding79 or @ozanoktem  does...

**Comment by adler-j** [comment]
@kohr-h, could you update your images to said high res fonts?

**Comment by kohr-h** [comment]
Updated the stuff

**Comment by aringh** [comment]
Both `LiberationSans-Regular` and `DejaVuSans` seems to be available on my Ubuntu machine.

**Comment by kohr-h** [comment]
Thanks for the info @aringh. I guess we can choose then. I'm skeptical that these are available on Mac OS, though, need some input there.

**Comment by ozanoktem** [comment]
A list of typefaces included with macOS can be seen [here](https://en.wikipedia.org/wiki/List_of_typefaces_included_with_macOS). Clearly, none of `LiberationSans-Regular`, `DejaVuSans` or `FreeSans` are available.

**Comment by kohr-h** [comment]
> A list of typefaces included with macOS can be seen here. Clearly, none of LiberationSans-Regular, DejaVuSans or FreeSans are available.

Hm, ok, then I guess we choose something neutral for Mac OS, for instance [Helvetica](https://en.wikipedia.org/wiki/Helvetica), `LiberationSans-Regular` for Linux, and `Arial` for Windows.
