### ISSUE TITLE
titles not displaying correctly in the standard .show() function

### ISSUE THREAD

**Issue by MJLagerwerf** [odlgroup/odl#1044]
Using the standard .show(title="") fucntion results in a figure where the title is cut off (see the figure below).
Note that this problem does not seem to occur when displaying the figure inline.

The following code illustrates the problem
```
import odl

space = odl.uniform_discr(min_pt=0, max_pt=20, shape=20, dtype='float32')

ramp = space.element(range(20))
ramp.show(title='Figure of a ramp with cut off title', method='plot')
```
This will result in this figure:

![figure_of_a_ramp_with_cut_off_title](https://user-images.githubusercontent.com/12029072/27584982-96b17866-5b3a-11e7-8b2b-7829ffce61d8.png)

**Comment by adler-j** [comment]
Thank you for the bug report!

What backend are you using when this occurs? Run:

```
>>> import matplotlib.pyplot as plt
>>> plt.get_backend()
'Qt5Agg'
```

to find out which one, here I have `'Qt5Agg'`.

**Comment by MJLagerwerf** [comment]
I have the same
```
>>>> import matplotlib.pyplot as plt
>>>> plt.get_backend()
 'Qt5Agg'
```

**Comment by adler-j** [comment]
Made a PR that solves this, see #1045. Should be fixed very soon. Thank you for the bug report.

**Comment by kohr-h** [comment]
> Running the script from my first post gives the following warning:

Everybody gets this warning :-)

**Comment by adler-j** [comment]
> > Running the script from my first post gives the following warning:

> Everybody gets this warning :-)

Not me: 724aaa5701cae5f57e6afecc4375e0a734c04121
