### ISSUE TITLE
Skip whole cu_ntuples_test instead of individual

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#105]
Currently we decorate each test with `@skip_if_no_cuda`. We could instead follow:

http://translate-toolkit.readthedocs.org/en/latest/developers/testing.html

and do

```python
# mark entire module as skipped for py.test if no indexer available
pytestmark = pytest.mark.skipif("not odl.")
```

**Comment by kohr-h** [comment]
Looks good. We had quite some duplication because of that. What does the indexer string exactly do?

**Comment by adler-j** [comment]
String as a misstake, should be

```python
# mark entire module as skipped for py.test if no indexer available
pytestmark = pytest.mark.skipif("not odl.CUDA_AVAILABLE")
```
