### ISSUE TITLE
Warning for pyfftw < 0.10.4 appears for pyfftw 0.10.4

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#1057]
Due to some *questionable* internal versioning of pyfftw, ODL now always warns because
```python
>>> import pyfftw
>>> pyfftw.__version__
'0.10.3.dev0+e827cb5'
```
This happens for packages installed through both `pip` and `conda` (using conda-forge).

**Comment by kohr-h** [comment]
Turns out that the version string is exactly the same as the one you get when installing 0.10.3 via pip, so we cannot even change the warning to "if version <= this then warn" because they're indistinguishable. It's possible to do
```python
import pip
dists = pip.get_installed_distributions()
for dist in dists:
    if dist.key.lower() == 'pyfftw':
        print(dist.version)
        # or do other stuff
        break
```
This prints `'0.10.4'` as expected.

However `pip` adds 0.2 s to the import time, kind of painful. Could be done lazily though if we're desperate.

**Comment by adler-j** [comment]
This is all weird, since I get

```
>>> import pyfftw
>>> pyfftw.__version__
'0.10.4'
```

Are you sure you have the latest version from pip?

**Comment by kohr-h** [comment]
> Are you sure you have the latest version from pip?

Yes, just tested it with a fresh conda environment (Python 3.5) and `pip --no-cache-dir` to make sure I don't use cruft lying around. Still the same result. (Again also with the version in conda-forge)

Did you test on Windows or Linux?

**Comment by kohr-h** [comment]
> (Python 3.5)

Same result for 2.7 (and 3.6 as tested yesterday)

**Comment by adler-j** [comment]
> Did you test on Windows or Linux?

This is on windows.

Perhaps an option would be to simply hard-code the version currently on pip? In pseudocode

```
# comment explaining why we do this magic
if pyfftw.__version < '0.10.3.dev0+e827cb5':
    do stuff
```

**Comment by kohr-h** [comment]
> Perhaps an option would be to simply hard-code the version currently on pip? In pseudocode

Problem with this is that the version string of the package you get with `pip install pyfftw==0.10.3` is exactly the same (I'm not joking).
