### ISSUE TITLE
Chambolle Pock Algorithm

### ISSUE THREAD

**Issue by MatthiasJE** [odlgroup/odl#1077]
I had a look at the implementation of the Chambolle Pock algorithm + its usage and I have a few thoughts to it. 

First, consider renaming it to PDHG (Primal-Dual Hybrid Gradient). 

Second, the parameter gamma is misleading. It should be used when F^ast is _strongly convex_ (documentation says uniformly convex). If G is strongly convex, one can do the same but scale tau and sigma differently. The current implementation would scale them in both cases the same (which is not correct). 

Third, the gamma has been used for the TGV example which is not strongly convex but only what is so called "partially strongly convex", see https://arxiv.org/pdf/1609.07373 for more details.

**Comment by adler-j** [comment]
I agree on all points. Would you consider making a pull request to fix these issues?

**Comment by MatthiasJE** [comment]
Sure, I can do that

**Comment by MatthiasJE** [comment]
I finally found time to make the changes discussed above. There is a comment in some files that I do not know how to update accordingly:

> For further details and a description of the solution method used, see
> :ref:`chambolle_pock` in the ODL documentation.

What does `chambolle_pock` refer to?

**Comment by adler-j** [comment]
https://odlgroup.github.io/odl/guide/chambolle_pock_guide.html

**Comment by MatthiasJE** [comment]
OK. For consistency, that would need to be changed, too. How would I do that?

**Comment by adler-j** [comment]
The source code is in here:

https://github.com/odlgroup/odl/blob/master/doc/source/guide/chambolle_pock_guide.rst

So you simply rewrite that as you see fit. It's typeset using RST.
