### ISSUE TITLE
AttributeError: 'module' object has no attribute 'tensorflow'

### ISSUE THREAD

**Issue by cleverzh** [odlgroup/odl#1084]
Traceback (most recent call last):
  File "learned_chambolle_pock.py", line 35, in <module>
    odl_op_layer = odl.contrib.tensorflow.as_tensorflow_layer(operator,'RayTransform')
AttributeError: 'module' object has no attribute 'tensorflow'

The above error appears, but I can not find the "odl.contrib.tensorflow" module in the odl/contrib folder.

**Comment by adler-j** [comment]
The tensorflow branch was recently updated and I just managed to update https://github.com/adler-j/learned_primal_dual to work with this version, it should work now if you update "Learned_primal_dual".

**Comment by cleverzh** [comment]
Thank you very much for the patients. I have already fixed up the problems. I should mention that if I directly install the odl package which with tensorflow support by the command "$ pip install https://github.com/adler-j/odl/archive/tensorflow_support.zip", it will be not correctly installed in my local lib. And I can not find the tensorflow support utils. The solution is:
1)download:odl-tensorflow_support.zip
2)python setup.py install
3) update the numpy to newest version
4) finished the installation.
If I done it this way, all things go well.
I hope the above may be helpful to the beginner.

**Comment by adler-j** [comment]
Interesting with the bug for you, it worked for me. Perhaps it's platform dependent. Good luck in using the code and please don't hesitate to ask more questions!

Thank you very much for providing the solution!
