### ISSUE TITLE
Inner product on a space with nonuniform discretization is not defined correctly

### ISSUE THREAD

**Issue by MJLagerwerf** [odlgroup/odl#1091]
As the title reads: The inner product on spaces with nonuniform discretizations are not defined correctly.

The following code:
```python
import odl
import numpy as np

part = odl.nonuniform_partition([0,1,4], min_pt=0, max_pt=4)
fspace = odl.FunctionSpace(part.set)
discr = odl.DiscreteLp(fspace, part, odl.rn(part.size), interp='linear')
space = odl.DiscreteLp(fspace, part, discr)

x1 = space.element(np.ones(3))
x2 = space.element(np.ones(3))

x3 = space.element(np.ones(3))
x4 = space.element(np.arange(3))
inner1 = space.inner(x1, x2)
inner2 = space.inner(x3, x4)
```
Returns:
inner1 = 3, inner2 = 3
Where I would expect:
inner1 = 4, inner2 = 5

I suspect that the inner product on this space is simply:
```python
np.sum(x1*x2)
```

EDIT: @adler-j updated typesetting

**Comment by adler-j** [comment]
First, there are two issues with your code:

* You use `discr` as an argument to space, resulting in a discretized space which has another discretized space as its data representation.

* You do not provide any weighting. Spaces created explicitly via `DiscreteLp` need to be manually weighted.

Fixing these gives:

```python
part = odl.nonuniform_partition([0,1,4], min_pt=0, max_pt=4)
weight = np.ravel(np.multiply.reduce(np.meshgrid(*part.cell_sizes_vecs)))

fspace = odl.FunctionSpace(part.set)
space = odl.DiscreteLp(fspace, part, odl.rn(part.size, weighting=weight), interp='nearest')

x1 = space.element(np.ones(3))
x2 = space.element(np.ones(3))

x3 = space.element(np.ones(3))
x4 = space.element(np.arange(3))
inner1 = space.inner(x1, x2)
inner2 = space.inner(x3, x4)
```

But doing this *still* gives bad results

```python
>>> inner1
3.0
>>> inner2
3.5
```

The reason has something to do with the magic inside [here](https://github.com/odlgroup/odl/blob/99b02efcba748f5e4b33e4403c836fb7ffdd6e90/odl/discr/lp_discr.py#L403-L418), which I'll have to refer to @kohr-h for a comment about.

I should also mention that all of this would be fixed if #672 got finalized.

**Comment by kohr-h** [comment]
Well, the distinction in the referenced magical code snippet is not quite correct. 
- The `is_uniformly_weighted` property is intended for uniform discretizations to determine if there are weights at the boundary which are different from the inner weights. Therefore the stuff happening on the boundary. It's likely more efficient to change a few values at the boundary and then use standard inner product than to define a full weighting array and compute a weighted inner product.
- The case of non-uniformly discretized spaces should actually also only refer to the parent class since the weights are per point there anyway.

Here, for instance, 
```python
>>> space.dspace.inner(x1.ntuple, x2.ntuple)
4.0
>>> space.dspace.inner(x3.ntuple, x4.ntuple)
5.0
```
This is as expected.

**Comment by adler-j** [comment]
But I have to agree with @MJLagerwerf here, if we have *any* space of functions on [a, b], we would expect `<1, 1> = b - a`, right?

What would be the correct way for him to write this?

**Comment by kohr-h** [comment]
Agreed, or to put it this way: functions that can be exactly represented should be exactly integrated.

The way to fix this is to change the referenced lines to this:
```python
    # The inherited methods by default use a weighting by a constant
    # (the grid cell size). In dimensions where the partitioned set contains
    # only a fraction of the outermost cells (e.g. if the outermost grid
    # points lie at the boundary), the corresponding contribuitons to
    # discretized integrals need to be scaled by that fraction.
    def _inner(self, x, y):
        """Return ``self.inner(x, y)``."""
        if not self.is_uniform or (self.is_uniform and self.is_uniformly_weighted):
            return super()._inner(x, y)
        else:
            # TODO: implement without copying x
            bdry_fracs = self.partition.boundary_cell_fractions
            func_list = _scaling_func_list(bdry_fracs)


            x_arr = apply_on_boundary(x, func=func_list, only_once=False)
            return super()._inner(self.element(x_arr), y)
```

**Comment by adler-j** [comment]
Can you do this @kohr-h? Should be simple I guess

**Comment by kohr-h** [comment]
I'm on it.
