### ISSUE TITLE
callback store

### ISSUE THREAD

**Issue by MatthiasJE** [odlgroup/odl#1093]
There is an issue when storing scalar values with CallbackStore. I followed the example in CallbackStore(SolverCallback). I suppose the example would have given the same error if the callback was applied!
 
```python
import odl
norm_function = lambda x: x.norm()
callback = odl.solvers.CallbackStore() * norm_function
space = odl.rn(3)
x = space.one()
callback(x)
```

>   File "<ipython-input-1-f49024937eaf>", line 8, in <module>
>     callback(x)
> 
>   File "/home/ehrhardt/repositories/git_ODL/odl/solvers/util/callback.py", line 162, in __call__
>     self.callback(self.operator(result))
> 
>   File "/home/ehrhardt/repositories/git_ODL/odl/solvers/util/callback.py", line 240, in __call__
>     self.results.append(result.copy())
> 
> AttributeError: 'float' object has no attribute 'copy'

**Comment by adler-j** [comment]
Thanks for the report. See https://github.com/odlgroup/odl/pull/1094 for a fix.
