### ISSUE TITLE
CallbackStore for algorithm analysis

### ISSUE THREAD

**Issue by MatthiasJE** [odlgroup/odl#1095]
This is not a real issue, but rather a question how to implement this nicely.

I want to run an algorithm and compute certain values along the iterations.
Intuitively, I would like to have a dictionary with the entries
iteration_count, time, error_function_value, obj_function_value
which store the iteration at which the function values are being computed, the time and finally the actual function values. 
For all of this I do see that there are callbacks that do the trick, but how do I combine them and save the values?

**Comment by kohr-h** [comment]
Well the most generic thing that lets you do almost anything is `CallbackApply`, which just takes some callable object and calls it in each iteration. If you want to store stuff, you can make a simple class like this:
```python
class StoreStuff(object):
    def __init__(self):
        self.iteration_count = 0
        self.info = {
            'iteration_counts': [],
            'times': [],
            'error_function_values': [],
            'obj_function_value': []
        }

    def __call__(self, x):
        # Fill in proper calls to functionals here
        self.info['iteration_counts'].append(self.iteration_count)
        self.info['times'].append(time())
        self.info['error_function_values'].append(err_func(x))
        self.info['obj_function_values'].append(obj_func(x))
        self.iteration_count += 1
```
Then you can use this class as
```python
store = StoreStuff()
callback = CallbackApply(store)
```
The only caveat here is that the iteration count will be off if you supply `step` different from 1 to `CallbackApply`.

**Comment by adler-j** [comment]
Agree with @kohr-h here. Writing a custom `Callback` would be best. With that said I'd make two changes:

* Inherit from `odl.solvers.util.callback.SolverCallback` (@kohr-h: should we move this top `odl.solvers.Callback`?)
* Skip using a `dict`

```python
class StoreStuff(odl.solvers.util.callback.SolverCallback):
    def __init__(self):
        self.iteration_count = 0
        self.iteration_counts = []
        self.times = []
        self.error_function_values = []
        self.obj_function_value = []

    def __call__(self, x):
        # Fill in proper calls to functionals here
        self.iteration_counts.append(self.iteration_count)
        self.times.append(time())
        self.error_function_values.append(err_func(x))
        self.obj_function_values.append(obj_func(x))
        self.iteration_count += 1
```

An even lazier way would be to write a "throwaway" function and just write to global arrays (I'll admit i might have done this myself):

```python
iteration_count = 0
iteration_counts = []
times = []
error_function_values = []
obj_function_value = []

def callback(x):
    global iteration_count  # needed since `int` is immutable
    iteration_counts.append(iteration_count)
    times.append(time())
    error_function_values.append(err_func(x))
    obj_function_values.append(obj_func(x))
    iteration_count += 1
    
mysolver(..., callback=callback)
```

**Comment by MatthiasJE** [comment]
Thanks for the swift response. I like the upper "non-lazy" solution :). I was just wondering if one can recycle some of the other call back functions here but this does not seem to be the case.

What is the smartest way of making time measurements? I would only know of:

```
import time
time.time()
```

**Comment by adler-j** [comment]
Well, if you want to time a specific function, I'd recommend

```
with odl.util.Timer():
    my_function()
```

If you want to continuously update, you should do `time.time()` as you mention.

**Comment by kohr-h** [comment]
In the IPython shell, you can also use the `%timeit` magic. It usually gives more precise timings since it runs stuff many times and then averages the times (it also switches off garbage collection which can skew timing results).
It's also very simple to use:
```python
In [1]: %timeit myfunction()
18.3 µs ± 42.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
```
