### ISSUE TITLE
PDHG examples

### ISSUE THREAD

**Issue by mehrhardt** [odlgroup/odl#1101]
ODL has two examples for PDHG: 1) 1/k rate, 2) 1/k^2 rate with primal acceleration.

Add two more examples: 3) 1/k^2 rate with dual acceleration, 4) linear rate.

This may be done in conjunction with #985.

**Comment by adler-j** [comment]
Sounds like a good initiative!

**Comment by MatthiasJE** [comment]
Where should I place these examples and the SPDHG? Shall I create a folder within "contrib" or try to have it in the core ODL?

**Comment by adler-j** [comment]
Examples should go into core, SPDHG is not "established" yet so to say and should go into contrib

**Comment by MatthiasJE** [comment]
Good, I'll do that. So I create a folder "odl/contrib/solvers/SPDHG" to put the algorithm and the examples there?

**Comment by adler-j** [comment]
Sure that sounds good (but use all lowercase)!
