### ISSUE TITLE
Test failure for FBP - slow test suite

### ISSUE THREAD

**Issue by aringh** [odlgroup/odl#1105]
In connection to #1102 I'm updating the slow test suite for FBP. I think the master branch has a failure for `helical` `astra_cuda` `uniform`. Is this known? Is it related to some Tam-Danielsson windowing?

**Comment by adler-j** [comment]
Not known, we'll have to look into it.

**Comment by kohr-h** [comment]
This looks awfully familiar to me. I think I increased the error margin on some branch, but I don't know the underlying reason, and whether it ever passed.
