### ISSUE TITLE
mean_squared_error fom computes wrong result

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#1114]
Basically the mean squared error fom computes the squared error (without the mean). This in turn causes lots of downstream issues.

**Comment by aringh** [comment]
In this discrete case you normalize with the number of data points. Do you want to do the same here? Or in a continuum setting should you correct with the total mass of the space? If so, would this be a correction to it?

```
diff = data - ground_truth
fom = l2_normSquared(diff)
fom /= data.space.one().norm()**2
```

**Comment by adler-j** [comment]
This looks perfectly fine to me!

**Comment by adler-j** [comment]
Was this fixed now?

**Comment by kohr-h** [comment]
Seems fixed:
```python
>>> space = odl.uniform_discr([0, 0], [1, 1], (10, 20))
>>> x = space.one()
>>> y = space.zero()
>>> fom.mean_squared_error(x, y)
1.0
>>> fom.mean_squared_error(x, y, normalized=True)
1.0000000000000002
```
