### ISSUE TITLE
Make CONTRIBUTORS file

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#1123]
Since the list of contributors is getting longer I suggest we add a file with each name plus GH alias. Sorted alphabetically I'd say.
The current "Contributors" section should be reduced to an acknowledgement and a link to the file.

**Comment by adler-j** [comment]
Agree, but we could add some comment on what they did as well. More full credits.

**Comment by kohr-h** [comment]
I'd say we put that in the release notes and prominently on the release page on GH. Otherwise I think the file also gets too busy.

**Comment by adler-j** [comment]
Now I did it anyway :O It seems quite common in open source to do it so I thought what the heck
