### ISSUE TITLE
Improve trivial docstrings

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#113]
We currently have *many* docstrings like:

```"""``op.__truediv__(s) <==> op / other``"""```

These should be improved imo. Some suggestions:

* Simple: ```"""``self / other``"""```
* Descriptive: ```"""Divide with scalar or vector"""```
* More?

**Comment by kohr-h** [comment]
I agree generally. ~~Not sure I like `self` in the docstring, though.~~ NumPy prints (at least for `ndarray`s) "return self/value". We could modify it with a bit more pretty printing as

    Return ``self / other``.

And for in-place operations, they do "Return self/=value", we would pretty-print

    Return ``self /= other``.

I think this is perfectly clear and concise.

**Comment by kohr-h** [comment]
The Python standard library apparently does it in the same way.

**Comment by adler-j** [comment]
If both numpy and the standard library does that, so should we. The further docstring should mention the method used, i.e. "using `lincomb`" or "using `multiply`".

**Comment by kohr-h** [comment]
Fair enough. 

The PSL seems to differentiate between not returning `out`, in which case they write "Implement" instead of "Return", and returning `out` with the obvious outcome. Since we, as NumPy, always return `out`, we should go for the second variant.

**Comment by adler-j** [comment]
Do we return in the inplace guys? I know you do this in C++ but I think you dont in python

```
Implement ``self /= other``.
```

**Comment by kohr-h** [comment]
I think we mostly do, and to cite again NumPy:

```python
>>> x = y = np.arange(3)
>>> out = np.empty_like(x)
>>> out is np.add(x, y, out=out)
x = y = np.arange(3)
>>> np.all(x + y == out)
True
```

I think it simplifies things if you can rely on a function to always return the result independent of whether there was an `out` parameter or not.

**Comment by adler-j** [comment]
Sure in the *functions* we do, but what about in the overridden inplace operators? `/=`, `+=` etc, i think these don't return?

**Comment by kohr-h** [comment]
I didn't check properly. Maybe we don't and should change that.

**Comment by adler-j** [comment]
Implemented as you said, now looks better.
