### ISSUE TITLE
nonuniform_partition bug with single element input

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#1133]
The following both fail:

```python 
>>> odl.nonuniform_partition(1)
```

```python 
>>> odl.nonuniform_partition([1])
```

We need to decide on if we want either of them to work, but I would actually suggest they should somehow give degenerate partitions. This would be useful with single-angle geometries.

**Comment by kohr-h** [comment]
Well I don't know what to do here. Take interval with length 1 so no weighting applies?

**Comment by adler-j** [comment]
My suggestion would be length 0 and then handle weighting "properly" downstream?

**Comment by kohr-h** [comment]
Oh, that. Okay, that could work. Remains to be seen in the downstream code.
