### ISSUE TITLE
contrib.fom.mean_squared_error logical error in range

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#1136]
As noted by @MJLagerwerf the documentation of `mean_squared_error` is wrong about the range of the normalized FOM. It claims that
```
MSE(f, g) = ||f - g||^2 / (||f||^2 + ||g||^2)
``` 
lies in `[0, 1]`. However, for `g = -f` the result is 2. We should change the doc or the formula.

**Comment by adler-j** [comment]
Really? |1 - (-1)| / (|1| + |1|) = 2 / 2 = 1

What am I missing here?

**Comment by olivierverdier** [comment]
Yes, the last formula makes much more sense, in my opinion.

**Comment by kohr-h** [comment]
Agreed, the square should outside.

**Comment by adler-j** [comment]
You fixing this @kohr-h?

**Comment by kohr-h** [comment]
OK

**Comment by zickert** [comment]
Thanks for finding and correcting this! Also applies to #1114
