### ISSUE TITLE
Add asarray to ProductSpaceElement

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#1139]
Currently this works:

```python
>>> np.asarray(vec)
```

but this does not

```
>>> vec.asarray()
AttributeError: 'ProductSpaceElement' object has no attribute 'asarray'
```

**Comment by kohr-h** [comment]
> Currently this works:
> 
> >>> np.asarray(vec)

for power spaces.

But yes, we should add it.

**Comment by MatthiasJE** [comment]
I think, this issue is related to the following bug:

```
import odl

space = odl.uniform_discr(
    min_pt=[-20, -20], max_pt=[20, 20], shape=[10, 10], dtype='float32')

geometry = odl.tomo.parallel_beam_geometry(space, num_angles=10)

G = 10 * odl.BroadcastOperator(
        *[odl.tomo.RayTransform(space, geometry[i::10], impl='astra_cpu')
          for i in range(10)])

Y = G.range
data = Y.one()

f = odl.solvers.KullbackLeibler(Y, data)

f(data)
```

>   File "/home/ehrhardt/repositories/git_myODL/odl/solvers/functional/default_functionals.py", line 1114, in _call
>     scipy.special.xlogy(self.prior, self.prior / x))
> 
> ValueError: object __array__ method not producing an array

**Comment by adler-j** [comment]
The workaround is clearly

```
f = odl.solvers.SeparableSum(*[odl.solvers.KullbackLeibler(Y, di) for di in data])
```

which is actually the "correct" way to do it I guess, but I agree, what you do should work.

**Comment by MatthiasJE** [comment]
Yes, your proposed solution works but then you end up with commands like

```
f = odl.solvers.SeparableSum(
        *[odl.solvers.KullbackLeibler(Y[i], data[i])
          .translated(-background[i]) for i in range(Y.size)])
```

and much of ODL's elegance is lost :(

**Comment by adler-j** [comment]
Agree that it is far less elegant :/
