### ISSUE TITLE
uniform noise

### ISSUE THREAD

**Issue by MatthiasJE** [odlgroup/odl#1143]
Not very urgent, but it would be good if ODL supports also uniform noise. This is particularly useful when dealing with ProductSpaces. As they do not have a "shape" the numpy workaround would be a couple of lines which is to be avoided.

**Comment by adler-j** [comment]
So basically like `odl.phantom.white_noise` but `odl.phantom.uniform_noise`?

Should be easy to add

**Comment by MatthiasJE** [comment]
exactly, super easy actually.

**Comment by MatthiasJE** [comment]
It probably makes sense to export it as the other noise models:

`__all__ = ('white_noise', 'poisson_noise', 'salt_pepper_noise', 'uniform_noise')
`

**Comment by adler-j** [comment]
wooops, fixing that.
