### ISSUE TITLE
Get rid of Interval, Rectange, Cuboid classes

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#117]
These should be made into functions, returning a `IntervalProd` instance. Specific methods (`area`, `length`) can be made functions of any `IntervalProd` with a simple test for `ndim`. The `__repr__` function of `IntervalProd` can be adapted to print what is currently shown.

The main external interface change would be to change `Interval` -> `interval` (small **i**) etc.

**Comment by kohr-h** [comment]
Agreed.
