### ISSUE TITLE
Use pep8speaks

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#1171]
Instead of using the `--pep8` pytest option we could integrate [pep8speaks](https://pep8speaks.com/) into our PR pipeline. The advantages would be

1. Not a full-blown Travis failure when pep8 is violated.
2. No more clicking into the Travis logs to find the pep8 issue - violations are reported in detail in the PR.
3. Less stuff to install in Travis.

**Comment by adler-j** [comment]
Looks nice to me!

**Comment by kohr-h** [comment]
Ok, I'll go ahead and add it.

**Comment by adler-j** [comment]
Guess this is closed now?

**Comment by kohr-h** [comment]
Oh yea, right.
