### ISSUE TITLE
Improved callbacks

### ISSUE THREAD

**Issue by MatthiasJE** [odlgroup/odl#1174]
I would like to propose two small improvements for callbacks. First, an optional "end" argument should be given which allows elegant concatenation of print callbacks such as

Iter = 9, time = 10 s, total time = 20 s

based on three different callbacks in one line rather than 3.

Second, as already hinted in the previous example, a new callback that measures the total time. To me, this is often more interesting than the time per iteration.

If you are happy with the two proposed changes, then I would prepare a pull request for this.

**Comment by MatthiasJE** [comment]
It is probably better to allow any kind of keyword arguments to be passed to the print function.

**Comment by adler-j** [comment]
Overall this sounds like a good addition, and for callbacks we can't really have to many I guess. If you could make a PR we could help distill it!

**Comment by adler-j** [comment]
I guess this is merged now, closing!

Thank you for the input!
