### ISSUE TITLE
callback for primal-dual algorithms

### ISSUE THREAD

**Issue by MatthiasJE** [odlgroup/odl#1179]
Another suggestion for a small modification regarding callbacks. For a primal-dual algorithms, it does not make much sense to call the callback only for the primal argument x, thus I would suggest calling it like 

    if callback is not None:
        callback([x, y])

where y is the dual variable.

**Comment by kohr-h** [comment]
See also #571 for some discussion.

**Comment by adler-j** [comment]
I actually recommend closing this and continuing the discussion in #571. With that said, this is a very much needed feature.

**Comment by kohr-h** [comment]
Okay, let's continue the discussion in the existing issue.
