### ISSUE TITLE
Bug in prox of l1 norm

### ISSUE THREAD

**Issue by mehrhardt** [odlgroup/odl#1181]
This example shows a bug in the prox operator of the l1 norm:
```
import odl

X = odl.rn(1)
f = odl.solvers.L1Norm(X)
x = 0.1 * X.one()

y1 = x.copy()
f.convex_conj.proximal(3)(y1, out=y1)

y2 = x.copy()
y2 = f.convex_conj.proximal(1)(y2)

(y1-y2).norm()
```
results in 0.9. Similar effects can be observed in `KullbackLeibler` but not in `L2Norm`.

**Comment by adler-j** [comment]
What would be the expected result and why?

**Comment by MatthiasJE** [comment]
As mentioned above already, replacing f by `f = odl.solvers.KullbackLeibler(X)` yields similar issues. Who knows which other functionals have the same problem.

**Comment by adler-j** [comment]
Darn it, you are right. I'll look into it.

**Comment by mehrhardt** [comment]
Any news here? Is there a way to write a test that gets run on all functionals (without us writing a new one every time)?

**Comment by adler-j** [comment]
No update sadly, havn't had time. With that said there is a rather enormous large-scale test here:

https://github.com/odlgroup/odl/blob/baecb8ada64995b7437cd21590f5a005f5695e9e/odl/test/largescale/solvers/nonsmooth/default_functionals_slow_test.py#L114

it should catch stuff like this, but apparently does not.

**Comment by kohr-h** [comment]
> No update sadly, havn't had time. With that said there is a rather enormous large-scale test here:
> 
> odl/odl/test/largescale/solvers/nonsmooth/default_functionals_slow_test.py
> 
> Line 114 in baecb8a
>  def test_proximal_defintion(functional, stepsize): 
> 
> it should catch stuff like this, but apparently does not.

Does it test with aligned input & output?

**Comment by adler-j** [comment]
> Does it test with aligned input & output?

Very much looks like it does not.

**Comment by mehrhardt** [comment]
Well done! This indeed fixed the bug I was observing.

**Comment by mehrhardt** [comment]
I just did a similar test with the l1-norm itself and not its conjugate. While the latter is indeed fixed, the former still has the same problem:

```
import odl

X = odl.rn(1)
f = odl.solvers.L1Norm(X)
x = 0.1 * X.one()

y1 = x.copy()
f.proximal(1e-2)(y1, out=y1)

y2 = x.copy()
y2 = f.proximal(1e-2)(y2)

(y1-y2).norm()
```
