### ISSUE TITLE
Allow Python functions as input to discretized spaces

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#119]
Similarly as in `Operator`, where the input is passed through `element()` rather than strictly checked, we should implement the same behavior in `RawDiscretization.element()`: instead of the current checks, we first try to pass an input directly to `restriction` and, if it fails, go on with the other options.

**Comment by adler-j** [comment]
Sounds good!

**Comment by kohr-h** [comment]
Implemented on my branch and works, I'll just pick it over to master.
