### ISSUE TITLE
add version defines

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#12]
we should add a way for users to determine the version of `odl`

```python
>>> import odl
>>> odl.ODL_MAJOR_VERSION
0
>>> odl.ODL_MINOR_VERSION
9
```

**Comment by kohr-h** [comment]
There is already `odl.__version__` which uses the version from `setup.py`. For parsing, one can use
```python
>>> from distutils.version import StrictVersion
>>> ver = StrictVersion(odl.__version__)
>>> major, minor, revision = ver.version
>>> print(major, minor, revision)
0 9 0
```
Not sure if constants in the top-level namespace are really needed.

**Comment by adler-j** [comment]
Valid point, suppose we can make do with that then.
