### ISSUE TITLE
Non-ASCII characters in docstrings

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#1207]
See the discussion [here](https://github.com/odlgroup/odl/pull/1166#discussion_r146475425).

We need to think about how to write names of authors of papers that we cite in docstrings. If a name contains non-ASCII characters, we need to either butcher the name or make sure the file is encoded in UTF-8.

A possible issue is that some editor errors when trying to open a file that contains non-ASCII strings. That editor should be ditched today rather than tomorrow IMO 🗑.
Another possible outcome is that the editor opens the file, decodes its contents as ASCII, and later writes garbage for the non-ASCII part when saving again. That would also count as an editor bug, since just saving that part unchanged won't hurt the content.

So unless somebody uses an editor with bugs, nothing should be wrong with a file whose docstring has non-ASCII characters.

That said, testing is better than guessing.

**Comment by adler-j** [comment]
One option would be to create a branch where we did some changes for this and then tested it with some editors. Some of the documentation (notably the solvers) could really use actual greek letters to significantly improve its readability.

Further, we need to make sure that e.g. sphinx (and most web-browsers) work will with it, so that the documentation is readable online.

**Comment by olivierverdier** [comment]
Normally, everything works with utf-8 nowadays: editors, web browsers, etc. Sphinx, Python, (Xe)LaTeX (not to mention MacOS X file system) and so on now use utf-8 by default. I've used utf-8 in docstrings in all my Python projects (including with sphinx).

The only problem that I can think of is that Python 2 requires that you specify the encoding, as @kohr-h was mentioning.

If someone adds, say a latin-1 character, by using the wrong editor, this will produce invalid utf-8, and I suppose this could be checked with travis? (if that ever is a problem...)

**Comment by adler-j** [comment]
Was this decided upon? E.g. we allow them?

**Comment by sbanert** [comment]
They're already in. ;-)
https://github.com/odlgroup/odl/blob/master/odl/solvers/functional/functional.py#L1
https://github.com/odlgroup/odl/blob/master/odl/solvers/functional/functional.py#L149

**Comment by adler-j** [comment]
Great!

Regarding linking to code, if you highlight the line you want to link to and click "y", you get a full URL with a commit number. That way, if ODL changes in the future, your links wont become dead.

It then looks like this:

https://github.com/odlgroup/odl/blob/4967e6d6492cdc1a72337639b882c1f1289ca836/odl/solvers/functional/functional.py#L1

https://github.com/odlgroup/odl/blob/4967e6d6492cdc1a72337639b882c1f1289ca836/odl/solvers/functional/functional.py#L149
