### ISSUE TITLE
A quick guide on how to install Python with the required dependencies

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#121]
As discussed in #98, we could use a guide on how to get started with some different OS's (notably the most common UNIX distribs and windows).

**Comment by kohr-h** [comment]
Can this be considered done?

**Comment by adler-j** [comment]
Well, we have [Installing](http://odl.readthedocs.io/guide/introduction/installing.html) in the doc, but I.m.o. this is not very OS specific.

We could add more hands-on subpages on how to install ODL for various OS's.

**Comment by kohr-h** [comment]
OK

**Comment by adler-j** [comment]
Some inspiration on how to do this can be found at [Theano's documentation](http://deeplearning.net/software/theano/install_ubuntu.html) which does this very well.

**Comment by adler-j** [comment]
Note that this interacts with #634 since the current documentation states a false way to run the tests.

**Comment by adler-j** [comment]
Hasn't this been done?

**Comment by kohr-h** [comment]
Oh yes, there was even a branch named after this. Only forgot to mention the issue :-)
