### ISSUE TITLE
x.show() does not work properly for colour images

### ISSUE THREAD

**Issue by mehrhardt** [odlgroup/odl#1213]
As will become apparent in my PR #1211 ODL does not plot colour images correctly. Instead, it plots them somehow as a gray scale image which is the mean of the colour values I presume.

**Comment by adler-j** [comment]
How are you representing the color images when doing this? Actual vector-valued functions are supported in a somewhat weak manner atm, but that should be improved

**Comment by mehrhardt** [comment]
This problem came up in #1211

**Comment by adler-j** [comment]
Well frankly there is no obvious way to handle color images as is right now :/ Once we get the tensors done I guess we could add a "as color image" option to show, but for now the best you can do is to directly call matplotlib or to show e.g. the greyscale image on its own.

**Comment by kohr-h** [comment]
Currently I think a `rgb_space = ProductSpace(image_space, 3)` is the way to go. For a simple linear [colorimetric conversion](https://en.wikipedia.org/wiki/Grayscale#Colorimetric_.28perceptual_luminance-preserving.29_conversion_to_grayscale) to grayscale you can use `PointwiseSum(color_space, weights=[0.2126, 0.7152, 0.0722])`. More fancy conversions require custom functions. Unfortunately the PIL conversions don't work directly unless you have a Numpy array.

**Comment by adler-j** [comment]
Do we consider this solved, or do we want to somehow add color image .show for product spaces?

**Comment by mehrhardt** [comment]
I think this functionality is not very urgent. Perhaps better to concentrate on other things.

**Comment by kohr-h** [comment]
Agreed, should be okay with the workaround anyway.
