### ISSUE TITLE
Missmatch in KullbackLeibler functional and doc

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#1218]
The documentation says:

![equation](http://latex.codecogs.com/gif.latex?F%28x%29%20%3D%20%5Cbegin%7Bcases%7D%20%5Csum_%7Bi%7D%20%5Cleft%28%20x_i%20-%20g_i%20&plus;%20g_i%20%5Clog%20%5Cleft%28%20%5Cfrac%7Bg_i%7D%7Bx_i%7D%20%5Cright%29%20%5Cright%29%20%26%20%5Ctext%7Bif%20%7D%20x_i%20%3E%200%20%5Cforall%20i%20%5C%5C%20&plus;%5Cinfty%20%26%20%5Ctext%7Belse.%7D%20%5Cend%7Bcases%7D)

while the implementation seems to implement

![equation](http://latex.codecogs.com/gif.latex?F%28x%29%20%3D%20%5Cbegin%7Bcases%7D%20%5Cint%20%5Cleft%28%20x%28t%29%20-%20g%28t%29%20&plus;%20g%28t%29%20%5Clog%20%5Cleft%28%20%5Cfrac%7Bg%28t%29%29%7D%7Bx%28t%29%7D%20%5Cright%29%20%5Cright%29%20dt%20%26%20%5Ctext%7Bif%20%7D%20x%28t%29%29%20%3E%200%20%5Cforall%20t%20%5C%5C%20&plus;%5Cinfty%20%26%20%5Ctext%7Belse.%7D%20%5Cend%7Bcases%7D)

while this may seem like a minor difference, it throws of computations where the scale is relevant.

Anyway, either we need to update the doc, or the implementation.

**Comment by kohr-h** [comment]
Documentation. The upper one is a special case of the lower one.

**Comment by adler-j** [comment]
I guess we could add a flag to toggle between them given that the above one is with 98% certanity the one people intend to use when they do e.g. CT imaging. Anyway, I'll get this solved

**Comment by mehrhardt** [comment]
I prefer to stick to the lower one which achieves a consistent story in ODL. If one wants the upper one, one needs to define the topology of the data space accordingly.

**Comment by adler-j** [comment]
Seems you are in agreement then, I'll update the doc!
