### ISSUE TITLE
Get rid of Rn, Cn classes

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#122]
These should be factory functions, the repr can be adapted to look like now and any `isinstance(space, Rn)` type test could either be written `is_real_dtype(space.dtype)` or we could add a property `isreal`/`iscomplex`.

**Comment by kohr-h** [comment]
You're really scraping away all old semi-needed classes :-)

Well, why not? How would you call the factory? Not sure if `rn` and `cn` are so good. Maybe one could violate conventions and call them `Rn` and `Cn`?

**Comment by adler-j** [comment]
I violated convention with `Interval` and those, but perhaps we should not. Basically I'm against having all of this lougagge of classes we need to maintain :) Also makes this stuff less confusing:

```python
>>> X = Rn(3)
>>> Y = Fn(3, float)
>>> X
Rn(3)
>>> Y
Fn(3, 'float')
>>> X == Y
True
>>> isinstance(X, odl.Rn)
True
>>> isinstance(Y, odl.Rn)
False
```
