### ISSUE TITLE
Write documentation on UFuncs

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#123]
We need to add this to the documentation (preferably in space where we document `FnBase`).

**Comment by kohr-h** [comment]
Done?

**Comment by adler-j** [comment]
Is this sufficient:

http://odl.readthedocs.io/guide/in_depth/numpy_guide.html#using-odl-vectors-with-numpy-functions

?

**Comment by kohr-h** [comment]
Should be okay for now. Good candidate for a tutorial though.
