### ISSUE TITLE
Difference between `any()` and `np.any()`?

### ISSUE THREAD

**Issue by aringh** [odlgroup/odl#1234]
I was writing test to check if an element contains `nan`s, and got some weird errors. Can someone explain the difference between pythons built-in `any`, and `numpy`s `any`? Is this expected behavior?

```
In [1]: import odl
   ...: import numpy as np
   ...: space = odl.uniform_discr([0,0], [1,1], [9,11])
   ...: x = odl.phantom.white_noise(space)
   ...: any(np.isnan(x))
Out[1]: True
```

```
In [2]: import odl
   ...: import numpy as np
   ...: space = odl.uniform_discr([0,0], [1,1], [9,11])
   ...: x = odl.phantom.white_noise(space)
   ...: np.any(np.isnan(x))
Out[2]: False
```

**Comment by kohr-h** [comment]
`any` has no idea of NumPy and just looks at the input as a sequence. The equivalent loop version of `any(np.isnan(x))` would be
```python
def any(seq):
    result = False
    for xi in seq:
        if xi:
            result = True
            break
    return result
```
The thing is that each of the `xi` is a vector of shape `(11,)` and will evaluate to `True` if passed to `bool`. Maybe we should overload `__bool__` for that case.

On the other hand, `np.any` looks at the flattened array by default and does what you expect.

**Comment by adler-j** [comment]
I'm busy fixing this

**Comment by adler-j** [comment]
The irritating thing is that the code as written by @aringh works differently with numpy arrays:

```
import numpy as np
x = np.random.randn(9, 11)
np.any(np.isnan(x))

Out[4]: False
```

vs

```
import numpy as np
x = np.random.randn(9, 11)
any(np.isnan(x))

Traceback (most recent call last):

  File "<ipython-input-5-8fb5901bf5f0>", line 3, in <module>
    any(np.isnan(x))

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

Traceback (most recent call last):

  File "<ipython-input-5-8fb5901bf5f0>", line 3, in <module>
    any(np.isnan(x))

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

**Comment by kohr-h** [comment]
Right. The difference is that for Numpy, the `if xi:` line fails, while for ours it just works in some broken way.
