### ISSUE TITLE
Remove the Sphinx warnings and errors

### ISSUE THREAD

**Issue by sbanert** [odlgroup/odl#1239]
When building the documentation with e.g. "make html" in the doc/ directory, I get a tremendous amount of warnings. Probably it would be a good idea to fix this (perhaps then the links would then work again).

Edit: I see that there already exists an issue on that, sorry for that. But it would be good to fix that soon, because otherwise I cannot see any chance of checking if the parts of documentation which I add are correct, so the problem gets worse and worse over time.

**Comment by adler-j** [comment]
Could you please link the other issue and then close this one? I agree that this should be addressed!

**Comment by sbanert** [comment]
The corresponding issues are #906 and #1058, I think, and maybe also #329.

**Comment by kohr-h** [comment]
Yep, all of those are relevant for this issue. However, for me the number of warnings has gone down significantly since the last release of Sphinx and/or the last update of numpydoc. Are you using the latest conda versions?

**Comment by sbanert** [comment]
I was not, but I ran “conda update --all” and the huge amount (26507, to be precise, after the update) of warning remains after the update.

**Comment by kohr-h** [comment]
We need to update numpydoc, our state is about a year old. I just tested the current one with our changes on top, that reduces the warnings to about 5000. Disabling the special methods (`__eq__` and such, I think we should do that in any case) reduces it further to around 2400.

**Comment by kohr-h** [comment]
In the long run we should move to one page per class or function, not per class member. That's just causing lots of trouble.

**Comment by adler-j** [comment]
> In the long run we should move to one page per class or function, not per class member. That's just causing lots of trouble.

Would doing so really be that complicated?

**Comment by kohr-h** [comment]
> Would doing so really be that complicated?

No idea. Isn't there some interplay between the files and the toctree that needs to be taken into consideration?
