### ISSUE TITLE
Behaviour of slicing for `zero` and `one`?

### ISSUE THREAD

**Issue by olivierverdier** [odlgroup/odl#1247]
Is this test supposed to pass or to fail? (it currently fails)

```python
def test_one_slice():
    space = odl.uniform_discr([0,0,0],[1,1,1],(10,20,30))
    x = space.one()
    x.shape # (10,20,30)
    assert x[0].shape == (20,30) # False, x[0] is a scalar
```

**Comment by adler-j** [comment]
It is currently supposed to fail, but should be fixed by #1113 (for which I guess this issue is a duplicate).

PR #1238 should solve this.
