### ISSUE TITLE
Remove FnBase

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#125]
I'm not sure of this but we could discuss it. What about removing `FnBase` (and all "child" spaces) and simply reducing it to a flag or two on `NtuplesBase`.

**Comment by kohr-h** [comment]
Any new thoughts on this?

**Comment by adler-j** [comment]
Well for now I dont feel like removing it, it serves a purpose I guess.

**Comment by kohr-h** [comment]
Close for now then?
