### ISSUE TITLE
Performance tests

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#128]
Since we now have a CI server, I think we should add more complicated tests that do not fall under the "unit test" category. There are a few reasons for this:

* We do not want ODL to become slower over time
* We need to see that ODL scales properly to large data sets
* We need to test algorithms with no quick example (reconstructions, large scale optimization)
* These can also serve as more complicated examples of solving "real" problems for our users.

I therefore propose that we add a new folder somewhere, and populate it with these tests. There are a few things to decide on first:

Scope
-----
To me, there are two purposes here, performance and solution of large scale problems. While they may coincide, they don't necessarily do so. In general the large scale problems are more of examples but with realistic-ish data, while the performance tests could be written in a more simple way but simply with larger parameters. This suggests that this is a two part endeavor.

Use of supporting library
-------------------------
With a short Google search, I've found the following:

* [AirSpeed Velocity](http://asv.readthedocs.org/en/latest/index.html) (asv): Used by numpy, seems to provide decent looking graphs. Syntax is quite pytest like.
* [benchmark](https://pypi.python.org/pypi/benchmark/0.1.5): On pip but seems abandoned.
* [codespeed](https://github.com/tobami/codespeed/): Used by PyPy. Also good looking. See http://speed.pypy.org/ for examples. Somewhat more complicated syntax.

Of these, to me AirSpeed Velocity looks the best.

Location
--------
Possible locations for these include:

* `benchmarks`: Numpy does this, and `asv` seems to prefer it.
* `test/benchmarks`: A bit more hidden away.
* `test/slow`: A more wide definition.

I propose that we do the first and the last one, we then add [custom command line options](https://pytest.org/latest/example/simple.html#control-skipping-of-tests-according-to-command-line-option) to py.test so that users can activate the slow tests by `py.test --runslow` (or similar). Finally we run the benchmarks by `asv run` if you want.

Does this sound like a good idea, do @kohr-h think it would be hard to add?

**Comment by kohr-h** [comment]
I'd say this is a great idea and one of the main reasons for me to put time into setting up the server. Looking at the example backends you linked to, codespeed seems to be a bit over the top for our purposes. It's probably better suited for projects with a very large number of scenarios and a need to "publicly show off" by making comparison a click-and-go experience. So I agree, `asv` looks best for our purposes, with a slim but well-structured frontend and a not too complicated syntax in code.

The hardest part seems to be setting up an initial test suite, populating over time with more benchmarks is probably easier. 

On the CI side, I don't think there is any conceptual problem. We need to decide on a strategy for testing, I'd say nightly benchmarks are ideal since we don't have a time constraint and get a data point every day.

Regarding location, `benchmarks` is the name to go IMO, and let's put them into the `test` folder if possible without too much interference with the unit tests. It should be simple to exclude the `benchmark` folder from the standard run.

**Comment by adler-j** [comment]
> I'd say this is a great idea and one of the main reasons for me to put time into setting up the server. Looking at the example backends you linked to, codespeed seems to be a bit over the top for our purposes. It's probably better suited for projects with a very large number of scenarios and a need to "publicly show off" by making comparison a click-and-go experience. So I agree, asv looks best for our purposes, with a slim but well-structured frontend and a not too complicated syntax in code.

Great, then we agree.

> The hardest part seems to be setting up an initial test suite, populating over time with more benchmarks is probably easier.

Indeed, thats why we should try doing it soon.

> On the CI side, I don't think there is any conceptual problem. We need to decide on a strategy for testing, I'd say nightly benchmarks are ideal since we don't have a time constraint and get a data point every day.

Depending on how long these take, we could also do it "in real time". We'll have to see. But indeed, the industry standard is once a night. (Just remember to save the commit hash we use)

> Regarding location, benchmarks is the name to go IMO, and let's put them into the test folder if possible without too much interference with the unit tests. It should be simple to exclude the benchmark folder from the standard run.

You dont think having two different folders is a good idea then?

**Comment by kohr-h** [comment]
> You dont think having two different folders is a good idea then?

Sure, just preferably under test, i.e. this way:
```
test
├── benchmarks
│   └── ...
├── discr
└── ...
```
or, alternatively
```
test
├── benchmarks
│   └── ...
└── unittests
     ├── discr
     └── ...
```
but this may become too deeply nested.

Having `benchmarks` at the top level is also an alternative, but I like having them under `test` since it is a sort of test, especially if we use a `pytest` option flag to activate them.

**Comment by adler-j** [comment]
Ok, how about `test/benchmarks` + `test/slow`? Or perhaps drop the `test/slow` folder and simply decorate all slow tests and let them reside with the others?

**Comment by kohr-h** [comment]
Ah okay, you mean the "realistic" tests vs. speed tests. I don't think they make much sense alongside with the unit tests. We may need substantial portions of code to init data etc. which would clutter the unittest suite, plus (probably) test data along with it which we probably don't want to ship by default. So yes, an extra folder for them would be best, I think. `slow` sounds a bit negative to me, maybe `largescale`?

**Comment by kohr-h** [comment]
Like this
```
test
├── benchmarks
│   └── ...
├── largescale
│   └── ...
├── discr
└── ...
```

**Comment by kohr-h** [comment]
Perhaps this solution is cleaner:
```
test
├── benchmarks
│   └── ...
├── largescale
│   └── ...
└── unittests
    ├── discr
    └── ...
```

**Comment by adler-j** [comment]
How about having the `largescale` in a separate repo? As you say we may want to ship with test data (although I'd prefer not) that would clutter this repo badly. Between the two alternatives I think I'd go for the second one.

**Comment by kohr-h** [comment]
Well, there is an option in `setuptools` to ship data with the code, and that should be possible to do in a conditional manner. But of course, a `git clone` would give you everything. Maybe a `git submodule`, and we try to figure out along the way how to best do it? I'm a bit hesitant to making a hard split.

**Comment by adler-j** [comment]
Agree on being hesitant. How about saying that we only use generated data for these tests? If we want to use actual physical data then we'll make a new repo for that (real data would probably also not be possible to publish this openly due to regulations etc).

**Comment by kohr-h** [comment]
That sounds like a way to go, agreed. Our good friend Shepp-Logan can probably help us out in a couple of cases, possibly new phantoms. We can have actual test data lying around at a private repo.

**Comment by adler-j** [comment]
Do you handle this since you are in charge of the CI?

**Comment by kohr-h** [comment]
Okay. I'm currently trying to get an older GCC working, far from trivial. Or is support for GCC 5.x in CUDA around the corner?

**Comment by adler-j** [comment]
There is no mention of GCC 5.x support anytime soon, you will need to "downgrade" GCC I guess.

**Comment by kohr-h** [comment]
I managed to build `odlpp` on my machine using a hand-compiled GCC 4.9.3 and forcing CMake to use it. Tests run smoothly :-)

**Comment by adler-j** [comment]
Since the build server does some of this, how about we start populating the test suite with these then?

**Comment by kohr-h** [comment]
Sure. Let's make a separate folder and and set up a build job for it.

**Comment by adler-j** [comment]
Will you make a branch for this?

**Comment by kohr-h** [comment]
Yes, I'll see if I can do something about it today.

**Comment by adler-j** [comment]
OK, lets make a list of test we'll write. How about I write some for the `FnBase` type spaces, and you do something for operators?

**Comment by kohr-h** [comment]
Okay. I guess we can take some of the examples from the unit tests and just blow them up. Probably best to make separate tests for different size scales so we get nice graphs for each scale.

**Comment by adler-j** [comment]
We also need to make sure the timings are only for the thing we want to test, for example if we want to test addition of long vectors, the generation of the vector as well as the reference result needs to be calculated elsewhere.

**Comment by kohr-h** [comment]
Should be sufficient if we do it outside the test function, Jenkins produces timing per test function. We should not use fixtures though, they cause the HTML output to be named by index, not by test function. I don't quite know why.

**Comment by kohr-h** [comment]
No, false alert, all good. Just the ufuncs and reductions tests end up in a separate link `test.discr.lp_discr_test` and with indices for the tests. Maybe a later pytest version will fix this.

**Comment by adler-j** [comment]
This is because I use `yield` with these. We could create a fixture for the same thing I suppose.

**Comment by kohr-h** [comment]
You write something about a pytest bug keeping you from doing so.

**Comment by adler-j** [comment]
Ah, that one, not really related. Basically the bug prevents you from mixing yield and fixtures, for example:

```python
def test_my_fun(space):
    for argument in [1, 2, 3]:
        yield _test_my_fun_impl, space, argument
```

py.test does not seem to recognize that I need a space fixture for this to work. We could write the whole test as

```python
def test_my_fun(space, argument):
    # to test
```

but then we'd need an `argument` fixture. Perhaps this is preferable.

**Comment by adler-j** [comment]
We have a start for this, close?

**Comment by kohr-h** [comment]
Is it in master yet?

**Comment by adler-j** [comment]
Good point, lets wait for that.

**Comment by kohr-h** [comment]
You seem to keep forgetting that there's an *actual* master branch ;-)
