### ISSUE TITLE
trivial ProductSpaceOperator

### ISSUE THREAD

**Issue by mehrhardt** [odlgroup/odl#1290]
this is not really an issue with ODL but rather a question how to implement something. I tried for a few hours myself but did not find a good way how to achieve what I wanted. My problem is the following.

Given an operator A, I want to define a new "ProductSpaceOperator" B such that B[0] = A. So, if A : X -> Y, then B : X -> Y ** 1. It may sound odd why I want this. This is for the stochastic PDHG as I would like to use the same implementation for n = 1, 2, ... . However, if n = 1, then one has the option to provide either the operator directly as a ProductSpaceOperator or as a normal operator.

The most promising approach I tried is `B = odl.ProductSpaceOperator([A])` but it did not quite work:

```
A = BroadcastOperator(PartialDerivative(
    uniform_discr([ 0.,  0.], [ 140.,  140.], (140, 140)),
    axis=0,
    pad_mode='symmetric'
), PartialDerivative(
    uniform_discr([ 0.,  0.], [ 140.,  140.], (140, 140)),
    axis=1,
    pad_mode='symmetric'
), OperatorLeftScalarMult(Blur2D(uniform_discr([ 0.,  0.], [ 140.,  140.], (140, 140)), array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.00014117,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.01709077,  0.10487391,  0.00014117],
       [ 0.        ,  0.        ,  0.01034763,  0.05699277,  0.08255521,
         0.1130805 ,  0.11157156,  0.00829128,  0.        ],
       [ 0.        ,  0.        ,  0.12334657,  0.04477073,  0.02423859,
         0.00367508,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.00482796,  0.10862899,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.03289691,  0.08210504,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.0487407 ,  0.02168345,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ]]), 'wrap'), 10.0))
```

and 

```
B = ProductSpaceOperator([[PartialDerivative(
    uniform_discr([ 0.,  0.], [ 140.,  140.], (140, 140)),
    axis=0,
    pad_mode='symmetric'
), PartialDerivative(
    uniform_discr([ 0.,  0.], [ 140.,  140.], (140, 140)),
    axis=1,
    pad_mode='symmetric'
), OperatorLeftScalarMult(Blur2D(uniform_discr([ 0.,  0.], [ 140.,  140.], (140, 140)), array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.00014117,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.01709077,  0.10487391,  0.00014117],
       [ 0.        ,  0.        ,  0.01034763,  0.05699277,  0.08255521,
         0.1130805 ,  0.11157156,  0.00829128,  0.        ],
       [ 0.        ,  0.        ,  0.12334657,  0.04477073,  0.02423859,
         0.00367508,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.00482796,  0.10862899,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.03289691,  0.08210504,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.0487407 ,  0.02168345,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ]]), 'wrap'), 10.0)]])
```

> A.range
> Out[76]: ProductSpace(uniform_discr([ 0.,  0.], [ 140.,  140.], (140, 140)), 3)
> 
> B[0].range
> Out[78]: uniform_discr([ 0.,  0.], [ 140.,  140.], (140, 140))

**Comment by kohr-h** [comment]
Oh boy, we got a bug here. Since `A` is a `BroadcastOperator` that supports indexing, `ProductSpaceOperator` believes that `[A]` is 2D (shape would be `(1, 3)`, with 3 being the length of `A`), and takes apart the operators in `A` as matrix entries.
The logically correct way to do this would probably be something like `ProductSpaceOperator([[A]])` or `BroadcastOperator(A)` but I'm not dead sure. I assume you tried this already because that doesn't work either.

I currently see no way of working around this since any indexable object with a length will in this case be interpreted as a sequence and turned into a row, also in Numpy. I also haven't managed to convince `scipy.sparse.coo_matrix` to just swallow the weird indexable type that is not supposed to be indexed.

It seems we need a better suited data storage for our `ProductSpaceOperator` objects, but I'm not sure what to use. Perhaps just a plain ol' dictionary? Maybe with some trickery like storing row and column indices separately in `set`s for faster lookup plus in Numpy arrays for faster indexing etc.

**Comment by kohr-h** [comment]
> It seems we need a better suited data storage for our ProductSpaceOperator objects, but I'm not sure what to use. Perhaps just a plain ol' dictionary? Maybe with some trickery like storing row and column indices separately in sets for faster lookup plus in Numpy arrays for faster indexing etc.

Or just reimplement the most basic functionality of COO sparse matrices with `dtype=object`, all in Python. How hard can it be? The current backend doesn't even support matrix multiplication.

**Comment by adler-j** [comment]
The problematic line seems to be this one:

https://github.com/odlgroup/odl/blob/6b73551e2287dc80315d455eb14a53c88c2addbe/odl/operator/pspace_ops.py#L161

One way to do this would be to "manually" extract the operators from the `operators` variable, and then use the `coo_matrix((data, (i, j)), [shape=(M, N)])` constructor of `coo_matrix`. That way we can control this ourselves.

Shouldn't be too bad, right?

**Comment by kohr-h** [comment]
That doesn't work either: it still believes that `[A]` is 2D, which is the whole source of the problem.

**Comment by adler-j** [comment]
Even if we give it the element-wise constructor with specific indices? It seems like there should be nothing to interpret then.

**Comment by kohr-h** [comment]
Sadly yes:
```python
>>> X = odl.rn(2)
>>> I = odl.IdentityOperator(X)
>>> A = odl.BroadcastOperator(I, I)
>>> i = [0]
>>> j = [0]
>>> data = [A]
>>> scipy.sparse.coo_matrix((data, (i, j)), shape=(1, 1))
Traceback (most recent call last):

  File "<ipython-input-24-1208eefded9e>", line 1, in <module>
    scipy.sparse.coo_matrix((data, (i, j)), shape=(1, 1))

  File "[...]\lib\site-packages\scipy\sparse\coo.py", line 191, in __init__
    self._check()

  File "[...]\lib\site-packages\scipy\sparse\coo.py", line 235, in _check
    if self.nnz > 0:

  File "[...]\lib\site-packages\scipy\sparse\base.py", line 221, in nnz
    return self.getnnz()

  File "[...]\lib\site-packages\scipy\sparse\coo.py", line 202, in getnnz
    raise ValueError('row, column, and data arrays must be 1-D')

ValueError: row, column, and data arrays must be 1-D
```
I guess we could bypass the check in some hacky way but I don't know if that's a good idea.

**Comment by kohr-h** [comment]
I looked at the scipy source code. Here's the solution:
```python
>>> X = odl.rn(2)
>>> I = odl.IdentityOperator(X)
>>> A = odl.BroadcastOperator(I, I)
>>> i = np.array([0])
>>> j = np.array([0])
>>> data = np.empty(1, dtype=object)  # force-feed Numpy
>>> data[0] = A
>>> scipy.sparse.coo_matrix((data, (i, j)), shape=(1, 1))  # Nothing more to interpret
<1x1 sparse matrix of type '<class 'numpy.object_'>'
	with 1 stored elements in COOrdinate format>
```

**Comment by mehrhardt** [comment]
Very good. Here are some of my experiences. Perhaps I am using your solution wrongly.

Option 1) `B = odl.ProductSpaceOperator([[A]])` appears to work fine. But the adjoint makes problems: 

> B.adjoint
> Traceback (most recent call last):
> 
>   File "<ipython-input-16-9037210ee17f>", line 1, in <module>
>     B.adjoint
> 
>   File "/home/ehrhardt/repositories/github_myodl/odl/operator/pspace_ops.py", line 430, in adjoint
>     adj_matrix = scipy.sparse.coo_matrix((adjoint_ops, indices), shape)
> 
>   File "/home/ehrhardt/anaconda2/envs/odl-py35/lib/python3.5/site-packages/scipy/sparse/coo.py", line 184, in __init__
>     self._check()
> 
>   File "/home/ehrhardt/anaconda2/envs/odl-py35/lib/python3.5/site-packages/scipy/sparse/coo.py", line 228, in _check
>     if self.nnz > 0:
> 
>   File "/home/ehrhardt/anaconda2/envs/odl-py35/lib/python3.5/site-packages/scipy/sparse/base.py", line 201, in nnz
>     return self.getnnz()
> 
>   File "/home/ehrhardt/anaconda2/envs/odl-py35/lib/python3.5/site-packages/scipy/sparse/coo.py", line 195, in getnnz
>     raise ValueError('row, column, and data arrays must be 1-D')
> 
> ValueError: row, column, and data arrays must be 1-D

Option 2) `B = odl.BroadcastOperator(A, 1)` works fine. No problems discovered so far.

Is this expected or another bug? What syntax would you recommend?
