### ISSUE TITLE
Warn about slow backends

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#1296]
In some settings, e.g. `FourierTransform` and `RayTransform`, we make backend choices defaulting to "best possible".

Currently there is no message about this, and users can possibly default to a backend that is so slow that it basically makes the code impossible to run. Compare e.g. `RayTransform` on a 512x512 grid with default parallel beam geometry

| `impl=`        | runtime (ms) |
|:---------------|--------------:|
| `'skimage'`    |      34 100     |
| `'astra_cpu'`  |     3 380     |
| `'astra_cuda'` |      25      |

Perhaps we should add a warning that for sufficiently large volumes `'skimage'` and even `'astra_cpu'` is not recommended.

The same could also be said about `pyfftw` vs `numpy` as backends for the Fourier transform, particularly in 3d.

**Comment by kohr-h** [comment]
I'm not so sure about spamming users with warnings. If we could find a way to emit a warning *once*, for instance during installation, I'd be fine, but a warning with every import, no.
However, the fallback behavior should be more prominent in the installation docs. It's currently implicit, one could also say undocumented.

**Comment by adler-j** [comment]
Well, we could make the warning happen upon automatic backend selection. Users could silence it by explicitly selecting the backend.

But yes, I'm very skeptical to warning "noise", it tends to be hard to understand and people very quickly start ignoring it.

**Comment by kohr-h** [comment]
> Well, we could make the warning happen upon automatic backend selection. Users could silence it by explicitly selecting the backend.

That doesn't sound too bad. Warn if auto-selection is used *and* the thus chosen backend is slow.

**Comment by kohr-h** [comment]
> That doesn't sound too bad. Warn if auto-selection is used and the thus chosen backend is slow.

And tell users how to silence the warning.

**Comment by adler-j** [comment]
I'll fix this myself.
