### ISSUE TITLE
Proper documentation of property.setter

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#1297]
As noticed by @aringh, `property.setter` methods do not really have any documentation, as is mentioned here:

https://stackoverflow.com/questions/23341106/python-2-7-doctests-ignored-in-setter-method-of-a-class

A side-effect of this is that doctests are only run on the getter.

So basically this means we should move any documentation from the setter into the getter.

**Comment by kohr-h** [comment]
Nice catch @aringh, @adler-j. We should move documentation out of the setters then.

**Comment by adler-j** [comment]
I'll assign this to myself and get it done.

**Comment by aringh** [comment]
I am a bit reluctant to removing all the documentation from all `setter`s. Although maybe not built in the documentation, at least for me it was quite helpful when going through the code to see what different parts are doing. I tried to make some kind of compromise in #1288, by keeping a minimal doc string but moving the doc-test to the `property` itself. What do you think about that?

**Comment by adler-j** [comment]
I'll do it in basically that way!
