### ISSUE TITLE
Overflow in size

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#1320]
Very easy to reproduce:

```python
>>> spc = odl.rn([10000]*3)
>>> spc.size
-727379968
```

**Comment by adler-j** [comment]
Happens for me with python 3.5, but I think *windows* is the key. Whoever decided that "long" should be the dtype of choice in python really did a mistake.

**Comment by kohr-h** [comment]
Huh? That's weird, the Python 3 `int` should be arbitrary precision and never overflow. It's probably a Numpy thing since they often use platform integers internally.

**Comment by kohr-h** [comment]
The implementation is `int(np.prod(self.shape))`, if you replace that with `functools.reduce(lambda x, y: int(x) * int(y), self.shape)` it should be fine (on Python 3, for Python 2 we may like to do `from builtins import int` locally).
