### ISSUE TITLE
Alternative boundary conditions for finite_diff

### ISSUE THREAD

**Issue by moosmann** [odlgroup/odl#133]
Implementation of alternatives boundary conditions is requested for the helper function `finite_diff` in module `odl.discr.discr_ops`.

**Comment by adler-j** [comment]
Modified title, the word "Implement" is somewhat rubberstamp for half of our issues and can be ignored for brevity.

**Comment by adler-j** [comment]
Whats left?

**Comment by adler-j** [comment]
We have some options now, are we fine with these?

**Comment by kohr-h** [comment]
There's still a TODO comment in the code of `finite_diff`. And the doc could use an update. And the derivative operators should default to the scheme that is implied by the underlying discretization.
