### ISSUE TITLE
Bug in OperatorRightVectorMult.derivative

### ISSUE THREAD

**Issue by ozanoktem** [odlgroup/odl#1330]
The current return statement is

``` 
return self.operator.derivative(x) * self.vector
``` 

but this missed pre-multiplying x by self.vector, it should be

``` 
return self.operator.derivative(x * self.vector) * self.vector
```

**Comment by kohr-h** [comment]
Oh, bummer.

We should, however, do the multiplication `x * self.vector` only if we have to, to which `self.operator.is_linear` is the closest approximation. Nonlinear operators that are their own derivatives (like `RealPart` are an unfortunate case where effort will be wasted.
