### ISSUE TITLE
Interpolation not working or not showing

### ISSUE THREAD

**Issue by mehrhardt** [odlgroup/odl#1336]
Not sure this is a bug or the desired behaviour, but the following example gives the same (visual) output in both cases. Could you comment on this?

```
import odl, numpy as np

space = odl.uniform_discr(-1, 1, 31, interp='nearest')
x = space.element(lambda x: np.exp(-x**2/2/0.25**2))
x.show()

space = odl.uniform_discr(-1, 1, 31, interp='linear')
x = space.element(lambda x: np.exp(-x**2/2/0.25**2))
x.show()
```

**Comment by aringh** [comment]
If you follow the chain from `uniform_discr` in this [file](https://github.com/odlgroup/odl/blob/master/odl/discr/lp_discr.py), it looks like the argument `interp` is never used. Instead, in `DiscreteLp` it looks like it is using the default `interp='nearest'` in the `__init__` method.

However, I don't know what python does if `kwargs` contains arguments with the same name as in the argument list. Will python then use the one provided by `kwargs` automatically? @adler-j or @kohr-h

**Comment by kohr-h** [comment]
> If you follow the chain from uniform_discr in this file, it looks like the argument interp is never used. Instead, in DiscreteLp it looks like it is using the default interp='nearest' in the __init__ method.

Not quite, the `interp` argument is in `kwargs`, and that one is passed all the way to the constructor of `DiscreteLp`.
The issue is that `interp` is not used in `DiscreteLpElement.show`! What's missing is something like
```python
if not isinstance(self.space.interp, tuple):
    # Otherwise different interp per axis
    kwargs['interp'] = self.space.interp
```

> However, I don't know what python does if kwargs contains arguments with the same name as in the argument list. Will python then use the one provided by kwargs automatically?

No, it will complain about multiple values for the same argument and raise a `TypeError`.

**Comment by aringh** [comment]
My bad, it should work correctly. Minimal working example for anyone else how have not fully understood the workings of **-arguments before: the following code
```python
def my_test_fun(my_arg='hi', **kwargs):
    print(my_arg)

def wrapper_my_test_fun(**kwargs):
    my_test_fun(**kwargs)

wrapper_my_test_fun(my_arg='small test')
```

gives the output `small test`
