### ISSUE TITLE
Readthedocs is dead

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#134]
It seems ReadTheDocs does not properly run `make clean` before the build. I'll see if there is some way to improve this.

**Comment by adler-j** [comment]
I've tried posting to an issue on this, but it seems our ReadTheDocs could be dead for a while, noone seems to be responding and we're not the first.

https://github.com/rtfd/readthedocs.org/issues/1770

**Comment by adler-j** [comment]
This could also cause issues with the change I did in commit DOC: remove autogenerated files from repo 7701de960c1d6877f6472706bf39d7df0d0bf3ff. Here I assume we build by `make html` etc, but it seems ReadTheDocs ignores the makefile and runs it's own scripts. 

Do you know if there is any way to handle this or to customize the build?

**Comment by adler-j** [comment]
Currently trying to fix this (hence the spam of commits to master). Still broken however. The current approach is to emulate the makefiles if on RTD.

**Comment by adler-j** [comment]
Now back to building with the obvious issue that it does not find the sub-packages, hence the doc is not properly populated. I'll see if it can be fixed.

**Comment by kohr-h** [comment]
There was one obvious error where the generating script was called under the wrong path in the Makefile. Maybe that's why RTD tried to do its own thing?

**Comment by adler-j** [comment]
No you found the error after I started this mess of commits. It was correct before, I'm trying to get RTD live now (debugging by pushing to git isnt the easiest), after that I'll restore anything broken.

**Comment by adler-j** [comment]
I think I solved it. I'm on windows atm, does everything seem to work on Linux as-well?

**Comment by adler-j** [comment]
It seems the biggest minus is that since I properly clear all files, the make is now even slower than before. I guess we can live with that though.

**Comment by kohr-h** [comment]
It's building at least. There is a build job for the docs on Jenkins, as you may have noticed. This one will probably succeed.

**Comment by kohr-h** [comment]
Well, the doc build step succeeds, but there are errors in the output.

**Comment by adler-j** [comment]
I cant see where it fails, do you see it? Ctrl-F finds no errors.

**Comment by kohr-h** [comment]
It's set to `FAILURE` due to 2 errors in the doc creation, dead links. Go to Jenkins, click on `odl-master-doc`, then on the most recent build and then on `Parsed Console Output`.

**Comment by kohr-h** [comment]
BTW, there are not really only 13 warnings, it's just that I filter out all the ones related to "not in any toctree" and the ambiguous links warnings.

**Comment by adler-j** [comment]
Ok, those two shouldnt inhibit the build, the `dict` one has been around for quite a while. I'll see if i can fix them.

**Comment by adler-j** [comment]
Attempted bug fixes commited. Regarding the ambiguous links warnings, are you sure you are using our fork of numpydoc? I dont get them anymore with it.

**Comment by adler-j** [comment]
It seems the `dict` thing could be related to this:

https://github.com/Abjad/abjad/issues/332

I've submitted a commit that should fix it.

**Comment by kohr-h** [comment]
> Attempted bug fixes commited. Regarding the ambiguous links warnings, are you sure you are using our fork of numpydoc? I dont get them anymore with it.

I think so. The job recursively updates submodules, so it should get the spinxext correctly.

**Comment by adler-j** [comment]
It seems readthedocs is up again, I'll close this once it builds a few times nicely.

**Comment by adler-j** [comment]
Seems to build, closing.
