### ISSUE TITLE
Finding a solver for my problem

### ISSUE THREAD

**Issue by miallo** [odlgroup/odl#1341]
Hello!
I know this is more of a personal problem but I am having a bit of a problem to find the right solver for my problem:
```python
reconSpace = ProductSpace(uniform_discr(dtype='complex'), 2)
f(x1, x2) = sum || abs(FFT(x_i)) - measurementData_i ||_2^2
g_Support(x1, x2) = sum || x_i * someMatrix ||
L_nuc(x1, x2) = [gradient(Real[x1, x2]), gradient(Imag[x1, x2])]
g_nuc(z1, z2) = sum nuclearNorm(z_i)
g_TNV = g_nuc * L_nuc  # or: nuclearNorm(gradient(Real[x1, x2])) + nuclearNorm(gradient(Imag[x1, x2]))
```

My problem is, that `f` does not have a proximal (in contrast to the [example](https://github.com/adler-j/odl-stem-examples/blob/master/multimodal_kl_nuclear.py) of @adler-j so I can't use the `douglas_rachford_pd` solver. But I must use a solver with separated `g` and `L`, since otherwise `g_TNV` doesn't have any of the properties:

|   | grad | proximal  | convex_conj  | convex_conj.proximal  |
|---|---|---|---|---|
| **f**  | x  |   |   |   |
| **g_Support**  | x  | x  | x  | x  |
| **g_TNV**  |   |   |   |   |
| **g_nuc**  |   | x  | x  | x  |

I didn't find any solver that would work for me. Any ideas on what I can do? (Appart from scrapping the `nuclearNorm`?)

**Comment by adler-j** [comment]
How about [`forward_backward_pd`](https://odlgroup.github.io/odl/generated/odl.solvers.nonsmooth.forward_backward.forward_backward_pd.html#odl.solvers.nonsmooth.forward_backward.forward_backward_pd), it supports all of the components you are discussing if I'm not wrong.

**Comment by miallo** [comment]
Oh, right, I didn’t see the `h` When looking through the solvers...

**Comment by adler-j** [comment]
With that said, you could also use proximal based solvers by using splitting since we do know the proximal of `|| . ||_2^2`!

**Comment by miallo** [comment]
You mean if I don't use the SeparableSum, but instead use a projection on the subspaces? That also sounds quite reasonable.

**Comment by miallo** [comment]
But wait. The operator inside of the norm is not linear: I take the absolute value of something complex. And so I couldn't spilt them into `g` & `L`; but if I didn't, the proximal is not trivial anymore, correct?
