### ISSUE TITLE
Possibility to turn off color bars in 2D image plots?

### ISSUE THREAD

**Issue by aringh** [odlgroup/odl#1342]
Should we add a possibility to turn off the color barn for the `.show` method for discrete data? One way to do it is to add a bolean flag which is used [here](https://github.com/odlgroup/odl/blob/master/odl/util/graphics.py#L412), e.g., `if method == 'imshow' and show_2d_color_bar:`.

I have a vague recollation of a similar discussion before, but could not find anything in the issue history. The reason that I ask is since I have found a case when this would be nice :-p, but maybe it is to specific and not generic need.

**Comment by adler-j** [comment]
Overall I'm in favor of being careful about adding too many "extras" to these functions. They are after all simply intended to be a quick baseline to see what is happening.

With that said, this sounds quite reasonable and reasonably easy to handle. I'd suggest try it out and see how it looks.

**Comment by aringh** [comment]
Closed via #1343
