### ISSUE TITLE
Licence for content in odl.contrib.datasets

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#1345]
It's not obvious from the documentation what licence applies here. Does @mehrhardt know?

**Comment by mehrhardt** [comment]
Good question. I initially thought that it would be covered by the https://mozilla.org/MPL/2.0/ license but the text in the source files explicitly says that this is only for the source files themselves. What licenses are the other data sets? The CT data set has the same issue, no?

**Comment by adler-j** [comment]
I guess the issue is quite general yes.

If you want to release them under e.g. MPL (or creative commons for images would be the most liberal I guess) that would be great, but it should be stated somewhere.

**Comment by aringh** [comment]
Is this solved with PR #1352? Or does it concern also the other data sets?

**Comment by mehrhardt** [comment]
I think ideally every data set has a license statement so I suggest to keep this open.

**Comment by kohr-h** [comment]
There's also this:
```
# You should have received a copy of the license along with this
# work. If not, see <http://creativecommons.org/licenses/by/4.0/>.
```
But we don't include a copy of the license. I guess we should do that.
