### ISSUE TITLE
Adjoint of SamplingOperator error in 1D

### ISSUE THREAD

**Issue by nabriis** [odlgroup/odl#1350]
The adjoint of the SamplingOperator is not working for me. 

ODL version.
'0.6.1.dev0'

Minimal example
````
import numpy as np
import odl

U = odl.uniform_discr(0, 100, 100) 
u = U.one()

idx = [2,3,4]

E = odl.SamplingOperator(U,idx)

E.adjoint(E(u))
```

**Comment by adler-j** [comment]
This should now be fixed, thanks again for the bug report!

**Comment by nabriis** [comment]
Works great. Thank you :)
