### ISSUE TITLE
Easy way to run tests in odl.contrib?

### ISSUE THREAD

**Issue by aringh** [odlgroup/odl#1354]
As it is now, the tests in `odl.contrib` are not run by travis (neither when one runs `py.test` in the terminal). Is there an easy way to run all the test in the contrib-package? Could one add a flag to pytest so that it also runs the test in the contrib-package?

**Edit**: individual tests can be run by
```bash
py.test path/to/test/test_myfun.py
```
but for example
```bash
py.test odl/contrib/
```
runs no test.

**Comment by kohr-h** [comment]
How about
```
pytest odl/contrib/<something>/test/
```
? Does that run the tests?

**Comment by adler-j** [comment]
We've intentionally decided to not have a "run all contrib tests" since that is basically guaranteed to fail since any one user will likely not have all dependencies installed at once. Some contrib packages might even be OS specific. I'm sure @kohr-h's approach should work though.

**Comment by aringh** [comment]
Unfortunately I don't get @kohr-h's approach to work. For example:

```bash
pytest odl/contrib/fom/test/
============================= test session starts ==============================
platform linux -- Python 3.6.4, pytest-3.3.2, py-1.5.2, pluggy-0.6.0
rootdir: [...]/odl/odl, inifile: pytest.ini
plugins: odl-0.6.1.dev0, pep8-1.0.6
collected 0 items                                                              

========================= no tests ran in 0.00 seconds =========================
```

I understand the arguments against having something that runs all contrib test. However, one issue with not being able to run all tests easily is that I think we have test fails we do not know about in the contrib package. For example, I get one test fail when I run the tests for unsupervised foms.

**Comment by aringh** [comment]
So, I did not get the suggestion by @kohr-h to work. I get
```
$ pytest odl/contrib/fom/test/
============================= test session starts ==============================
platform linux -- Python 3.6.1, pytest-3.0.5, py-1.4.33, pluggy-0.4.0
rootdir: [...]/odl/odl, inifile: pytest.ini
plugins: odl-0.6.1.dev0, pep8-1.0.6
collected 0 items 

========================= no tests ran in 0.00 seconds =========================
``` 
However, I get the following to work
```
$ pytest odl/contrib/fom/test/*
============================= test session starts ==============================
platform linux -- Python 3.6.1, pytest-3.0.5, py-1.4.33, pluggy-0.4.0
rootdir: [..]/odl/odl, inifile: pytest.ini
plugins: odl-0.6.1.dev0, pep8-1.0.6
collected 14 items 

odl/contrib/fom/test/test_supervised.py .s......
odl/contrib/fom/test/test_unsupervised.py ......

===================== 13 passed, 1 skipped in 0.24 seconds =====================
```
By that there is indeed a simple way to run all tests in each of the parts of `contrib` (or even large part of `contrib` at the same time by `pytest odl/contrib/*/test/*`) why I consider this closed.

**Comment by kohr-h** [comment]
Hey, that's actually quite useful information. How about adding that to [contrib/README.md](https://github.com/odlgroup/odl/blob/master/odl/contrib/README.md)?

**Comment by adler-j** [comment]
Good idea from @kohr-h. But shouldnt `pytest odl/contrib/*` work?

**Comment by kohr-h** [comment]
I'll reopen this to track that doc addition.

**Comment by aringh** [comment]
Regarding @adler-j's comment: I just get this
```
$ pytest odl/contrib/*
============================= test session starts ==============================
platform linux -- Python 3.6.1, pytest-3.0.5, py-1.4.33, pluggy-0.4.0
rootdir: [...]/odl/odl, inifile: pytest.ini
plugins: odl-0.6.1.dev0, pep8-1.0.6
collecting 0 items
========================= no tests ran in 0.01 seconds =========================
ERROR: not found: /home/axel/git/odl/odl/contrib/README.md
(no name '[...]/odl/odl/contrib/README.md' in any of [])
```

**Comment by adler-j** [comment]
Good that you investigated it and nice fix!
