### ISSUE TITLE
Diagnostics seems fully broken

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#136]
This package has not worked for a while, should be solved by the operator branch.

**Comment by kohr-h** [comment]
Closed by #116

**Comment by adler-j** [comment]
This has been actually tested?

**Comment by kohr-h** [comment]
I ran the examples using diagnostics, `space_test` for the spaces and several others for the operators. There's a bug in the CUDA spaces (#184) related to `dist`, but everything else works.
