### ISSUE TITLE
Set default order to 'F' in DiscreteLp for cuda

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#138]
It seems CUDA uses this order internally, so we should likely have this as a default.

**Comment by kohr-h** [comment]
Okay, agreed.

**Comment by adler-j** [comment]
The more i've thought of this, the more I feel that we should stay consistent inside ODL rather than focus on cuda, thus I say we keep 'C' order. Other than that, this should be an issue in `odlcuda` now.

**Comment by kohr-h** [comment]
Wouldn't it be best if the space implementation would define its own default ordering? It could be optional and default to `'C'`. Becomes even more relevant in the (truly) multi-dimensional data storage case, i.e. Numpy arrays as tensors, or arrays based on `libgpuarray`.

**Comment by adler-j** [comment]
> Wouldn't it be best if the space implementation would define its own default ordering?

`DiscreteLp` already does this, and it is `'C'`, or do you mean that the `dspace` should define the ordering?

> Becomes even more relevant in the (truly) multi-dimensional data storage case, i.e. Numpy arrays as tensors, or arrays based on libgpuarray.

Certainly agree here.

**Comment by kohr-h** [comment]
> DiscreteLp already does this, and it is 'C', or do you mean that the dspace should define the ordering?

That's what I meant, yes. But perhaps we can postpone that until we have multi-dimensional storage and go with default 'C' for now.
