### ISSUE TITLE
Axis of show() slightly off

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#139]
It seems the axis of show uses the grid points and not the full voxels, an example is

```python
>>> disc = odl.uniform_discr([-1, -1], [1, 1], [5, 5])
>>> odl.util.shepp_logan(disc).show()
```

which gives

![bug](http://i.imgur.com/xYhUb98.png)

Here, the axises should be labeled from -1 to 1, but it seems we use the midpoints (-0.8, -0.4, 0.0, 0.4, 0.8) in this case.

I'll try to fix this.

**Comment by adler-j** [comment]
Now much better:

![bug](http://i.imgur.com/oiwzeZC.png)

**Comment by kohr-h** [comment]
Indeed!
