### ISSUE TITLE
Change structure of odlpp

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#14]
I suggest that we do the following:

We make `odlpp` a proper sub-package. I.e. we move all `odl/space/cu_ntuples` and `test/space/cu_ntuples` out of this repo and into the current `odlpp` repo.

We then change `odlpp` to `odl-cuda`

Finally we make `odlpp` a [Namespace package](https://pythonhosted.org/setuptools/setuptools.html#namespace-packages). What this means is that the users can install it separately, and it will appear just as now under `odl.space.cuda`.

What do we think?

**Comment by adler-j** [comment]
This has been canceled now. The new suggestion is that we:

* Make the folders `odl/cuda/` and `test/cuda`
* Move `odl/space/cu_ntuples` to `odl/cuda`
* Move `test/space/cu_ntuples_test` to `test/cuda`
* Move `test/operator/difference_test_cuda` to `test/cuda` (possibly remove this?)
* Leave `odlpp` where it is, its package structure has been changed so building `cuda` is optional, and adding more packages should be easy.

**Comment by kohr-h** [comment]
Agree.

**Comment by adler-j** [comment]
These ideas are way outdated, closing.
