### ISSUE TITLE
Drop Python 3.4 from tests

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#1425]
I suggest that we drop Python 3.4 from our tests. We might still want to build wheels and conda packages, but the language at version 3.4 is not so different from later versions that separate unit tests are really necessary.

Just as a side note, when making a conda test environment for Python 3.4, it pulls in NumPy 1.11 and SciPy 0.18, which are several versions behind. So upstream support of our dependencies is fading as well.

**Comment by adler-j** [comment]
I agree, 3.4 is not widely used at all so it can be realtively safely dropped from the tests.

**Comment by kohr-h** [comment]
Actually this is already done, so I'll close it.
