### ISSUE TITLE
More phantoms?

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#143]
I need input from others here, perhaps @niinimaki and @moosmann? What phantoms do we want available? We currently have a util that creates some phantoms, but what are we missing?

- [x] Modified Shepp-Logan 2d ![1](http://i.imgur.com/24dqTJx.png)
- [x] Modified Shepp-Logan 3d
- [x] Shepp-Logan 2d
- [x] Shepp-Logan 3d
- [x] Derenzo 2d ![3](http://i.imgur.com/EhU1Hdu.png)
- [ ] Derenzo 3d

More?

**Comment by adler-j** [comment]
Added normal shepp-logan phantom.

**Comment by moosmann** [comment]
It would be good to have:
* Shepp-Logan phantom with a gradient to test TV regularization for staircasing artefacts.
* Phantoms with noise. For comparisons it's maybe good to have a fixed noise component such that phantoms do not vary from run to run.
*  Very simple phantom for implementing backends: a small rectangle or cuboid in a quadrant to quickly check the feasibility of the projections data, the direction of rotation, the projection direction, etc

**Comment by kohr-h** [comment]
> Phantoms with noise. For comparisons it's maybe good to have a fixed noise component such that phantoms do not vary from run to run.

Set the seed in `np.random`?



> Very simple phantom for implementing backends: a small rectangle or cuboid in a quadrant to quickly check the feasibility of the projections data, the direction of rotation, the projection direction, etc

Sounds reasonable.

**Comment by adler-j** [comment]
> Shepp-Logan phantom with a gradient to test TV regularization for staircasing artefacts.

What method would be preferable to do this? Applying a post-smoothing?

>> Phantoms with noise. For comparisons it's maybe good to have a fixed noise component such that phantoms do not vary from run to run.

>Set the seed in np.random?

The seed is global and quite hacky, but sure it works.

My takeaway from the two suggestions above is that we should add `**kwargs` to the phantoms, like `smoothing=0.05` or `noise=white`. These could in turn be implemented with a backend function that basically wraps numpy. We could perhaps add a `seed` option to the noise as-well.

> Very simple phantom for implementing backends: a small rectangle or cuboid in a quadrant to quickly check the feasibility of the projections data, the direction of rotation, the projection direction, etc

Sure, naming suggestion?

**Comment by moosmann** [comment]
>> Shepp-Logan phantom with a gradient to test TV regularization for staircasing artefacts.
 
> What method would be preferable to do this? Applying a post-smoothing?

I think to start with a linear variation of the phantom along one of the axis should do, eg:

![shepp_log](https://cloud.githubusercontent.com/assets/6815901/11779616/ac241fc0-a25c-11e5-92b8-5e1ffe02594d.png)

**Comment by adler-j** [comment]
Thats quite specific, how about you simply

```
>>> X = odl.unifrom_discr([0, 0], [1, 1], [100, 100])
>>> phantom = odl.util.shepp_logan(X)
>>> phantom = phantom.ufunc.multiply(X.points()[:,0])
>>> phantom.show()
```

![result](http://i.imgur.com/HnHFUzE.png)

**Comment by adler-j** [comment]
Ongoing work, but nothing needed atm, right?

**Comment by kohr-h** [comment]
Yes, this was the kickoff. We'll simply add more when needed.
