### ISSUE TITLE
Benchmark attribute lookup implementations

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#1431]
See [this comment](https://github.com/odlgroup/odl/pull/1043#discussion_r216107838) for details.

The gist is: in the light of [PEP 509](https://www.python.org/dev/peps/pep-0509/), we should revise and benchmark this
```python
def __init__(self):
    self.__attr = None

@property
def attr(self):
    if self.__attr is None:
        a = compute_attr()
        self.__attr = a
        return a
    else:
        return self.__attr
```
against this:
```python
@property
def attr(self):
    try:
        return self.__attr
    except AttributeError:
        a = compute_attr()
        self.__attr = a
        return a
```

**Comment by adler-j** [comment]
Should be a rather easy exercise :)

**Comment by kohr-h** [comment]
I just tested the above code with some trivial `compute_attr()`. Doesn't matter anyway. The result: the top variant takes about 23 % more time than the bottom variant on Python 3.6, similarly in 3.5. I'll close this as resolved.

**Comment by adler-j** [comment]
For how many accesses is that? One would expect the same runtime in case of "infinitely many"?

**Comment by kohr-h** [comment]
These are the classes I used:
```python
class A(object):
    def __init__(self):
        self.__attr = None

    @property
    def attr(self):
        if self.__attr is None:
            a = 2 * 3 * 4
            self.__attr = a
            return a
        else:
            return self.__attr


class B(object):
    @property
    def attr(self):
        try:
            return self.__attr
        except AttributeError:
            a = 1 * 2 * 3
            self.__attr = a
            return a
```
And I ran this code (in a pure Python interpreter, not IPython):
```python
>>> import timeit
>>> a_res = [timeit.timeit("a.attr", setup="a = A()", globals={"A": A}) for _ in range(50)]
>>> b_res = [timeit.timeit("b.attr", setup="b = B()", globals={"B": B}) for _ in range(50)]
>>> a_mean = sum(a_res) / len(a_res)
>>> b_mean = sum(b_res) / len(b_res)
```
Note: `timeit.timeit` defaults to 1e6 runs.

Here's a graph of the results (means as horizontal lines):
![access_times](https://user-images.githubusercontent.com/5030250/45257027-6fb36580-b39f-11e8-9c69-5c4eb9b987a1.png)

**Comment by kohr-h** [comment]
> One would expect the same runtime in case of "infinitely many"?

It seems not to be the case. My best guess is that the `try... except` construct literally runs the code unobstructed, whereas the other variant has to do a comparison against `None` each time.
