### ISSUE TITLE
How to exclude module name in leaf value of Identityref during ODL validation?

### ISSUE THREAD

**Issue by Dashia18** [odlgroup/odl#1447]
I have YANG model and JSON object which will be verified by ODL.

I need to exclude module name from JSON to verify.

When I exclude module name from identityref (**"type": "center-car-sale-type:sedan"**) and send only identityref name (**"type": "sedan"**) ODL throw exception that this identityref is not found:
**_"Parsed QName (car?revision=2017-04-11)car-type does not refer to a valid identity"_**

I want to send object without module name "module name" only "identityref name" to simplify work with big amount of data.

How can I set up ODL validation to avoid module name in leaf value for identityref?

I parse JSON by **_JsonParserStream.parse_**(JsonReader) from org.opendaylight.yangtools.yang.data.codec.gson module.

Thank you in advance!

**Comment by sbanert** [comment]
This is the not the right ODL. For Opendaylight, see https://github.com/opendaylight.

**Comment by Dashia18** [comment]
I am sorry!
