### ISSUE TITLE
Travis-CI broken

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#1450]
It seems they are migrating from travis-ci.org to travis-ci.com, with some related issues. I've sent them an email according to "https://docs.travis-ci.com/user/open-source-on-travis-ci-com/#existing-open-source-repositories-on-travis-ciorg" and asked for help in migrating.

Currently all of our build tests are failing.

**Comment by adler-j** [comment]
It's now ported, hoping to get it up and running with the PRs

**Comment by adler-j** [comment]
This now seems to be alive again. Are we happy with the new version @kohr-h?

**Comment by kohr-h** [comment]
General answer: If it works, yes. :-)

What exactly did change?

**Comment by adler-j** [comment]
It was 

* ported from a .org address to a .com address
* Changed to GitHub apps (see https://blog.travis-ci.com/2018-09-27-deprecating-github-commit-status-api-for-github-apps-managed-repositories)
