### ISSUE TITLE
Remove FunctionSpace, Discretization and FunctionSpaceMapping classes

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#1457]
All of those classes don't really serve a purpose and just add code and complexity. Nobody will miss them.

### `FunctionSpace`

The only purpose of `FunctionSpace` is to temporarily create a `FunctionSpaceElement` that is immediately turned into a discretized element of some space. That whole functionality could be reduced to a single Python function.
The `FunctionSpaceElement` objects implement a bunch of (arithmetic and other) methods that are never used. Apart from blowing up the test suite, there is no use for it.

### `Discretization`

This one is nothing but an annoying layer between `DiscreteLp` and `TensorSpace`. Any meaningful functionality it implements (not a lot) could just be placed on `DiscreteLp` directly.
Its element class is entirely useless.

### `FunctionSpaceMapping`

If this weren't a property of `Discretization` spaces, they could just be `Operator`s. A problem similar to that of `Weighting`s that cannot be `Operator`s either. All a `FunctionSpaceMapping` does is to either perform point collocation or interpolation. That could easily be moved into a couple of normal Python functions.

**Comment by adler-j** [comment]
I'm fine with removing these, but we really need to make sure that element creation in discretised spaces using lambdas is still supported. Other than that, go ahead imo.

Reducing complexity like this would really make ODL more accessible to large communities.

**Comment by mehrhardt** [comment]
I can't really judge whether these classes are needed at the moment but I am a strong supporter of reducing complexity. I introduced two of my students to ODL and I have to admit that it gave them a hard time. Partly because it is difficult to "just look at the code of ODL" partly due to these many classes / layers.

**Comment by adler-j** [comment]
Ok, so then I think we're in agreement that these "not so useful" classes should be removed, the main discussion is on #1458 I guess.
