### ISSUE TITLE
Decorated fixture parameters don't work any more

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#1460]
With latest pytest 4.2.0 the Fourier transform tests raise an error if some tests ought to be skipped due to missing backend:
```
[...]
if impl not in _SUPPORTED_FOURIER_IMPLS:
>           raise ValueError("`impl` '{}' not supported".format(impl_in))
E           ValueError: `impl` 'MarkDecorator(mark=Mark(name='skipif', args=('False', 'numpy'), kwargs={'reason': 'Fill in, never skips'}))' not supported

odl/trafos/fourier.py:94: ValueError
```

Either this was never an intended use of the `MarkDecorator`, or it got deprecated. In any case, we need to do something.

**Comment by adler-j** [comment]
Is this related to the error

```
_pytest.warning_types.RemovedInPytest4Warning: Applying marks directly to parameters is deprecated, please use pytest.param(..., marks=...) instead.
```

that I'm getting?

**Comment by kohr-h** [comment]
Yes, that looks exactly like the error. If you check out the fix in the above commit, I'm using the recommended fix.

**Comment by adler-j** [comment]
Can't you cherry pick that commit?

**Comment by kohr-h** [comment]
See #1461
