### ISSUE TITLE
error after latest changes

### ISSUE THREAD

**Issue by mehrhardt** [odlgroup/odl#1464]
If I fetch the most recent version of master, I get the error below. Checking out a version from 3 weeks ago is just fine. Perhaps @kohr-h hasn't committed all updated files?

```
In [1]: import odl
Traceback (most recent call last):

  File "<ipython-input-1-e3f6ebf773b2>", line 1, in <module>
    import odl

  File "/Users/me549/repositories/github_myodl/odl/__init__.py", line 47, in <module>
    from .set import *

  File "/Users/me549/repositories/github_myodl/odl/set/__init__.py", line 15, in <module>
    from .sets import *

  File "/Users/me549/repositories/github_myodl/odl/set/sets.py", line 17, in <module>
    from odl.util import is_int_dtype, is_real_dtype, is_numeric_dtype, unique

  File "/Users/me549/repositories/github_myodl/odl/util/__init__.py", line 15, in <module>
    from .testutils import *

  File "/Users/me549/repositories/github_myodl/odl/util/testutils.py", line 208, in <module>
    from odl.util import OptionalArgDecorator as identity

ImportError: cannot import name 'OptionalArgDecorator'
```

**Comment by adler-j** [comment]
The problem is that this is a codepath that we cannot test (since it only happens when pytest is not installed). We should be able to fix it rather easily though, it looks like a case of "circular" imports. Could you try moving testutils to the end in [this file](https://github.com/odlgroup/odl/blob/1085045b9fcfc6b375d3f5ff52dcb58a91f9ec67/odl/util/__init__.py)?

**Comment by kohr-h** [comment]
That doesn't avoid the circular import either. I've reverted to the trivial implementation from earlier, see #1465

**Comment by kohr-h** [comment]
Thanks for reporting this, @mehrhardt Indeed, this is kind of a blind spot since all tests environments do have `pytest` installed. Not sure what we should do about it, though.

**Comment by adler-j** [comment]
This should be fixed, tell us if something is still wrong @mehrhardt

**Comment by kohr-h** [comment]
For me it works fine when `pytest` is not installed. Before, I could reproduce the error.

**Comment by kohr-h** [comment]
I've created an issue for the missing test scenarios.
