### ISSUE TITLE
Unexpected behavior of ReductionOperator and SeparableSum ?

### ISSUE THREAD

**Issue by zickert** [odlgroup/odl#1467]
```
import odl
space = odl.rn(2)
L2 = odl.solvers.L2Norm(space)
identity = odl.IdentityOperator(space)
sep_sum = odl.solvers.SeparableSum(identity, 2)  # This should produce an error?
red_op = odl.ReductionOperator(L2, 2)  # This should work?
```
ODL _does not_ complain when I define `sep_sum` above as the `SeparableSum` of two operators which are not functionals. It _does_ complain when I try to define `red_op` as the the `ReductionOperator` of two functionals (so in particular, they are operators). This seems like unexpected behavior?

**Comment by adler-j** [comment]
I fully agree that this is buggy behaviour. Would you be interested in helping out to fix it?

**Comment by zickert** [comment]
Sure, I will look into it.
