### ISSUE TITLE
Squish commits for PR

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#1471]
Maybe it's a good idea to start squishing commits in PRs into one. That allows a bit more sloppiness in intermediate commits since they would only appear as items in the final commit message.

The main advantage of not squishing is that you have better granularity for tools like `git bisect` to find sources of errors. But in my experience, lots of intermediate commits are broken anyway, so `git bisect` would just return noise.

**Comment by adler-j** [comment]
I agree with this, but we should also strive to keep PRs as small as possible to make e.g. review easier.

**Comment by kohr-h** [comment]
>  keep PRs as small as possible

That's on me I guess :-)

Anyway, I'll call this an agreement and close the issue. From now on I'll use the squashing feature for PRs.
