### ISSUE TITLE
Operator norm of ray transform is not discretization invariant

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#1495]
Minimal example:

```
import odl
import numpy as np

size = 32
space = odl.uniform_discr([-200, -200], [200, 200], [size, size])
geometry = odl.tomo.cone_beam_geometry(space, src_radius=1000, det_radius=1000)
rt = odl.tomo.RayTransform(space, geometry)

rt.norm(True)  # prints 246.27631688614636

phantom = space.one()
data = rt(phantom)
adj = rt.adjoint(data)
np.mean(adj)  # prints 59454.131433649498
```

While a larger discretization gives different values:

```
import odl
import numpy as np

size = 512
space = odl.uniform_discr([-200, -200], [200, 200], [size, size])
geometry = odl.tomo.cone_beam_geometry(space, src_radius=1000, det_radius=1000)
rt = odl.tomo.RayTransform(space, geometry)

rt.norm(True)  # prints 61.577006241473185

phantom = space.one()
data = rt(phantom)
adj = rt.adjoint(data) 
np.mean(adj)  # prints 3716.4732131173164
```

Some other observations:

* The problem does not exist with parallel beam geometry
* The forward transform seems discretization invariant in 3D, but not 2D.
* The problem exists with cone beam geometries (in fact, it seems worse in this setting, and the scaling goes the other way around).

My astra installation is downloaded from the astra dev branch on conda lately.

```
>>> astra.__version__
'1.9.0dev'
```

**Comment by adler-j** [comment]
So it seems I needed to update my ODL (but it was not very old frankly), this seems to fix the issue in 3D but it persists in 2D.

**Comment by kohr-h** [comment]
I think in the latest dev build of ASTRA, some scalings in the 2D case changed, likely related to https://github.com/odlgroup/odl/issues/1415. I currently get test failures, also on CPU.

**Comment by adler-j** [comment]
I'll close this in favor of #1415.
