### ISSUE TITLE
Angle measurements of parallel beam CT geometry not shifted inwards at domain boundary

### ISSUE THREAD

**Issue by RingoIngo** [odlgroup/odl#1497]
I am using odl 0.7.0 and would like to use an angle partition for a low dose parallel 2D geometry where measurements are taken every 5 degrees starting at 0 degrees, i.e. measurements at `[0, 5, …, 175]` degrees. To make sure that the measurements at the border (0 degrees and 175 degrees) are not shifted I guess I have to use `nodes_on_bdry=True` in the angle partition. However, creating a ray transform `ray_trafo` with this setup results in an exception when constructing the fbp with 

```
odl.tomo.analytic.filtered_back_projection.fbp_op(ray_trafo)
```

This does not happen when setting `nodes_on_bdry=False` in the angle partition. (However, then I think the measurements at the boundary are shifted inwards). I appended a minimum working example in a python notebook converted to pdf and would greatly appreciate any hints on the issue.

[Minimum working example.pdf](https://github.com/odlgroup/odl/files/3187478/Minimum.working.example.pdf)

**Comment by adler-j** [comment]
Could you try with the latest version of ODL, just run

```
pip install https://github.com/odlgroup/odl/archive/master.zip
```

**Comment by RingoIngo** [comment]
Then I run into the problem mentioned in issue #1498 when importing ODL.

**Comment by adler-j** [comment]
Ok, sorry about that. We'll try fixing it asap. Meanwhile perhaps git clone ODL and install from source so we can fix this as well, could you do that?

**Comment by adler-j** [comment]
#1498 is now fixed, could you please try again and we can try to debug this?

**Comment by adler-j** [comment]
Ok, I've reproduced the issue, see this colab:

https://colab.research.google.com/drive/1tkP7nLja54Gbrh9r_AZtL8r3Wk9I9Aec

**Comment by RingoIngo** [comment]
Thanks for reproducing the issue, Jonas!
