### ISSUE TITLE
Wavelet tests take too much time

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#150]
The wavelet tests take about 1.5 seconds now, which is too much in relation to the rest of the library. We should make smaller examples and add some larger test cases to our "largescale" test suite once it's there.

**Comment by niinimaki** [comment]
I can reduce the sizes of the examples. What would be the "optimal rate of reduce" (..on my machine the wavelet tests take about 0.7 seconds..)

**Comment by kohr-h** [comment]
Make them as small as possible such that they still "make sense". Reduce the smallest size in the test to `(1, 1)` or whatever is the smallest possible, instead of `(8, 8)`. Another quite remarkable observation from the test results
```
test_DiscreteWaveletTrafo                           0.28 sec
test_coeff_size_list                                0.57 sec
test_pywt_coeff_to_array_and_array_to_pywt_coeff2d	5 ms	Passed
test_pywt_coeff_to_array_and_array_to_pywt_coeff3d	0.13 sec	Passed
test_wavelet_decomposition3d_and_reconstruction3d	0.36 sec	Passed
```
is that the `test_coeff_size_list` takes longer time than all the other tests, even longer than the decomposition and reconstruction test. This is a red flag since this function is only supposed to be a helper and, if possible, instantaneous.

**Comment by kohr-h** [comment]
Much of this is probably related to #153.

**Comment by adler-j** [comment]
#153 is now closed, how about this?

**Comment by kohr-h** [comment]
The open pull request contains some reduction in test problem sizes. If we get down to acceptable times by that, we can close.

**Comment by kohr-h** [comment]
But the `test_coeff_size_list` is no basically instantaneous.

**Comment by adler-j** [comment]
Close this?

**Comment by kohr-h** [comment]
Last time we had 0.23 seconds, I guess we're good with that.

**Comment by adler-j** [comment]
Good enough for now I guess.
