### ISSUE TITLE
Plot vector field

### ISSUE THREAD

**Issue by chongchenmath** [odlgroup/odl#1502]
Hi! How to plot the vector field in various scale?
```
rec_space = uniform_discr(min_pt=[-4.5, -4.5], max_pt=[4.5, 4.5], shape=[120, 120], dtype='float32', interp='linear')
pspace = rec_space.tangent_bundle
vector_field = pspace.one()
```

**Comment by adler-j** [comment]
Hi @chongchenmath! Sorry about the late answer, but did you solve this problem? In that case it would be great to have a solution here so others can use it :)
