### ISSUE TITLE
Error with adjoint of adjoint of FlatteningOperator

### ISSUE THREAD

**Issue by mehrhardt** [odlgroup/odl#1507]
The minimal example that reproduces the error is:

```
import odl

U = odl.uniform_discr(-1, 1, 10)
F = odl.FlatteningOperator(U)
F.adjoint.adjoint
```

> Traceback (most recent call last):
> 
>   File "<ipython-input-32-9ea3e960878c>", line 5, in <module>
>     F.adjoint.adjoint
> 
>   File "/Users/me549/repositories/github_myodl/odl/operator/operator.py", line 1672, in adjoint
>     return self.scalar.conjugate() * self.operator.adjoint
> 
> TypeError: unsupported operand type(s) for *: 'float' and 'method'

**Comment by kohr-h** [comment]
That's because `adjoint` of the inverse (used for adjoint, too) is missing a `@property` decorator:

https://github.com/odlgroup/odl/blob/c14cad5ec3ee6fe878a48023ed774be719d8047b/odl/operator/tensor_ops.py#L1538-L1541

**Comment by kohr-h** [comment]
Thanks for pointing it out @mehrhardt! (Demonstrates the lack of tests for this operator.)

**Comment by adler-j** [comment]
See #1508
