### ISSUE TITLE
DiscreteXrayTransform does not use weighting properly

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#151]
The current implementation of the `DiscreteXrayTransform` operator initializes a `DiscreteLp` for its range from the given geometry, however without using proper weighing. This should be fixed.

**Comment by kohr-h** [comment]
I should add that this refers to a branch. The exact location of the bug is [here](https://github.com/odlgroup/odl/blob/issue-87__conebeam/odl/tomo/operators/xray_trafo.py#L117-L118). The space initializer should use `grid.cell_volume()` as weight.

This is only a temporary fix, we need to have a closer look on the desired structure of the range.

**Comment by adler-j** [comment]
This should be fixed now, correct?

**Comment by kohr-h** [comment]
It is indeed, but still on a branch, so technically it's still open. But since there is no bug on `master`, let's say it's fixed. We should, however, open a new one regarding non-uniform sampling of the angles and the weights which follow from that. It's not supported yet.
