### ISSUE TITLE
test_L1_norm[ space=power_space_unif_discr - sigma=10 - tspace_impl='numpy' ]: TypeError: len() of unsized Object

### ISSUE THREAD

**Issue by navya-xx** [odlgroup/odl#1510]
Installed ODL on python3 version 3.7.3 (anaconda).
Got TypeError during testing.
Please check the attached file.

[odl_test_error.txt](https://github.com/odlgroup/odl/files/3376571/odl_test_error.txt)

**Comment by kohr-h** [comment]
Hi, @navya-xx, thanks for the report. This is an issue with NumPy that changed the implementation of reductions like `sum` and `max` from standalone functions to `ufunc.reduce`. Product spaces don't fully support the `ufunc` machinery yet, only the part where shape and data type don't change.

The same issue was already reported in #1487, so I'll close this one in favor of the original issue.
