### ISSUE TITLE
Adding Contributor Covenant Code of Conduct

### ISSUE THREAD

**Issue by tapaswenipathak** [odlgroup/odl#1522]
Hey maintainers: Can the project has Contributor Covenant Code of Conduct added https://en.wikipedia.org/wiki/Contributor_Covenant?

**Comment by adler-j** [comment]
Possibly but we'd need to know more. Do you know some more details and/or comparisons to other standard codes of conduct?

**Comment by tapaswenipathak** [comment]
Hey @adler-j: The Contributor Covenant Code of Conduct described https://en.wikipedia.org/wiki/Contributor_Covenant is slightly different than a usual code of conduct document. Different open source communities have different code of conducts.

Quoting:

> Open Source has always been a foundation of the Internet, and with the advent of social open source networks this is more true than ever. But free, libre, and open source projects suffer from a startling lack of diversity, with dramatically low representation by women, people of color, and other marginalized populations.

> Often it is the unintentional assumptions and actions of project maintainers and participants that make open source projects unwelcoming (or even hostile) to marginalized people: making assumptions about gender or race, reinforcing stereotypes, using sexualized or otherwise inappropriate language, or demonstrating a lack of regard for the safety and well-being of vulnerable people.

> One way to begin addressing this problem is to be overt in our openness, welcoming all people to contribute, and pledging in return to value them as whole human beings and to foster an atmosphere of kindness, cooperation, and understanding.

> Adopting the Contributor Covenant can be one way to express and codify these values and signal your intention to make your open source community welcoming, diverse, and inclusive.

Ref: https://www.contributor-covenant.org/. I like her work and would be happy if odl community sign as well; works for me if you would like adding a doc like Contributor Covenant Code of Conduct w/ defining the values and principles you would like the community should follow.

**Comment by kohr-h** [comment]
Hi @tapaswenipathak, thanks for reaching out to us. We discussed the matter internally and decided that at this point in time we don't feel the need to adopt a CoC. For one, more or less all contributors know each other in person, and the tone on the issue tracker has always been quite positive and upbeat. And furthermore (maybe more importantly) we don't want to regulate *upfront* what people are supposed to say and what not.
I understand that spreading the word and gaining traction are important goals for CoC advocates. But unless the need for us to do something about our discussion and welcoming culture emerges from *within* our community or becomes apparent in this forum, we are not going to take further steps in this direction.

With that said, I'll close the issue.

**Comment by tapaswenipathak** [comment]
Hey @kohr-h! I respect the decision and confidence in the culture of the organisation. Thanks.
