### ISSUE TITLE
Question on two diagonal operators with duplicate unknown

### ISSUE THREAD

**Issue by jakeoung** [odlgroup/odl#1527]
I want to optimize a regularization term similar to total nuclear variation. But instead of gradient operator, I have two diagonal operators A and B. And the unknown vector is duplicated as follows:

[A 0] [ u ]
[0 B] [ u ]

If I have n unknown vectors, I want to minimize the nuclear norm of:

[A 0] [ u1, u2, ..., un ]
[0 B] [ u1, u2, ..., un ]

In this case, is there any way to use ODL? (If the question is not clear, please let me know!)

**Comment by adler-j** [comment]
You would have to ellaborate a bit on what you mean in the second case, how does the matrix act on the vectors?

Anyhow, the answer to these questions in ODL is almost always to use a [`ProductSpaceOperator`](https://odlgroup.github.io/odl/generated/odl.operator.pspace_ops.ProductSpaceOperator.html) to define the operator and then to use e.g. [`SeparableSum`](https://odlgroup.github.io/odl/generated/odl.solvers.functional.default_functionals.SeparableSum.html) to define a functional.

If you could give some further information it feels like this should be easy to work out.

**Comment by sbanert** [comment]
In the first case you mention,
```
[A 0] [u]     [Au]     [A]
           =        =      [u]
[0 B] [u]     [Bu]     [B]
```
so you don't need the duplicate unknown if you just want to solve the system. The operator you are looking for might then be a [`BroadcastOperator`](http://odlgroup.github.io/odl/generated/odl.operator.pspace_ops.BroadcastOperator.html#odl.operator.pspace_ops.BroadcastOperator).

In the second case, you get back a matrix
```
[Au1 Au2 ... Aun]     [A]
                   =      [u1 u2 ... un]
[Bu1 Bu2 ... Bun]     [B]
```
What exactly do you mean by minimizing the nuclear norm of this?

**Comment by jakeoung** [comment]
Thank you for the replies! For example, as far as I understand, the total nuclear norm minimizes the nuclear norm of
```
[Du1,  Du2, ..., Dun] = D [u1, ..., un]
```
where D is the gradient operator and u1,...,un are the images. So we can use the Douglas-Rachford method by Bot et al. (I might be wrong.)

In my case, u1, u2 ,... are not images but I have a matrix like:
```
[ Au1 Au2 ... Aun ]
[ Bu1 Bu2 ... Bun ]
```
and I want to minimize its nuclear norm. Is it more clear now? 

Thanks in advance!

**Comment by adler-j** [comment]
I feel that you are correct about what the nuclear norm does.

It's still not quite clear what Au1 is, is it a vector itself? In that case you need some form of tensor equivalent of the nuclear norm (shouldn't be too hard, just needs some thought).

**Comment by jakeoung** [comment]
Yes, exactly. Au1 is the vector. (To be specific, in my case, A is just diagonal matrix). Okay, I will look up the tensor form or other ways. Many thanks.
