### ISSUE TITLE
Broken ASTRA DensityWeighting check

### ISSUE THREAD

**Issue by wjp** [odlgroup/odl#1529]
The check for applying `cone3d_approx_density_weighting` / `DensityWeighting` in `astra_setup.py`, `astra_projector()` is broken since it checks `astra_proj_type` (which is always `cuda3d`) against `cone` or `cone_vec`, instead of checking `astra_geom`.

The current ASTRA master branch no longer supports this `DensityWeighting` option, since it is always enabled now.

At first glance it seems to be okay to fix the check and also adapt the `cone3d_approx_density_weighting` feature version range to `'>=1.8,<1.9.9.dev'`, but since apparently this intermediate `DensityWeighting` option was never used and tested, it may be safer to just remove it entirely?

**Comment by wjp** [comment]
This would be the fix:

```diff
diff --git a/odl/tomo/backends/astra_setup.py b/odl/tomo/backends/astra_setup.py
index dfd189cbd..9c0fb6658 100644
--- a/odl/tomo/backends/astra_setup.py
+++ b/odl/tomo/backends/astra_setup.py
@@ -107,7 +107,7 @@ ASTRA_FEATURES = {
     # Approximate version of ray-density weighting in cone beam
     # backprojection for constant source-detector distance, see
     # https://github.com/astra-toolbox/astra-toolbox/pull/84
-    'cone3d_approx_density_weighting': '>=1.8',
+    'cone3d_approx_density_weighting': '>=1.8,<1.9.9.dev',
 
     # General case not supported yet, see the discussion in
     # https://github.com/astra-toolbox/astra-toolbox/issues/71
@@ -699,7 +699,7 @@ def astra_projector(astra_proj_type, astra_vol_geom, astra_proj_geom, ndim):
     # Add the approximate 1/r^2 weighting exposed in intermediate versions of
     # ASTRA
     if (
-        astra_proj_type in ('cone', 'cone_vec')
+        astra_geom in ('cone', 'cone_vec')
         and astra_supports('cone3d_approx_density_weighting')
     ):
         proj_cfg['options']['DensityWeighting'] = True
```

**Comment by wjp** [comment]
I think I spoke too soon. Looking at this a little closer, it was broken by #1485 last month; I had missed that that was merged now. So presumably the above patch is the right approach.

**Comment by kohr-h** [comment]
Agreed, the above fix is the way to go, thanks for spotting the issue.

The version range is large enough to continue supporting this intermediate solution, and IIRC the effect was quite significant compared to no density weighting.

**Comment by kohr-h** [comment]
Fixed in https://github.com/odlgroup/odl/pull/1528
