### ISSUE TITLE
Init of DiscreteWaveletTransform costs as much as a full transform

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#153]
I noticed while looking through the code of that function that [it actually calculates a wavelet decomposition](https://github.com/odlgroup/odl/blob/master/odl/trafos/wavelet.py#L104-L111) of an array of zeros and takes the sizes from the result. And since this function is used [in the initialization method of `DiscreteWaveletTransform`](https://github.com/odlgroup/odl/blob/master/odl/trafos/wavelet.py#L613-L614), this means that the cost for creating a wavelet trafo operator is roughly the same as calculating a full wavelet decomposition, which is clearly not acceptable for large data sizes. We need to find a way to get these sizes "for free", possibly by looking more closely into the `pywt` provided functions or, if necessary, into their source code.

**Comment by kohr-h** [comment]
There is [a utility function in `pywt`](https://pywavelets.readthedocs.org/en/latest/ref/dwt-discrete-wavelet-transform.html#result-coefficients-length-dwt-coeff-len) which does what we need. Not with all bells and whistles, i.e. recursively and for any number of dimensions, but that we can fix ourselves.

**Comment by adler-j** [comment]
Regarding this issue, you should not link to lines, you need to link to lines in a commit. Compare:

[Bad link](https://github.com/odlgroup/odl/blob/master/odl/trafos/wavelet.py#L104-L111)

with

[Good link](https://github.com/odlgroup/odl/blob/733fb9f082c4262ed03216ce8b1dc748864e68ad/odl/trafos/wavelet.py#L104-L111)

The easiest way to do this is to highlight the code you want to link to and press "y", this redirects you to the latest commit that changed the code, you can then link as usual.

**Comment by kohr-h** [comment]
You mean the bad link follows the current head? That's bad, of course. Thanks for the hint with "y".

**Comment by adler-j** [comment]
Yes thats what I meant.
