### ISSUE TITLE
memory error

### ISSUE THREAD

**Issue by cherryandmoon** [odlgroup/odl#1535]
I tried to run the FBP example code : https://github.com/odlgroup/odl/blob/master/examples/tomo/filtered_backprojection_cone_3d.py

however, I have received "memory error", when run the line 
fbp_recontruction = fbp(proj_data)

 I didn't expect this as i was running this on a HPC. it has a high-memoery login node with 768 GB RAM and 16 computer nodes, each comprising 192 GB RAM. 

The python version is 3.7.3

Any idea of what may go wrong?

**Comment by kohr-h** [comment]
> it has a high-memoery login node with 768 GB RAM and 16 computer nodes, each comprising 192 GB RAM.

Good for you :-)

> however, I have received "memory error",

Is that a Python `MemoryError`?

> when run the line
> fbp_recontruction = fbp(proj_data)

The example should run on moderate hardware. The 3D projector uses the ASTRA toolbox and runs on the GPU. Do you have enough memory there?
(However, ASTRA doesn't raise a `MemoryError` on insufficient memory.)

I've heard of issues with allocating NumPy arrays of large size, although I could never reproduce them. Maybe you want to check where the limit lies? It may also be worth to try different NumPy versions.

**Comment by cherryandmoon** [comment]
Hi Holger,

Thanks for your reply. Yes, I got this error in Jupyter. As I am running the example code, the data isn’t that big. And I just checked the version of Numpy is  numpy==1.16.5

Regards,
Wenjuan

**Comment by cherryandmoon** [comment]
I have tried to install odl on one of our local computers. I have installed odl 1.0.0 using code: pip install https://github.com/odlgroup/odl/archive/master.zip


however, jupyter seems cannot allocate the odl on this machine and shows AttributeError: module 'odl.tomo' has no attribute 'ConeBeamGeometry'

Any idea what may goes wrong?

Thanks.

**Comment by kohr-h** [comment]
> Yes, I got this error in Jupyter.

I meant, does Python raise a [`MemoryError`](https://docs.python.org/3/library/exceptions.html#MemoryError)? What is the exact error message (with traceback)?

> And I just checked the version of Numpy is numpy==1.16.5

Yeah, as I wrote, I've only heard of someone having a memory issue with Numpy on a machine with much more available memory. I haven't encountered the error myself, so I can't say "this version is buggy, use that one". You need to try different Numpy versions yourself.

> I have tried to install odl on one of our local computers. I have installed odl 1.0.0 using code: pip install https://github.com/odlgroup/odl/archive/master.zip however, jupyter seems cannot allocate the odl on this machine and shows AttributeError: module 'odl.tomo' has no attribute 'ConeBeamGeometry' Any idea what may goes wrong?

Seems like you're using an older version. It's possible that `pip` won't replace an existing installation if the versions are the same. You can try `pip install --force-reinstall ...` to make sure you really have the newest version.
If you have Git, I would recommend cloning the repository and doing the Git install that's described in the documentation. It works better.

**Comment by kohr-h** [comment]
I'll close this for lack of information / things to do.
