### ISSUE TITLE
 can't install the latest odl in Anaconda

### ISSUE THREAD

**Issue by cherryandmoon** [odlgroup/odl#1536]
I would like to use the latest odl(version 1.0.0) in jupyter in one of our lab computers.
I have tried the following code to install odl:
 pip install https://github.com/odlgroup/odl/archive/master.zip

then in anaconda prompt, when I run pip freeze, I can see odl 1.0.0

But when I load anaconda navigator, the system only find odl 0.7.0
and there is no option to upgrade this to 1.0.0

any idea how can I install the 1.0.0 version? Thanks.

**Comment by kohr-h** [comment]
First, please observe that there is no ODL 1.0.0. The latest Git version is 1.0.0.dev0 (development version, not release). The latest release is 0.7.0.

Regarding anaconda navigator, I have no idea what it does and how it checks what packages there are. However, when I do this:
```
conda create -n tmp
conda activate tmp
conda install python numpy scipy future packaging
pip install https://github.com/odlgroup/odl/archive/master.zip
python
```
Then I get this:
```py
>>> import odl
>>> odl.__version__
'1.0.0.dev0'
>>>
```

**Comment by cherryandmoon** [comment]
Sorry, I meant 1.0.0.dev0

I have tried your code, it seems the programme installed 1.0.0.dev0, but when I import it from python, they still show 0.7.0, so strange.

Screenshot attached below:
[cid:image001.jpg@01D5A122.A313EE10]

**Comment by aringh** [comment]
I may be out on a limb here, but I would guess that you have several python versions installed on your machine, and that you are in fact not running the version you think you are. I suggest:

- check where the `odl`-installation actually used by python is. This can be done by running ` python -c "import odl; print(odl.__path__)"`

- check where your python is installed, for example by running `python -c "import sys; print('\n'.join(sys.path))"`.

**Comment by kohr-h** [comment]
I don't really see a way to "solve" this, so I'll close the issue. Whoever sees a concrete issue and/or reasonable follow-up actions may reopen it.
