### ISSUE TITLE
How to define the transpose of system matrix

### ISSUE THREAD

**Issue by Hznnn** [odlgroup/odl#1566]
ART Equation
x^(k+1) = x^k + lambda * AT(b - A(x))/ATA

For low-dose CT reconstruction, how do I define a full-view fan-beam projection process A and AT without using  kaczmarz function.

**Comment by ozanoktem** [comment]
Honestly, I don't understand your question. In ODL, Kaczmarz iterates (and any other iterative and/or optimisation based scheme) do not require information about how A (and A*) are digitised. 

Regarding the projection operator A (and its transpose/adjoint A*), in ODL you typically use a helper function to construct A. This helper function needs a specification of the tomographic acquisition geometry.

**Comment by Hznnn** [comment]
How do I construct the projection operator A (and its transpose/adjoint A*) by using helper function.

**Comment by adler-j** [comment]
For constructing the operator, look at the examples here: https://github.com/odlgroup/odl/tree/master/examples/tomo

For finding the adjoint, simply call `operator.adjoint` on the constructed operator.

**Comment by Hznnn** [comment]
Are adjoint and transpose equal？

**Comment by ozanoktem** [comment]
For reconstruction, it is the adjoint you need. In most cases the adjoint coincides with the transpose.

**Comment by ozanoktem** [comment]
> In fan beam projection, how to define a geometry with projection number 720 and detector unit number 860？

I suggest you check the documentation: [https://odlgroup.github.io/odl/generated/odl.tomo.geometry.conebeam.FanBeamGeometry.html](https://odlgroup.github.io/odl/generated/odl.tomo.geometry.conebeam.FanBeamGeometry.html)

**Comment by adler-j** [comment]
Quick answer is

```
geometry = odl.tomo.cone_beam_geometry(space, src_radius, det_radius, num_angles=720, det_shape=860)
```
