### ISSUE TITLE
Multidimensional product spaces

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#157]
Not a must-have, but certainly nice: a way to produce product spaces which are more than one-dimensional, i.e. the factors are stored in a multidimensional array rather than a list. With all the connected questions of norms, inner products etc.

We could follow a similar approach as in the case of `FnBase` vs. `DiscreteLp`: make the underlying storage linear (e.g. a NumPy array with `dtype=object`) and reshape to higher dimensions only on demand by some generalized `Discretization` class.

Of course, this will give a substantial speed penalty for a large number of member spaces compared to the situation where we have a discretization of a single large space, but I think we're going to need something like this in the long run, see e.g. #156.

**Comment by adler-j** [comment]
There is a age old issue on this on the [old github](https://gits-15.sys.kth.se/LCR/odl/issues/173).

A trivial way to do this is to implement this recursively, something like

```python
>>> space1 = odl.ProductSpace(projectionDisc, [2, 2])
>>> space2 = odl.ProductSpace(odl.ProductSpace(projectionDisc, 2), 2)
>>> space1 == space2
True
```

**Comment by kohr-h** [comment]
As long as we don't need anything else than our good old weighted p-norms, this should be working. More thoughts necessary for more complicated things.

**Comment by kohr-h** [comment]
For power spaces, this will be trivial with #857. For the general case, I guess as long as there's no real need for it we don't do it?

**Comment by adler-j** [comment]
I agree. #857 solves the most common use cases and in other cases it's just a matter of somewhat clunky syntax that we can live with.
