### ISSUE TITLE
error message in forward projection

### ISSUE THREAD

**Issue by cherryandmoon** [odlgroup/odl#1579]
Good evening,

I am trying to develop cone beam projection images, but got stuck

I tried to run this code as an example https://github.com/odlgroup/odl/blob/master/examples/tomo/filtered_backprojection_cone_3d.py
but received an error message as shown in the attached image. Can anyone give me an clue? Thanks.
![image](https://user-images.githubusercontent.com/56595769/93687451-f8e4f300-fab5-11ea-9084-6c5f834527dd.png)

**Comment by kohr-h** [comment]
Thanks for raising the issue @cherryandmoon 
The error message simply did a wrong name lookup, fix see PR. The message that would have been printed otherwise would have told you about this projector (`skimage`) not being suitable for 3D. You need the ASTRA GPU backend for that.

**Comment by cherryandmoon** [comment]
sorry I am new to github. Can you point me to where is the PR?

Thanks for the help.

**Comment by kohr-h** [comment]
This PR: https://github.com/odlgroup/odl/pull/1580
