### ISSUE TITLE
Attribute error while creating coneFlat geometry in the latest git version

### ISSUE THREAD

**Issue by anindgupta** [odlgroup/odl#1582]
Hi, 
While trying to create a coneFlat Geometry from odl.tomo, I am getting an Attribute Error. Here is the information about my current running setup:
![odlerror](https://user-images.githubusercontent.com/43072093/94683346-a5c93680-0326-11eb-8960-cb38d5f44fd9.png)

**Comment by adler-j** [comment]
ConeFlatGeometry has been replaced with ConeBeamGeometry, could you try it instead?

**Comment by anindgupta** [comment]
Thanks for the response. I realise it  as well after going through the documentation again. 
Cheers
