### ISSUE TITLE
rotation angles

### ISSUE THREAD

**Issue by cherryandmoon** [odlgroup/odl#1592]
hi, hope this is not a silly question to ask. 
I am trying to create an angle partition, using angle_part = odl.uniform_partition(0,2 * np.pi,393)
however, I need anticlockwise angles, i.e., with -2*np.pi, but seems not allowed.
Would you please give me some advice? Thanks.

**Comment by adler-j** [comment]
ODL enforces strictly increasing angles as a convention, the standard solution if you have real data is to re-order your data to have clockwise angles using e.g. `data = data[::-1]`.

**Comment by cherryandmoon** [comment]
Hi Jonas,

Thanks for your reply. It works.

Best regard,
Wenjuan

**Comment by adler-j** [comment]
That's great! If there's nothing more I'll close this issue.

**Comment by cherryandmoon** [comment]
Sure, no problem. Thanks.
