### ISSUE TITLE
How to use ODL with Tensorflow 2

### ISSUE THREAD

**Issue by hjahan58** [odlgroup/odl#1594]
Hello.Thank you for your efforts for ODL
I want to write a deep learning framework for ct mage reconstraction with extremly few view.
from tensorflow totrial it is undrestood that tensorflow 2 realase is more eficient from tensorflow 1  .
I did not find any records of using the ODL library with TensorFlow 2.
Does this library have a particular inconsistency with TensorFlow 2?
What is your suggestion for me?
Should I use ODL with TensorFlow 2 ?
  or                ODL with TensorFlow 1 ?
or                  ODL with pytorch ?

**Comment by adler-j** [comment]
The current setup is only made to be run with tensorflow in v1 mode, but TF v2 should be really easy to set up (a lot easier than v1 in fact). With that said, as a new user you should be totally fine just running TF v1, there is no speed penalty.

**Comment by hjahan58** [comment]
Thank you
