### ISSUE TITLE
Doc gives several warnings

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#16]
Keeping `make html` warning free enables us to notice when we get new warnings. We should thus try to make it warning free. I am currently on my way to do this.

**Comment by adler-j** [comment]
Added a new branch for this:

[issue-16](https://github.com/odlgroup/odl/tree/issue-16__doc_warnings)

**Comment by adler-j** [comment]
This issue is moving ahead, but slowly. Basically I've had to fix approximately 1000 warnings.

The warnings are primarily of two kinds:

* Unable to resolve type, aka we need to specify :class:\`LinearSpace\` instead of \`LinearSpace\`
* Bad usage of \` . Across all of the documentation we have been using \` ambiguously. Basically a single \` something \` means reference to something, and a dubble  \`\` something \`\` means inline code.

In the future we need to be more strict in this.

**Comment by kohr-h** [comment]
Sure, no big deal.

Does this also apply to core classes like `list`? Or is Sphinx smart enough there?

**Comment by adler-j** [comment]
Sphinx using `intershpinx` is smart enough for all core classes such as `list`, but also for concepts such as `callable`. These do not seem to require further info.

**Comment by adler-j** [comment]
Even more commits added, I'll submit a pull request now so we can start reviewing this.

**Comment by kohr-h** [comment]
We should add a chapter on docstrings in our documentation "how to contribute". Or do we already have something?

**Comment by adler-j** [comment]
We do not have this. Imo simply saying that before merging a pull request we should make sure the doc builds properly is enough, then add these two hints as to why you may get warnings.

**Comment by kohr-h** [comment]
The thing is that now that there is a `CONTRIBUTING.md`, you get a hint above title field when you start an issue (or pull request), so at least first-timers might click. That document (which needs some improvement) could at least show some quick info like the following:

#### Pull requests

Before you send a pull request make sure that

1. All tests succeed (except those which are known to fail)
2. The code is properly formatted
3. New functions or classes are documented

**Comment by adler-j** [comment]
Yes that is enough for the simple `CONTRIBUTING.md` document, further info can be in the docs.

**Comment by adler-j** [comment]
Thread merged, should maintain 0 warnings now.
