### ISSUE TITLE
Issue when using odl and import pytorch

### ISSUE THREAD

**Issue by drgHannah** [odlgroup/odl#1608]
Hi, I would like to run radon transformation and filtered backprojection on my pytorch data. However, the transformation is only correct if I do not import pytorch _(import torch)_ and the same applies to _from odl.contrib.torch import OperatorModule_. Can anyone help me with this?

I have attached the code and my results below for reproducibility.

![With_Import_Torch](https://user-images.githubusercontent.com/53939150/129707746-0df14b9a-82ec-4427-a1b2-cf2e906b1729.png)

```
# Imports
import numpy as np
import odl
import torch
#from odl.contrib.torch import OperatorModule

# ODL
reco_space = odl.uniform_discr(min_pt=[-20, -20], max_pt=[20, 20], shape=[300, 300], dtype='float32')
angle_partition = odl.uniform_partition(0, np.pi, 50)
detector_partition = odl.uniform_partition(-30, 30, 300)
geometry = odl.tomo.Parallel2dGeometry(angle_partition, detector_partition)

ray_trafo = odl.tomo.RayTransform(reco_space, geometry,impl='astra_cuda')
fbp = odl.tomo.fbp_op(ray_trafo)


## Run
phantom = odl.phantom.shepp_logan(reco_space, modified=True)
proj_data = ray_trafo(phantom)
fbp_reconstruction = fbp(proj_data)

phantom.show(title='Phantom')
proj_data.show(title='Projection Data (Sinogram)')
fbp_reconstruction.show(title='Filtered Back-projection', force_show=True)
```

**Comment by oooo1114** [comment]
I met the same situation. Has the bug been solved?

**Comment by JevgenijaAksjonova** [comment]
I can't reproduce the problem.  I recommend using recent Pytorch version and installing ODL from source ://odlgroup.github.io/odl/getting_started/installing_source.html

**Comment by oooo1114** [comment]
> I can't reproduce the problem. I recommend using recent Pytorch version and installing ODL from source ://odlgroup.github.io/odl/getting_started/installing_source.html

Which version of torch do you have?
I installed odl from source from the zip file downloaded from github.
I have tried with torch 1.10, but got an error "CUDA error: invalid device symbol ".
I also tried with torch 1.7.1, but reproduced the fbp intensity error above.
I am using ubuntu.

**Comment by JevgenijaAksjonova** [comment]
torch 1.12.1, cudatoolkit 11.3

**Comment by oooo1114** [comment]
> torch 1.12.1, cudatoolkit 11.3

First I think astra-toolbox is restricted to python 3.6. Today I find that astra is also compatible with python 3.8.
It works now. 
My environment is :
torch 2.10+cu118
astra-toolbox 2.1.0
odl 1.0.0.dev0

Thanks a lot for your help.
