### ISSUE TITLE
How to call objects which can be passed to element()?

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#161]
On the operator branch soon ready for merge, we allow input of operators to be not strictly in the domain, but interpretable as a domain element via the `element()` method. In NumPy lingo this would be array-like since they pass input through their `array` constructor.

What should we call such objects? `element-like`? Maybe more precisely `range element-like` depending on the situation.

**Comment by adler-j** [comment]
`element-like` if we do not know more, for `FnBase spaces` I'd go with `array-like` since we have a guarantee here.

**Comment by kohr-h** [comment]
Alright, I'll close then.
