### ISSUE TITLE
RayTransform： ValueError: The 'astra_cuda' `impl` is not found.

### ISSUE THREAD

**Issue by zhongniuniu** [odlgroup/odl#1624]
ValueError: The 'astra_cuda' `impl` is not found. This `impl` is either not supported, it may be misspelled, or external packages required are not available. Consult `RAY_TRAFO_IMPLS` to find the run-time available implementations.

My code is：
ray_trafo = odl.tomo.RayTransform(vol_space=reco_space, # domain of forward projector
                                     geometry=geometry, # geometry of the transform
                                     impl='astra_cuda') # implementation back-end for the transform: ASTRA toolbox, using CUDA, 2D or 3D

I tried to run:conda install -c astra-toolbox astra-toolbox，And I installed successfully install astra-toolbox 2.1.2, but it still pops up the error just now.

**Comment by zhongniuniu** [comment]
my odl is 1.0.0.dev0

**Comment by JixiangChen-Jimmy** [comment]
Hi, I am encountering the same problem, did you figure out the solution?

**Comment by JevgenijaAksjonova** [comment]
The problem is that ODL does not find ASTRA installation with GPU support.

**Comment by JixiangChen-Jimmy** [comment]
@JevgenijaAksjonova Thanks for your relpy. I solve this problem via simply running conda install -c astra-toolbox astra-toolbox. After installation, I checked that all impl options are then supported.

**Comment by zlbbme** [comment]
> The problem is that ODL does not find ASTRA installation with GPU support.

If we want  astra-toolbox to deal wtih 3D data，there are must have GPU with cuda

**Comment by ozanoktem** [comment]
> > The problem is that ODL does not find ASTRA installation with GPU support.
> 
> If we want astra-toolbox to deal wtih 3D data，there are must have GPU with cuda

If one installs ASTRA correctly, ODL has no problems finding it as clarified by @JevgenijaAksjonova

**Comment by taliwxy** [comment]
> ValueError: The 'astra_cuda' `impl` is not found. This `impl` is either not supported, it may be misspelled, or external packages required are not available. Consult `RAY_TRAFO_IMPLS` to find the run-time available implementations.
> 
> My code is： ray_trafo = odl.tomo.RayTransform(vol_space=reco_space, # domain of forward projector geometry=geometry, # geometry of the transform impl='astra_cuda') # implementation back-end for the transform: ASTRA toolbox, using CUDA, 2D or 3D
> 
> I tried to run:conda install -c astra-toolbox astra-toolbox，And I installed successfully install astra-toolbox 2.1.2, but it still pops up the error just now.

Hello, I have the same problem as you, did you solve it?

**Comment by leftaroundabout** [comment]
@taliwxy how did you install Astra? As said before, this should work if you've actually installed the Cuda version, but not if you only have the CPU version.

If you're unsure, please show the output of

```conda list```

and

```python -c 'import astra; print(astra.get_gpu_info())'```

**Comment by taliwxy** [comment]
> @taliwxy how did you install Astra? As said before, this should work if you've actually installed the Cuda version, but not if you only have the CPU version.
> 
> If you're unsure, please show the output of
> 
> `conda list`
> 
> and
> 
> `python -c 'import astra; print(astra.get_gpu_info())'`

Thanks for your reply! I have solved this problem by changing the version of astra-toolbox from 2.2.0 to 1.9.9 to match the version of odl.

**Comment by leftaroundabout** [comment]
@taliwxy good to hear you found a solution!

We will also bring ODL up to date with the latest Astra versions; not immediately but probably in the next months.
