### ISSUE TITLE
Python version

### ISSUE THREAD

**Issue by pierre-weiss** [odlgroup/odl#1629]
I decided to give a try to your nice library and when using conda install, I got the following error :
Could not solve for environment specs
The following packages are incompatible
└─ odl   is installable with the potential options
   ├─ odl [0.5.3|0.6.0|0.7.0] would require
   │  └─ python [3.6* |>=3.6,<3.7.0a0 ], which can be installed;
   ├─ odl [0.2.2|0.2.3|...|0.5.2] would require
   │  └─ nomkl  , which requires
   │     └─ blas * openblas, which can be installed;
   ├─ odl 0.7.0 would require
   │  └─ python >=3.7,<3.8.0a0 , which can be installed;
   ├─ odl [0.5.3|0.6.0|0.7.0] would require
   │  └─ python [2.7* |>=2.7,<2.8.0a0 ], which can be installed;
   ├─ odl [0.5.3|0.6.0] would require
   │  └─ python 3.4* , which does not exist (perhaps a missing channel);
   └─ odl [0.5.1|0.5.3|0.6.0|0.7.0] would require
      └─ python [3.5* |>=3.5,<3.6.0a0 ], which can be installed.

So, the toolbox is not available for version of Python older than 3.7.0 ? Is there a chance to have it running for, say python 3.10 ?

**Comment by JevgenijaAksjonova** [comment]
Hi, to get the version that works with the latest packages, please install the ODL from source as described here  https://odlgroup.github.io/odl/getting_started/installing_source.html

**Comment by pierre-weiss** [comment]
Thanks a lot and sorry for the nuisance.

Best regards,
Pierre
