### ISSUE TITLE
Issue with using callback to show intermediate results in iterative solvers

### ISSUE THREAD

**Issue by ozanoktem** [odlgroup/odl#1636]
Most solvers in ODL are iterative and my understanding is that setting a callback offers a way to pass instructions to such a solver that can be executed in each iterate. There now seems to be an issue with the way the callback-function in ODL interfaces with the show-function. More specifically, one can use callback to show intermediate reconstructions in each iterate by setting

`callback_settings = (odl.solvers.CallbackPrintIteration() & odl.solvers.CallbackShow())`

and then calling the ODL solver with `callback=callback_settings`. However, this yields an attribute error that allow the first iterate to be shown, but then iterates are terminated with the message 

> iter = 0
> iter = 1
> Traceback (most recent call last):
> 
>   File ~/opt/anaconda3/envs/ODL/lib/python3.9/site-packages/spyder_kernels/py3compat.py:356 in compat_exec
>     exec(code, globals, locals)
> 
>   File ~/Library/CloudStorage/Dropbox/Teaching/KTH/SF3582 Inverse Problems/Laborations/issue_callback.py:42
>     odl.solvers.iterative.iterative.landweber(fwd_op, reco, data, niter=10, callback=callback_settings)
> 
>   File ~/odl/odl/solvers/iterative/iterative.py:120 in landweber
>     callback(x)
> 
>   File ~/odl/odl/solvers/util/callback.py:133 in __call__
>     p(result)
> 
>   File ~/odl/odl/solvers/util/callback.py:666 in __call__
>     self.fig = x.show(title, fig=self.fig,
> 
>   File ~/odl/odl/discr/discr_space.py:1515 in show
>     return show_discrete_data(values, part, title=title, method=method,
> 
>   File ~/odl/odl/util/graphics.py:439 in show_discrete_data
>     csub.colorbar.set_clim(minval, maxval)
> 
> AttributeError: 'Colorbar' object has no attribute 'set_clim'

Below is a small example demonstrating the issue. 

```
import numpy as np
import odl
      
# Reconstruction space: discretized functions on the rectangle
# [-20, 20]x[-20,20] with 300 samples per dimension.
reco_space = odl.uniform_discr(
    min_pt=[-1, -1], max_pt=[1, 1], shape=[256, 256], dtype='float32')

# Create a discrete Shepp-Logan phantom (modified version)
phantom = odl.phantom.shepp_logan(reco_space, modified=True)

# Data space: Parallel-beam geometry with flat detector
# Angles: uniformly spaced, n = 1000, min = 0, max = pi
angle_partition = odl.uniform_partition(0, np.pi, 1000)
# Detector: uniformly sampled, n = 500, min = -30, max = 30
detector_partition = odl.uniform_partition(-1.5, 1.5, 300)
# Make a parallel beam geometry with flat detector
geometry = odl.tomo.Parallel2dGeometry(angle_partition, detector_partition)

# Forward operator: Ray transform 
fwd_op = odl.tomo.RayTransform(reco_space, geometry)

# Create projection data by calling the ray transform on the phantom
data = fwd_op(phantom)

# Optionally pass callback to the solver to display intermediate results
callback_settings = (odl.solvers.CallbackPrintIteration() & odl.solvers.CallbackShow())

# Built in Landweber reconstruction 
reco = fwd_op.domain.zero()
odl.solvers.iterative.iterative.landweber(fwd_op, reco, data, niter=10, callback= callback_settings)
```

**Comment by paulhausner** [comment]
I think this is just a problem with `odl.utils.graphics` usage of matplotlib. Rescaling the colorbar seems to not work anymore but it should be possible to instead rescale the plot (https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.clim.html). See #1635

**Comment by leftaroundabout** [comment]
`fig.canvas.draw_idle()` seems to do the trick:

![odl_plotcallback_colorbarupdate](https://github.com/odlgroup/odl/assets/1528675/115177d9-07ab-416a-a094-42b7371c541f)
