### ISSUE TITLE
Improve the Installing documentation

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#165]
[This](http://odl.readthedocs.org/guide/introduction/installing.html) is probably one of the most visited pieces of doc and should be improved.

- [ ] We currently recommend Anaconda in general, I'd say we only recommend it on windows (since it lacks a default installation).
- [ ] We need our users to install numpy etc to a "new version", some words on how to do that
- [ ] odlpp install instructions should be written out

**Comment by kohr-h** [comment]
Regarding the last part, I've written a small build script to stop the pain configuring in `ccmake`. Users could apply that, adapted to their needs, of course. Or just take as a template.

```bash
#!/bin/sh

# Copyright 2014, 2015 The ODL development group
#
# build.sh - build script template for odlpp with explicit CMake options
#
# Usage: build.sh <python version> <odlpp source dir>"
#
# This file is part of ODL.
# License: GPLv3
# See LICENSE for more information

if [ "$#" -ne 2 ]; then
    echo "Usage: $0 <python version> <odlpp source dir>"
    exit 1
fi

PYTHON_VERSION=$1
if [ $PYTHON_VERSION == "2.7" ]; then
    PYTHON_INCLUDE_DIR=/usr/include/python$PYTHON_VERSION
    PYTHON_LIBRARY=/usr/lib64/libpython$PYTHON_VERSION.so
    BOOST_LIBRARY=/usr/lib64/libboost_python.so
else
    PYTHON_INCLUDE_DIR=/usr/include/python${PYTHON_VERSION}m
    PYTHON_LIBRARY=/usr/lib64/libpython${PYTHON_VERSION}m.so
    BOOST_LIBRARY=/usr/lib64/libboost_python3.so
fi
ODLPP_SRCDIR=$(cd "${2%/*}" && echo "$PWD/${2##*/}")  # Absolute path of the source

ODLPP_BUILDDIR=$ODLPP_SRCDIR/build-py$PYTHON_VERSION
# You may need to replace `lib64` by `lib` depending on where your distribution places its system libraries
ODLPP_NUMPY_BUILDOPTS="-DPYTHON_NUMPY_INCLUDE_DIR=/usr/lib64/python$PYTHON_VERSION/site-packages/numpy/core/include"
ODLPP_PYTHON_BUILDOPTS="-DPYTHON_INCLUDE_DIR=$PYTHON_INCLUDE_DIR -DPYTHON_LIBRARY=$PYTHON_LIBRARY"
ODLPP_CUDA_BUILDOPTS="-DCUDA_HOST_COMPILER=/usr/bin/gcc -DODL_CUDA_COMPUTE=52"
ODLPP_BOOST_BUILDOPTS="-DBoost_PYTHON_LIBRARY_RELEASE=$BOOST_LIBRARY -DBoost_PYTHON_LIBRARY_DEBUG=$BOOST_LIBRARY"
ODLPP_CC_BUILDOPTS="-DCMAKE_CXX_COMPILER=/usr/bin/c++ -DCMAKE_C_COMPILER=/usr/bin/gcc"
ODLPP_CMAKEOPTS="$ODLPP_PYTHON_BUILDOPTS $ODLPP_NUMPY_BUILDOPTS $ODLPP_CUDA_BUILDOPTS $ODLPP_BOOST_BUILDOPTS $ODLPP_CC_BUILDOPTS"

ODLPP_CMAKE_COMMAND='cmake $ODLPP_CMAKEOPTS $ODLPP_SRCDIR'

mkdir -p $ODLPP_BUILDDIR && cd $ODLPP_BUILDDIR
eval $ODLPP_CMAKE_COMMAND
make pyinstall
cd -
```

**Comment by adler-j** [comment]
Sure we could add this to the documentation, in general the CMake gui should be enough for most users (on linux, I think we are quite close to requiring no configuration nowdays).

**Comment by kohr-h** [comment]
I cannot quite agree. A basic non-gui software like `ccmake` should be sufficient to configure the build without setting ca. 5 critical parameters manually. The problems are basically the following:

- `FindNumpy.cmake` does not find anything (tested with Fedora and Gentoo Linux)
- Discovery of `PythonLibs` doesn't work properly since it defaults to the highest version available, which is usually 3.x irrespective of the other variables. There is some interaction going on with the `PythonInterp` value, but not in a way that it just works.
- The `CUDA_COMPUTE` parameter needs to be manually set *exactly* right. Too high or too low makes the code crash.
- Sometimes even the boost stuff is not correctly discovered, although that problem may go away by itself.

At least the first three points require either assistance in the intro or more reliable CMake solutions so that users don't have to worry.

**Comment by adler-j** [comment]
> FindNumpy.cmake does not find anything (tested with Fedora and Gentoo Linux)

We should change to the one I added to STIR: [link](https://github.com/odlgroup/STIR/blob/master/src/cmake/FindNumpy.cmake). It should work.

> Discovery of PythonLibs doesn't work properly since it defaults to the highest version available - which is usually 3.x - irrespective of the other variables. There is some interaction going on with the PythonInterp value, but not in a way that it just works.

This is the "official" findpython, and it works well on windows and Ubuntu (if you use the default python). With that said, it is lacking and that is acknowledged by the community. What version do you expect to find first? The system python?

> The CUDA_COMPUTE parameter needs to be manually set exactly right. Too high or too low makes the code crash (too high for sure, too low at least in the case you set it to 30 and have 52 in fact).

Complicated issue indeed, dunno how to solve it. There is some discussion [here](http://stackoverflow.com/questions/2285185/easiest-way-to-test-for-existence-of-cuda-capable-gpu-from-cmake/2297877#2297877), perhaps we could use that python script.

>Sometimes even the boost stuff is not correctly discovered, although that problem may go away by itself.

Hopefully switching to pybind11 will solve this.

**Comment by adler-j** [comment]
In a closing statement. Any user not on windows/mac/ubuntu can (imo) be considered an advanced used and be expected to set a few parameters here and there. With that said, yes we need to improve the install experience.

**Comment by kohr-h** [comment]
> This is the "official" findpython, and it works well on windows and Ubuntu (if you use the default python). With that said, it is lacking and that is acknowledged by the community. What version do you expect to find first? The system python?

My ideal setting would be that `PythonInterp` comes first, which fixes the major version of Python to be used. Then `PythonLibs` is discovered accordingly (which I think works), i.e. consistently with the interpreter version. Then, thirdly, the NumPy headers in the site-packages of the same Python distribution are searched and found. This may be the hardest to achieve, but if the STIR-one you linked to works, great.



> Complicated issue indeed, dunno how to solve it. There is some discussion here, perhaps we could use that python script.

There was an implementation of this in opencv. No idea how hard it is to untangle, though.

**Comment by kohr-h** [comment]
How about this guy? The mentioned document still needs a bit of a brush-up, but now the installation instructions on the main page are much better, I guess, so perhaps not so many people will actually go to that page?

**Comment by adler-j** [comment]
We should at least make sure that they are consistent, other than that I'm quite fine now that we got pip running.

**Comment by adler-j** [comment]
I say we close this. It is quite fine atm, especially since `odlcuda` is no longer covered and the fixes thanks to Frank.

**Comment by kohr-h** [comment]
I'll have a look over those parts anyway in #121, we can close this in favor of the latter.
