### ISSUE TITLE
Improve wavelet transform

### ISSUE THREAD

**Issue by niinimaki** [odlgroup/odl#166]
A couple of improvements to the wavelet transform:
The docstrings of wavelet transform class could be more informative (for example the signal extension modes are not described there, only in the docstrings of  helper functions).
Fix linearity check.

**Comment by adler-j** [comment]
:+1: sounds good. Btw, you could make a checklist like this:
```
- [ ] The docstrings of wavelet transform class could be more informative (for example the signal extension modes are not described there, only in the docstrings of helper functions).
- [ ] Fix linearity check.
```

- [ ] The docstrings of wavelet transform class could be more informative (for example the signal extension modes are not described there, only in the docstrings of helper functions).
- [ ] Fix linearity check.
