### ISSUE TITLE
Numpy >=2.0.0 compatibility

### ISSUE THREAD

**Issue by samuelnub** [odlgroup/odl#1661]
Hiya,

I'm just getting started on the basic "First Steps" example, and I have been having issues with the latest version of numpy (2.1.3), I seem to get:

```
`np.sctypes` was removed in the NumPy 2.0 release. Access dtypes explicitly instead.
  File "/home/samnub/dev/lircst/src/misc.py", line 1, in <module>
    import odl
  File "/home/samnub/dev/lircst/src/__main__.py", line 1, in <module>
    from misc import odl_test
AttributeError: `np.sctypes` was removed in the NumPy 2.0 release. Access dtypes explicitly instead.
```

Downgrading this to <2.0.0 (i.e. 1.26.4) leads to this issue arising instead:

```
module 'numpy' has no attribute 'object'.
`np.object` was a deprecated alias for the builtin `object`. To avoid this error in existing code, use `object` by itself. Doing this will not modify any behavior and is safe. 
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  File "/home/samnub/dev/lircst/src/misc.py", line 1, in <module>
    import odl
  File "/home/samnub/dev/lircst/src/__main__.py", line 1, in <module>
    from misc import odl_test
AttributeError: module 'numpy' has no attribute 'object'.
`np.object` was a deprecated alias for the builtin `object`. To avoid this error in existing code, use `object` by itself. Doing this will not modify any behavior and is safe. 
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations`
```

And trying to downgrade to a version prior to 1.20.0 seems to be a fix for #1628 , but I can't seem to get a version of numpy from three years ago to install properly (and I am unsure if it is a wise fix) - so I am wondering if there is a solution to this issue with numpy's compatibility (it _should_ be compatible with >2.0.0 or versions around 1.26.4, right? I am unable to find any official numpy version requirements for ODL)

I am running on WSL Ubuntu 24.04

Thank you!

**Comment by leftaroundabout** [comment]
Thanks for the report.

NumPy-2 is indeed still not working, but we spent considerable effort getting ODL compatible with 1.20 - 1.26.

Is this the Github `master` development version of ODL you tried to install?

Do you also run into problems when installing ODL-0.8 from Conda?

**Comment by leftaroundabout** [comment]
Regarding dependency bounds, I specified them in [a pull request last month](https://github.com/odlgroup/odl/pull/1659) that had not been merged into `master` yet. Done that now.

**Comment by samuelnub** [comment]
Thanks for the quick response! With #1659 being merged in, I can see now that my issue likely came from trying to do this via Pip (which has been at version 0.7.0 from 2018). I've setup a new environment in Conda, with ODL 0.8.0 and this seems to work well.

Thanks!
