### ISSUE TITLE
Optional plt.show in show method

### ISSUE THREAD

**Issue by moosmann** [odlgroup/odl#168]
Unless IPython/Spyder or a non-interactive backend (or probably something else) is used, calling `plt.show` in `odl.util.graphics.show_discrete_function()` blocks the execution of subsequent code until the window which has popped up is closed. Calling `plt.show` should be made optional, thus that one can call `plt.show` explicitly at the end of the script to display the previously created images.

**Comment by adler-j** [comment]
Do you have the latest version? The "show" is now blocking=False, does that help?

**Comment by moosmann** [comment]
The block=False option never worked properly for me. I already tried it several times. When I'm using
```
plt.show(block=False)
```
or
```
plt.show(block=False)
plt.draw()
```
then empty figures pop up which when using Pycharm do not respond anymore and require a force quit or which close immediately when executing a script directly. If I use
```
plt.show(block=False)
plt.draw()
plt.pause(0.1)
```
then windows pop up and the figures are displayed properly, but just for the time specified in plt.pause. 

There's also the option to enable interactive mode with plt.ion() which, however, never worked for me. I think it would easiest to allow for an additional argument to call plt.show or not. This at least works for me without problems.  Using interactive plotting one can in general not guarantee that plotting works as expected, see [matplotlib interactive mode](http://matplotlib.org/faq/usage_faq.html?highlight=usage#what-is-interactive-mode). The situation also differs if you are displaying a graph with plt.plot or an image with plt.imshow: the examples in [matplotlib  interactive mode](http://matplotlib.org/faq/usage_faq.html?highlight=usage#interactive-example) only worked for me as described when using plt.plot but not with plt.imshow.

**Comment by adler-j** [comment]
Ok, I guess we will need to do some thinking on the interactive plots, they are very useful in some situations.

**Comment by kohr-h** [comment]
Definitely! I suspect that global commands like `ion` don't help, and in my experience any of those global commands like `plt.figure` or global `axis` instances cause problems when one tries to change stuff. Maybe it is possible to do something similar locally, via class methods on the objects which are created along the way, in our case `figure`, which can be reused. We need to have a closer look.

**Comment by niinimaki** [comment]
Calling plt.show() fails
`TypeError: show() got an unexpected keyword argument 'block'`

**Comment by adler-j** [comment]
What version of matplotlib do you use? This keyword should exist.

**Comment by niinimaki** [comment]
Seems that I have version 1.3.1 ... too old?

**Comment by adler-j** [comment]
Dunno, I have 1.4.3 and it works. The doc doesn't mention when it was added.

**Comment by adler-j** [comment]
Should be solved now according to this suggestion, show is optional. See [show_1d.py](https://github.com/odlgroup/odl/blob/master/examples/visualization/show_1d.py) for an example.
