### ISSUE TITLE
Backprojection, adjoint for  DiscreteXrayTransform?

### ISSUE THREAD

**Issue by sseebbbbee** [odlgroup/odl#169]
How do you do the backprojection?
I tried the following but it fails as adjoint is not implemented for  DiscreteXrayTransform?

```python
xray_trafo = DiscreteXrayTransform(discr_reco_space, geom,backend='astra')
cont_phantom = reco_space.element(phantom)
discr_phantom = discr_reco_space.element(cont_phantom)
# Create data
proj_data = xray_trafo(discr_phantom)
phant=xray_trafo.adjoint(proj_data)
```

EDIT: adler-j formatted code.

**Comment by adler-j** [comment]
Added a commit 9319c68ac58df81c5342bb87b0b3920cfea00ce1, that should solve this. Does it work?

**Comment by sseebbbbee** [comment]
If I do git pull, the code should be updated for me right? 

I still got the same problem. I use https://github.com/odlgroup/odl/blob/issue-87__conebeam/examples/astra_parallel_2d_fp.py and have only added phant=xray_trafo.adjoint(proj_data)

**Comment by adler-j** [comment]
The code gets updated if it says so in the terminal, very hard to remote debug, you can look into the file and verify if it is there or not.

What error message do you get?

**Comment by sseebbbbee** [comment]
phant=xray_trafo.adjoint(proj_data)
  File "C:\Users\Sebastian\AppData\Roaming\Python\Python27\site-packages\odl\operator\operator.py", line 279, in adjoint
    ''.format(self))
odl.operator.operator.OpNotImplementedError: adjoint not implemented for operator DiscreteXrayTransform: uniform_discr([-1.0, -1.0], [1.0, 1.0], [50, 50]) -> DiscreteLp(
    FunctionSpace(Rectangle([0.0, -1.5], [3.1415926535897931, 1.5])),
    RegularGrid([0.0, -1.47], [3.1415926535897931, 1.47], [20, 50]),
    Rn(1000, 'float32')
    ).

**Comment by adler-j** [comment]
Did you check if you have [this code](https://github.com/odlgroup/odl/blob/9319c68ac58df81c5342bb87b0b3920cfea00ce1/odl/tomo/operators/xray_trafo.py#L172-L184) locally?

**Comment by sseebbbbee** [comment]
it said it updated and when i went in to odl and looked, the file was updated. But now I unistalled odl and installed it again, then it worked!

**Comment by adler-j** [comment]
How did you install odl? If you do

```
pip install --user .
```

```
pip install .
```

Then the current version of odl will be installed. If you want to be able to edit odl (for example by pulling), you need to add `-E`

```
pip install --user -e .
```

**Comment by adler-j** [comment]
Ping @kohr-h on the last question.

**Comment by sseebbbbee** [comment]
I used pip install --user .  Then I will reinstall using pip install --user -e .instead

**Comment by kohr-h** [comment]
Agreed. As long as we don't have a PyPI package, `pip install --editable --user` should be default.
