### ISSUE TITLE
Examples for show()

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#170]
We have many methods in show, scatter, imshow, real, complex, etc. Is there some example for all of these laying around? Would be nice to have a "test" if you change something.

**Comment by kohr-h** [comment]
No, those have not been tested in a while. I checked all of them in the initial implementation, but having an example lying around which checks those would of course be better.

**Comment by adler-j** [comment]
If you have them somewhere, could you add them to examples?

**Comment by kohr-h** [comment]
No, but I can write some simple ones.
