### ISSUE TITLE
Diagonal operator

### ISSUE THREAD

**Issue by wjp** [odlgroup/odl#173]
It would be nice to have an operator for multiplication with a diagonal matrix.

Currently it can be written as

    y = some_vector
    D = odl.OperatorLeftVectorMult ( odl.IdentityOperator(y.space), y )

But this is rather unwieldy.

**Comment by adler-j** [comment]
You could also do

```
y = some_vector
D = y * odl.IdentityOperator(y.space)
```

But I agree, we need this. Ill add something.

**Comment by adler-j** [comment]
Now added, syntax is

```python
y = some_vector
D = odl.MultiplyOperator(y)
```
