### ISSUE TITLE
Switch argument order of insert methods

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#175]
The index parameter of the `insert` methods of `IntervalProd` and `TensorGrid` comes second, whereas the corresponding method of core Python lists take the index parameter first. We should mirror that signature.

**Comment by adler-j** [comment]
Should be a simple change, please go ahead. Some additional suggestions, probably fit for the same branch, would be

Append and extend
-----------------

Currently the following is valid

```python
>>> rbox = IntervalProd(0, 1)
>>> rbox.insert(IntervalProd(2, 3))
IntervalProd([0.0, 2.0], [1.0, 3.0])
```

This would clearly fail with the proposed change. To remedy this, I propose that we add `IntervalProd.append` and `IntervalProd.extend` defined as

```python
def append(self, item):
    return self.insert(self.ndim, item)
    
def extend(self, seq):
    result = self
    for item in seq:
        result = result.append(item)
    return result
```

this would give us similar syntax to `list`.

Simplified insert
-----------------

Currently we have an auto-casting syntax given by [casting the input argument](https://github.com/odlgroup/odl/blob/1a0c8385563783807531f63ef11c691663081854/odl/set/domain.py#L539-L540)

```python
if not isinstance(other, IntervalProd):
    other = IntervalProd(other, other)
```

Imo, this is not very useful and would probably not be used much. I propose we make the following small change:

```python
if not isinstance(other, IntervalProd):
    other = IntervalProd(*other)
```

This would allow the following syntax:

```python
>>> rbox = IntervalProd(0, 1)
>>> rbox.insert(1, [2, 3])
IntervalProd([0.0, 2.0], [1.0, 3.0])
```
