### ISSUE TITLE
Magic methods not part of documentation

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#18]
With `:automodule:` it seems class magic methods, most notably `__init__` does not get documented. This causes some obvious issues.

**Comment by adler-j** [comment]
Partial fix of this committed, we can provide a list in `conf.py` of methods *not* to skip. i added `__init__` here but we may want the others as well?

**Comment by adler-j** [comment]
I also added `__eq__` and `__contains__`, any more we want to add?

**Comment by kohr-h** [comment]
`__init__()` is definitely needed, **or** alternatively, we can move the code from `__init__()` into the class docstring. I don't think we need any one of the other functions in the doc. Many double underscores look sort of frightening.

**Comment by adler-j** [comment]
[pep-258](https://www.python.org/dev/peps/pep-0257/)

> The class constructor should be documented in the docstring for its __init__ method.

How about `_lincomb` and `_multiply`, the info in these somehow need to be exposed, no?

**Comment by kohr-h** [comment]
It would be great if one could just "put" the documentation of `LinearSpace.lincomb()` to into the child classes instead of documenting the private ones. The same for `multiply()`, `divide()` etc. Any chance to do this with Spinx?

**Comment by adler-j** [comment]
I'll see what we can do with "reference doc"

**Comment by adler-j** [comment]
We need to remove `__hash__`, then we can close this.

**Comment by kohr-h** [comment]
I see `__hash__` in the config file, closing.
