### ISSUE TITLE
Maximum levels in wavelet transform

### ISSUE THREAD

**Issue by niinimaki** [odlgroup/odl#182]
Currently we have
` if nscales >= max_level:`
`         raise ValueError('Too many scaling levels, got {}, maximum useful level is {}'
                                     ''.format(nscales, max_level))`
which is inconsistent if the maximum number of levels is given. So we should change this to:
 
` if nscales > max_level:`
`         raise ValueError('Too many scaling levels, got {}, maximum useful level is {}'
                                     ''.format(nscales, max_level))`

since we can allow the number of scaling levels to be the maximum useful number, if user so wishes (this also makes the error message more understandable if max number is used).

**Comment by adler-j** [comment]
Please fix and commit straight to master, should be fine.

**Comment by niinimaki** [comment]
Fixed and commited, closing this issue.

**Comment by adler-j** [comment]
Tip: when you do commits like this, you can write in the commit message:

`MAINT: fix check related to maximum scaling levels. close #182`

that way the issue is auto-closed and we get a link to the fix here.

P.S.
commit was: 62c7353f136135ae56e2f521687f036c39559547
