### ISSUE TITLE
Add optional support for Numba

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#188]
There's a very interesting project called [Numba](http://numba.pydata.org/) which adds JIT functionality to core python with a focus on mathematical functions. A very brief but still interesting summarizing talk can be watched in [this video from this year's SciPy conference](https://www.youtube.com/watch?v=eYIPEDnp5C4&index=23&list=PLYx7XA2nY5Gcpabmu61kKcToLz0FapmHu).

What is good about it compared to other approaches like PyPy is that it sets on top of CPython instead of defining a new language, so we don't have to make compromises wrt functionality.

The most interesting use cases for us would be
- Proper, fast vectorization instead of our own shitty one. Numba has its own [`vectorize` decorator](http://numba.pydata.org/numba-doc/0.21.0/user/vectorize.html#the-vectorize-decorator) 
- Possibility to define more general Numpy Ufuncs in the Python layer with [the `guvectorize` decorator](http://numba.pydata.org/numba-doc/0.21.0/user/vectorize.html#the-guvectorize-decorator)
- Crank down execution time of functions with repeated Ufunc evaluation as [in this issue](https://github.com/odlgroup/odl/pull/178#discussion_r48008288). Here, Numba detects the repeated evaluations and aggregates them into one loop if possible. The list of [supported Python features](http://numba.pydata.org/numba-doc/0.21.0/reference/pysupported.html) and [NumPy features](http://numba.pydata.org/numba-doc/0.21.0/reference/numpysupported.html) seems quite exhaustive.

Adding support for Numba would not be a big deal since it basically consists of a couple of decorators only. We just decorate the functions we think (or know after profiling) will be worth it, and if Numba isn't installed, all decorators are just identity.

**Comment by adler-j** [comment]
An interesting idea, and I have done some simple tests with this. However, nIn general I am skeptical to optional features like this, mainly because we get more cases to test and support. Issues like "ODL crashing on arch-linux when using numba 1.337 in german locale" come to mind.

With that in mind, these are my comments to your use-cases

> Proper, fast vectorization instead of our own shitty one. Numba has its own vectorize decorator

For all inherent implementations we should try to use numpys vectorization, for user defined operators they are free to use Numba to vectorize their functions, and we should make sure that we properly support this, maybe even provide an example.

> Possibility to define more general Numpy Ufuncs in the Python layer with the guvectorize decorator

Which ones would we standardize?

> Crank down execution time of functions with repeated Ufunc evaluation as in this issue. Here, Numba detects the repeated evaluations and aggregates them into one loop if possible. The list of supported Python features and NumPy features seems quite exhaustive.

This case was solved using numpy vectorization, but if one of these pop up later where we really cant optimize it manually, we could discuss adding Numba there.

> Adding support for Numba would not be a big deal since it basically consists of a couple of decorators only. We just decorate the functions we think (or know after profiling) will be worth it, and if Numba isn't installed, all decorators are just identity.

Adding is trivial, supporting is not ;)

**Comment by kohr-h** [comment]
> For all inherent implementations we should try to use numpys vectorization, for user defined operators they are free to use Numba to vectorize their functions, and we should make sure that we properly support this, maybe even provide an example.

Maybe that's even sufficient. If we show how to use Numba for vectorization of functions, we don't have the duty to fully support and test it.

While thinking about this, I was wondering if the different syntax really was the only thing keeping me from using Numpy's `vectorize`. If yes, there should be a possibility to wrap it and throw out our own, very simple, implementation. I'll have a look into it.

> Which ones would we standardize?

I was more thinking of custom transforms, like multiplication with a user-defined 1D function. Nothing really "standard" worth adding to our vector ufuncs. Would also be sufficiently handled by an example.

> This case was solved using numpy vectorization, but if one of these pop up later where we really cant optimize it manually, we could discuss adding Numba there.

Outdated, yes.

> Adding is trivial, supporting is not ;)

I know, yes. We're probably better off just showing users how to do it rather than providing our own support internally.
