### ISSUE TITLE
Move solvers to odl-solvers

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#19]
I think that in the long run, the solvers need more structure than can be handled in a single file. They will probably also add dependencies on third-party software which we don't want in the core ODL package. So unless there are strong reasons against it **now**, I'll move the code to the [odl-solvers](https://github.com/odlgroup/odl-solvers) repository.

**Comment by adler-j** [comment]
I have a proposal here, and it is that we follow the idea i gave in #14. That is, we make `solvers` a `namespace package`. That way, after running something like `pip install odl-solvers`, users can access the solvers by `odl.solvers` as expected.

**Comment by kohr-h** [comment]
Actually, I think this would make sense for all of the `odl-*` packages, wouldn't it?

**Comment by adler-j** [comment]
Yes thats my idea!

**Comment by adler-j** [comment]
It seems the tests where not properly moved along the rest of the code, we need to move it and open a proper test library inside odl-solvers.

**Comment by adler-j** [comment]
This is done.

**Comment by kohr-h** [comment]
Done in which way?

**Comment by adler-j** [comment]
It is moved, now we have a larger discussion on how to handle the packages in #20. But this specific issue is performed.

**Comment by kohr-h** [comment]
Ok sure, I was hoping you had found a solution to #20 ...
