### ISSUE TITLE
Axes for show

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#191]
Currently show does not display axises, this can be somewhat confusing. I propose that we add an axis labling (and label according to numpys `[z, y, x]` scheme.

**Comment by kohr-h** [comment]
It doesn't? What about [this](https://github.com/odlgroup/odl/blob/issue-168__show/odl/util/graphics.py#L144) and [this](https://github.com/odlgroup/odl/blob/issue-168__show/odl/util/graphics.py#L242-L246)? No effect?

**Comment by adler-j** [comment]
Try the examples, I don't seem any.

**Comment by kohr-h** [comment]
You're right, they're gone. Maybe the command must be run with a method of a different class?

**Comment by kohr-h** [comment]
Maybe it's better to use the class-based approach in `matplotlib` directly instead of going via `pyplot`, e.g. `fig = mpl.figure.Figure(...)` and go on with that object instead of using `plt.figure(...)`. At least it "feels" more robust. AFAIK the `pyplot` interface is intended for interactive shells and plotting on the fly, not so much in library code.

**Comment by adler-j** [comment]
I found the bug, it seems setting the titles caused an axis to be created, which stopped them from being generated. I moved the title setting part to the end and now it works.

On a related note, calling them "x, y, z" is likely inferor to calling them something numbered: "x_0, x_1, x_2", that way, the numbering of the axes is easier to see.

**Comment by kohr-h** [comment]
> I found the bug, it seems setting the titles caused an axis to be created, which stopped them from being generated. I moved the title setting part to the end and now it works.

Yeah, that sort of stuff happens with the `pyplot` backend. Maybe we should look into this a bit further and try to use the plain `matplotlib` class interface.


> On a related note, calling them "x, y, z" is likely inferor to calling them something numbered: "x_0, x_1, x_2", that way, the numbering of the axes is easier to see.

The latter is default for more than 3 axes. With 2 or 3 axes, I thought (applied) people were more used to "x, y" and "x, y, z". I personally don't have a preference here.

**Comment by adler-j** [comment]
> Yeah, that sort of stuff happens with the pyplot backend. Maybe we should look into this a bit further and try to use the plain matplotlib class interface.

I certainly see why, but I dont feel like spending to much time on this atm

> The latter is default for more than 3 axes. With 2 or 3 axes, I thought (applied) people were more used to "x, y" and "x, y, z". I personally don't have a preference here.

I agree that most applied people would be used to "x, y, z", the issue is that numpy uses "z, y, x", so we get a clash of definitions here.

**Comment by kohr-h** [comment]
Okay, new issue then.
