### ISSUE TITLE
Pylint complains about element_type 

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#192]
The implementation of `element_type`, e.g.

``` python
class FunctionSet(object):
    ...
    @property
    def element_type(self):
        """`FunctionSetVector`"""
        return FunctionSetVector
```

makes Pylint complain about an instance method not using the `self` argument, and rightly so IMO. One way to remedy this would be to replace the code by just

``` python
class FunctionSet(object):
    ...
    element_type = FunctionSetVector
```

which I think would be acceptable. It sure removes the write protection, but do we really need it?

I don't know a better workaround since `@property` and `@staticmethod` cannot be combined.

Last possibility is to just add `no-use-self` to the Pylint ignore list.

**Comment by adler-j** [comment]
A valid concern and imo we should use the:

```python
class FunctionSet(object):
    ...
    element_type = FunctionSetVector
```

solution. Especially since one may want to access the element type of the `class` and not of a single instance.

**Comment by kohr-h** [comment]
This is still valid and easy to fix. I'll get this done.

**Comment by kohr-h** [comment]
Are we still gonna do this? It will require to reorder the definitions of element and space, since otherwise the element class is not defined at the time it's needed in the definition of the space class.

**Comment by kohr-h** [comment]
I'll close this, we have more important things to do.
