### ISSUE TITLE
Remove order argument in FunctionSetMapping

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#193]
Now that grids handle 'C' and 'F' orderings internally, I guess there is no more need for an extra argument in the `FunctionSetMapping` classes. We should remove the argument and use the grid ordering instead.

**Comment by adler-j** [comment]
Agree, especially since we could have `FunctionSetMapping`s on non `TensorGrid`s I suppose?

**Comment by kohr-h** [comment]
Exactly. We already duck-type to a certain degree by relying on `contains_set` and `contains_all`, where the latter can be circumvented by switching off `bounds_check`. Other than that, we could generalize `FunctionSetMapping` to non-`TensorGrid` structures.

**Comment by kohr-h** [comment]
This is obsolete after the discussion in #249.
