### ISSUE TITLE
Reduce Pylint warnings

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#194]
We have close to 1000 Pylint errors and warnings now. Some are just a result of Pylint not being able to understand the code properly. Others are things we don't want to change like variable names `x` or `n`. But then there are also relevant warnings where we should take a closer look.

I suggest that we
- globally disable errors and warnings where Pylint simply screws up,
- add variable names we consider okay to the list of accepted ones and change others to something better,
- try to resolve the remaining relevant warnings.

**Comment by kohr-h** [comment]
Apart from the list above, I suggest that we remove any local `# pylint: disable=...` comments and live with the warnings. Such comments just clutter the code at no real gain.

**Comment by adler-j** [comment]
A very nice idea, especially agree with removing the `# pylint : disable=...` since these are tool-dependent.
