### ISSUE TITLE
Write a CONTRIBUTING document

### ISSUE THREAD

**Issue by odlgroup** [odlgroup/odl#2]
We need some advice for people who want to contribute but do not exactly know how. Intended audience are users and developers. We should describe

- How to best get acquainted with the code
- How to work with Git[Hub] - fork, branch, pull request
- How we would like contributed code to look like

**Comment by Berzerka** [comment]
Regarding the second two parts, I recommend we use [GitWash](https://github.com/matthew-brett/gitwash) to provide a introduction to this. GitWash provides a standardized "howto" for git flow, and is used by many projects, including numpy.

**Comment by Berzerka** [comment]
Regaring *How to best get acquainted with the code* this is something we need to write on our own.

**Comment by adler-j** [comment]
The document still needs improvements, for example some references on styles. I'll reopen this until it is in place.

**Comment by adler-j** [comment]
Looks quite good to me. Now we simply need to write a more detailed guide at some time, but that's not for this issue. Right?

**Comment by kohr-h** [comment]
I think the gitwash documentation is quite detailed about the workflow, just a bit unspecific. I'd say we just improve that. New issue!

**Comment by adler-j** [comment]
Gitwash is mostly for git workflow. I was thinking more of the "where would I put method X", how do I think about concept "Y" things. ODL specific stuff.
