### ISSUE TITLE
Tessellations

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#202]
It seems that we don't get around implementing these properly separately from grids and ease the latter from their "double" function of representing point collections and spatial partitions at the same time.

Name TBD, suggestions are
- `Tessellation`: correct, but rather unknown I guess
- `Tiling`: more intuitive, but a 2d notion
- `Partition`: general and extensible (e.g. with overlap). Maybe too general?
- `Voxelization`: ok but 3d notion and very special

I personally like `Partition` best.

**Comment by adler-j** [comment]
Is this done by the partitions?

**Comment by kohr-h** [comment]
Yes
