### ISSUE TITLE
Direction of rotation

### ISSUE THREAD

**Issue by moosmann** [odlgroup/odl#205]
I'm not sure if this was already discussed, but how do we handle if we have to reverse the direction of rotation? One cannot simply reverse the interval limits since `Interval` requires that `begin<end`. So should one add an additional argument in the geometry classes or is there a way to provide a grid with negative stride?

**Comment by adler-j** [comment]
The obvious way would be to do:

```python
grid = odl.TensorGrid(np.linspace(1, 0, 10))
```

and use that. Currently it fails since we (for some reason) require the grid points to be increasing.

In the long run, we may want a way to create these. But we need to decide on a way to do this that applies also for higher dimensional cases.

**Comment by moosmann** [comment]
It wasn't that obvious to me and probably won't be for the user, especially if it fails. When using Matlab with GATE simulated, I already had an issue with an incorrect direction of rotation which is why I think we will need this feature rather soon.

**Comment by kohr-h** [comment]
I'm hesitant toward the "reversed interval" approach. There are some things (e.g. gridding and then interpolation) which require increasing values.

My suggestion would be to steer this via the `axis` parameter of the rotation, i.e. `[0, 0, 1]` for "right-hand-rule" rotation around the third axis ("z"), and `[0, 0, -1]` for the opposite direction. We're going to need helpers for class creation in the standard cases anyway, and there we could simple add a `clockwise=False` parameter.

I think we should start writing such helpers soon.

**Comment by adler-j** [comment]
> I'm hesitant toward the "reversed interval" approach. There are some things (e.g. gridding and then interpolation) which require increasing values.

Valid concern, lets see if we can work around it.

> My suggestion would be to steer this via the `axis` parameter of the rotation, i.e. `[0, 0, 1]` for "right-hand-rule" rotation around the third axis ("z"), and `[0, 0, -1]` for the opposite direction. We're going to need helpers for class creation in the standard cases anyway, and there we could simple add a `clockwise=False` parameter.

Using the axis is perfectly viable I suppose, but it would require some conversions in some cases, perhaps thats fine though.

> I think we should start writing such helpers soon.

Yes, when we have time :)

**Comment by kohr-h** [comment]
This seems to be settled for now, closing.
