### ISSUE TITLE
Premade geometries

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#206]
One of the most common use-cases will be users that want to use some of the well known manufacturers geometries, for example the Elekta Icon geometry. To do this, I suggest we add a new file `odl/tomo/geometry/[NAME]` where NAME could be `preset`/`helpers` or something else.

Inside this we add a few classes that inherit from the corresponding generalized geometry, i.e. something like

``` python
class ElektaIconGeometry(ConeFlatGeometry):
    """ A CBCT geometry using the Elekta Icon calibration parameters """
    def __init__(self, SAD=780, SDD=1000, piercing_point=[390, 0], angles=np.linspace(1.2, 5.0, 332)):
        """ Create geometry

        Defaults given by design specification
        """

        ...

        super().__init__(...)
```

**Comment by kohr-h** [comment]
How about this? Is it still relevant?

**Comment by adler-j** [comment]
It is highly relevant, in fact, maybe I actually have permission to do this and should get it done.

**Comment by adler-j** [comment]
The main change from the suggestion would be to simply make this a free function.

**Comment by adler-j** [comment]
This has been added. https://github.com/odlgroup/odl/tree/master/odl/contrib/tomo
