### ISSUE TITLE
Readthedocs failing due to ufuncs

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#207]
At some point ufuncs where rewritten to get information from numpy, but since we bootstrap numpy at readthedocs, we now fail with:

```
  File "/home/docs/checkouts/readthedocs.org/user_builds/odl/envs/latest/lib/python3.4/site-packages/odl-0.9b1-py3.4.egg/odl/util/ufuncs.py", line 71, in <module>
    descr = ufunc.__doc__.splitlines()[2]
AttributeError: 'NoneType' object has no attribute 'splitlines'
```

**Comment by kohr-h** [comment]
I see. We can for sure go back to an explicit list, but that's quite a maintenance nightmare. Any chance to get this running in a different way?

**Comment by kohr-h** [comment]
On the other hand, an upside of the explicit list is that we can fix the dead links in the Numpy docstrings.

**Comment by adler-j** [comment]
Enabled `numpy` on RTD and removed mock of it, should be fixed now. Close after build button is green.
