### ISSUE TITLE
Allow operator + vector in range

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#21]
Since operators like the `ResidualOp` in the solver tests probably occur rather often, I suggest that we support adding an operator and an element in its range to create a new `AffineOperator` (may suggest linearity) or `ShiftedOperator` whose derivative is the one of the original operator, of course.

**Comment by adler-j** [comment]
What would the action of that be?

````python
(op+vec)(x) = op(x) + vec*x
```

right?

**Comment by adler-j** [comment]
If we do this we clearly want to add a `op - vec` aswell.

**Comment by kohr-h** [comment]
I was more thinking of `(op+vec)(x) = op(x) + vec`, for range elements at least. Actually mostly `op-vec`, as you wrote, as in `residual_op = op - vec`.

**Comment by kohr-h** [comment]
If there is no obvious behavior of this operator overload, then it's probably better to just create a class to support it.

**Comment by kohr-h** [comment]
Actually, your proposed action is already covered by `op + vec.T`, right?

**Comment by adler-j** [comment]
I dont think we should do what you propose then, simply because it would violate the distributive law.

What you said is equivalent to

```python
(op+vec.T)(x) = op(x) + x.inner(vec)
```

I think we should implement this as a named operator in `default_ops`.

**Comment by kohr-h** [comment]
Err, I don't quite follow. This is already supported, or am I missing something? `vec.T` is an `Operator`, and that you can add to `op` as long as `op` is a functional.

Can you be more specific about the distributive law violation? I don't see it.

**Comment by adler-j** [comment]
`op + vec.T` is supported where `op` is a functional, indeed.

Regarding violating the distributive law, one would expect

```
(A+B)(x) = A(x) + B(x)
```

Here `A=op` so the intepretation is obvious, but with `B=vec` this is nonobvious. For most of us, one generally inteprets `vec` as multiplication by the vector. See e.g. our quasi-newton algorithm

```
(vec * vec.T)(x) = vec * vec.T(x)
```

The other case doesnt realy make sense to me, then we would have `vec(x) = vec`, which doesnt realy rhyme for me.

One option would be to add (and we prolly should do this anyhow)  a function called `ConstantOperator` such that:

```python
ConstantOperator(vec)(x) = vec
```

That way we could write, very clearly

```python
(A - ConstantOperator(vec))(x) = A(x) - vec
```

**Comment by adler-j** [comment]
Any decision on this?

**Comment by kohr-h** [comment]
Dunno. But the expression type operator looks fine to me, and if we want some shortcut later, we can still add it. Or just forget about that this issue ever existed :wink:

**Comment by kohr-h** [comment]
Does the `ConstantOperator` exist? We may want to implement it together with the `ResidualOperator`.

**Comment by adler-j** [comment]
Proposal made for that, closing this.
