### ISSUE TITLE
TensorGrid.size not consistient with other methods

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#214]
For all our classes (and numpys) `size` returns the number of elements, this does not apply for `TensorGrid` and `RegularGrid`.

**Comment by kohr-h** [comment]
We should then find a better name for what now is `size`, i.e. the vector of total extent per axis. Maybe `extent` would be appropriate.

**Comment by adler-j** [comment]
`extent` is a perfectly ok name for me.

**Comment by kohr-h** [comment]
Then we should rename also the `IntervalProd` mehtod accordingly.
