### ISSUE TITLE
DiscreteLp.show() displays two identical figures

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#217]
As the title says, when calling `show()` without arguments, two figures appear.

**Comment by kohr-h** [comment]
Update: that must have something to do with the interactive mode. If I additionally specify `show=False`, it still shows a plot - in the console if I plot inline, otherwise in a window.

**Comment by adler-j** [comment]
It is because show returns the fig object, and apparently that causes it to be shown in IPython.

**Comment by kohr-h** [comment]
> It is because show returns the fig object

Do we always have to do that?

**Comment by adler-j** [comment]
> Do we always have to do that?

No, but it is convenient to get the image when you plot.
