### ISSUE TITLE
Title for second subfigure gone in DiscreteLp.show for complex data

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#219]
For plots of complex-valued functions, the subplots should have the labels "Real part" and "Imaginary part", which was the case until some internal change. Now the title for the first subfigure is still there, but the second one is gone.

**Comment by kohr-h** [comment]
![phantom_dft](https://cloud.githubusercontent.com/assets/5030250/12327587/b14d1a22-bad7-11e5-9bc2-6c770bb136d3.png)

**Comment by adler-j** [comment]
Add an example to `examples/visualize` of this, then we can try to find the bug.

**Comment by kohr-h** [comment]
Okay, now we have one since 0ca93d94d224b5cdf926de584ee9512bc084dc4f.

**Comment by kohr-h** [comment]
If I store the figure of the plot in `fig`, I get the following:
```python
>>> for ax in fig.axes:
>>>     print(ax.title)
Text(0.5,1,'Real part')
Text(0.5,1,'')
Text(0.5,1,'')
Text(0.5,1,'')
```
The title is never stored properly.

**Comment by adler-j** [comment]
It is likely never set, we had this bug before. Check the length of the axes, they may not be as small as we expect in the `len(axes)` calls.

**Comment by kohr-h** [comment]
I checked that, the control flow goes into the case where the title is set.
