### ISSUE TITLE
Astra and exception safety

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#221]
Currently our astra code is not exception safe. For example, if the user does `CTRL-C` during execution, the allocated volume will not be deallocated, but irreversibly lost.

I suggest that we implement a context manager so that we do not leak memory in these cases.

**Comment by kohr-h** [comment]
We have a context manager now, does this still apply?

**Comment by adler-j** [comment]
Yes, the manager is only used in some cases and could still leak memory in some corner cases. With that said, we could perhaps close this since this *really* is an upstream astra issue.

**Comment by kohr-h** [comment]
Since there already is [an upstream issue](https://github.com/astra-toolbox/astra-toolbox/issues/20) on this, let's close it here.
