### ISSUE TITLE
Tests for STIR bindings

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#222]
We currently don't have any tests for the STIR bindings. The interface is still rudimentary, but at least some very simple tests should be possible. Our Jenkins CI has a build job for it which successfully compiles STIR (at least on Python 2.7, on 3.4 their Numpy detection is broken), so it's integrated into our CI flow.

**Comment by adler-j** [comment]
We do have an example, perhaps adding a slow test for STIR that makes sure it can be used to reconstruct some volume to decent precision would be nice?

**Comment by kohr-h** [comment]
That would indeed be nice. Maybe it's even possible to generate a very small example which runs fast enough for a unit test? Otherwise, a test mock would help. Right now STIR bindings have zero test coverage, which is somewhat retarded.

**Comment by adler-j** [comment]
A mock could do but thats damn complicated, Ill likely just make a slow test for this.

**Comment by adler-j** [comment]
Added some, but made it a pull into conebeam since we may want to do this for astra and others as well.
