### ISSUE TITLE
Automatic build jobs per branch

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#223]
The current landscape of builds for issue branches is somewhat okay to start with, but not ideal. There is one job (in different flavors) for all branches containing "issue", so at least all branches following that name convention will be built and tested.

This is quite limited obviously - if there are alternating pushes to different branches, all figures like test results, code coverage etc. will be rather jumpy and not very useful. And the email notifier has a hard time figuring out to whom emails should be sent.

I'm looking for a solution to create jobs on the fly from templates in a way that new jobs are created for each new branch, and old jobs without repo branch are deleted. 

I tried [Jenkins build per branch](https://entagen.github.io/jenkins-build-per-branch/), which is supposed to do exactly that, but it relies on outdated features of [gradle](http://gradle.org/), and I didn't get it to work with our authentication layout.

Further possibilities are the [Jenkins Job Generator Plugin](https://wiki.jenkins-ci.org/display/JENKINS/Job+Generator+Plugin) and the direct use of [the command line interface](https://wiki.jenkins-ci.org/display/JENKINS/Jenkins+CLI) and some bash-scripting.

**Comment by kohr-h** [comment]
Found a nice solution, the [Multi Branch Project Plugin](https://wiki.jenkins-ci.org/display/JENKINS/Multi-Branch+Project+Plugin). It creates groups of build jobs with a (static) configuration, one for each branch, and it automatically manages new and deleted branches. I'll migrate our server to that solution.

**Comment by kohr-h** [comment]
This is up and running now, together with a mechanism that reuses old builds of compiled extensions if the commit hash has not changed. There are some remaining issues:

- [ ] Sometimes new scheduled builds (usually the first one on a brand new branch) are "empty" and just block the executors until they bail out. Need to check when exactly this happens and if there's a way to avoid it.
- [ ]  New branches require compilation of all extensions from scratch since the stored builds are per job. Maybe storing at a central location would be possible, but if I remember correctly it's not possible to reuse compiled objects in CMake after changing parameters in the configuration, even if it's only the install location.
- [ ] Email notification does not yet do what it's supposed to do, namely notify the people involved in changes that require a notification. There seems to be some trouble with the interaction with Git. Some more observations and tests necessary.

**Comment by adler-j** [comment]
Do we need this issue to stay open?

**Comment by kohr-h** [comment]
No, this has been working reliably for some time. Closing.
