### ISSUE TITLE
Using __array_ufunc__

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#225]
Since numpy 1.10 the function `__numpy_ufunc__` is available, this allows us to "steal" calls such as:

`np.multiply(x, y)` and use our own implementation. This could be useful for CUDA, and would allow users to use the more traditional `np.absolute(x)` syntax instead of only allowing `x.ufunc.absolute()`.

**Comment by kohr-h** [comment]
That's cool, and the good thing is that it's only an optional add-on in case you have Numpy >= 1.10.

**Comment by adler-j** [comment]
Agree!

**Comment by kohr-h** [comment]
Now that we intend to implement this to solve #248, it will be part of the "obvious way to do things" rather than something optional. Or at least the `numpy.something` full functionality will be reserved to `numpy>=1.10`.

A quick research on the availability of this version in the distros shows:
- Ubuntu / Debian: 1.8.2 (really ancient)
- Fedora 23 (current stable): 1.9.2 (not ancient but not cutting edge either)
- Fedora 24 (upcoming): 1.10.4
- [Sabayon Linux](https://www.sabayon.org/): 1.10.4 (honestly the best distro I tried so far)

So most people would need a `pip` version or use anaconda.

**Comment by adler-j** [comment]
Well IMO, the obvious thing is to use built in operators (`a + b`) and the efficient thing is to use our own inplace guys `a.lincomb(1, a, 1, b)`. 

This is mostly for users who feel "at home" with numpy and expect it to work. We already kindoff support it through `__array__` and `__array_wrap__`, adding this would enable users to use the `out` argument. I would still consider it optional (but it should be documented).

**Comment by adler-j** [comment]
It seems this feature is actually not in 1.10, see https://github.com/numpy/numpy/pull/6146

We'll have to wait for it.

**Comment by kohr-h** [comment]
Oh god yes, I remember reading into a similar discussion way back when I was curious. Must have been a predecessor to the linked one. Oh well, then we simply wait.

Still weird that our vectors are not accepted as `out`.

**Comment by adler-j** [comment]
We now have an issue for that on numpy:

https://github.com/numpy/numpy/issues/7158

**Comment by kohr-h** [comment]
Great!

**Comment by kohr-h** [comment]
This feature is [finally available in Numpy 1.13](https://github.com/numpy/numpy/blob/master/doc/release/1.13.0-notes.rst#__array_ufunc__-added)!

**Comment by adler-j** [comment]
Oh my God, it's happening! Let's get this done ASAP!

**Comment by adler-j** [comment]
Ok, now that this has been finally made available, we need a transition plan.

My suggestion is as follows:

* Implement `__array_ufunc__` and make a default that has it call `vec.ufuncs` for now.
* Try to keep all logic inside `__array_ufunc__` from now on (e.g. less logic in the ufuncs library)

Open questions:

* Do we mark `vec.ufuncs` as deprecated for users with `numpy >= 1.13`?

**Comment by kohr-h** [comment]
> Implement `__array_ufunc__` and make a default that has it call vec.ufuncs for now.

Why this way? Can't we let `ufuncs` try to call `__array_ufunc__`? Somewhat similar to [here](https://github.com/kohr-h/libgpuarray/blob/002fd94bb53804f2cbc37659608913252b9c6506/pygpu/_array.py#L22-L59). This is basically only a bundling of all ufunc logic which happens to have the name `__array_ufunc__`. So the internal workings don't rely on Numpy 1.13, only the external `numpy.ufunc(myvec)`.



> Do we mark vec.ufuncs as deprecated for users with numpy >= 1.13?

I'm for it, at least if we can make the new solution work exactly the same.

**Comment by kohr-h** [comment]
I'll try to get this done.

**Comment by adler-j** [comment]
WOOOHOOO
