### ISSUE TITLE
Landweber solver for self adjoint positive definite operators

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#229]
It is sometimes interesting to consider self-adjoint positive definite operators, often they occur as the normal operator (`A.adjoint * A` for some `A`).

The regular landweber iteration is:

```python
x = x + omega * A.adjoint(b - A(x))
```

which for SPD operators can be simplified to 

```python
x = x - omega * (b - A(x))
```

this gives better convergence and slightly better storage use.

**Comment by kohr-h** [comment]
Have you checked in the literature if that really does something sensible? What does the iteration converge to? There is a result for Kaczmarz type methods where you can replace the normal operator inverse with some other positive operator if the norm of the replacement is larger than the square of the norm of the original operator. I'm quite sure you need something similar here, too. But Landweber is not scale-invariant anyway (need to adapt omega).

**Comment by adler-j** [comment]
> Have you checked in the literature if that really does something sensible? What does the iteration converge to?

A is SPD, so we have A^(1/2) = B where B is also SPD, and lets call B^(-1) b = c, then the iteration is:

```
x = x - omega * (  b - A(x))
x = x - omega * B * B^(-1) * (  b - A(x))
x = x - omega * B * ( B^(-1) b - B^(-1) A(x))
x = x - omega * B * ( c - B(x))
x = x - omega * B.adjoint * ( c - B(x))
``` 

Hence it converges to the same result as applying landwebers method to the problem `B(x) = c`, which has the same solution (if one exists) as `B * B(x) = B c` -> `A(x) = b`). Omega may ofc need to be adapted.

**Comment by kohr-h** [comment]
Sure, makes sense.

**Comment by adler-j** [comment]
This is obviously a version of gradient descent, sometimes you are stupid. Anyway I improved `steepest_descent` somewhat to allow this use case more simple. Closing.

**Comment by kohr-h** [comment]
> This is obviously a version of gradient descent, sometimes you are stupid. 

I hope you didn't mean me :-)

Quick thought: If I'm not totally off, Landweber's method is simply a gradient descent for the minimization problem `||A(x) - y|| -> min`, where the gradient is calculated with respect to the inner product in the range of `A`.

Your version of Landweber would then, I think, correspond to gradient descent for the same problem, but with respect to the inner product `<x, u>_A = <Ax, u>` (or perhaps `A^(-1)`) which makes sense because `A` is self-adjoint and positive definite.

That's what came to my mind when I read it, not sure if it's correct.

> Anyway I improved steepest_descent somewhat to allow this use case more simple. Closing.

**Comment by adler-j** [comment]
> I hope you didn't mean me :-)

ofc not :-)

> Quick thought: If I'm not totally off, Landweber's method is simply a gradient descent for the minimization problem `||A(x) - y|| -> min`, where the gradient is calculated with respect to the inner product in the range of `A`.

More simply (and perhaps equivalently) `x^T A x - 2 * a^T y -> min`

**Comment by kohr-h** [comment]
> Quick thought: If I'm not totally off, Landweber's method is simply a gradient descent for the minimization problem ||A(x) - y|| -> min, where the gradient is calculated with respect to the inner product in the range of A.
> 
> More simply (and perhaps equivalently) x^T A x - 2 x^T y -> min

For linear and self-adjoint `A`: probably yes. Anyway.
