### ISSUE TITLE
Write a summary of supported operator expressions

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#23]
I have somewhat lost track about what expression in which combinations of operators, scalars and vectors are currently supported and what they mean mathematically.

I suggest that we write up a documentation chapter about operator expressions, possibly summarized as a table containing (example: `operator * scalar`)

- The expression: `op * scal`
- What it means mathematically: `x --> op(scal * x)`
- Conditions: `scal in op.domain.field`
- The created expression class: `OperatorRightScalarMult`

**Comment by adler-j** [comment]
Sure we can do this, but this is already documented (or should be) in the functions `__add__`, `__mul__` etc, shouldnt this be enough?

**Comment by kohr-h** [comment]
Yes, sure, but I was more thinking of a chapter in the introduction. IMO it is one of the strengths of ODL and it should not be hidden in the API doc.

**Comment by adler-j** [comment]
Sure why not. In that case I'd simply do the first three points however. The last one is a "implementation detail" imo.

**Comment by kohr-h** [comment]
Right. But we could link to the place in the API doc.

**Comment by adler-j** [comment]
Yes indeed! Simply writing:

`(scalar * A)(x) = scalar * A(x)`
`(A* scalar)(x) = op(scalar * x)`
`(A * B)(x) = A(B(x))`

etc would be enough imo. With good naming it will be clear that `A` is a operator and `scalar` is a "appropriate" scalar.

**Comment by kohr-h** [comment]
Alright! I can take that one.

**Comment by adler-j** [comment]
Has this been done?

**Comment by adler-j** [comment]
The intro has been moved to the doc, I'll add this summary there.

**Comment by adler-j** [comment]
This has been solved [Operator Arithmetic](http://odl.readthedocs.org/en/latest/guide/in_depth/operator_guide.html#operator-arithmetic)

**Comment by kohr-h** [comment]
Looks good!
