### ISSUE TITLE
Get unicode_literals working

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#24]
Since we're building a new package, we have the luxury of choosing whether to have unicode literals enabled by default or not. Since they are standard in Python 3, I strongly suggest that we make an attempt at it.

A known issue is the `ABCMeta` class complaining when `unicode_literals` are imported. Back then, I tried to solve it by explicitly passing a byte string, but that didn't help. There is, however, [good documentation available](http://python-future.org/unicode_literals.html) which may point to an elegant solution of this problem.

If some external module really screws up and cannot be convinced at all to work, it is still possible to remove `unicode_literals` from imports selectively.

**Comment by adler-j** [comment]
A word of warning is that `unicode_literals` causes all kinds of issues when used with other Python 2 packages that assume that the input is not unicode. I spent quite a bit of time debugging one of these a few months back.

**Comment by adler-j** [comment]
Decision on this? Imo it is too complicated (and we should avoid `import unicode_literals` across the board since it "contaminates" python 2)

**Comment by kohr-h** [comment]
Well we seem to have reached some sort of de facto decision, which works well so let's keep it as it is. [At some point in the future](https://www.python.org/dev/peps/pep-0373/) we can just drop Python 2 support altogether and simplify a bunch of things.

**Comment by adler-j** [comment]
So in 4 years then, how about we close this? :D

**Comment by kohr-h** [comment]
And reopen in 2020 :-)
