### ISSUE TITLE
Where did the solvers tests go?

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#244]
I cant seem to find them?

**Comment by moosmann** [comment]
Axel also has been wondering where they are.

**Comment by adler-j** [comment]
Perhaps they got lost with odl-solvers. Does someone have a local copy of it?

**Comment by aringh** [comment]
I had a local copy in my trash, which I restored, but there are now tests in odl-solvers either...

**Comment by adler-j** [comment]
Found it! Obviously I'm the guilty one.

bd5f39be9b0676ab0fada80829249882f14c3268

Was removed when we created `odl-solvers` which caused these tests to fail, it seems no-one migrated the tests. Perhaps we should migrate some of it back.
