### ISSUE TITLE
LinearSpaceVector.multiply is not intuitive

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#248]
The purpose of
```python
>>> rn = Rn(3)
>>> x, y, z = rn.one(), 2* rn.one(), 3 * rn.one()
>>> z.multiply(x, y)  # ??? What happens with z? Is x*y returned?
```
is not really obvious, and it doesn't reflect the in-place addition etc. - instead it takes the `LinearSpace` method one-to-one. It would be much more intuitive to have `multiply` (and `divide`, which is missing) instead do
```python
def multiply(self, x):
    self.space.multiply(self, x, out=self)
```
From a user's perspective, `element.multiply()` is expected (I assume) to multiply `element` by a single given argument, equivalent to `element *= other`. The `LinearSpace` method is a different ball game, there users would expect slightly more flexibility: `space.multiply(x, y, out=z)` here it's completely clear what happens.

**Comment by kohr-h** [comment]
Apart from what I wrote above, with the current version it's *impossible* to use `element.multiply()` to multiply `element` with *one* other vector. That does not make much sense either.

**Comment by adler-j** [comment]
Its done that way because of consistency with `lincomb` and it adds functionality. The definition you suggest really doesn't add anything since you could simply write it more simply as

```python
>>> rn = Rn(3)
>>> x, y = rn.one(), 2* rn.one()
>>> x *= y
```

which is equivalent. Whereas the current implementation makes a difference in simplifying an expression:

```
>>> x.multiply(y, z)  # current
>>> x.space.multiply(y, z, out=x) # other implementation
```

> From a user's perspective, element.multiply() is expected (I assume) to multiply element by a single given argument, equivalent to element *= other

Not sure if i agree that is the correct interpretation, for example, `ndarray.multiply` returns a value:

```python 
def multiply(self, x, out=None):
    if out is None:
        out = self.space.element()
    self.space.multiply(self, x, out=out)
    return out
```

this could also be an option, but would probably "force" us to change `lincomb` to stay consistent.

>Apart from what I wrote above, with the current version it's impossible to use element.multiply() to multiply element with one other vector. That does not make much sense either.

You could do it like this:

```python
>>> x.multiply(x, y)
```

**Comment by kohr-h** [comment]
> You could do it like this:
> 
> >>> x.multiply(x, y)

I realized that some time after I wrote, but then it was too late. Forget that remark.

Regarding the core topic: I had not used this functionality for quite a while and totally forgotten how it works. So I was about in the situation of a new user trying to get accustomed with the code. For some odd reason (maybe mixing of bytecode files), the statement `vector *= other` failed to modify the vector, so I moved on to use the `vector.multiply` method. Having forgotten about its syntax, I used Spyder's internal help functionality which displayed the documentation of `multiply` as follows:
```
Definition : multiply(x, y)

Type : Method of FnVector instance

Multiply by other inplace.

LinearSpace.multiply
```
So I was confused by the (obviously wrong) documentation and by the fact that the method takes 2 arguments. I thought that (and I can very well imagine that most people would assume the same) it worked like `y.multiply(x)`, which would be the same as `y *= x` (and thus superfluous). Confronted with the fact it takes 2 input arguments, I could not really make sense of the method. The main reason for that is that I automatically read `object.action(args)` as "perform `action` with `args` on `object`", in the case of `z.multiply(x, y)` as "`multiply` `x, y` with `z`". Which is not what happens.

The point here is that the **verb** "multiply" strongly suggests the above behavior, while the `lincomb` is not immediately associated with that pattern because it's not explicitly a **verb**. It would be different if the method was called `linearly_combine`.

Looking at Numpy: the `ndarray` does not have a `multiply` method. They have the `__imul__` syntax and the `numpy.multiply` function, which corresponds to `vec.space.multiply` in our case. And that makes sense in my opinion since 
```python
>>> import this
The Zen of Python, by Tim Peters

[...]
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
[...]
```
We violate that principle to some extent because we have `space.multiply` and `vector.multiply` which *do exactly the same*, while `numpy.multiply` and `ndarray *= other` are different.

##### Summary
- `space.multiply` and `vector.multiply` are redundant and offer two ways of doing the same thing (with the former being slightly less obvious, admittedly)
- It is non-obvious what `z.multiply(x, y)` does. The IMO obvious guess that it multiplies `z` with `x` and `y` would bring nothing new to the table compared to `z *= x` followed by `z *= y`.

##### Suggestion
I suggest we remove `vector.multiply` and stick with `space.multiply` for that functionality. Since the latter is less obvious at first, i.e. to write `vec.space.multiply` if only a vector is given, we can think about implementing the analogue of `numpy.multiply` on the top level. This is, of course, not so easy since we don't have the same "linear" object hierarchy as Numpy, i.e. it would be much harder for us to determine the result type of `multiply(x, y)` with arbitrary ODL types. But that could be easily circumvented with making `out` mandatory:
```python
def multiply(x, y, out):
    """Multiply ``x`` with ``y`` and write to ``out``."""
    out.space.multiply(x, y, out=out)
```
So users could simply use `odl.multiply(x, y, out=x)` and the result type would always be perfectly clear.

**Comment by adler-j** [comment]
> Regarding the core topic ...
    
Certainly agree that it is confusing, and that doc is old. In these cases, simply "go to definition" is often helpful and gives a clear answer: `return self.space.multiply(x, y, out=self)`. Clearly that is not what we want our users to do, but the solution to that is fixing the doc.

> The point here is that the **verb** "multiply" strongly suggests the above behavior, while the `lincomb` is not immediately associated with that pattern because it's not explicitly a **verb**. It would be different if the method was called `linearly_combine`.

I always read it as "multiply these two vectors", but it's certainly not obvious which one is meant.

> Looking at Numpy: the `ndarray` does not have a `multiply` method ...

Ooops

> There should be one-- and preferably only one --obvious way to do it.

Dont realy see the problem here, sometimes a convenience is useful. For example, numpy has several ways to multiply matrices:

```python
>>> np.dot(A, B)
>>> A.dot(B)
>>> A @ B
```

they are all useful in various cases, and `np.dot(A, B)` vs `A.dot(B)` are also exactly equivalent. The same applies to `any`, `all`, `argmax`, `margmin`, `argpartition`, `argsort`, `clip`, `conjugate`, `copy`, `cumprod`, `cumsum`, `max`, `mean`, `min`, `nonzero`, `prod`, `ravel`, `sort`, `squeeze`, `std`, `sum`, `swapaxes` and `max` (just listing them all to illustrate that it's quite common).

> `space.multiply` and `vector.multiply` are redundant and offer two ways of doing the same thing (with the former being slightly less obvious, admittedly)

Agree

> It is non-obvious what `z.multiply(x, y)` does. The IMO obvious guess that it multiplies `z` with `x` and `y` would bring nothing new to the table compared to `z *= x` followed by `z *= y`.

Agree here aswell, but these are "advanced" methods, only used when users want to squeeze that last piece of performance out of storing the result in place, requiring users to read doc at that stage isnt that harsh of a requirement.

> I suggest we remove `vector.multiply` and stick with `space.multiply` for that functionality. 

Disagree, by the exact same argument we should remove `lincomb`, `norm`, `dist`, `inner` etc aswell, and they are all very convenient, or is there something specific about multiply?

> Since the latter is less obvious at first, i.e. to write `vec.space.multiply` if only a vector is given, we can think about implementing the analogue of `numpy.multiply` ...
    
Adding such a function could be done, another approach is to solve issue #225 and simply ask users to write `np.multiply(x, y, out=out)`.

Finding the type of `out` should be trivial since `x`, `y` and `out` all need to be in the same space.

**Comment by kohr-h** [comment]
>> The point here is that the verb "multiply" strongly suggests the above behavior, while the `lincomb` is not immediately associated with that pattern because it's not explicitly a verb. It would be different if the method was called `linearly_combine`.
> 
> I always read it as "multiply these two vectors", but it's certainly not obvious which one is meant.

We should make a small survey among our group and see what other people assume. Obviously there is not *the* way of reading this; you may be a bit biased because you implemented this and immediately think of the underlying space mehtod :-)





> Dont realy see the problem here, sometimes a convenience is useful. For example, numpy has several ways to multiply matrices:
>
```python
>>> np.dot(A, B)
>>> A.dot(B)
>>> A @ B
```
But you see that the method is not `A.dot(B, C)`. I'm not arguing against convenience at the cost of slight redundancy. We shouldn't confuse people, though.

>> It is non-obvious what `z.multiply(x, y)` does. The IMO obvious guess that it multiplies `z` with `x` and `y` would bring nothing new to the table compared to `z *= x` followed by `z *= y`.
> 
> Agree here aswell, but these are "advanced" methods, only used when users want to squeeze that last piece of performance out of storing the result in place, requiring users to read doc at that stage isnt that harsh of a requirement.

That's true. One could even argue that reading the doc and then use `space.multiply` isn't asking for too much either.



> I suggest we remove `vector.multiply` and stick with `space.multiply` for that functionality.
> 
> Disagree, by the exact same argument we should remove `lincomb`, `norm`, `dist`, `inner` etc aswell, and they are all very convenient, or is there something specific about `multiply`?

Yes, there is something special about `multiply` (and `divide` if it was there):
- It's a verb, suggesting that the implementation is "do this with the object I belong to" (at least IMO). This is in contrast to `lincomb`, which is less obvious from the very beginning and where I would always look up the doc.
- It maps to the same space, in contrast to all the other methods except `lincomb` you mention. For those it's clear that the result cannot be stored back in the vector, so it must be returned. There is no ambiguity. For the same reason, it is clear that Numpy's `A.dot(B)` has to return the result since it may not have the same shape as `A`.
- There is `__mul__` and `__imul__`, while the others have no corresponding syntactic sugar.


> Adding such a function could be done, another approach is to solve issue #225 and simply ask users to write `np.multiply(x, y, out=out)`.
> 
> Finding the type of `out` should be trivial since `x`, `y` and out all need to be in the same space.

Using Numpy for all of that would of course solve this. Regarding the return type, I was thinking of coercion which users may expect to work but wouldn't since we haven't formalized it yet. Of course, if we don't coerce, it's trivial.

**Comment by adler-j** [comment]
> We should make a small survey among our group and see what other people assume. Obviously there is not the way of reading this; you may be a bit biased because you implemented this and immediately think of the underlying space method :-)

Well I first implemented it as you suggested (hence the old doc), but then realized that it did not match `lincomb` and there was no way to perform `z = x * y` with the old syntax, so it was changed for practical reasons (at the same time we changed `space.multiply` from 2 args to 3 args).

> But you see that the method is not A.dot(B, C). I'm not arguing against convenience at the cost of slight redundancy. We shouldn't confuse people, though.

Agree, this is more a "tipping point" style question.

> That's true. One could even argue that reading the doc and then use space.multiply isn't asking for too much either.

Sure could, i simply think that `z.space.multiply(x, y, out=z)` violates DRY and that this is more important than the current implementation violating "there should be one way to do it", clearly a question of line drawing.

> Yes, there is something special about multiply (and divide if it was there)

> It's a verb, suggesting that the implementation is "do this with the object I belong to" (at least IMO).

Then `space.multiply` does not make much sense either, should we rename it totally?

> This is in contrast to lincomb, which is less obvious from the very beginning and where I would always look up the doc.

Agree, lincomb is "nicely complex" making users think twice.

> There is `__mul__` and `__imul__`, while the others have no corresponding syntactic sugar.

Well there is for `inner`: `x.T(y)` and `lincomb`: `x + y`. But sure.

> Using Numpy for all of that would of course solve this. Regarding the return type, I was thinking of coercion which users may expect to work but wouldn't since we haven't formalized it yet. Of course, if we don't coerce, it's trivial.

Sure, once we get to coercion this would become more complex.

##### My suggestion:

Change to numpy style implementation, this agrees with both how all our operators are implemented and with numpy and preserves the syntactic simplicity of the current implementation. Also, it is seemingly more intuitive.

**Comment by kohr-h** [comment]
>> We should make a small survey among our group and see what other people assume. Obviously there is not the way of reading this; you may be a bit biased because you implemented this and immediately think of the underlying space method :-)
> 
> Well I first implemented it as you suggested (hence the old doc), but then realized that it did not match lincomb and there was no way to perform z = x * y with the old syntax, so it was changed for practical reasons (at the same time we changed space.multiply from 2 args to 3 args).

Yes, I remember that you changed that, and sure, for spaces that was a good change.



>> That's true. One could even argue that reading the doc and then use space.multiply isn't asking for too much either.
> 
> Sure could, i simply think that z.space.multiply(x, y, out=z) violates DRY and that this is more important than the current implementation violating "there should be one way to do it", clearly a question of line drawing.

That's a good point. Hence the Numpy style implementation makes even more sense.



>> Yes, there is something special about multiply (and divide if it was there)
It's a verb, suggesting that the implementation is "do this with the object I belong to" (at least IMO).
> 
> Then space.multiply does not make much sense either, should we rename it totally?

Well, then `numpy.multply` would also make no sense. No, I think the name for the space method is fine for the same reason as the Numpy method name is fine: Because the above way of reading the method makes no sense, it must mean something else, and this "something else" is explained in the doc.

>> There is __mul__ and __imul__, while the others have no corresponding syntactic sugar.
> 
> Well there is for inner: x.T(y) and lincomb: x + y. But sure.

Yes, but `x.T(y)` really takes a heck of a detour until it becomes equivalent :-). And `x + y` only implements a small subset of the `lincomb` functionality.



> My suggestion:
> 
> Change to numpy style implementation, this agrees with both how all our operators are implemented and with numpy and preserves the syntactic simplicity of the current implementation. Also, it is seemingly more intuitive.

All good, agreed. Just to make sure we mean the same thing: "numpy style implementation" means solving #225? Or rather putting some of those ufuncs to ODL top level?

**Comment by adler-j** [comment]
> All good, agreed. Just to make sure we mean the same thing: "numpy style implementation" means solving #225? Or rather putting some of those ufuncs to ODL top level?

Well I mean both solving #225, and changing the implementation of the function to mean:

```python 
def multiply(self, x, out=None):
    if out is None:
        out = self.space.element()
    self.space.multiply(self, x, out=out)
    return out
```

perhaps we can leave `lincomb` unchanged.

**Comment by kohr-h** [comment]
Okay, cool.
