### ISSUE TITLE
What do we mean by grid ordering?

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#249]
This seems like an old issue which has been solved long ago, but I still struggle to get this straight. To me, ordering has to do with underlying storage and means that for `'C'`, the first axis is slowest, the last fastest, and vice versa for `'F'`. There are no axes swapped, no shapes changed, just the strides in the dimensions are different.

How should this be translated for grids? We cannot reorder the coordinate vectors since this would mean axis swapping. When we create meshgrids, we cannot slice differently into the 1d arrays when "blowing them up" since that would influence the final shape of a broadcast. So there's nothing left for meshgrids.
For the `points` method, it does make sense to talk of ordering since the result is an array where axes actually have a chance to vary.

It seems to me that the only place where it makes sense to define an ordering is the place where a grid (or partition) is connected to an underlying storage, i.e. in `DiscreteLp` (or `Discretization`, have to check). Apparently we should let ordering be handled there and add an `order` option to `TensorGrid.points` but not to `sparse_meshgrid`.

Side note: When arrays are broadcast in Numpy, the result is in almost all cases C-ordered, even if all involved arrays are F-contiguous:
```python
>>> x, y = np.zeros(2), np.zeros(3)
>>> x = np.asfortranarray(x[:, None])
>>> y = np.asfortranarray(y[None, :])
>>> (x + y).shape
(2, 3)
>>> (x + y).flags
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False
```

**Comment by adler-j** [comment]
Too me, orderings of a grid correspond to ordering of the points in the grid (as given by the `points` method), this exists independtly of the `DiscreteLp`

**Comment by kohr-h** [comment]
Grid ordering manifests itself in the ordering of the points array, but it's not intrinsic. The grid axes refer to actual spatial axes which are ordered as they are in the `coord_vectors` tuple. Only when you create all points and flatten, ordering comes into the game. Therefore only that method has an `order` parameter now. I think that's the way to look at it.

**Comment by adler-j** [comment]
Sounds good to me, can we close this since I think you implemented that?

**Comment by kohr-h** [comment]
It's implemented like that, yes. Closing.
