### ISSUE TITLE
Change argument of show

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#252]
Currently the first argument is in general `method`, this is basically never used, and could be changed to something more simple. Imo, there are two options:

* Change to `title` since this is quite intuitive:

    ```python
    x.show('plot name')
    ```
    
    Pros:
    * Easy to understand from code what is meant in most cases
    * Common usecase when using ODL
    
* Change to `indices` since this is most commonly used:

    ```python
    x.show(np.s_[:, 50, 50])
    ```
        
    Pros:
    * Easily the most commonly used parameter, especially with `ShowPartial`.

Thoughts?

**Comment by kohr-h** [comment]
How about this: we do something similar as Numpy in [IndexExpression](https://github.com/numpy/numpy/blob/144c34b8ecd051e05a93c6268290eadb1827afb0/numpy/lib/index_tricks.py#L603-L657). We could add a `__call__` method where the current code would go, and the `__getitem__` would take the slice and put it as `indices` into call with all other arguments default and return the result. I think this should work, and we could then write (after making the first change you suggested)
```python
>>> x.show('plot name')
>>> x.show('plot name', indices=idx_expr)
>>> x.show[:, 1]
```
How about that? I think that would at least cover the vast majority of use cases.

**Comment by adler-j** [comment]
Excellent idea, but what do we do/return in the third case? Would users need to:

```python
>>> x.show[:, 1]()
```

and would we need to make such a class for all the `show` cases (3 atm).

**Comment by kohr-h** [comment]
So I think something like this should work:
```python
class Show(object):
    def __init__(self, call):
        self.call = call

    def __call__(self, *args, **kwargs):
        return self.call(*args, **kwargs)

    def __getitem__(self, indices):
        return self.__call__(indices=indices)
```
And then, we would do the following in `DiscreteLpVector`, up to placement of `_show`:
```python
class DiscreteLpVector(...):
    ...
    # This is the old show() method
    def _show(self, ...):
        # Blabla

    @property
    def show(self):
        return Show(_show)
```
If I'm not totally off, this should work without change for all cases we have. Perhaps some wrapping / unwrapping of `self` is necessary.

**Comment by adler-j** [comment]
That would cover some use cases, but it would (perhaps) be useful to be able to do:

```python
>>> x.show[:,:,n//2](clim=[0, 2])?
```

Tbh perhaps this may be somewhat complicated. I wonder how complicated it would be to allow slice getting instead:

```python
>>> x[:,:,n//2].show(clim=[0, 2])?
```

this would also follow conventional syntax.

**Comment by kohr-h** [comment]
Yeah the quirk really offers only the basic slicing as convenience, slicing directly into the vector would be better, of course.
