### ISSUE TITLE
Helper for __repr__

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#255]
As mentioned in #253, we currently hardcode in many places how objects print themselves, especially when it comes to arguments, line breaks etc. We should use a flexible helper as noted in [this post](https://github.com/odlgroup/odl/pull/253/files#r51535642) and consistently use it across the library.

**Comment by adler-j** [comment]
It feels like the number of repr is not growing as much anymore, and standardizing this at this point would be a hefty effort with marginal gain. Do we still want to do this?

**Comment by kohr-h** [comment]
I agree that it doesn't feel quite as urgent any more. We can close and re-open when we feel the need to do so.
