### ISSUE TITLE
DiscreteLp for p='inf' gives wrong norm

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#259]
We have this currently:
```python
>>> discr = odl.uniform_discr([-1, -2], [1, 2], (4, 8), exponent='inf')
>>> discr.one().norm()
0.25
```
The reason for this behavior is that we decided to implement the weighted infinity-norm as
```
||x||_w,inf := ||w*x||_inf
```
which is not consistent with other values of `p`. I'd say we revert this decision and ignore weighting for the inf-case. Otherwise, any implementation using norms with exponents will have to set the weight manually to 1 for p=inf, which is kind of annoying.

**Comment by adler-j** [comment]
Why not simply have the weight be set properly as the default in the case of p==inf?

**Comment by kohr-h** [comment]
That's possible, but then, as I wrote, any future space involving such a p-norm would need to make this distinction. This is easy to forget and leads to surprising results as above.

**Comment by adler-j** [comment]
Well removing the option makes weighted l infinity spaces impossible to create, which is obviously not that good. Perhaps somehow making this misstake harder to make would be an option?

**Comment by kohr-h** [comment]
I started writing three different arguments against keeping it but all of them broke down after a second thought. So okay, we keep it as it is.

The only place this is currently actively used is in `uniform_discr`, where the weight for the `dspace` is set. Perhaps a utility like the `dspace_type` for the creation of the instance would be helpful and reusable later.

**Comment by kohr-h** [comment]
This is fixed.
