### ISSUE TITLE
Alternative to indices in show

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#260]
We strive quite hard to allow users to think continuous, the `indices=...` concept kindoff breaks this, and is often hard to think about (at least I have to do some mental gymnastics each time I call it for nontrivial cases).

How about adding some "continuous" syntax, that translates to indices. Some examples of how this could look is:

```python
# Make space
X = uniform_discr([-1, -1], [1, 1], 157)
x = X.element(...)

# Current
x.show(indices=np.s_[:, 78])  # slice through the middle

# Some alternatives
x.show(values=[None, 0.0])
x.show(values=np.s_[:, 0.0])
x.show(y=0.0)
```

**Comment by kohr-h** [comment]
That's a good idea. The indices thing was more of a quick hack to get slices fast and error-proof. Perhaps it's possible to use the syntax in the last row dynamically, i.e. we look in `kwargs` for parameters `x0, x1, ...` and slice according to the assigned values:
```python
slice_args = {k: v for k, v in kwargs.items() if k.startswith('x') and k[1:].isdecimal()}
for xi, vals in slice_args.items():
    # calculate slices for each given parameter pair
```
This syntax could include ranges (`x0=[0, 1]`), maybe even value lists (`x0=(-1, 0, 2)`)? The latter may be hard to get right, or it would involve interpolation.

**Comment by adler-j** [comment]
Good suggestions, but then we should change the text shown in the plots to x0, x1, etc so they match.

Regarding ranges and value lists, I think it would be nice!
