### ISSUE TITLE
Ensure ODL works with Mac

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#261]
ODL has never been run on Mac OSX, we need to make sure it works.

There's only one person with a Mac in the group, so @ozanoktem will need to do this.

**Comment by adler-j** [comment]
@ozanoktem, is this done? Do all the tests run?

**Comment by ozanoktem** [comment]
Installed Python 3.5 and Spyder on MacOS X 10.11. ODL worked fine apart from some issues related to Spyder (matplotlib and iPython). ODL tests ran fine.
