### ISSUE TITLE
Add pitch_offset

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#262]
Currently there is no way to give a "offset" along the axis for helical geometries, at angle 0, the source/detector is in a fixed hight (at z=0, by default). I propose we add a `pitch_offset` variable that allows users to specify how far along the axis the source should be when ``angle=0``.

This is redundant, since users could theoretically move the volume such that it matches, but this requires a specific choice of coordinate system which may not be natural.

**Comment by kohr-h** [comment]
You may even have to rotate the whole system since your new starting point may not lie on the old helix. Makes sense
