### ISSUE TITLE
ODL version

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#269]
We are currently at `0.9b1` for some reason (change [here](https://github.com/odlgroup/odl/commit/68d737024ae4be1c268bedc53c918bdf37866fd8)), I.m.o, once we have the tomography in, we should declare ODL to be beta 0.1, and start official versioning, aka starting a dev branch.

**Comment by kohr-h** [comment]
Sure, agreed. And then put it on pypi, see #20.



> aka starting a dev branch.

In what way would that be different from master? Wouldn't you usually define milestones with goals and a deadline, and then attach tags once you reached a version milestone?

**Comment by adler-j** [comment]
> In what way would that be different from master? Wouldn't you usually define milestones with goals and a deadline, and then attach tags once you reached a version milestone?

No not really, we could keep using master for it.

**Comment by adler-j** [comment]
Version now set to 0.1.0, and we should properly adher to this and follow good versioning from now on. I also made a tag of this release:

https://github.com/odlgroup/odl/releases/tag/v0.1.0
