### ISSUE TITLE
Sequence space l^p

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#270]
For the Fourier and wavelet transforms it would be nice to have a sequence space to map to, instead of a pure `Fn` (multidimensional sequence spaces). I suppose that it could simply be done by a factory function which creates a `DiscreteLp` with grid stride 1 and no weighting:
```python
def sequence_space(shape, exponent=None, weighting=...):
    ndim = len(shape)
    # Handle weighting, e.g. a constant or an (ndim,) array of constants
    return uniform_discr([0] * ndim, shape, shape, nodes_on_bdry=True, weighting=weighting)
```

**Comment by adler-j** [comment]
Do we want to view these as discretizations of the infinite dimensional space of convergent sequences?

**Comment by kohr-h** [comment]
We could, but then we'll have the same situation as with functions. We cannot formally check if a series converges or not (e.g. if it is represented by an `iterable`). So in a way, we could see sequences as a functions mapping an index from some index set (Z^d) to a real or complex number.

**Comment by kohr-h** [comment]
Done
