### ISSUE TITLE
Implement linear deformations using reproducing kernels

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#273]
We need to implement linear deformations of the form

```
g(x) = f(x + v(x))
```

where `f(x)` is a `DiscreteLp` vector and `v(x)` is given by

```
v(x) = sum_i K(x, y_i) alpha_i
```

Where `K` is a n x n matrix (n dimension of space) and `alpha_i` are coefficients in positions `y_i`.

**Comment by adler-j** [comment]
Will this truly be in core ODL? Close?

**Comment by chongchenmath** [comment]
Close please.
