### ISSUE TITLE
Biorthogonal wavelet transform

### ISSUE THREAD

**Issue by niinimaki** [odlgroup/odl#274]
Add biorthogonal wavelet transforms (related to J.-O. Stromberg's wavelet library).

**Comment by kohr-h** [comment]
Honestly I see little chance to get this
- reliable
- general (dimensions, sizes, data types etc.)
- maintainable
I suggest we close this.

**Comment by kohr-h** [comment]
Apart from that it's in a separate repo anyway. Closing.

**Comment by adler-j** [comment]
I disagree with closing. Until said repo has been opened this should stay open.

**Comment by kohr-h** [comment]
I don't see anybody *needing* this and any way to get it usable. In a way we already have biorthogonal wavelets through pywavelets. I see little chance of making JO's library usable in the [above](https://github.com/odlgroup/odl/issues/274#issuecomment-274654741) sense.

**Comment by adler-j** [comment]
We'll that is true.
