### ISSUE TITLE
Style of citation

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#279]
### Examples

- Journal article, 1 author
```
.. [Eul1741] Euler, L. *Solutio problematis ad geometriam situs pertinentis*.
   Commentarii academiae scientiarum Petropolitanae, 8 (1741), pp 128--140.
```
- Book, 2 authors
```
.. [SW1971] Stein, E and Weiss, G. *Introduction to Fourier Analysis on
   Euclidean Spaces*. Princeton University Press, 1971.
```
- Book, 3+ authors
```
.. [Pre+2007] Press, W H, Teukolsky, S A, Vetterling, W T, and Flannery, B P.
   *Numerical Recipes in C - The Art of Scientific Computing* (Volume 3).
   Cambridge University Press, 2007.
```
- Proceedings article, 3 authors
```
.. [BLZ2008] Bertero M, Lanteri H, and Zanni, L. *Iterative image
   reconstruction: a point of view*. In: Censor, Y, Jiang M, Louis, A K.
   Proceedings of the Interdisciplinary Workshop on Mathematical
   Methods in Biomedical Imaging and Intensity-Modulated Radiation
   (IMRT), Pisa, Italy, 2008, pp 37--63.
```

### Tags

Since [these references are global](http://www.sphinx-doc.org/en/stable/rest.html#citations) throughout the doc, we need unique citation tags. I suggest the following, close to what @moosmann has been using in the Chambolle-Pock branch, which is a slight variant of the "alpha" BibTeX style (see examples):

- 1 author: **First three letters** of the family name plus **full year**. Append "a", "b" etc. if there are multiples.
- 2-3 authors: Capitalized **first letters** of the family names plus **full year**. Disambiguation as above.
- More than 3 authors: **First three letters of first author** plus **"+"** plus **full year**. Disambiguation as above.

### Authors
- **Family name** (no special characters) - comma - **first letters of given names** without punctuation, separated by space
- 2 authors: "and" between author names without preceding comma
- 3 or more authors: "and" between second last and last author names, including preceding comma

Full stop at the end.

### Title
**Full title** (no special characters) as **emphasized** type (between `*`). For books, volume info is appended after the closing `*` as "(Volume n)".

Full stop at the end.

### For books
**Full name of the publisher** (without city) - comma - **year**.

Full stop at the end.

### For journal articles
**Full name of the journal** - comma - **issue** - **year in parentheses** - comma - **"pp" plus page range**.

Full stop at the end.

### For proceedings
**"In: "** - **editor(s)** (format as above) - **"(Ed.)"** or **"(Eds.)"** - full stop - **full name of the collection** - comma - **publisher** (if available) - comma - **year**

Full stop at the end.

EDIT: adapted 3+ authors example, removed introductory text.

**Comment by adler-j** [comment]
Is there an ongoing effort to fix this?

**Comment by kohr-h** [comment]
Mostly done, waiting for tests.
