### ISSUE TITLE
pep8 checking in build server

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#28]
The build server should do pep8 checking and report fail if it does not work.

**Comment by kohr-h** [comment]
Yes! :sunglasses:

**Comment by adler-j** [comment]
There is now a branch for this, and I can confirm that the build server gives us errors when the pep8 tests fail.

I opted to disable E402, that imports are not on top. This is since it seems to fail with `future`. Other than that, I've fixed 17 files, 13 to go.

Currently pep8 is run on the tests as well, I suppose that s good?

**Comment by kohr-h** [comment]
Yes, why not. It's easy to fix, not like writing docs or similar. And yes, disable the 402 error, we cannot avoid it.

**Comment by adler-j** [comment]
This is now up to date and working, closing this.
