### ISSUE TITLE
rounding error in grid

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#280]
The following code seems to have some issue:

```python
>>> n = 2  #seems independent of this
>>> agrid = odl.uniform_sampling(0, 1, n)
>>> agrid.convex_hull().contains_all(agrid)
False
```

**Comment by kohr-h** [comment]
Confirmed. The problem seems to be in `contains_all` since
```python
>>> 0.0 in agrid.convex_hull()
True
>>> 1.0 in agrid.convex_hull()
True
```

**Comment by kohr-h** [comment]
Turns out to be a missing feature rather than a bug, `contains_all` does not handle grids.

**Comment by adler-j** [comment]
If I'm not missunderstanding that code, it does not handle iterables at all? Shouldnt the final `return False` instead be `return super().contains_all(other)`? or similar?

**Comment by adler-j** [comment]
Btw, regarding feature missing vs bug, I'd still consider this a bug since the behaviour is not the same as the expected behaviour (in this case as implied by the doc "Test if all points defined by ``other`` are contained."), for me feature missing is for when there is no implied way to do something (such as no default convolution operator).

**Comment by adler-j** [comment]
The issue seems to still hold according to my comment above, but we can simplify the example:

```python
>>> I = odl.Interval(0, 1)
>>> I.contains_all([0.1, 0.2])
False
```

**Comment by adler-j** [comment]
Improved the fix somewhat, now the examples above all run.

**Comment by kohr-h** [comment]
We also discussed the `is_valid_...` functions, and with the change that lists are considered valid arrays and tuples always meshgrids if possible, the list example would work with that one, too. So actually, the `asarray` should take place in the `is_valid_input_array` function.

**Comment by kohr-h** [comment]
Ok, maybe it is a bug
