### ISSUE TITLE
Grid.append causes rounding errors

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#281]
The following appears to be a bug:

```python
>>> n = 2
>>> agrid = odl.uniform_sampling(0, 1, n)
>>> dgrid = odl.uniform_sampling(-50, 50, n)
>>> agrid.convex_hull().append(dgrid.convex_hull()) == agrid.append(dgrid).convex_hull()
True  # as expected
```

but if we change `n` to 3, we get

```python
>>> n = 3
>>> agrid = odl.uniform_sampling(0, 1, n)
>>> dgrid = odl.uniform_sampling(-50, 50, n)
>>> agrid.convex_hull().append(dgrid.convex_hull()) == agrid.append(dgrid).convex_hull()
False  # wtf?
```

**Comment by kohr-h** [comment]
Cannot confirm this bug. I get `True` in both cases.

**Comment by adler-j** [comment]
This may be on the conebeam branch (which still doesnt have partitions), could you try it with `uniform_partition` instead?

**Comment by kohr-h** [comment]
If I make a uniform partition and fish out the grid, there's no difference:
```python
>>> part = odl.uniform_partition(0, 1, 2)
>>> part.grid.convex_hull().contains_all(part.grid)
True
```
Anything else you may mean with "it"?

**Comment by adler-j** [comment]
That is not the examples in this issue though?

**Comment by adler-j** [comment]
This likely has to do with the `as_midp` thing, so should probably carry over into partitions. Should be no need to fish out the grid.

**Comment by kohr-h** [comment]
> That is not the examples in this issue though?

Sorry. Mixing up issues.



> This likely has to do with the as_midp thing, so should probably carry over into partitions. Should be no need to fish out the grid.

There is no `as_midp` for partitions. And furthermore, there are not really two ways of doing the same thing as you did above. With some acrobatics, one can do this, but then you actually discard information about the endpoints which need to be recomputed, so we can get rounding errors:
```python
>>> n = 2
>>> apart = odl.uniform_partition(0, 1, n)
>>> dpart = odl.uniform_partition(-50, 50, n)
>>> apart.insert(1, dpart) == odl.uniform_partition_fromgrid(
...     apart.grid.append(dpart.grid))  # The second way is shitty code
True
>>> n = 3
>>> apart = odl.uniform_partition(0, 1, n)
>>> dpart = odl.uniform_partition(-50, 50, n)
>>> apart.insert(1, dpart) == odl.uniform_partition_fromgrid(
...     apart.grid.append(dpart.grid))  # This code deserves to fail
False
```
This is not a bug IMO since the `uniform_partition_fromgrid` has no knowledge of the true endpoints.

**Comment by kohr-h** [comment]
BTW, I realized that partitions don't have an `append` method yet. Will add.

**Comment by adler-j** [comment]
Perhaps this goes away with the partitions. Will close this for now.

**Comment by kohr-h** [comment]
We'll see what happens when the partitions are in the cone beam branch.
