### ISSUE TITLE
Helper function for computing edge slices in `finite_diff` function

### ISSUE THREAD

**Issue by moosmann** [odlgroup/odl#282]
See title.

**Comment by kohr-h** [comment]
Background: `finite_diff` has to handle a substantial amount of complexity in the way the boundary is handled. It depends on the parameters `edge_order`, `padding` and `method`. This complexity should be factored out (especially since there will probably be more padding methods).

**Comment by adler-j** [comment]
I've read through the code and honestly doing this would be hard, there is just enough differences for this to not be doable without overlap, and quite a bit of repetition would need to be done if these parts were factored out into a free function. Suggest close.

**Comment by kohr-h** [comment]
Well yeah. Probably it would make the code more implicit and harder to read.
