### ISSUE TITLE
Optimization for x[:] = x.asarray()?

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#284]
In some constellations one ends up with a situation equivalent to the title. For example, if one has a function expecting an array-like input and an optional `out` parameter, where changes are made in place for the case `out is arr`:
```python
def modify_array(arr, out=None):
    if out is None:
        out = np.array(arr, copy=True)
    elif out is arr:
        pass
    else:
        out[:] = arr

    # modify out
    return out
```
If used with, e.g., a `DiscreteLpVector` `x`, it would be nice to just write
```python
>>> x[:] = modify_array(x.asarray(), out=x.asarray())
```
without substantial overhead if `x` has a Numpy array as storage backend, i.e. if `x` would understand that the return value of the function is just the result of its own `asarray()`. For CUDA arrays, this construct would work anyway, with the unavoidable copy back and forth.

Now the `asarray` method of `DiscreteLpVector` creates a reshaped view into the result of its `ntuple.asarray()` result, which in turn is a copy for CUDA vectors and a view for Numpy vectors. So the core issue is to find out if two views are equivalent.

One possible way to do this is to first check if `isinstance(self.space.dspace, Ntuples)` to make sure that we have Numpy backend and then compare `self.asarray()` to the `values` in `__setitem__`. Something like this perhaps:
```python
class DiscreteLpVector(...):
    ...
    def __setitem__(self, indices, values):
        if values in self.space:
            return self.ntuple.__setitem__(indices, values.ntuple)  # already there
        elif (isinstance(self.space.dspace, Ntuples) and
              equiv_views(self.asarray(), values) and
              indices in (slice(None), Ellipsis)):
            return self  # no-op
        else:
            # pipe through array
```
and the `equiv_views` method would do something like this:
```python
def equiv_views(v1, v2):
    for v in (v1, v2):
        if not isinstance(v, np.ndarray) or v.base is None:
            # base is None means own data, i.e. not a view
            return False

    return (v1.base is v2.base and
            v1.shape == v2.shape and
            v1.strides == v2.strides and
            v1.dtype == v2.dtype)
```
This should uniquely determine a view, right?

Or perhaps there is a completely different way to address the whole issue.

EDIT: added missing condition on `indices` for the optimization.

**Comment by kohr-h** [comment]
Some quick testing with the above in place:
```python
>>> discr = odl.uniform_discr([0, 0], [1, 1], [1000, 1000])
>>> x = discr.element()
>>> y = discr.element()

>>> %timeit x[:] = x.asarray()
The slowest run took 16.70 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 3: 19.8 µs per loop

>>> %timeit x[:] = x
The slowest run took 15.61 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 2.05 µs per loop

>>> %timeit x[:] = y
The slowest run took 26.66 times longer than the fastest. This could mean that an intermediate result is being cached.
1000 loops, best of 3: 370 µs per loop

>>> %timeit x[:] = y.asarray()
The slowest run took 4.14 times longer than the fastest. This could mean that an intermediate result is being cached.
1000 loops, best of 3: 400 µs per loop
```
According to a quick profiling run, the main difference in time between the version with `asarray` and without is spent in additional instance checks (only the one for `Ntuple`, not `np.ndarray`), which is another good reason to get rid of `abc`.

**Comment by adler-j** [comment]
This needs some benchmarking, but the current pattern should clearly be changed to using #254 instead. When doing that one we can ensure that we solve all issues with performance.

**Comment by adler-j** [comment]
Can we close this?

**Comment by kohr-h** [comment]
Yes
