### ISSUE TITLE
Style of examples

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#290]
We have some good example code snippets, but other examples are not so digestible. I'll try to collect some guidelines for writing good introductory examples. Feel free to edit and extend.

### 1. Be concise
- Keep the code as **short** as possible. Try to stay below 20-30 statements.
- Show **one functionality** at a time. Make separate files for different scenarios, group them in a folder if adequate.

### 2. Be explicit
- Write a **docstring** telling in sufficient detail **what the code does**. Don't assume users will infer that information from the comments.
- **Comment** the code adequately (but still try to be concise and exact).
- Use **arguments by keyword**. This can in many cases replace an explaining comment.
- Mention limitations or usage of experimental code which may be subject to change.

### 3. Don't assume anything
- Write code and comments for somebody who skims through the repository for the very **first time** and happened to click on this file.
- Assume **no prior knowledge** of the programming concepts we apply. Explain what is obvious to you.

### 4. Have somebody else read the code
- A second pair of eyes will spot weaknesses or unclear explanations better than yours.
- If possible, ask a colleague or even a person not familiar with the software if the example is comprehensible.

**Comment by adler-j** [comment]
I have a short suggestion in that we should have someone else than the guy who wrote the example initially go through the examples and add doc as needed. We may also want to remove some examples.

**Comment by kohr-h** [comment]
Good suggestion, agreed.

**Comment by adler-j** [comment]
I suppose the actual issue here is fixing this and adding this to the "developing for odl"? I'll get to it as a easy exercise.

**Comment by adler-j** [comment]
Anything to do here atm?

**Comment by kohr-h** [comment]
We can close for now and use this as reference.
