### ISSUE TITLE
Input parameter checks in geometry methods

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#296]
From the discussion on the `issue-87__conebeam` branch:

> We need to find a better way to handle the checks for validity of
>     given parameters. Better both with respect to DRY (which is horribly
>     violated right now) and with respect to vectorization (which is
>     effectively disabled now). The latter could be remedied by using
>     `contains_all` everywhere, but while we're at it we should also
>     address the first issue.

The only thing preventing the implementation as `FunctionSpace` elements with a specified domain is the fact that most of them are vector fields, which are not supported by `FunctionSpace`. The latter would be a rather large change with guaranteed follow-up issues, although nice to have.

In the meanwhile, we need to find a way to get rid of all the code duplication. Perhaps a small decorator would do the trick for now.

**Comment by kohr-h** [comment]
There's a chance to solve these when tensors are supported, i.e. when vector- and tensor-valued functions become possible.

**Comment by adler-j** [comment]
How does this related to recent stuff in #968? What is left to do?

**Comment by kohr-h** [comment]
The vectorization is on the way (I'll make a PR into master very soon). When it comes to input checks and DRY, okay, it may be possible to do the checks in a less repetitive way. But it's not that bad honestly, and using some `FunctionSpaceElement` or so for the methods would be way overkill IMO. I say leave it as it is for now.

**Comment by kohr-h** [comment]
I'd say this is done with the merged vectorization PR #1059
