### ISSUE TITLE
Test geometries properly and handle corner cases

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#298]
From the discussion on the `issue-87__conebeam` branch:

> The documentation says that the detector in the geometries with flat
>     detector is assumed to be perpendicular to `src_to_det`. However,
>     since the detector axes can be defined freely, this is no longer true.
>     That is especially relevant for the calculation of the correct back-projection
>     weight, which has not been done at all yet.

And:

> Some of the options can be combined in quite awkward ways, and I'm
>     not always sure that the assumptions we make hold in all thinkable
>     situations. We definitely need to sit down and think these scenarios
>     through. In any case, **we need tests** for all these methods!
> 
> One example for this is the parameter `src_to_det` in the helical
>     geometry. If this vector does not happen to lie in the plane perpendicular
>     to the `axis`, it is probably not handled correctly down the road (e.g. in
>     `src_position`).

Hence, the following TODOs:
- [ ] Write tests for all input parameter configurations
- [ ] Update the documentation
- [ ] Fix handling of corner cases like described above (if necessary)

**Comment by adler-j** [comment]
Was this fixed by #968?

**Comment by kohr-h** [comment]
Actually yes. I'll close it.
