### ISSUE TITLE
RayTransform and its adjoint duplicate lots of code

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#299]
From the discussion on the `issue-87__conebeam` branch:

> `RayTransform` and its adjoint share quite a bit of code. I think the
>     better pattern here would be to add an optional `range` parameter to
>     `RayTransform`, then make `RayBackProjection` a subclass of it and
>     just switch the roles of domain and range, plus adapt the `adjoint` and
>     `_call` methods, of course. Everything else should be the exact same.

This applies to many operators, e.g. also the wavelet transform. Basically the adjoint is copy-paste with adaptions at the obvious places.

**Comment by adler-j** [comment]
A quite note here is that the solution to this is to use something along the lines of the `FourierTransformBase` design.
