### ISSUE TITLE
Very late failure of RayTransform

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#300]
From the discussion on the `issue-87__conebeam` branch:

> Some failures in tomographic operator occur very late, e.g. when the
    reco space has `impl='cuda'` but one chooses `'astra_cpu'` as
    operator `impl`. The error occurs only when calling the operator since
    such a check exists in the `astra_cpu_...` functions. This should be
    checked during init.

A related issue is that unknown `kwargs` parameters go through unchecked, which e.g. caused GPU projectors to fail when the name of the option was changed from `backend` to `impl`. In that case, the then-valid-but-now-unknown parameter is silently ignored, and the program falls back to default behavior.

**Comment by adler-j** [comment]
Some work has been done on this over time, but I say we leave this as is right now and update once we have actual cases. The above example has been fixed.
