### ISSUE TITLE
Standard point-wise operators on product spaces of DiscreteLp

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#306]
Some standard operations on product spaces of `DiscreteLp`, i.e. effectively vector fields, would be nice to have, in particular optimised, using temporaries, etc. Not exactly sure what's already there, but the most useful ones which I *think* are not available "for free" are

- point-wise p-norm, reducing vector fields to scalar functions
- automatic broadcasting of arithmetic operations of the type `ProductSpace(X, k).element() + X.element()`
- automatic broadcasting of operations "product space vector (length k) * array (length k)", i.e. scaling per dimension
- inner product probably works through `pspace_vec.T`?
- perhaps more stuff I forgot

**Comment by adler-j** [comment]
Hasnt this been implemented? The only one I'm missing is the option to do pointwise sum.

**Comment by kohr-h** [comment]
How about the automatic broadcasting (second and third points)? That is, if we want it.

**Comment by adler-j** [comment]
New issue I.m.o.

**Comment by kohr-h** [comment]
Okay, why not
