### ISSUE TITLE
Use Scipy FFT instead of the Numpy one

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#315]
Scipy's FFT implementation has two main advantages over Numpy's somewhat basic one:
1. It handles data types correctly, i.e. 'float32' input is transformed to 'complex64'. Numpy always upcasts to double-precision types.
2. It supports in-place evaluation, which would save us a copy.

We should definitely use it. Some care has to be taken with respect to mocking it for ReadTheDocs.

**Comment by kohr-h** [comment]
See also [here](https://github.com/numpy/numpy/issues/6012).

**Comment by ozanoktem** [comment]
Agree with Holger. So how does it?

**Comment by kohr-h** [comment]
Low priority I'd say. The scipy version also has the problem that it stores real and imaginary parts separately rather than an array of complex numbers. That makes it tedious to handle and probably voids parts of the potential speed benefits. I'd say close this.

**Comment by adler-j** [comment]
Well another option is to add a third backend, but I'd like to know that it has any benefit before we proceed. I say close for now since i highly doubt we will ever do this.

**Comment by kohr-h** [comment]
> Well another option is to add a third backend, but I'd like to know that it has any benefit before we proceed. I say close for now since i highly doubt we will ever do this.

This would only be a slight speedup for the default back-end, but representing the range would cost extra effort, or alternatively efficiency would suffer by casting between Scipy representation and our own. I'd consider an additional back-end based on [scikit-cuda](https://github.com/lebedov/scikit-cuda) much more promising.
