### ISSUE TITLE
Make LinearSpace methods more permissive?

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#319]
We have very strict rules currently when it comes to `LinearSpaceVector` methods, like arithmetic, inner product etc. For example, the following is an error:

``` python
>>> odl.Rn(2).one() + (2, 2)
Traceback (most recent call last):
...
TypeError: unsupported operand type(s) for +: 'FnVector' and 'tuple'
```

At the same time, this is okay:

``` python
>>> odl.Rn(2).one() + 2
Rn(2).element([3.0, 3.0])
```

I think we should consider a change of paradigm here, from "forbid all except" to "allow all except". Concretely, this would mean that we test for `other in space` first. Then we check if `isinstance(other, self.space.element_type)` and raise an exception if `True` (don't allow foreign space elements). We go on with `other in space.field` and if both were `False`, we use `self.element(other)`. If it fails, we return `NotImplemented`. For example

``` python
class LinearSpaceVector(...):
    ...
    def __add__(self, other):
        """Return ``self + other``."""
        # Instead of using __iadd__ we duplicate code here for performance
        if other in self.space:
            tmp = self.space.element()
            return self.space.lincomb(1, self, 1, other, out=tmp)
        # --- Start added code ---
        elif isinstance(other, self.space.element_type):
            raise TypeError('other is of the same type, but not an element of {}'.
                            ''.format(self.space))
        # --- Stop added code ---
        elif other in self.space.field:
            one = getattr(self.space, 'one', None)
            if one is None:
                return NotImplemented
            else:
                # other --> other * space.one()
                tmp = one()
                self.space.lincomb(other, tmp, out=tmp)
                return self.space.lincomb(1, self, 1, tmp, out=tmp)
        else:
            # --- Start modified code ---
            try:
                other = self.space.element(other)
            except (TypeError, ValueError):
                return NotImplemented
            else:
                return self.__add__(other)
            # --- Stop modified code ---
```

A side effect of this would be that we get rid of the notorious 

```
TypeError: unsupported operand type(s) for +: 'DiscreteLpVector' and 'DiscreteLpVector'
```

error message which makes no sense at all.

**Comment by adler-j** [comment]
Will read more on this, see also #272.

**Comment by kohr-h** [comment]
Any new insights on this? I feel it hasn't hurt too much in the past.

**Comment by adler-j** [comment]
Well my biggest issues with this are twofold:

* `x.inner([1, 2])` feels like it should work.
* #272, i.e. adding vectors and arrays work. sometimes.

The second is obviously a bug, while the first is more subtle. Do we want to allow it?

**Comment by kohr-h** [comment]
The first one would be a change from requiring `y in x.space` to `y = x.space.element(y)`, which would be simple to implement. But we shouldn't try to be too liberal regarding broadcasting etc., need to find a good compromise there. See also #856.
