### ISSUE TITLE
Move oputils to util

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#325]
This would allow us to call the oputils things as

```
odl.util.MYUTIL
```

instead of the clumsy and less obvious

```
odl.operator.oputils
```

**Comment by kohr-h** [comment]
This will create circular dependencies since `util` is implicitly assumed not to depend on anything. I suggest that we simply import the names in `oputils` one level up so we get `odl.operator.MYUTIL`. That's semantically even better that the non-telling `odl.util` prefix.

**Comment by adler-j** [comment]
With the current design we cannot do that since anything in the `operator` namespace is imported into the `odl` namespace, I'm not quite sure how we would handle that.
