### ISSUE TITLE
Building doc on RTD fails

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#332]
We get this error:

```python
Error

Build exited due to time out
```

This obviously has to be rectified.

**Comment by adler-j** [comment]
Should be fixed (for now) by disabling some of the build options (PDF and single HTML). This is not a long term solution since we will fail once more when the code grows (to about twice the current size).

**Comment by kohr-h** [comment]
That's weird, they host much bigger code docs. What makes our docs heavier than others'?

**Comment by adler-j** [comment]
We build a separate webpage for each doc in each subclass, even down to inherited methods, I dont think others do that as much.
