### ISSUE TITLE
Move odlpp out of the core library

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#336]
Basically it is cluttering the library and we should be able to move it out. This would allow for a more extensible architecture.

I think that we should be able to do this using some kind of plugin architecture. Basically an external library (odl-cuda, in this case) could be registered, giving a "name" of the Rn type space ('cuda', here) and a "list" of appropriate classes. Pytest has a way of doing this, using something called "pluggy".

This would force us to remove all "if 'cuda'" things and instead make these general, something that is good anyway. It would also allow us to add parallel spaces later on, or allow users to extend ODL themselves more easily.

Edit: Clarification: once installed, any current usage (except explicitly instantiating a CudaRn space) would be the same as now. For example `odl.uniform_discr(..., impl='cuda')` would stay the same.

**Comment by kohr-h** [comment]
I fully agree. As far as I see it, the `default_dtype` property already moved a number of such conditional clauses out of the way. A `name` or `impl` property would then take care of the mappings from space type to `impl` string (mainly in `__repr__`). What requires most work is the `dspace_type` helper, which is too complicated anyway.

**Comment by kohr-h** [comment]
Done.
