### ISSUE TITLE
Non-obvious error messages from vectorization/meshgrid

### ISSUE THREAD

**Issue by aringh** [odlgroup/odl#343]
I have been lagging on following the updates on odl the last months, but when I tried to run my old code I got the strange error message
```ValueError: unable to create an element of uniform_discr([0.0, 0.0], [256.0, 256.0], [256, 256]) from FunctionSpace(Rectangle([0.0, 0.0], [256.0, 256.0]))Vector: float() argument must be a string or a number, not 'FunctionSpaceVector' ```
For me this is a counter-intuitive error message, but after some help from @adler-j it turned out to be due to that when the discretization calls the continuous function, it does so with a meshgrid (which I could not handle). Hence with a simple ```vectorized=False``` the problem was solved. However, it is not obvious from the error message that that is what is wrong.

I also had trouble with a 1D case. A minimal working example is
```
def my_cos(x):
    return np.cos(x * 2)

dom = odl.FunctionSpace(odl.Interval(-1, 1))
f = dom.element(my_cos)
disc_domain = odl.uniform_discr_fromspace(dom, 10, exponent=2.0)
f_disc = disc_domain.element(f)
```
Again, a ```vectorized = False``` in the continuous definition solves the problem. But in this case there should, in principle, be no problem with having vectorized input. Another fix is, for example, to redefine the function to ```return np.cos(x[0] * 2)```. But then the function cannot take scalars as input, which one would maybe expect.

So:
1. Should ```vectorized = True``` or ```False``` be default?
2. Is there a way to handle the 1D-case?

**Comment by adler-j** [comment]
I agree that this is an issue and the errors are not very telling. A even shorter example would be:

```python
>>> disc_domain = odl.uniform_discr(0, 1, 10)
>>> disc_domain.element(lambda x: np.cos(x * 2))
ValueError: output shape (2, 10) not equal to shape (10,) expected from input.
```

here the output is duplicated since `x * 2` is interpreted as "repeat the tuple `x` twice", clearly not the intent of the programmer.

**Comment by kohr-h** [comment]
Ah rats, this stupid 1d case is just causing trouble. Perhaps one should pass everything through a Numpy array from the beginning and do something sensible if it fails (e.g. meshgrids with different length vectors). Needs some thought.

**Comment by kohr-h** [comment]
Or, probably better, check explicitly for a `tuple` (not a general sequence) and interpret it as a meshgrid, otherwise do something else.
