### ISSUE TITLE
Remove run_tests.py

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#35]
It seems having such a file is not pythonic, instead users should simply do

```
$ py.test
```

which should run the "usual tests". We need to update the readme aswell if we do this.

**Comment by kohr-h** [comment]
Yes sure. Seems to work the same that way. And one can enable `--pep8` :-)

**Comment by kohr-h** [comment]
Oops didn't mean to close

**Comment by adler-j** [comment]
Yeah, and with pep8 testing at travis, it should be quite easy to review pull requests.

**Comment by kohr-h** [comment]
For me, `py.test` always excludes CUDA tests. Is that intentional?

**Comment by adler-j** [comment]
Nope, fixed now, closing this run_tests is removed.
