### ISSUE TITLE
Class or helper functions to specify detector

### ISSUE THREAD

**Issue by ozanoktem** [odlgroup/odl#353]
I'm not sure if this is part of ODL or not, but I still write it as a missing feature. I think we need a class or helper functions for specifying detectors. The geometries allows one to specify the detector surface (flat, circular, cylindric, ...) and the pixelization of that surface is given by a discretization of the coordinates for the points on the detector surface. Now, detectors may contain dead areas as in many emission tomography set-ups. These are merely regions between detector blocks. One should have a higher level class where the detector layout is specified and this will generate the necessary discretization of the coordinates for the points on the detector surface.

**Comment by kohr-h** [comment]
We have [`Detector`](https://github.com/odlgroup/odl/blob/master/odl/tomo/geometry/detector.py) and subclasses. I think we can represent these more complex hierarchical detectors.

**Comment by adler-j** [comment]
So do we keep this issue open? I feel the original problem can be solved by right multiplication with a indicator vector, for more complciated cases the Detector class is where to go. I cant see anything in particular being done on this issue atm.

**Comment by kohr-h** [comment]
To me this is a non-issue.

**Comment by ozanoktem** [comment]
Judging from the comments, there is no need to introduce additional structure for defining response models associated with various detector set-ups. Is that right?

**Comment by kohr-h** [comment]
That could be easily added in concrete subclasses. `Detector` does not disallow that.

**Comment by ozanoktem** [comment]
Ok, then close this issue and we add things when needed. I expect the first use case will be SPECT and/or ET.
