### ISSUE TITLE
Rename partial's

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#367]
The "Partial" structure should be renamed so they all start with `Partial`, this will allow autocomplete to be significantly more helpful.

**Comment by kohr-h** [comment]
While we're at it: I think the name "partial" is not really conveying so much, or even slightly wrong things. It sounds like you would do something with parts of the data, or something related to  `functools.partial`. In SciPy, they call the corresponding guys [callback](http://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.linalg.cg.html#scipy.sparse.linalg.cg), which is a bit more intuitive, at least if one knows what a callback is :-).

**Comment by adler-j** [comment]
I agree, callback is much better. I'll go for that.
