### ISSUE TITLE
Failing test in test_matrix_inner

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#37]
According to [this travis](https://travis-ci.org/odlgroup/odl/jobs/91684313), the test [test_matrix_inner](https://github.com/odlgroup/odl/blob/master/test/space/ntuples_test.py#L582) occationally fails.

This is because the result in `almost_equal` is a `float`, and our automated precision selector will select a higher precision (since float is 64 bit), but the calculation was actually in 32 bit!

**Comment by kohr-h** [comment]
Should be fixed now. I think the matrices were sometimes of the wrong type. And second, the `almost_equal` helper function first converted to `complex` and then determined the places, which would then always be 5. We need tests for these helpers :-)

**Comment by adler-j** [comment]
In general I dislike testing testers (retursion, i.e. who watches who watches the watchers). We simply need another two good eyes to read that through properly. Can we close this then?

**Comment by kohr-h** [comment]
It's not that complicated, actually a small test for `_places()` would suffice. Looks like it's fixed though.

**Comment by adler-j** [comment]
How has this been fixed? I see no commit to fix it and It was failing randomly.

**Comment by kohr-h** [comment]
Oh I thought the test had failed on the issue branch. It's fixed there, time to merge :-)

**Comment by kohr-h** [comment]
Fixed now in 523934896dde312a3e505bd62a8207da88c9ce7d and 37e4216f22e7ba9c5620077c05ee989fc88913ce.
