### ISSUE TITLE
Nonsensical init pattern for Divergence operator

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#375]
Currently, we do the following:
```python
>>> space = odl.uniform_discr([0, 0], [1, 1], (10, 10))
>>> div = odl.Divergence(space)
>>> div.domain
ProductSpace(uniform_discr([0.0, 0.0], [1.0, 1.0], [10, 10]), 2)
>>> div.range
uniform_discr([0.0, 0.0], [1.0, 1.0], [10, 10])
```
I think this is very counter-intuitive and convenience at the wrong place. The obvious choice is to create an operator with its domain only if the range can be inferred, never the other way around.

**Comment by adler-j** [comment]
Agree. Our pattern is to infer ranges from domains if possible, should be simple to change.

**Comment by kohr-h** [comment]
Even the doc is wrong:
```
        Parameters
        ----------
        space : `DiscreteLp`
            The space of elements which the operator is acting on
```
I'll get it fixed.

**Comment by adler-j** [comment]
Perhaps optionally making it so that you can give domain OR range?

```python
def __init__(self, domain=None, range=None):
    if domain given
        set domain
        infer range
    if range given
        set range
        infer domain
    if both given
        set domain, range
```

**Comment by kohr-h** [comment]
I don't know.. I see your point, but I think for convenience one can simply use `Gradient.adjoint`?

**Comment by adler-j** [comment]
Im not sure if that is obvious to all users? Imo it wouldnt hurt to add this extra convenience.

**Comment by kohr-h** [comment]
Okay, but then we should do the same for the gradient.

**Comment by kohr-h** [comment]
We should also move both to `tensor_ops`, along with `Laplace` and the `finite_diff` helper.

**Comment by adler-j** [comment]
tensor_ops? not quite sure it fits there. Imo they should have their own file, something like "gradient_ops" or "derivative_ops".

**Comment by kohr-h** [comment]
`tensor_ops` is currently everything that maps `X^n` to `X^m`, where `X` is a discretized function space. In other words, one vector field to another (`n` or `m` can be 1). To me it seems there is no better place for these guys.

**Comment by adler-j** [comment]
Well we could argue the same and say both Rn and CudaRn should go into the NtuplesBase file, but it would be cluttered. I feel the same here, it will be cluttered.

**Comment by kohr-h** [comment]
> Also, my basic understanding of tensor_ops was that it was supposed to be "pointwise" operations, which these are not.

That's true so far. But while writing the PR I thought for a moment about dropping the "pointwise" from the parent class at least since it's fairly generic - just mapping one vector field to another. But then I forgot.

Anyway, the placement / naming will pop up again later when we implement more of these, but right now I think we can live with the current status.

**Comment by adler-j** [comment]
Agree, this is quite fine for now.
