### ISSUE TITLE
Where to add extra dependencies?

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#38]
For some reason, we needed the requirements in text files instead of a string in `setup.py`. What about extra dependencies? For example, the Fourier transform operator will depend on `pyfftw`, and the wavelet transform will use `PyWavelets`. I'd want to be able to pull the dependencies by writing

    pip install --user -e .[fft,wavelets]

This actually works and asks for the `extras_require` dictionary for the dependencies, so the dependency info goes there.

Question is: also into a file? Or in a string? Or is it perhaps possible to create extra sections in the requirements file? I could not find anything on the web treating the last topic.

**Comment by adler-j** [comment]
To my knowledge you can simply write (in `requirements.txt`):

```
pyfftw >= 0.1 [wavelets]
```

this is according to the [pip documentation](https://pip.readthedocs.org/en/1.1/requirements.html#the-requirements-file-format)

**Comment by kohr-h** [comment]
Hm, I'll try that, but I read that as an extra requirement *passed to the `pyfftw` install*.

**Comment by adler-j** [comment]
Regarding RTD, I changed the behaviour of `cu_ntuples` so that it is always imported. Instead, calling any of It's functions (really only `CudaRn` since this is the sole entry point) should give a "nice" error message. I think this is more appropriate behaviour, AND it works better with RTD.

**Comment by kohr-h** [comment]
So then there's no problem, right? I'll just add the stuff as extra dependencies.

**Comment by adler-j** [comment]
Sure add then as `extras_require` for now, we'll have to look into this for PyPI later.

**Comment by kohr-h** [comment]
Closed by dfc8f493d1d6ae0edd529c6fbb4ab744bb842c3f.
