### ISSUE TITLE
Chambolle-Pock denoising example produces garbage

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#383]
See title. Maybe a recent change in the CP implementation that screwed the example?

**Comment by aringh** [comment]
Depends on what you mean with garbage... I get the following reconstruction (I'm using commit 6ba4348e8cef8f23f58455fcd62ec79903a5ed85 so the change must have occurred after that if so)
![reconstruction_part_0](https://cloud.githubusercontent.com/assets/15774494/15104711/88452018-15bb-11e6-8f29-fd4c761cf74c.png)

**Comment by kohr-h** [comment]
I mean this:

![cp_denoising](https://cloud.githubusercontent.com/assets/5030250/15106042/cf938ecc-15c6-11e6-91a2-2d48640d8ef2.png)

**Comment by aringh** [comment]
Is it the [denoising](https://github.com/odlgroup/odl/blob/master/examples/solvers/chambolle_pock_denoising.py) (that is the one I have used to produce the above image), the [deconvolution](https://github.com/odlgroup/odl/blob/master/examples/solvers/chambolle_pock_deconvolve.py), or the [denoising with entropy](https://github.com/odlgroup/odl/blob/master/examples/solvers/denoising_with_entropy_type_regularization.py) you mean?

My deconvolution also produces good output, and in the current version I have the example with entropy was not yet added.

**Comment by kohr-h** [comment]
It was the standard denoising example. Never mind, it was a scaling issue. The fix is the lazy one :-).
