### ISSUE TITLE
Change combine_proximals syntax to *args

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#398]
BroadcastOperator which is the obvious "companion" of this operator has this syntax:

```python
op = odl.BroadcastOperator(smoothing, gradient)
```

While combine_proximals uses a list as input

```python
prox_dual = odl.solvers.combine_proximals([prox_l1, prox_tv])
```

I suggest we change combine_proximals to take the proximal operators by *args.

```python
prox_dual = odl.solvers.combine_proximals(prox_l1, prox_tv)
```

**Comment by kohr-h** [comment]
Agree. Manual packing into a list is unpythonic, I guess.
