### ISSUE TITLE
Division-by-zero-error in cg method

### ISSUE THREAD

**Issue by aringh** [odlgroup/odl#40]
From #36 it seems like the cg method ([found here](https://github.com/odlgroup/odl/blob/master/odl/solvers/iterative/iterative.py)) can get a division-by-zero error.

I think (but I'm not sure) that the problem is that if to many iterations are used, the exact solution is found. In this case, in the next iteration the search direction `p` found is the zero-direction, and thus `p.inner(Ap)` is zero, which is used in the code as `alpha = sqnorm_r_old / p.inner(Ap)`.

**Comment by adler-j** [comment]
More generally this is true if `p` lies in the null-space of `A`!

**Comment by kohr-h** [comment]
Even more generally, when `p` is `A`-orthogonal to itself. If `A` is Hermitian and positive definite (which I hope), it's equivalent to lying in the null space though.

**Comment by adler-j** [comment]
Ok, but since we assume those properties in `conjugate_gradient` (do we write it in the doc?), we could have a error message for this.

**Comment by aringh** [comment]
But do we only want an error, and/or should it return? If it is that `p` is in the nullspace, shouldn't we already be optimal in some sense? Is there any reason to why this is not to be considered the solution to the problem the user wanted to solve?

**Comment by adler-j** [comment]
You are correct, we should return the current solution.

However, if we ever make the solvers more thorough, we could allow it to have something like a return flag/message: `optimal solution not found, p lies in nullspace of A`

**Comment by aringh** [comment]
That sounds like a good solution. I guess the same goes for the [QN methods](https://github.com/odlgroup/odl/blob/master/odl/solvers/findroot/newton.py)... right now we only return in similar situations (but maybe there is theory that states that you are in fact optimal in these cases, I don't remember).

**Comment by adler-j** [comment]
Well if `A` is positive definite (which it should be in CG), then this has to be optimal. For the CGN method, im not so sure.

**Comment by kohr-h** [comment]
I can check it in a book. The CG method is rather tough to analyze in the infinite-dimensional setting. I think I remember a statement about what it means that the method "stops".

**Comment by aringh** [comment]
I have not read this, and the reason I found it was that I was looking for something like GMRES in infinite dimensions (since, if I remember correctly, GMRES solves `Ax = b`, but we don't need `A > 0`), but [this link](http://www.mat.univie.ac.at/~neum/contrib/cgcompact.txt) might be helpful when it comes to finding literature on CG in general spaces.
