### ISSUE TITLE
Improved integration with PyWavelets

### ISSUE THREAD

**Issue by ozanoktem** [odlgroup/odl#400]
The PyWavelet package has an extensive set of wavelets with over 70 built in filters, see [webpage](http://wavelets.pybytes.com). Furthermore, there is already an ODL wavelet operator structure that couples to PyWavelet, thus making this extensive library available from within ODL. The integration can however make better use of the capabilities offered by PyWavelet. 
1. Computing adjoint wavelet operator 
   Currently, there is no easy way to compute the adjoint of the ODL wavelet operator that makes us of PyWavelet routines. It should be rather straight forward to derive the adjoint wavelet operator even when we consider the PyWavelet routines as black/grey box. The first step is to express the filter for the adjoint. Next, these adjoint filters need to be computed for the built in filters in PyWavelet. This will allow us to implement the adjoint.
2. Applying wavelet operators along specific coordinates
   PyWavelet package offers its users the possibility to apply the Wavelet transform along specific axis, e.g., one may take the 2D wavelet transform in the first and third coordinates of function defined on R^3. One can here take a look at how @kohr-h implemented the Fourier transform in ODL.
3. Integrating wavelet functions
   There are PyWavelet routines for [Integrating wavelet functions](http://pywavelets.readthedocs.io/en/latest/ref/other-functions.html#integrating-wavelet-functions). This can be used to compute the various p-norms of wavelet functions.

**Comment by adler-j** [comment]
What's up with this one. Will it ever happen in this form?

**Comment by kohr-h** [comment]
I don't  have the time, and it doesn't seem to be terribly high on the list of folks. If someone complains about a missing feature, we can open a more focused issue IMO.
