### ISSUE TITLE
Documentation review

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#408]
Some parts of the documentation (especially the older stuff) are a bit rough and not on the same level of clarity and completeness as the newer additions. So a check and rewrite of those parts wouldn't hurt. While we're at it, there are a few points we should address as well. From the top of my head, probably more to come while going through the code:

- **Magic methods:** Documentation should be uniform. Since `_call` in `Operator` has a similar functionality, it should follow the same pattern.
- **`__init__`:** I think it suffices to write `Initialize a new instance.` instead of naming the operator explicitly. Also more friendly towards subclassing.
- **Math stuff:** In the math-heavy operators and functions, we should not try to write "pseudo-formulas". Instead, we should reduce everything before the `Parameters` section to bare minimum and leave the mathematical background to a separate `Notes` section, where it's allowed to use LaTeX markup. This is the same approach as NumPy/SciPy uses, and I think it's good. But even those math parts should be kept very brief. If more explanation is necessary, a section in the `Mathematical Background` part of the main documentation should be created instead.
- **Doctests:** I think our examples are good. But they should also follow the same style rules as the rest of the code. This includes PEP8 and variable name conventions (e.g. not `X` for a space). If lines get too long, they can be broken with a `...` in the beginning of the next line. The doctests are the code pieces that users are most exposed to, so they should be good in style.
- **Application of back-ticks:** Currently we overuse back-ticks IMO. There is no need to use them for each float or list occurrence. I think we should restrict them to internal links. Otherwise, the online documentation looks cluttered.
- **Remove leading "The":** Instead of writing e.g. "The object to test for equality", we should simply write "Object to test for equality". Less noise.
- **Consistency with trailing dots:** ~~The rule is to set a dot after a proper sentence (with predicate), or if more sentences follow.~~ We go for the solution to always put a dot at the end, see #432.
- **Properties:** Since properties look like attributes, the docstring should not say "Return ...", but rather what it *is*.

Feel free to edit and add stuff to the list.

**Comment by adler-j** [comment]
Does this issue have a definition of done or a reasonable timeframe in which something of this will be worked on? Otherwise I say we classify it as ongoing work. Doing an actual readthrough of the doc with fixes is way beyond our current scope.

**Comment by kohr-h** [comment]
There's actually a branch for this with updates for a couple of modules. I used to spend some time on it once in a while, but not so much lately. I'd still say we keep this issue open until that branch has gone in. After that it's ongoing.

**Comment by adler-j** [comment]
In my experience ongoing updates to doc is doomed to fail since the merge will become impossible to handle. Why not make several pull requests with incremental improvements? Unless there is dependencies between the changes, ofc.

**Comment by kohr-h** [comment]
That's okay for me. The changes so far affect only modules that have seen hardly any change in the last half year or so. The conflicts should be solvable.

**Comment by adler-j** [comment]
I wouldn't say any module has been left untouched, there have been a few overarching fixes to docs across the board that basically changed all files. Also, if the change is in some sense done, why not make it available to everyone.
