### ISSUE TITLE
Make developer doc more specific

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#41]
The off-the-shelf gitwash documentation is a good start, but some aspects the work flow are a bit unspecific or missing. We need to adapt those sections, e.g. coding style, commit messages.

**Comment by kohr-h** [comment]
Not sure what exactly there is to do here.

**Comment by adler-j** [comment]
Perhaps a short "introduction" under [Contributing to ODL](http://odl.readthedocs.io/dev/dev.html). It is currently very "harsh".
