### ISSUE TITLE
Doctests should not need to import odl

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#410]
EDIT: hit the Enter button too early, here comes the text.

When writing running the doctests, often times one needs some functionality from another part of the library. Then, an explicit `import odl` is necessary, otherwise pytest complains. I noticed that in Numpy, they don't have to do that. Probably one can tell the `doctest` module thing what to import before running. I'll investigate that possibility.

**Comment by adler-j** [comment]
Any idea on how to do this?

**Comment by kohr-h** [comment]
In Numpy, they [modify the test context](https://github.com/numpy/numpy/blob/1429c606643d1ad305e710c4a31cb6f398d04c53/numpy/testing/noseclasses.py#L210-L221) by injecting `numpy` under the name `np` into all doctests. I'm not quite sure how to do that in `pytest`, but it must be possible.

**Comment by adler-j** [comment]
Seems that we would need to do something similar to that then.

**Comment by kohr-h** [comment]
Actually there is a functionality in `pytest` as shown in [this pull request](https://github.com/pytest-dev/pytest/pull/1428). It's been merged into the `features` branch but not yet to `master`. So at best, it becomes available in version 2.9.2. We'll have to wait.

**Comment by adler-j** [comment]
That would require us to wait quite noticable time, at least half a few months after release, to allow people to catch up.

**Comment by kohr-h** [comment]
Sure. We can still keep this issue open until then, just to remember it. Requiring a very new version of `pytest` is anyway only possible as soon as the major distributions provide it. Or we guarantee testing support only for installations using `pip` or `conda` where the newest packages are available.

**Comment by adler-j** [comment]
This is done.
