### ISSUE TITLE
Boundary behavior for RayTransform

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#413]
@ozanoktem:

> When calculating the backprojection operator in a limited angle setting, one might very well want to include weightings at the boundary of the angular range.

**Comment by adler-j** [comment]
Frankly the above use case can be done by simply right multiplying with a weighting vector. Isn't that sufficient?

**Comment by kohr-h** [comment]
We have no possibility of convincing a back-end to do this for us, so we'll have to settle for a data pre-processing solution as @adler-j writes.
