### ISSUE TITLE
dom vs domain as operator argument

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#416]
Several operator take their domain as an argument. This is often done done by taking a `domain` OR `dom` parameter. The same applies to the `range` OR `ran`.

We need to decide on one way of doing this:

* `domain` and `range`

OR

* `dom` and `ran`

**Comment by aringh** [comment]
I think the longer names are clearer, but I guess it is considered bad to use ```range```. To not upset the community, I guess the shorter names are better?

**Comment by kohr-h** [comment]
I'd be all in for `domain` and `range`, but the big trouble is that a parameter `range` would shadow the reserved word `range` as in `for i in range(10)`.
The situation has not occurred yet, but if we happen to need the `range` sequence in the `__init__` method of an operator, we need to work around it, e.g. do locally
```python
from builtins import range as range_seq

for i in range_seq:
   ...
```
This is possible, but then we need to have a good FAQ entry for users trying to follow the same parameter name suggestion. I'd actually be okay with this.

**Comment by adler-j** [comment]
Users can ofc use whatever naming they prefer, users competent enough to follow a naming convention would probably solve this in a heartbeat. I'll do this change.
