### ISSUE TITLE
Implement Shearlet transform as operator

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#417]

**Comment by kohr-h** [comment]
I'm closing this since any code that does this would be a compiled extension and would have to live outside the core library.

**Comment by adler-j** [comment]
Agree. Until there is an universally agreed uppon backend (like numpy/pyfftw for the fft) this should be an extension in another repo. With that said, until we create said repo I'd leave this open.

**Comment by kohr-h** [comment]
Done

**Comment by adler-j** [comment]
A link helps:

https://github.com/odlgroup/odl-shearlets
