### ISSUE TITLE
Rules for proximal operators

### ISSUE THREAD

**Issue by aringh** [odlgroup/odl#419]

**Comment by adler-j** [comment]
See the ones that already exist for inspiration:

* Separable sum: [combine_proximals](https://github.com/odlgroup/odl/blob/deec86db698cbf3def7984704a9e9185b63893f5/odl/solvers/advanced/proximal_operators.py#L49)
* Complex conjugate (Moreau identity): [proximal_cconj](https://github.com/odlgroup/odl/blob/deec86db698cbf3def7984704a9e9185b63893f5/odl/solvers/advanced/proximal_operators.py#L88)
* Composition with (certain) linear operators [proximal_composition](https://github.com/odlgroup/odl/blob/deec86db698cbf3def7984704a9e9185b63893f5/odl/solvers/advanced/proximal_operators.py#L135)

Which ones are we planning to add here?

**Comment by aringh** [comment]
Versions of i), ii) and iv) from https://www.ljll.math.upmc.fr/~plc/prox.pdf
