### ISSUE TITLE
RectPartition has no length

### ISSUE THREAD

**Issue by ozanoktem** [odlgroup/odl#423]
Sometimes we need to know the number of partitions. Trying to execute the `len` command on a partition gives an error message;
```
TypeError: object of type 'RectPartition' has no len()
```

**Comment by kohr-h** [comment]
Why was this auto-closed? The PR was not merged. Bug in GitHub?

**Comment by adler-j** [comment]
The issue is open, what is the bug?

**Comment by kohr-h** [comment]
Hm, I must have looked in the wrong line in notifications. Was sure the issue appeared as closed. Never mind.
