### ISSUE TITLE
Punctuation in parameter text

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#432]
We are currently having an argument on the style of parameter doc in a few cases, I thought we could condense it here and get a final verdict.

##### The problem

There are currently three "types" of parameter docs floating around

```
Parameters
----------
trivial_param : `int`
    Something trivial
    
standard_param : `str`
    The standard parameter is very important because it is a parameter.
    
complicated_parameter : `numpy.array`
    The complicated parameter does many weird things and needs a long doc.
    Among others, it changes how the function works. It also changes the result type.
```

This issue is for the discussion on capitalization and punctuation in these three cases.

For the first, i propose two options

```
trivial_param_without_dot : `int`
    Something trivial
    
trivial_param_with_dot : `int`
    Something trivial.
```
    
For the second case, the same two options apply:

```
standard_param_without_dot : `str`
    The standard parameter is very important because it is a parameter
    
standard_param_with_dot : `str`
    The standard parameter is very important because it is a parameter.
```

I.m.o, the last case is trivial and should be written as is, with punctuation(input is ofc welcome). The first two are the hardest.

**Comment by adler-j** [comment]
My opinion is that any full sentence in ODL should have proper capitalization and punctuation, that means that in the second case we should have a dot at the end. In the first case, this is left open, but I'd probably go for a dot anyway.

For me this is mostly based on "feeling" and style, so any arguments to the contrary are welcome. My strongest objective argument would be that numpy uses punctuation.

**Comment by kohr-h** [comment]
Agree on full sentences.

To be honest, when I look at the comparison in the first case, the dotted version has something powerful and definite, while the non-dotted one looks a bit indecisive.

My main guideline here was [PEP257](https://www.python.org/dev/peps/pep-0257/#multi-line-docstrings) (scroll down to the example with parameters), as well as general language principles. But admittedly, putting a dot after a half-sentence is not wrong, so why not?

Also, it's easiest to remember to always put a dot at the end. Let's settle for that.

**Comment by adler-j** [comment]
We have a decision and have done some updates on this.
