### ISSUE TITLE
Parallel 2d backprojections are rotated by 90 degrees

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#435]
We [explicitly rotate](https://github.com/odlgroup/odl/blob/88fb4739cf7b79409507097ec9dc0265860a4d97/odl/tomo/backends/astra_setup.py#L359) by `pi/2` when translating from our geometry to ASTRA's convention. Either they changed something on their side so our fix becomes a bug, or our code was a bug in the first place.

**Comment by adler-j** [comment]
Any case where this is a known bug?

**Comment by kohr-h** [comment]
Yes. If you change [this line](https://github.com/odlgroup/odl/blob/88fb4739cf7b79409507097ec9dc0265860a4d97/examples/tomo/ray_trafo_parallel_2d.py#L37) to 
```python
angle_partition = odl.uniform_partition(0, np.pi / 4, 2, nodes_on_bdry=True)
```
and run the example, you get this:
![backproj](https://cloud.githubusercontent.com/assets/5030250/15749422/9c0d253e-28e2-11e6-99c4-fd23eecea316.png)

Apart from the weird stripes from the CPU backprojector I just used, the vertical stripe should be horizontal, and the diagonal one should run from the lower left to the upper right. In our geometry, the initial position of the detector is by default `(1, 0)` and its axis `(1, 0)`.

**Comment by adler-j** [comment]
Looks valid, should be easy do fix. Make sure you do the fix for the scikit projector as well

**Comment by kohr-h** [comment]
Same problem with the scikit guy.
