### ISSUE TITLE
Style of error messages

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#446]
We currently have a mix of styles in error messages, a cleanup would certainly not hurt. I'll use this page to compile my viewpoint on a number of error message types so we can discuss and decide on a common style. Some of these stylistic questions were already subject to earlier discussion, see #427. I cite examples from NumPy or the standard library whenever applicable.

### General points

- Do **not capitalize** error messages and do **not** end them with a **full stop**.
```python
>>> [1, 2, 3][27]
...
IndexError: list index out of range
```
- Enclose **parameter names in single back-ticks** when mentioning them explicitly.
- **Don't put back-ticks around class names** (they are capitalized and stick out anyway).
- Use the **`repr` conversion** (`{!r}` in the format string) **only for `TypeError`**. Otherwise, apply standard pretty-printing (`{}`).
- Whenever possible, write the **expected type or value first**, then what the actual input was.

### Type checking
```python
raise TypeError('`param` must be a MyClass instance, got {!r}'.format(param))
```

### Parameter validation

- If the set of **valid parameters can vary over time** (e.g. supported implementations, data types, ...) or the set of valid parameters is **too large to display**, simply print that the **value was not understood**.
```python
>>> np.sum(np.ones(1), dtype='foo')
...
TypeError: data type "foo" not understood
```
- If the **restrictions** on parameters are **easy to describe, name them** in the message. For array-like parameters that are expected to be small, they can be printed as a whole, too.
```python
raise ValueError('`ndim` must be positive, got {}'.format(ndim))
raise ValueError('`begin` and `end` must have the same lengths, '
                 'got {} and {} with lengths {} != {}'
                 ''.format(begin, end, len(begin), len(end)))
```
- For potentially **large data**, print **only the relevant figure** in the message.
```python
raise ValueError('`inp` must have shape {}, got {}'
                 ''.format(expected_shape, inp.shape)
```

### Error types
- **Raise `TypeError`** only if an input parameter is **of the wrong type**. In particular, a wrong *data type* is **not** a `TypeError`
- **Raise `IndexError`** only if an index expression that is **used to slice into data contains out-of-bounds indices**. This means in particular that e.g. an invalid `axes` argument is *not* an `IndexError`. Compare
```python
>>> np.sum(1, axis=2)
ValueError: 'axis' entry is out of bounds
```
- Pretty much **anything else is a `ValueError`**, except invalid internal states (`RuntimeError`) and perhaps some other corner cases.

**Comment by adler-j** [comment]
This has been monstly implemented and is now an ongoing issue.
