### ISSUE TITLE
Composed "convenience" operators

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#449]
I'd like to discuss an issue I have encountered several times now. Suppose there is an operator `A` and an operator `B`, and one would *really* like to have a short-hand for `A o B` since it's so convenient. One typical example is the convolution: here one has `Convolution = const * FT.inverse * kernel_ft * FT`.

For somebody who knows the math it's trivial to implement, basically one can take exactly the code as above. However, if one packages the operator `C` into a new class, then that class needs to know about all options (if one is that ambitious) of `A` and `B` and needs to check which combinations are valid. That can result in quite an explosion of complexity, without much value added apart from a new operator instead of an example of how to construct the same thing from its parts.

So the question is: on which grounds do we want to make decisions regarding creating such composition type operators? Are there any general principles we could follow?

**Comment by adler-j** [comment]
Is this issue still relevant, or do we have a decision?

**Comment by kohr-h** [comment]
I think it's settling in the case of convolution, otherwise a case-by-case decision.
