### ISSUE TITLE
Handle float64 data in astra

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#455]
ASTRA currently requires the domain to use float32 data, this feels arbitrary and adds complexity to the examples. Users should be allowed to use float64 if they want to.

**Comment by ozanoktem** [comment]
Do you mean that this is something we can fix in ODL? It sounds more that this is an ASTRA issue.

**Comment by adler-j** [comment]
Well we could copy data I guess, but yes astra should probably support this.
