### ISSUE TITLE
Helper to convert "scalar or sequence of scalar" parameters

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#460]
At a number of places, we have parameters which can be a single value or a sequence of such. In the function call, we then check if it's a single value and turn it into a sequence of identical values before we go on. A small helper would keep us from copying around code.

**Comment by adler-j** [comment]
Agree, this would be useful in many cases. Basically this would wrap [`np.broadcast_to`](http://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.broadcast_to.html), perhaps with a better interface and a backport.

**Comment by adler-j** [comment]
Done?

**Comment by kohr-h** [comment]
Sure
