### ISSUE TITLE
Deformation operators

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#464]
We need a framework for handling deformations defined by certain actions of deformation groups. 
- [x] [PR 488](https://github.com/odlgroup/odl/pull/488) Currently, we have the "standard" group action defined by right composition

```
phi.f = f o phi = ( x --> f(phi(x)) )
```
- [ ] [Issue 505](https://github.com/odlgroup/odl/issues/505) and the mass-preserving group action using

```
phi.f = |det(Dphi)| f o phi = ( x --> |det(Dphi(x))| f(phi(x)) )
```

where `Dphi(x)` is the Jacobian matrix of `phi` in `x`.

**Comment by adler-j** [comment]
edited the issue to add checklist, checked of non mass preserving and added link to the mass preserving case.

**Comment by chongchenmath** [comment]
For the mass-preserving or standard deformation operator, the case is a little bit complicated with regard to the derivative and its adjoint. Sometimes we need to compute the Eulerian derivative rather than the standard derivative. So we can first just implement the deformation operator itself.

**Comment by kohr-h** [comment]
For us, `operator.derivative` is always the standard derivative. If the Eulerian derivative is required somewhere, it needs to be a separate operator.

**Comment by chongchenmath** [comment]
Yes. But the `operator.derivative` might be useless. The another problem is the group actions like: `phi.f = f o phi^{-1}` or `phi.f = |det(Dphi^{-1})| f o phi^{-1}` where the `phi^{-1}` and `|det(Dphi^{-1})|` are given as arguments directly, rather computed from `phi`.

**Comment by kohr-h** [comment]
> Yes. But the operator.derivative might be useless.

If it's useless, we don't implement it.



> The another problem is the group actions like: phi.f = f o phi^{-1} or phi.f = |det(Dphi^{-1})| f o phi^{-1} where the phi^{-1} and |det(Dphi^{-1})| are given as arguments directly, rather computed from phi.

Makes sense, I don't see a problem as long as we don't need `phi` as well.

**Comment by chongchenmath** [comment]
Agree. The `phi^{-1} ` can be seen as a general `deformation`, and the `f o deformation` and `|det(D deformation)| f o deformation` is always useful.

**Comment by adler-j** [comment]
Closing this in favor of #505 which covers whats left.
