### ISSUE TITLE
Add FAQ

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#47]
We should gather common questions and put together a FAQ. I started one in 5fe6d3a1d9776b192ef6ffefb6d2fe3aebf12b53.

**Comment by adler-j** [comment]
Great idea!

**Comment by adler-j** [comment]
Ok suggestion time:

* "Answers to common questions" should be "Frequently asked questions" since this is the standard
* Add a word on
    ```python
    >>> import odl
    >>> rn = odl.CudaRn(10)
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "odl\space\cu_ntuples.py", line 869, in __init__
        super().__init__(size, dtype, **kwargs)
      File "odl\space\cu_ntuples.py", line 555, in __init__
        super().__init__(size, dtype)
      File "odl\space\base_ntuples.py", line 339, in __init__
        super().__init__(size, dtype)
      File "odl\space\cu_ntuples.py", line 103, in __init__
        raise TypeError('data type {} not supported in CUDA'.format(dtype))
    TypeError: data type <type 'numpy.float32'> not supported in CUDA
    ```
* Add all the stuff from the odlpp FAQ in the readme, or at least a pointer to it.
* Move the FAQ under `As a user`, no need for a new header.

**Comment by kohr-h** [comment]
> "Answers to common questions" should be "Frequently asked questions" since this is the standard

In principle, yes. We should be very careful, however, not to include stuff we *would like to be* frequently asked, like "your software is so great, how can I get it". I've seen to many FAQs without relevant contents. So okay, we change but add only stuff which is actually asked more than once.



> Add a word on (or improve)
...

Good idea to add something about that. We need to fix the error message, though. We should use a string `'float32'` as default rather than the NumPy data type, and the error message should use that, not the result after conversion by `numpy.dtype`.

> Add all the stuff from the odlpp FAQ in the readme, or at least a pointer to it.

Pointer would be sufficient, I think. And that FAQ also needs an update.



> Move the FAQ under `As a user`, no need for a new header.

Make a developer FAQ and a user FAQ?

**Comment by adler-j** [comment]
Agree on all the above.

**Comment by adler-j** [comment]
Anything more we want to add to this for now?

**Comment by kohr-h** [comment]
Yeah, close. We keep collecting questions.
