### ISSUE TITLE
Display axes end too early

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#470]
Since we use `grid` to determine the size and the ticks of the display axes in plots, the plot axes are slightly off. Example:
```python
>>> discr = odl.uniform_discr([0, 0], [2, 2], [50, 50])
>>> discr.one().show()
```
![axes](https://cloud.githubusercontent.com/assets/5030250/16413665/853b641e-3d33-11e6-9bfa-252b86f0e451.png)

We should use `partition` instead to get the limits right.

**Comment by adler-j** [comment]
There is also a possibly related issue that should be fixed while at it: The coordinates do not properly show on mouseover anymore. In this image, I'm mouseovering the image (at a pixel with value 0), but it says `x= y= [0]`, which doesnt make sense.

![img](http://i.imgur.com/e9w57uO.png)
