### ISSUE TITLE
More flexible checks for `x in RealNumbers()`?

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#481]
The current `isinstance(other, Real)` works with built-in types and perhaps some non-standard but widely spread number types, but `np.array(1.0)` evaluates to `False`. I guess the instance check is good because it's fast and checks like the one in the title are ubiquitous.

The question is if we can (want to) be more flexible and accept things that are "obviously" real numbers. Single-element arrays would be such a case, and, actually from a duck-typing perspective, anything that implements `__float__`. A corner case would be number strings like `'1.0'`.
This could be devastatingly slow, though, and I don't have a feeling for this.

**Comment by adler-j** [comment]
Well first, this is an overall decision and holds for more than `RealNumbers`. The same could be said about, for example `[0, 0] in rn(2)`. Our current policy about this is that it only returns true if it works with all elements in the space, i.e. `[0, 0] in rn(2) == False`. I feel like we should be consistent here.

A workaround for some cases would be to try converting:

```python
try:
    x = RealNumbers().element(x)
catch ...:
    pass
```

**Comment by kohr-h** [comment]
Well, the design decision was probably guided by feasibility - checking `x in rn(n)` for large `n` and some array-like structure `x` of size `n` would be expensive.

The question came up in combination with functionals and addition of scalars (range elements -- therefore the specific question for `RealNumbers`). My first reaction was that this should be done in `RealNumbers` directly, but that would make that set somewhat special, which we probably don't want. For functionals, though, I think the situation is a bit more relaxed since we know casting won't be slow, so we can be a bit more flexible here in what we allow as scalar.
