### ISSUE TITLE
Suffix "Vector" for space elements future-proof?

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#484]
By default, our space element classes have the name `<Space>Vector`, which makes sense in the context of general vector spaces - an element of a vector space is a vector. It also makes intuitive sense when talking about simple spaces like `R^n`, since there, "vector" is in line with the underlying implementation, which is a 1d array, i.e. a vector.

However, it already becomes a bit less obvious in `DiscreteLpVector`. Storage is still 1d, sure, but superficially (as in `asarray()`), i.e. from the user's perspective, it looks multi-dimensional, so the vector connotation is no longer natural. It's also not really natural math language to talk about a "vector in L^p", the majority would probably say "function" or "element".

There will be additional troubles with new data structures that are not too far away. We will, e.g., have tensors and vector fields at some point. Here, "vector" becomes kind of redundant or even contradictory. `TensorSpaceVector`? `VectorFieldVector`? That is because "vector" has a different meaning in those settings that does not match the original purpose.

So I propose that we consider renaming those classes and use a more neutral suffix. My first choice would be `Element`. It's slightly longer, but we seldom have to use the class names, and it makes an obvious connection to the `space.element()` method and the `space.element_type` property.

**Comment by adler-j** [comment]
> By default, our space element classes have the name <Space>Vector, which makes sense in the context of general vector spaces - an element of a vector space is a vector.

Well to me, there is no default except a default `__repr__` somewhere which I dislike, it says something like `<Space>Vector` and should probably be removed or changed.

> However, it already becomes a bit less obvious in `DiscreteLpVector`. Storage is still 1d, sure, but superficially (as in `asarray()`), i.e. from the user's perspective, it looks multi-dimensional, so the vector connotation is no longer natural. It's also not really natural math language to talk about a "vector in L^p", the majority would probably say "function" or "element".

Sure, a rename to `DiscreteLpElement` here would be helpful if it adds clarity.

> There will be additional troubles with new data structures that are not too far away. We will, e.g., have tensors and vector fields at some point. Here, "vector" becomes kind of redundant or even contradictory. `TensorSpaceVector`? `VectorFieldVector`? That is because "vector" has a different meaning in those settings that does not match the original purpose.

To me naming is free, we could easily call them `TensorSpaceElement` while having a `NumpyFnVector` class.

> So I propose that we consider renaming those classes and use a more neutral suffix. My first choice would be `Element`. It's slightly longer, but we seldom have to use the class names, and it makes an obvious connection to the `space.element()` method and the `space.element_type` property.

For clarity this would perhaps be the best, we may however need to have a look at the documentation if we do this, this may be used in quite a few places.

**Comment by kohr-h** [comment]
> To me naming is free, we could easily call them TensorSpaceElement while having a NumpyFnVector class.

Hm yes, perhaps these things are so deep under the hood (except when one writes `type(something)`) that naming really does not matter that much. I'm currently working on tensors and needed to break the current naming scheme, resulting in things like `NumpyTensorSpace` and `NumpyTensor`. It also seems like not all notions of space vs. element play together in the same way. Sometimes the space defines the element, like in `DiscreteLp -> DiscreteLpVector`, where one thinks of "an element of this space", sometimes it's the other way around, e.g. `VectorFieldSpace -> VectorField`, where one thinks more of "a space of such elements". Maybe it is best to respect these natural connections and adapt the naming of the classes accordingly.

**Comment by adler-j** [comment]
If you want to fix this please go ahead, it is a very minor find replace issue and shouldnt change much, but the longer we wait code may start depending on this so better do it quick.

**Comment by kohr-h** [comment]
OK, OK

**Comment by adler-j** [comment]
This is done, right?

**Comment by kohr-h** [comment]
Yes!
