### ISSUE TITLE
Expose sub-operators of operator algebra

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#486]
##### Private/public

Currently an expression like `op = op1 + op2` creates a `OperatorSum` object. If a user, for some reason, wants to access the sub-operators of this operator that is not possible using the public interface, instead users need to access the protected variable `op._op1`. There are basically two options to fix this and expose this:

* Make `_op1` public.
* Make `_op1` private, add a property.

I say we do the second.

##### Naming

These currently have weird names like `_op1` or `_left`. If we make this public, we need a standard name. There are a few options

* `op1`, `op2`
* `left`, `right`
* `first`, `second`
* etc?

I like the `left`, `right` naming since it is kindoff obvious and can be applied to all expressions like this.

In the case of scalar/vector expressions we can either chose to follow `left`/`right` convention slavishly, or go for something like `scalar`/`op`.

**Comment by kohr-h** [comment]
> I like the left, right naming since it is kindoff obvious and can be applied to all expressions like this.

Me too, it works for any kind of binary operation.



> In the case of scalar/vector expressions we can either chose to follow left/right convention slavishly, or go for something like scalar/op.

I say we do not follow slavishly if there is a better solution, like for scalar times operator.

**Comment by adler-j** [comment]
> I say we do not follow slavishly if there is a better solution, like for scalar times operator.

One obvious reason to follow it slavishly is that we can add a superclass like `BinaryOperatorAlgebra` or w/e that provides an interface for these.

**Comment by kohr-h** [comment]
Also possible, if we expect many of those guys. Perhaps the number we have already now suffices to justify such a class. We can still add properties to specialize in cases where the default names are not great.
