### ISSUE TITLE
Add function that gives matrix representation of operator

### ISSUE THREAD

**Issue by aringh** [odlgroup/odl#49]
I know that for large problems this is a BAD idea. However, for small test problems this might be a good things, especially to check things like conditioning of the problem (in my case it would be a 510x510 matrix, so it should be possible to handle).

What lead to the thought was a discussion with @ozanoktem. I have a nonlinear operator and want to solve `f(x) = 0`. I'm trying to do this with [Newton's method](https://github.com/odlgroup/odl/blob/master/odl/solvers/vector/newton.py), however the CG used there does not seem to find a solution to `gradf(x)p = -f(x)`, although  `gradf(x)` is a positive definite operator for all `x`. It would therefore be useful to be able to investigate the matrix, to see if it is ill-conditioned.

**Comment by adler-j** [comment]
I have a implementation of this laying around

```python
def getMatrixForm(op):
    n = op.range.dimension
    m = op.domain.dimension

    matrix = np.zeros([n,m])
    for i in range(m):
        v = op.domain.zero()
        v[i] = 1.0

        matrix[:,i] = op(v)[:]
    return matrix
```

**Comment by adler-j** [comment]
With that said, we could maybe add this to `utils`?

**Comment by ozanoktem** [comment]
A good idea to add the getMatrixForm type of utility to utils. Who does that?

**Comment by aringh** [comment]
@adler-j With the code you have written, would it work for discretized function spaces?

**Comment by adler-j** [comment]
Yes, it works for any `FnBase` type space.

**Comment by kohr-h** [comment]
Nice idea! Now the function just needs a proper (not-C++ style :wink:) name.

**Comment by kohr-h** [comment]
Oh, and one should add a check for `op.is_linear`.

**Comment by adler-j** [comment]
```python
def matrix_representation(op):
    assert op.is_linear
    assert isinstance(op.domain, FnBase)
    assert isinstance(op.range, FnBase)

    n = op.range.size
    m = op.domain.size

    matrix = np.zeros([n, m])
    v = op.domain.element()
    tmp = op.range.element()
    for i in range(m):
        v.set_zero()
        v[i] = 1.0
        matrix[:,i] = op(v, out=tmp)

    return matrix
```

**Comment by aringh** [comment]
I tried this on my local code, and it does not work for product operators as it is written now (first I get assertion error for not FnBase, then n and m takes value 2, since my operator goes from a product space of two spaces into a product space of two other spaces). I will have a look at it.

**Comment by kohr-h** [comment]
As a side note, `assert` should be used with care in real (read: not testing) code. According to [this discussion](http://stackoverflow.com/questions/2142202/what-are-acceptable-use-cases-for-pythons-assert-statement), `assert` can be used to test for "**invariants** and **preconditions**", but in general assert failures are bad error messages, so it is preferable to test with `if` and raise a proper exception with a good error message.

**Comment by aringh** [comment]
I'm trying to use rewrite this to work for my product operator (and currently without working for anything else than this operator. Later this can be generalized. On that note: is there a class for operators on product spaces? Is there a way to inherit from this class and create your own operator?)

So my code looks like
```
def matrix_representation(op):
    assert op.is_linear

    # For product spaces
    assert op.first_domain() == op.second_domain()

    tmp = op.first_domain().spaces
    n1 = tmp[0].size
    n2 = tmp[1].size
    n = n1 + n2


    m1 = op.first_range().size
    m2 = op.second_range().size
    m = m1 + m2

    #assert isinstance(op.domain, odl.space.base_ntuples.FnBase)
    #assert isinstance(op.range, odl.space.base_ntuples.FnBase)

#    n = op.range.size
#    m = op.domain.size

    matrix = np.zeros([n, m])
    v = op.domain.element()
    tmp = op.range.element()
    for i in range(m):
        v.set_zero()
        v[i] = 1.0
        matrix[:,i] = op(v, out=tmp)

    return matrix
```

On the line `v[i] = 1.0` spyder completely crashes... The dimensions we are talking about is n = m = 510, so quite big but it shouldn't completely kill it, or? Can anyone see some other error?

**Comment by adler-j** [comment]
* `first_domain` is not a property of operators, use `domain[0]`.
* `first_range` -> `range[0]`
* For what index does it crash?

Can we have a [minimal working example](https://en.wikipedia.org/wiki/Minimal_Working_Example)?

**Comment by adler-j** [comment]
Also, have a look at my proposal #53. With it, you could (with my `matrix_representation`)

```python
mat_1 = matrix_representation(Projection(op, 0))
mat_2 = matrix_representation(Projection(op, 1))
```

**Comment by aringh** [comment]
I know that the `first_range()` and similar are not properties of operators, I created a `ProductOperator` and in this I created these functions to be able to access them. I didn't know you could do `rang[0]`, but I will switch to it.

Regarding the crash: I can run it in the terminal without crash (in that place), so I guess it is something with my spyder (it also prints things in the terminal like `QTextCursor::setPosition: Position '35696' out of range`, which I haven't really found what it is, but it is not related to this.) Therefore I think that it is a bug in my machine somewhere, not in the code.

And yes, given #53 it could work rather easy.

**Comment by adler-j** [comment]
Regarding this proposal, I would *not* implement this for product space operators, simply because its way to complicated and the `Projection` operator would solve the issue in a mathematically nice way.

**Comment by aringh** [comment]
Yes, you are right. I will skip that and try with the `Projection` operator instead.

**Comment by aringh** [comment]
I don't really get your two-liner
```python
mat_1 = matrix_representation(Projection(op, 0))
mat_2 = matrix_representation(Projection(op, 1))
```
to work... To me it looks in #53 like the `Projection` operator should be initialized with a space (I assume the product space of interest) and not with an operator (which I assume `op` is)?

**Comment by adler-j** [comment]
The line was edited in the post earlier, try the new

```python
mat_1 = matrix_representation(op * Projection(op.range, 0))
mat_2 = matrix_representation(op * Projection(op.range, 1))
```

**Comment by aringh** [comment]
Ok, I see.

However the projection in #53 on solves part of my problem... I still have a product space as domain so `m = op.domain.size` will return 2 (in my case, since it is of the form `X1 times X2`). Moreover, the element `v` if printed in the terminal gives output of the form `ProductSpace(X1, X2).element([ [some numbers], [some other numbers] ])`, which means that `v[i] = 1.0` over-writes one of the entire "sets of numbers".

I therefore did what you advised me not to, namely changed the implementation of the matrix representation to handle product spaces. However only in the domain, since a product space in the range can be handled according to the above post. It looks like
```python
def matrix_representation(op):
    assert op.is_linear
    assert isinstance(op.domain, odl.space.base_ntuples.FnBase) or isinstance(op.domain, odl.set.pspace.ProductSpace)
    assert isinstance(op.range, odl.space.base_ntuples.FnBase)

    n = op.range.size

    m = []
    op_dom = op.domain
    if isinstance(op_dom, odl.set.pspace.ProductSpace):
        num_dom = op_dom.size
        for i in range(num_dom):
            m.append(op_dom[i].size)
    else:
        num_dom = 1
        m.appned(op_dom.size)

    matrix = np.zeros([n, np.sum(m)])
    tmp = op.range.element()
    v = op_dom.element()
    index = 0
    for i in range(num_dom):
        for j in range(m[i]):
            v.set_zero()
            v[i][j] = 1.0
            matrix[:,index] = op(v, out=tmp)
            index += 1

    return matrix
```
If you don't protest now already, I will try to branch - add - pull-request this later this afternoon.

**Comment by adler-j** [comment]
I will protest, why did you not use linearity of the operator?

```python
mat_00 = matrix_representation(Projection(op.range, 0) * op * Projection(op.range, 0).adjoint)
mat_01 = matrix_representation(Projection(op.range, 0) * op * Projection(op.range, 1).adjoint)
mat_10 = matrix_representation(Projection(op.range, 1) * op * Projection(op.range, 0).adjoint)
mat_11 = matrix_representation(Projection(op.range, 1) * op * Projection(op.range, 1).adjoint)
```

?

**Comment by adler-j** [comment]
The reason I am sceptical i that these cases tend to become somewhat complicated in the long run if we add to much complexity. They also become hard to test.

**Comment by adler-j** [comment]
With that said, please make a pull request, the functionality is clearly needed!

**Comment by adler-j** [comment]
See comment in issue 59 on another way to solve this, it would be slightly more complicated however. With that you could:

```
lin_op = coerce(op.domain, Rn(op.domain.size)) * op * coerce(Rn(op.domain.size), op.domain)
mat = matrix_representation(lin_op)
```

**Comment by aringh** [comment]
Should these kind of things be added under [odl/util/utility](https://github.com/odlgroup/odl/blob/master/odl/util/utility.py), under [odl/operator](https://github.com/odlgroup/odl/tree/master/odl/operator) in a new file called something like utility, or somewhere else?

**Comment by adler-j** [comment]
`util/utility` is for internal things and is not generally guaranteed to be tested. I'd add it under operator I think.

**Comment by kohr-h** [comment]
I think this fits better into `discr`, mostly because the matrix representation depends on the discretizations of domain and range. If the discretized operator is consistent with that, the matrix representation is what this algorithm does.
