### ISSUE TITLE
Common step length class

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#50]
Copied from [odl-solvers issue 5](https://github.com/odlgroup/odl-solvers/issues/5)

I suggest that we write a common class for step length calculation which tells the algorithm what it needs (which part of the history), such that an algorithm can determine which iterates and gradients (what else?) to keep.

A simple approach would be to give the `StepLength` class attributes

- `iter_idcs` (iterates)
- `func_idcs` (function evaluations)
- `grad_idcs` (gradient evaluations / approximations)
- `hess_idcs` (Hessian evaluations / approximations)
- `step_idcs` (step lengths)

which all return lists of indices of items to keep. An algorithm could manage lists of all these objects and pass its lists (possibly kept in a dictionary) to the step length call, which in turn does its thing to calculate the step length.

**Comment by adler-j** [comment]
We have already added a class that does some of this. Do we think that anything this advanced will be done, ever?

**Comment by kohr-h** [comment]
I don't think there will be much activity here anytime soon. The current design of step length rules is limited, though.
