### ISSUE TITLE
Python 2/3 compability in examples

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#501]
We currently have lots of examples where we do the standardized

```
# Imports for common Python 2/3 codebase
from __future__ import print_function, division, absolute_import
from future import standard_library
standard_library.install_aliases()
```

in the beginning. I personally feel that this is not good to do in general, mostly because it makes the examples technical and harder to read, as well as forcing users to scroll unnecessarily much to get to the point. My suggestion is to write rewrite the examples such that this is not necessary (where, if anywhere, this is needed) and then simply remove these lines.

**Comment by kohr-h** [comment]
Sounds good. I guess the history of this code is mostly a combination of copy-and-paste and laziness ("why remove?").
