### ISSUE TITLE
Add mass preserving deformations

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#505]
Since we have now added linearized deformations, a natural next step (needed to get OIT in, for example) is to add mass preserving deformations.

I propose that @chongchenmath does this as well, since you headed the linearized deformations.

**Comment by chongchenmath** [comment]
Yes, that is indeed supposed to do. Another thing is the implementation of LDDMM for 4D imaging problems, which is so far not involved the mass-preserving deformation, but the linearized deformation of a deformation and the general deformation of a fixed template. Maybe we need to make a discussion about this problem first.

**Comment by kohr-h** [comment]
@chongchenmath one step at a time :-). LDDMM is a whole new thing (although structure-wise we now know what to do). This is more of an extension of the linearized deformations.

**Comment by adler-j** [comment]
What do we think of this issue, will it happen? What is the fundamental difference top left multiplication with the masses?

**Comment by adler-j** [comment]
I'll close this for now. Left/right multiplication solves this.
