### ISSUE TITLE
About ProductSpace

### ISSUE THREAD

**Issue by chongchenmath** [odlgroup/odl#514]
Why cannot produce a product space like the following: 
``pspace = ProductSpace(template.space.vector_field_space, template.space)``?

**Comment by adler-j** [comment]
What error do you get?

**Comment by adler-j** [comment]
Works perfectly for me, so something is wrong

```python
>>> space = odl.uniform_discr(0, 1, 5)
>>> pspace = ProductSpace(space.vector_field_space, space)
>>> pspace
ProductSpace(ProductSpace(uniform_discr(0.0, 1.0, 5), 1), uniform_discr(0.0, 1.0, 5))
```

Will need further information to solve this. Please provide a [minimal working example](http://stackoverflow.com/help/mcve).

**Comment by chongchenmath** [comment]
Yes. The example you provided is perfect. But if I use `interp='linear'`, the type error will appear.

```python
>>> space = odl.uniform_discr(0, 1, 5, interp='linear')
>>> pspace = ProductSpace(space.vector_field_space, space)
TypeError: [ProductSpace(uniform_discr(0.0, 1.0, 5, interp=u'linear'), 1), uniform_discr(0.0, 1.0, 5, interp=u'linear')] not LinearSpace instance(s)
```

**Comment by chongchenmath** [comment]
Sorry. That is no problem.

**Comment by adler-j** [comment]
Your example works fine for me, did you find the problem?

**Comment by chongchenmath** [comment]
It is fine now.
