### ISSUE TITLE
OperatorTest adjoint test bails out if no operator norm is given

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#522]
This happens:
```python
>>> optest = odl.diagnostics.OperatorTest(my_op)
>>> optest.adjoint()
...

  File "/home/hkohr/git/odl/odl/diagnostics/operator.py", line 140, in _adjoint_definition
    denom = self.operator_norm * x_norm * y_norm

TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'
```
Either a norm estimate should be computed in the init code, or an error should be raised in the above case. However, since it's a public method, it is "intended use" and should work.

**Comment by adler-j** [comment]
I suppose the opnorm should be computed in this case, no?

**Comment by kohr-h** [comment]
Yes. The same probably applies to any public method. The question is if those methods should each check first and compute norm if necessary, or if that should happen in `__init__`.

**Comment by adler-j** [comment]
Lets make it happen in __init__ for now, why would you create such an object and not want to call a  method?
