### ISSUE TITLE
Move usage examples from _call to __init__

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#530]
We currently have documentation on how operators behave in the _call method. This is ok for the webpage, but for editors we need this to show up more simply, and there is no reasonable way to find _call as it is right now.

My suggestion is that we move the `_call` examples into `__init__`. This should reduce some code overhead (since we dont need to init things twice) and also make finding this information much easier.

**Comment by kohr-h** [comment]
Totally agree.
