### ISSUE TITLE
Read the docs is dead

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#535]
It is down once again due to long computation times. This is becoming a hassle. We have a few options atm:

* Reduce duplication: We currently rebuild the doc even for inherited methods. Thus we build a total of 2072 methods while we only "need" to build 1024 of them. This could buy us "twice the time".
* Somehow move the doc building to the release script and build it ourselves.

At this point, I'm all for alternative 2. It would also allow us to use intersphinx and other things that read the docs currently lack.

**Comment by kohr-h** [comment]
> At this point, I'm all for alternative 2. It would also allow us to use intersphinx and other things that read the docs currently lack.

Question: How would that play together with the hosting at RTD? Is there an option to upload self-built docs?

**Comment by adler-j** [comment]
There is curretly an issue about that on their git repo, but last reply was 7 months ago and rather vague. Id say it would be dead. In gemeral their issue tracker is a mess.

I was looking at how numpy does it, bit it seems they have abandoned RTD as well.

If we could get RTD working it would be great, but atm I dont know how to fix this long term.
