### ISSUE TITLE
edge_order should not be a separate argument to finite_diff

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#538]
It makes no sense to have a specified edge order AND a padding mode. The edge order is (i.m.o) simply a special case of `pad_mode` and should be baked into that parameter.

While at it, we could perhaps expose this in the cases of `Gradient` etc where this parameter is currently not exposed.

**Comment by kohr-h** [comment]
Agree. I guess this does the same as `'order0'` and `'order1'` in the `ResizingOperator`, so it should be easy to stay consistent.

**Comment by adler-j** [comment]
I already fixed so `WaveletTransform` follows the "order1", "order2" style, so grad would be the logical next step.
