### ISSUE TITLE
Branch cleanup

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#542]
We need to prune the number of branches badly. We currently have the following branches, of which I'll mark the ones I think we should close.

 - [x] autoapi
 - [ ] geometry_getitem
 - [ ] gh-pages
 - [x] issue-128__performance_tests
 - [ ] issue-209__convolution
 - [x] issue-220__split_bregman
 - [x] issue-228__rtk
 - [ ] issue-246__functional
 - [x] issue-271__bad_error_add
 - [ ] issue-274__biorthogonal_wavelets
 - [x] issue-305__gradient
 - [ ] issue-312__tutorial
 - [ ] issue-314__fractional_ft
 - [ ] issue-322__weight_pspace_ops
 - [x] issue-325__oputil
 - [ ] issue-342__tensor
 - [x] issue-363__anaconda
 - [x] issue-379__diagonal_precon
 - [x] issue-379__diagonal_precon_cherrypick
 - [ ] issue-387__spect
 - [ ] issue-392__pet
 - [ ] issue-400__improve_PyWavelet_integration
 - [ ] issue-417__shearlet
 - [ ] issue-418__mayo
 - [x] issue-442__nonlinear_cp
 - [ ] issue-451__optimal_mass_transport
 - [ ] issue-452__begin_end
 - [x] issue-455__float64_astra
 - [ ] issue-456__geometry_sum
 - [ ] issue-464__deformation_operators
 - [ ] issue-473__remove_Interval
 - [ ] issue-474__broadcast_pspace_arithmetic
 - [ ] issue-496__mlem_solver
 - [ ] issue-501__python23_examples
 - [ ] issue-515__pytest_30
 - [ ] issue-59__coerce
 - [x] issue-pybind11
 - [ ] master
 - [x] pdhg_method
 - [x] phase_contrast
 - [x] phase_contrast_rebase
 - [x] plugintest
 - [x] preconditioned_tomography_example
 - [x] revert-380-issue-379__diagonal_precon
 - [ ] steplen_test
 - [ ] subspaces
 - [ ] travis_deploy_test
 - [x] variable_lp
 - [x] wavelet_test
 - [ ] writing_operator_example

In addition to this, I feel that we may have gotten to the point where we should stop having "private" branches on the official repo, and instead use the full git workflow (actually fork the repo). The "issue-XXX" branches are somewhat more official and can stay for a while i guess.

**Comment by kohr-h** [comment]
I checked a few more, some are already removed at the time of writing.

**Comment by adler-j** [comment]
Closed the ones discussed here, we now "only" have 10 branches that are not in the pull request chain, so I guess that's ok for now.
