### ISSUE TITLE
Proposal label is somewhat useless

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#55]
Somehow 98 % of our issues end up having the `proposal` label. Slightly pointless. My suggestion is that we follow the commit message label distinction made in NumPy. I'll post it here so we don't have to follow a link:

```
API: an (incompatible) API change
BLD: change related to building numpy
BUG: bug fix
DEP: deprecate something, or remove a deprecated object
DEV: development tool or utility
DOC: documentation
ENH: enhancement
MAINT: maintenance commit (refactoring, typos, etc.)
REV: revert an earlier commit
STY: style fix (whitespace, PEP8)
TST: addition or modification of tests
REL: related to releasing numpy
```

Out of these, I'd say we take

- `api change`
- `bug` (already there)
- `deprecation`
- `documentation`
- `maintenance`
- `style`
- `testing`
- `release` 
- instead of enhancement, `new feature` or `feature request`, (more specific)

And I would also vote for labels for different parts of the library,

- `core`
- `solvers`
- `trafos`
- `cuda`
- ...

I'll label this as a proposal despite the irony.

**Comment by adler-j** [comment]
Sounds like a good idea. Basically there are (imo) three "orthogonal" cathegories

##### Location in code

- `core`
- `solvers`
- `trafos`
- `cuda`
- ...

##### Reason/Problem type

- `bug` (already there)
- `failing test`
- `documentation`
- `style`
- `Continuous Integration`
- `Help needed`
- `Missing feature`

##### Action/Solution

- `new feature` or `feature request`, New stuff
- `maintainance`, Modify current
- `deprecation`, Remove

The risk here is that we create to many and people wont take the time to pick one. I think we should try to be specific "enough", at some point we have to ask ourself. Does the distinction of these two (say `new feature` vs `feature request`) actually change something in how we'd handle it?

**Comment by kohr-h** [comment]
Sure, if we have `missing feature` we don't need `new feature` or `feature request`. I'd argue that we should only have two categories, namely "where" and "what", and combine labels to be more precise. For example, `failing test` could be combined by `testing` and `bug`, whereas just `testing` and `needs improvement` could be an issue about test coverage.

So apart from that example and the `new feature` and `feature request`, we can use those you wrote. I'll make a quick adaption.

**Comment by adler-j** [comment]
My idea with `missing feature` vs `new feature` is that `missing feature` (possibly under another name) is for users who try to do something and it doesnt work (like a bug report). New feature is with an actual proposal on how to solve it and discussion on that.

**Comment by kohr-h** [comment]
Hm okay, makes sense.

**Comment by kohr-h** [comment]
This is done.

**Comment by kohr-h** [comment]
Closing this.
