### ISSUE TITLE
See Also vs See also

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#550]
We have 63 occurances of "See Also" and 65 of "See also" in the doc. Which one do we go for?

**Comment by kohr-h** [comment]
I find the capitalized "Also" unnatural, would go for "also".

**Comment by adler-j** [comment]
I simply went for capitalized since numpydoc uses it, I guess we can go for "also" however since it seems to build just fine.

**Comment by kohr-h** [comment]
In that case, there is a certain (albeit small) risk that Sphinx decides to become case-sensitive in its directives. Currently `operator` and `Operator` are considered identical, which causes us problems. In the same way, `See also`, `See Also`, `see also` and `see Also` should all be indistinguishable, but if `numpydoc` defines the header as `See Also`, we should probably go for that.

**Comment by adler-j** [comment]
Fixed on master.
