### ISSUE TITLE
Rename example_element to random_element

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#557]
The name `example` suggests that the element is somehow reasonable. Changing it to `random_element` gives the impression that it is actually noise.

**Comment by kohr-h** [comment]
Now that you write "noise", what about `noise_element`? "random" could mean randomly selected from a collection of "reasonable" elements.

**Comment by adler-j** [comment]
Well f it, why not simply call `odl.phantom.white_noise` and be done with it?

**Comment by kohr-h** [comment]
Yeah, screw this m****er!

**Comment by adler-j** [comment]
Put some more thought into it and it seems like this is used with some other methods so removing it would be complicated. I'll probably end up doing the `noise_element` rename.
