### ISSUE TITLE
Crash in cuda ntuples

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#56]
Example

```python
>>> import odl
>>> R10 = odl.CudaRn(10, dtype='float64')
>>> x = R10.one()
>>> print(repr(x))
Traceback (most recent call last):

  File "<ipython-input-22-2adecf379609>", line 6, in <module>
    print(repr(x))

  File "/home/jonasadler/Programming/ODL/odl/space/base_ntuples.py", line 318, in __repr__
    array1d_repr(self))

  File "/home/jonasadler/Programming/ODL/odl/space/cu_ntuples.py", line 787, in __repr__
    weight=weight)

KeyError: 'dtype'
```

Edit: clarified code

**Comment by kohr-h** [comment]
I had a similar problem once where the error was produced **by `repr` in an error message** due to the fact that a property could not be evaluated. Not sure if that's the problem here. In some way there is no `dtype` attribute available.

**Comment by adler-j** [comment]
It is a problem in `__repr__` since i get the error there.

**Comment by adler-j** [comment]
This seems to be solved now, closing.

**Comment by kohr-h** [comment]
Just one quick comment on this, no matter where the exact error was, but it fits anyway: 

We should consider **not** to rely on properties and attributes of the **finalized** object in its `__init__()` method. The problem I mentioned above was in the `DiscreteLp` which had no `dspace` when an exponent check was made in its `__init__()` method, even though the `super()` call had set its `_dspace` attribute and the `dspace` property must have been there. I don't remember what exactly fixed it, but when we hit such a mysterious problem again, it could be an idea to try using only the `_attr` ones in `__init__()` and see if that fixes the problem.
