### ISSUE TITLE
Migrate solvers to use functionals?

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#569]
In the same spirit as #566: Solvers should probably allow one or several functionals to be passed instead of passing proximals, gradients or similar directly. We need to assess the feasibility of the approach for the individual methods, but if possible, I think an additional optional argument to provide full-fledged functionals would be the way to go.

**Comment by adler-j** [comment]
The hard part here is how to handle the two ways of calling the solvers. 

* One option is to simply force users to create a functional (even if it is a empty shell) and only accept functionals as arguments. We do get into issues with forcing users to create whole towers of them for some common cases however, e.g. `fun.convex_conjugate.proximal`.
* Another option is to close this issue and leave it as is.
* A third option is to allow users a choice, i.e. allowing them to provide the parameter in two ways. For example:
    * Allowing both in the same argument:
    ```
    f_cconj_prox : `Functional` or `callable`
        Functional with convex conjugate with proximal or proximal of convex conjugate of ``f``
    ```
    The problem here is obviously to handle determining which one is which.
    * Another option is to create two parameters and let users choose. Since they are supposed to be exclusive we need to make them both keyword arguments.
    ```
    f : `Functional` or `callable`
        Functional with convex conjugate. Mutually exclusive with ``f_cconj_prox``.
    f_cconj_prox : `Functional` or `callable`
        Proximal of convex conjugate of ``f``. Mutually exclusive with ``f``.
    ```

**Comment by kohr-h** [comment]
> One option is to simply force users to create a functional (even if it is a empty shell) and only accept functionals as arguments. We do get into issues with forcing users to create whole towers of them for some common cases however, e.g. fun.convex_conjugate.proximal.

That's not an option for me, frankly. It puts unnecessary load on users with no substantial gain.



> Another option is to close this issue and leave it as is.

Surely a viable option.



> Allowing both in the same argument:

That becomes hard when you have lists of functionals / proximals and need to determine which is which.



> Another option is to create two parameters and let users choose. Since they are supposed to be exclusive we need to make them both keyword arguments.

That was the option I had in mind. It still requires some handling of different cases and error raising, but is the easiest way to distinguish between the different call patterns.

**Comment by adler-j** [comment]
Full implementation of this depends at least partially on #564. Does anyone want to look at that? Specifically we need to figure out how to handle the L1 norm case, others can wait.

**Comment by aringh** [comment]
I didn't think of that this one and #564 might be interlinked... I can have a look at it but will probably need help. Also: I won't be able to focus on it properly until mid-next week.

**Comment by adler-j** [comment]
It's all a design issue there, implementation should be trivial. I could probably help if you want someone to discuss with.
