### ISSUE TITLE
Callback for primal-dual gap and others

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#571]
Besides printing information on the primal iterates, which is what most current `Callback<xyz>` classes do, one often wants to observe the primal-dual gap during the iteration of a method operating in both primal and dual variables. Similarly, other information (norm etc.) about the dual variable would be valuable during iteration, too. With the current design, this is not possible.

What is missing is a way to distinguish callbacks that act only on the primal variable (usable in primal-only or dual-only methods) from ones that act on both of them.

Once that is settled, it would be rather simple to implement the primal-dual gap callback by initializing it with a `Functional` (and its convex conjugate if not present in the class), and call it in an iterative method on `(primal, dual)`.

**Comment by adler-j** [comment]
This depends strongly on how we decide to handle #569

**Comment by adler-j** [comment]
Proposed way of handling this:

Add `**kwargs` to all callbacks where the solvers can feed in anything they want. Make the solvers return things in a ordered manner here, with standardized names like `dual_iterate`. Then we can add a callback that prints the primal dual gap.

**Comment by kohr-h** [comment]
Sounds reasonable. The subsequent question is how the callback is getting the functional(s) to evaluate. I'd probably go for a callback that takes either a functional `func` as input and then calls it on the primal iterate and `func.convex_conj` on the dual iterate, and then prints both results, or their difference. Or it takes both `func` and `func_convex_conj` as arguments (could be callables then) and does the same thing. One could also easily generalize this idea and accept two arbitrary callables for the primal and the dual, respectively, along with a callable doing something with the results. Somewhat an extension of the existing `CallbackApply`.

**Comment by MatthiasJE** [comment]
The solution with `dual_iterate` sounds good to me. This is not implemented or finally agreed yet, isn't it?

**Comment by MatthiasJE** [comment]
On the other hand, one could define primal-dual algorithms as working on a product space which combines primal and dual iterates. This may better reflect the nature of these algorithms.

**Comment by kohr-h** [comment]
> On the other hand, one could define primal-dual algorithms as working on a product space which combines primal and dual iterates. This may better reflect the nature of these algorithms.

That's a good point. From the API, though, I don't think it makes much sense to completely rewrite the methods for product spaces. We need to specify the problem in split form in any case (I think).
What I can imagine is that instead of only the primal variable `x`, you could pass in a product space element containing both primal and dual (or more if there are more variables), and then the callbacks could be implemented in a quite simple manner.

**Comment by mehrhardt** [comment]
Either way, it would be good to make a decision so that we can start implementing these.

**Comment by kohr-h** [comment]
Ping @adler-j opinion?

**Comment by adler-j** [comment]
In my opinion we should gof or the `dual_iterate` style since it is the easiest to follow. With that said we need to somehow handle callbacks that want to ignore it in a graceful manner, e.g. we should not need to rewrite all callbacks to support this. I'm not quite sure how to do this nicely.

**Comment by kohr-h** [comment]
Are we talking about the same thing? Just to make sure: my idea above was to change the *solvers* to take in a product space element containing all variables that take part in the iteration. No change to the callbacks required, they just get different inputs compared to before. The examples would need adaption in that case.
If we want something that shows only the primal iterate, it should look at `x[0]`, and the primal-dual gap could be computed with `x[0]` and `x[1]` (usually).

It's not clear to me why we treat the primal specially in the sense that we pass it in for mutation, but allocate the dual on the fly.

(I know we have been laboring with the solvers API quite a bit, but let's not take that as a reason to rule out changes now - we're still before 1.0.)

**Comment by adler-j** [comment]
I am personally rather strongly against modifying the solvers to take product-spaces as input. In a sense this would change them from solving minimization problems to solving sadle point problems, which while more general is also much more complex to understand for most users.

So, with that in mind I'd recommend changing the callbacks. Doing so would also be "scalable" in that we could start feeding more information to the callbacks later on, e.g. step-lengths etc.

**Comment by mehrhardt** [comment]
I think the option @kohr-h was proposing was not to change the solver but only how we call the callbacks, i.e. `callback([x, y])`. To me, I don't think it is too much to ask that the users understand that there is a dual variable y when calling PDHG even if they don't understand what it means.

**Comment by adler-j** [comment]
Well, I guess that is a better option, but it would still break a large number of solvers, not to mention adding an arbitrary distinction in how callbacks are written for primal-dual and "regular" optimization algorithms.

Can we spend at least some thought on if it is possible to do something like this:

```python
def simple_callback(x):
    print(x)

def super_advanced_callback(x, dual_iterate=None):
    print(x)
    print(dual_iterate)

def my_optimization_algorithm(..., callback):
    ...
    callback(primal_iterate, dual_iterate=dual_iterate)  
    # ^ works for both simple and advanced callbacks
```

one option would be to add a `call_callback` function that does this somewhat intelligently, e.g. only calls with `dual_iterate` if it is a valid argument. The syntax would be somewhat like

```python
call_callback(callback, x, dual_iterate=dual_iterate)
```

how do you feel about such an approach?

**Comment by mehrhardt** [comment]
To me either options `callback([x, y])` or `callback(x, dual_iterate=y)` is fine but I would not like to make it much more complicated than that. I guess the two of you @kohr-h , @adler-j should battle this out but I would very much appreciate if the fight is quick :).

**Comment by mehrhardt** [comment]
Any news on this front? By now I am actually in favour of @adler-j 's `callback(x, dual_iterate=y)` and even more so for a quick solution.

Related to this, I had the issue that I needed a callback that accepts the projected iterate "Ax" to not compute this again. If we have `**kwargs` everywhere, then I can just write `callback(x, projected=Ax)` or so and everything falls into place.

**Comment by adler-j** [comment]
No news so far, but I'll see what can be done. Should be a decent "project" so to say.

**Comment by adler-j** [comment]
I've made a small example of this, if we could have a look at it and see if it's fine I can get it done tomorrow or so.

**Comment by kohr-h** [comment]
> Any news on this front? By now I am actually in favour of @adler-j 's callback(x, dual_iterate=y) and even more so for a quick solution.

Quick solution it is, so I agree for now.



> Related to this, I had the issue that I needed a callback that accepts the projected iterate "Ax" to not compute this again. If we have **kwargs everywhere, then I can just write callback(x, projected=Ax) or so and everything falls into place.

Well, here we go. To me this shows that the chosen approach lacks extensibility, other than adding more and more stuff to the signature. Not that the use case is invalid (I do see the point), but in the long run we clearly need a better approach.

**Comment by mehrhardt** [comment]
Just to link these: @adler-j's small example is #1240.

**Comment by adler-j** [comment]
I guess #1400 takes this, so we can close?

**Comment by kohr-h** [comment]
Agreed, that one will get rid of the issue without requiring hacks.
