### ISSUE TITLE
Update name of `proximal_zero`

### ISSUE THREAD

**Issue by aringh** [odlgroup/odl#572]
This is the proximal operator, not only for the zero functional but for any constant functional. Thus the name should be updated: `proximal_const_func`? Other suggestions?

(The issue was discovered in the functional branch #246 #498, but in order to not have that one grow to large I create a new issue and will fix it when the other one is merged).

**Comment by adler-j** [comment]
`proximal_const_func` is fine by me. These wont be used as agressively once we have the functionals in anyway.

**Comment by aringh** [comment]
Closed via #582
