### ISSUE TITLE
Naming convention for convex conjugate functional

### ISSUE THREAD

**Issue by aringh** [odlgroup/odl#575]
Currently in odl, convex conjugate is abbreviated `cconj` in most places. In the functional branch #246 #498 we are using `convex_conj` to denote the convex conjugate of a functional. If possible, the two should probably be harmonized.

Try to change `cconj` to `convex_conj`?

**Comment by adler-j** [comment]
Finally getting around to this, yes I agree we should rename `cconj` to `convex_conj`, it is more clear, and having long names on the proximals is not really a problem.

**Comment by adler-j** [comment]
Do we want to do something about this?

**Comment by kohr-h** [comment]
Yes, why not. There are [not so many places](https://github.com/odlgroup/odl/search?utf8=%E2%9C%93&q=cconj), and it just affects internal stuff, should be easy to change.
