### ISSUE TITLE
Readthedoc build failed: No module named 'scipy.special'

### ISSUE THREAD

**Issue by aringh** [odlgroup/odl#577]
If I knew how to fix it, I would just do it. Unfortunately I don't, and hence I post and issue. Here is the build log: http://readthedocs.org/projects/odl/builds/4408684/

**Comment by adler-j** [comment]
Two ways to solve this. 

* Either it needs to be added to the list of mock modules in the doc conf:
       https://github.com/odlgroup/odl/blob/38c4f90fbeafce850db3833a8209f9da90386c98/doc/source/conf.py#L50-L55

* Or you remove all `import scipy.special` calls and use `import scipy` and later do `scipy.special.???`. I would recommend this approach.

**Comment by aringh** [comment]
Closed via #579
