### ISSUE TITLE
Quotient and product of functionals

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#581]
It is (at least sometimes) of interest to speak of quotients of functionals, and I think we should have these in the system.

There are a to my knowledge two options on how to do this:

* Implement operators `__mul__`/`__div__`. I am personally against this since one would expect `/` to be the inverse of `*`, but `*` means composition and letting `functional * functional` mean multiplication while `functional * operator` means composition is doomed to be problematic.

* Add free operators. We already have `OperatorPointwiseProduct`, so this would be a natural start and easy to extend.

**Comment by aringh** [comment]
I agree. Things like `FunctionalPointwiseProduct` and `FunctionalPointwiseQuotient` seems like a good way to go about it.

**Comment by adler-j** [comment]
I'll get this done as practice with the functionals.
