### ISSUE TITLE
Ugly commit history due to RTD bogus docs

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#595]
Commits b4f25c324e719738993dad571ca6012bb7e245a0 and e1cddca3344b2dcaf5c106be2380b7f170f6e9e3 changed all of the docs, causing rebases that go past this point to be very ugly. I say we rebase master to get rid of this from the commit history.

**Comment by kohr-h** [comment]
I don't quite see why this is a problem. The commits are in very close succession, so they shouldn't mess up any rebase. IMO, don't do this unless there is a messed-up example, we've got worse things in the commit history.

**Comment by adler-j** [comment]
Rebases walk through commit by commit, so at least I had to skip these commits when rebasing #587 just a few minutes ago.

**Comment by adler-j** [comment]
Also, they mess up git blame of the whole docs since what you will find is this and not the latest actual change.

**Comment by kohr-h** [comment]
> Rebases walk through commit by commit, so at least I had to skip these commits when rebasing #587 just a few minutes ago.

I still don't see why there is a problem during rebase. The two commits in question don't effectively change the code, so subsequent commits changing the docs (the commits on the branch are subsequent during rebase by definition) won't conflict with them unless they did before.

So I just tested rebasing ~5 different branches on master, some of which made modifications to the docs. No problem. On the other hand, I took a branch that was rebased on master, created a new branch where the commits in question were removed and tried to rebase the other branch on this on. That would basically be the flow for all branches after removing the two commits. And here, things blow up in your face directly, you need to remove files manually and then add again to resolve the conflicts - that's just a pain. This would, of course, only apply to branches that have been rebased on master after the merge, but we have at least 4 or so.



> Also, they mess up git blame of the whole docs since what you will find is this and not the latest actual change.

That's a valid point, but you can always start the search from a different point on, e.g.
```
git blame e1cddca3~2 doc/source/index.rst
```
starts backwards two before the last "bogus" commit, showing proper history before that point. There's certainly also an option to exclude a commit range from the blame.

**Comment by adler-j** [comment]
> This would, of course, only apply to branches that have been rebased on master after the merge, but we have at least 4 or so.

I'm totally fine with waiting with rebasing this away until those are solved, but I still think it has to be done. Needing to remember this hash every time you want to do a blame, and that [github's built in blame](https://github.com/odlgroup/odl/blame/master/doc/source/guide/faq.rst) gives nonsense is simply not acceptable.

The commit history should be a history of how ODL has changed over time, not a history of how we needed to hack external services.

**Comment by kohr-h** [comment]
Well then, so be it. We just need to make sure that people don't rebase on master in the meanwhile or provide help when things screw up.

**Comment by adler-j** [comment]
I propose that we do this now after #121 is in and we ship 0.5, do we agree?

**Comment by kohr-h** [comment]
Yes, I'll do it right away!

**Comment by kohr-h** [comment]
Done. Everything messed up :-)

**Comment by adler-j** [comment]
It is indeed messed up :D I'll write a short guide on how to fix branches after this (hint for next time: we should have done this rebase directly after we did the bogus commit):

```
git checkout master
git pull
git checkout MY_BRANCH
git rebase master -i
# Uncheck the two commits, bogus commit and revert bogus commit
# Solve any issues you may have (should not be many)
git push --force
```

leaving this for later if someone else has an issue with it.
