### ISSUE TITLE
Release 0.5

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#596]
We've had quite an extensive number of added stuff since 0.4, most notably `Functional`, along with some rather deep API changes. We should make a new release, also because it's not possible to build and test `odlcuda` conda packages since the build is tested with the newest `odl` conda package, which currently has the old API.

Missing PRs to add to release notes (check if added or not needed):
- [x] #497 
- [x] #521 
- [x] #523 
- [x] #528 
- [x] #534 
- [x] #536 
- [x] #540 
- [x] #549 
- [x] #555 
- [x] #559 
- [x] #560 
- [x] #579 
- [x] #580 
- [x] #587 
- [x] #591 
- [x] #594 
- [x] #602 
- [x] #604 
- [x] #608 
- [x] #615 
- [x] #624 
- [x] #630 
- [x] #638 

Edit: TODO list added

**Comment by aringh** [comment]
I will add release notes for #561 and #572 as you asked for, but not tonight ;)

**Comment by adler-j** [comment]
I propose that we wait until #587 is settled since it is a large API change that heavily depends on the functionals. Other than that I agree.

**Comment by aringh** [comment]
I have added notes for #561 and #572/#582 :)

**Comment by adler-j** [comment]
Since #569 is now in, we should start preparing for this. What needs to be done? I know at least I have missed release notes for some of my late pulls, and we also need to write some overall notes.

**Comment by kohr-h** [comment]
I'm compiling the missing PR mentions. We should also get the "rebase master" thing done before releasing.

**Comment by adler-j** [comment]
We should also have #515 done before this since we do some test cleanups

**Comment by adler-j** [comment]
Made a pull request where we can fix the doc, see #654.

**Comment by adler-j** [comment]
I say we try to go ahead with this asap since we probably want a "stable"-y release next week.

**Comment by adler-j** [comment]
This is done
