### ISSUE TITLE
Implement smoothed L1 style "norms"

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#597]
We should add the option of smoothing L1 norms so that they can be used with smooth solvers.
### Smoothed L1

The most simple way, which i say we go for, is to add a parameter `smoothing` to `L1Norm` so users can call it as such

```
>>> space = rn(2)
>>> l1 = L1Norm(space, smoothing=0.01)
>>> l1([1, 2]) == (sqrt(1**2 + 0.01**2) + sqrt(2**2 + 0.01**2))
```

Precisely, with smoothness `eps`

```
smoothed L1 = sum_i sqrt(eps^2 + x_i^2)
```

This has the nice property of having a easy to compute gradient `L1Norm(space, smoothing).gradient(p) == p / np.sqrt(p**2 + smoothing**2)`
### Huber

[Huber regularization](https://en.wikipedia.org/wiki/Huber_loss) is similar, but instead of a smooth transition it agrees almost exactly (down to a offset) with the l1 norm in case `x > smoothing` for some (small) scale `smoothing`, and agrees exactly with the l2 norm for `x < smoothing`

Precisely, with smoothness `eps`

```
Huber L1 = sum_i { x_i^2 / (2 eps)   if  |x_i| \leq eps
                   |x_i| - eps / 2   else

```
### The design question

To me, there are a few options in how to implement this
- Create separate classes for the above cases
- Let the above cases all be options to `L1Norm`
- Create a new `HuberFunctional` class, but let the smoothed case be an option to `L1Norm`
### Notes
- @ozanoktem has expressed interest in this so I'll assign to him.
- Along with implementing this we could use an example of using this with a smooth solver to solve TV regularized problems.

**Comment by aringh** [comment]
Working on other things, I needed a Huber norm. So I made a crude implementation of the Huber norm (it only has call and gradient and does NOT work for all kind of linear spaces) and then I cherry-picket that commit and put it in another branch (called issue-597__smooth_l1_and_huber). If @ozanoktem is still interested in implementing this, he could start from there :)

**Comment by adler-j** [comment]
Could you make a separate branch with only the huber norm @aringh?

**Comment by aringh** [comment]
I created a new branch (issue-597__huber_norm), cherry-picked the "huber-norm commit", pushed the branch, and removed the other branch. That was the easiest way I found :)

**Comment by kohr-h** [comment]
Well done :-)

**Comment by adler-j** [comment]
Pull request incomming?

**Comment by adler-j** [comment]
Bump, would be nice to get this into the pipeline

**Comment by aringh** [comment]
The Huber norm is in no way in a working condition (it will crash on a number of different things I think), and I won't have time to do it right now. I will have a look at it as soon as I have time. If @ozanoktem wants to do it, he is more than welcome ;-)

**Comment by adler-j** [comment]
@ozanoktem is indeed a great candidate for this, would be a nicely sized exercise.

**Comment by adler-j** [comment]
Reminder that this issue is still assigned to @ozanoktem :smile:

**Comment by kohr-h** [comment]
Close this, given that Huber norm and Moreau envelope are implemented?

**Comment by ozanoktem** [comment]
There are of course many ways to smooth L1-style norms, but agree with @kohr-h that we may close this since Huber norm and Moreau envelope are implemented.
