### ISSUE TITLE
broydens_first_method and broydens_second_method not working

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#599]
I'm currently porting these as part of #569, but I quickly found it was a long time since these were touched. Among other things, they lack any tests, and when I try running them in some basic tests I get failures all over the board.

When was the last time these were tested properly, if at all?

**Comment by aringh** [comment]
They were probably implemented slight less than a year ago. Unfortunately I think most of the history is gone, since it was first a separate package `odl-solvers` and later moved. They might never have been tested properly...

**Comment by adler-j** [comment]
Ok! Then I'll try to get them alive again. Do you have a good source on what they are supposed to do? For some reason I can make thm work with `|| . ||_2^2`, but when I give them ``|| grad f ||_2^2`` they both fail :/ BFGS seems to work without problems.
