### ISSUE TITLE
Create public documentation

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#6]
We need a public documentation page. This would include both the odl programming doc, but also issues  #2, #4, #5. First we need to decide on where to put this documentation, some options are

* Use [Read the docs](https://readthedocs.org/)
* Create a proper odl webpage
* Use [GitHub](http://daler.github.io/sphinxdoc-test/)

Since we have decided to use Sphinx for the documentation, all of these are ofc compatible, and we could for example use all of them. For maintainance, I propose that we try to keep this at a minimum, at least until we get stable releases.

**Comment by aringh** [comment]
I'm definitely not an expert in the area, but before starting to write documentation one might want to have a look at http://hplgit.github.io/doconce/doc/web/index.html To cite the home page "From DocOnce source you can generate LaTeX, Sphinx, HTML, IPython notebooks, Markdown, MediaWiki, and other formats."

**Comment by kohr-h** [comment]
Interesting! For our API doc, we have the Sphinx doc, but this seems to be suitable for more advanced usage with e.g. LaTeX. We should keep this in mind when we write something more similar to a user's guide (including math).

Regarding doc publication, I think ReadTheDocs is my favorite. GitHub supports it natively as a "service", so it should not be too hard to get it running. After all, it is their htmldoc style we already use :-)

**Comment by adler-j** [comment]
Added GitWash in commit ed175d1776af3f09fbb99b8394f09e25d5076100, looks quite good.
