### ISSUE TITLE
Add famous example functionals

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#600]
Several famous "test" functionals exist. [Wikipedia has a long list](https://en.wikipedia.org/wiki/Test_functions_for_optimization) and there is a good [literature study](https://arxiv.org/pdf/1308.4008.pdf).

Some that we should add to ODL, mostly for testing purposes, are:

* [Rosenbrock function](https://en.wikipedia.org/wiki/Rosenbrock_function)
* More?

**Comment by aringh** [comment]
We have a simple version of a 2d rosenbrock function [here.](https://github.com/odlgroup/odl/blob/7dad80ed4342346126b0df36f931556ada5596a0/test/solvers/vector/newton_test.py#L40)

**Comment by aringh** [comment]
@ozanoktem also sent me these suggestions a couple of months ago, but I never had time to really look into it:
 
- L1 test pack: https://www.tu-braunschweig.de/iaa/personal/lorenz/l1testpack
- SPEAR project: http://wwwopt.mathematik.tu-darmstadt.de/spear/
- Global Optimization Test Problems: http://www.mat.univie.ac.at/~neum/glopt/test.html
- Handbook of Test Problems in Local and Global Optimization: http://titan.princeton.edu/TestProblems/
- The book "A Collection of Test Problems for Constrained Global Optimization Algorithms” by Floudas C A and Pardalos P M, Springer, 1990.

**Comment by adler-j** [comment]
Closed this since rosenbrock is in, if we need more we should probably make an issue for each since it is a bit of work to add them.

**Comment by ozanoktem** [comment]
One may here also consider test suits developed specifically for sparse inverse problems. One such suit is [SPARCO](http://www.cs.ubc.ca/labs/scl/sparco/), another is [COPS](http://www.mcs.anl.gov/~more/cops/).
