### ISSUE TITLE
Discretization of a functional fails

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#603]
Noticed when working on pull #602 and trying to discretize a functional, we get a weird error:

```
>>> r2 = odl.rn(2)
>>> l2norm = odl.solvers.L2Norm(r2)
>>> space = odl.uniform_discr([-1, -1], [3, 3], [5, 5])
>>> space.element(l2norm, vectorized=False)

  File "d:\programming\odl\odl\discr\lp_discr.py", line 317, in element
    inp_elem = self.uspace.element(inp, vectorized=vectorized)
  File "d:\programming\odl\odl\space\fspace.py", line 667, in element
    fcall = vectorize(otypes=[dtype])(fcall)
  File "d:\programming\odl\odl\util\vectorization.py", line 179, in __call__
    return self._wrapper(func, *self.wrapper_args, **self.wrapper_kwargs)
  File "d:\programming\odl\odl\util\vectorization.py", line 232, in _wrapper
    **vect_kwargs))
  File "D:\Anaconda\lib\functools.py", line 33, in update_wrapper
    setattr(wrapper, attr, getattr(wrapped, attr))
AttributeError: 'L2Norm' object has no attribute '__name__'
```

Wrapping it in a function gives another problem, seemingly unrelated, everything becomes NaN

```
>>> def f(x): l2norm(x)
>>> space.element(f, vectorized=False)
uniform_discr([-1.0, -1.0], [3.0, 3.0], [5, 5]).element([[nan, nan, nan, nan, nan],
 [nan, nan, nan, nan, nan],
 [nan, nan, nan, nan, nan],
 [nan, nan, nan, nan, nan],
 [nan, nan, nan, nan, nan]])
```

@kohr-h is kindoff in charge of the vectorization, so perhaps you know why this happens?

Edit: Change to use a more standard functional. Error stays.

Edit2: Second case lacks a return statement, my fault, but perhaps.we should throw here?

**Comment by kohr-h** [comment]
How does the first example even make sense? Anyway, just hack `self.__name__ = self.__class__.__name__` in `Operator.__init__`. That should do the deal.


> Edit2: Second case lacks a return statement, my fault, but perhaps.we should throw here?

Yeah, would make sense to raise an exception.

**Comment by kohr-h** [comment]
Saw you already fixed it. Why append `.__call__` to the name? I'd simply go with the class name.

**Comment by adler-j** [comment]
> Saw you already fixed it. Why append .__call__ to the name? I'd simply go with the class name.

To make it clear that you will not get a object back that acts as a class, for example it will lose its domain etc. it will basically be a wrapping of the `__call__` method.
