### ISSUE TITLE
Return codes for solvers

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#605]
We currently have a lot of cases where our solvers simply `return` with no further info. I say we should add some return code system so that users can refer in what sense it returned, such as
- maximum iterations reached
- gradient is zero
- etc

**Comment by kohr-h** [comment]
Good idea. If you mean integers or something like that with "code", I'm against such a low-level and C-style solution. One should be able to ask the returned object what exactly happens and get a nicely formatted string as result. Something like "stopped after 5 iterations: gradient magnitude 0.008 below chosen threshold 0.001".

**Comment by adler-j** [comment]
```
return OptimizerResult('Did not converge due to stupid data')
```

and

```
return OptimizerSuccess()
```

etc is what I had in mind.

**Comment by adler-j** [comment]
According to e.g. #1400, it seems this will not be implemented?

**Comment by kohr-h** [comment]
Yeah, I guess some high-level functionality is going to evolve around that new interface, so it might pop up again, but it doesn't seem necessary for the function interface.
