### ISSUE TITLE
Quadratic form functional

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#606]
It often occurs in applications that you want to solve problems of the form

```
min_x  x^T H x + ...
```

where `H` is some symmetric positive definite operator.

We should add this as a functional to ODL.

**Comment by aringh** [comment]
Sounds like a good idea. As a special case we could include affine functional.

**Comment by kohr-h** [comment]
To include both, I'd just use the term `QuadraticFunctional` - that would include terms up to second order, including constant.

**Comment by adler-j** [comment]
Technically we have affine already, but I'll go for holgers approach.
