### ISSUE TITLE
Disjoint sum of functionals

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#611]
The disjoint sum of two functionals `f(x)` and `g(y)` is given by `h(x, y) = f(x) + g(y)`. We already have the proximal of such a construction through `combine_proximals`, but we do not have the functional itself.

This is relevant for #569, since we require the disjoint sum of functionals in order to fully move `chambolle_pock_solver`.

It should be reasonably simple to get this in.

**Comment by kohr-h** [comment]
Agree, name propositions? `FunctionalSeparableSum`?

**Comment by adler-j** [comment]
I made a initial commit of this (needed it for #569), where I went for `SeparableSum`, I think adding `Functional` in front would probably be good.
