### ISSUE TITLE
Use AppVeyor for Windows testing?

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#618]
We had an old issue #29 regarding CI on Windows, which we closed. Perhaps we want to consider using [AppVeyor](https://github.com/integrations/appveyor) for this purpose. There's a good starting point for a  build recipe [here](https://github.com/conda-forge/staged-recipes/blob/master/appveyor.yml), with lots of stuff we don't need to care about. It seems to work rather similar to Travis.

**Comment by adler-j** [comment]
I vote no, since we really have no windows specific stuff in odl and if we did, it would be odlcuda which AppVeyor doesnt handle anyway.

**Comment by kohr-h** [comment]
Okay, if we don't need it we skip it.
