### ISSUE TITLE
Implement Fourier transform

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#62]
This is clearly a must-have. 

For a starters, I will implement a uniformly spaced version based on FFTW, using [pyfftw](https://pypi.python.org/pypi/pyFFTW). That wrapper seems to be well-written and support many features one expects from C FFTW. The only worry is that the package has not seen any updates for quite some time (last version from 2013-09-26).

After that, a non-uniform version would be nice. There is the [NFFT](https://www-user.tu-chemnitz.de/~potts/nfft/index.php) library I have experimented a bit with, and it has a [Python wrapper](https://pypi.python.org/pypi/pyNFFT), which is a plus. Also somewhat worrisome that the code hasn't been updated for a year (not even on GitHub), but better than nothing.

On the CUDA side, there must be an FFT CUDA library, CUFFTW I would spontaneously guess. I've also seen a CUDA implementation of NFFT, but that's old and didn't compile last time. For later.

**Comment by aringh** [comment]
The [NFFT on github](https://github.com/NFFT/nfft) seems to have been updated rather recently, and also at least a couple of times every year. You also seem to have [a python wrapper for it](https://github.com/ghisvail/pyNFFT) with is maintained.

You also have [NUFFT](http://www.cims.nyu.edu/cmcl/nufft/nufft.html) (this seems to be the [github page](https://github.com/biotrump/nufft)). Also to this you seem to have some kind of [python wrapper](https://github.com/dfm/python-nufft), however I don't know how well maintained this is.

**Comment by kohr-h** [comment]
The first two are the same as I linked to, and in the python wrapper on GitHub you see that the last update was "a year ago". Thanks for posting the links to the other two. We can keep an eye on that, but to be honest I don't feel like writing a wrapper for Fortran code. Maybe generalizing their Python wrapper, which only supports 1D, would not be that hard, but then it must really be worth it. Would be nice to have some sort of speed and quality comparisons. There's also the Fessler code linked from the NUFFT homepage, plus potentially some more. To me the Chemnitz library NFFT seems to be best maintained.

**Comment by kohr-h** [comment]
Oh god, this has never been closed! BAM!
