### ISSUE TITLE
MatVecOperator only works for NumpyFn, why not FnBase?

### ISSUE THREAD

**Issue by aringh** [odlgroup/odl#635]
I'm trying to prototype some ideas in `odl`, and for a first coarse implementation I would like to have a linear operator defined by a matrix. I therefore turned to `MatVecOperator`. However, I am interested in working with discretized function spaces, but `MatVecOperator` only allows `NumpyFn`-like range and domain. Is there a reason to not allow and `FnBase`-like space?

**Comment by adler-j** [comment]
Only works because the data has to be a `NumpyFn`, we could technically let it work for any `FnBase` with the restriction that the optimizations only kick in for `NumpyFn`, I'd be fine with that.

**Comment by kohr-h** [comment]
Fine with me, too. While at it. I think we should rename the operator to `MatrixOperator` - the `MatVec` thing was BLAS inspired but isn't really relevant here.

**Comment by aringh** [comment]
If it is renamed and extended, should it be located in `odl/space/npy_ntuples.py` or moved to `odl/operator/default_ops.py` (or somewhere else)?

**Comment by adler-j** [comment]
yes it should be moved

**Comment by kohr-h** [comment]
> Edit: I'd probably move it to fn_base.py

`base_ntuples.py`

**Comment by aringh** [comment]
I looks like someone has done this, except the renaming :-) (and it has been moved to `npy_ntuples`). Close this?
