### ISSUE TITLE
Place for "advanced" operators

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#637]
We need a place for operators that make use of "advanced" features of ODL like deformations or Fourier transforms and thus don't naturally fit into any of the current sub-packages. We could make a new sub-package on the top level like `builtin_ops` and throw our stuff into modules there. It would even be a viable option to move all such operators that are spread out right now to this place.

**Comment by ozanoktem** [comment]
Perhaps we can introduce the notion of core operators. These are operators that should be supported on a broad basis. To exemplify what this would entail, assume we add functionality in ODL for more systematically handling boundary behavior (as discussed in issue #355), then the ambition would be that `core_ops` (core operators support this. Likewise, adding a new discretization scheme should ideally include adding support for it in the core operators. Examples of core operators are the inner product, norm, interpolation and sampling operators. The next level would be built in operators, like the Fourier transform, convolution, wavelet transforms and (perhaps) the ray transform. Finally we have the advanced operators mentioned by @kohr-h.

**Comment by adler-j** [comment]
MatrixOperator has now been moved, and we have had at least some success on this with the others (namely `tensor_ops`). Is there any other operator that still needs solving? Else we close.

**Comment by kohr-h** [comment]
Yes, I guess currently everything is fine, placement of new operators can be discussed individually.
