### ISSUE TITLE
Default documentation should be the latest release, not latest master

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#641]
The documentation is currently linked to the latest master version, not the latest version released. This causes some discrepancies in that users do `pip install odl` and then follow some instructions that may perhaps be refering to the latest (unreleased) version of ODL.

We should change the doc to refer to the latest release (currently 0.4) by default.

**Comment by kohr-h** [comment]
I'm not sure I agree here. If we fix the online doc to a certain version, we have no good way of fixing it when it's broken or wrong for a certain release. We would have the bad doc hanging around until the next release, or we would have to issue minor releases for each doc fix, which is also not great.

I like the current possibility to fix the documentation without having to make a new release. We should try to keep that possibility.

An alternative approach would be to write a note like "Deprecated in 0.5: ..." for things that change in the next release. On the downside, this can potentially be a bit of maintenance work.

I have written [a little script](https://github.com/odlgroup/odl/blob/issue-121__install_docs/doc/doctest_doc.py) that doctests all the `.rst` files in selected folders under `doc/source`. That can help a lot in keeping the examples there up to date.

**Comment by adler-j** [comment]
> I'm not sure I agree here. If we fix the online doc to a certain version, we have no good way of fixing it when it's broken or wrong for a certain release. We would have the bad doc hanging around until the next release, or we would have to issue minor releases for each doc fix, which is also not great.

> I like the current possibility to fix the documentation without having to make a new release. We should try to keep that possibility.

We could handle this by actually making two branches, release and development and having the doc point to the release branch, then we could make updates to the release branch if we find urgent bugs etc, but any breaking changes, new features etc go on the development branch and are shipped out in controlled versions. This is kinda what numpy does. Overall this may be too much work atm and we should probably wait with this until we are at non-beta releases.

> An alternative approach would be to write a note like "Deprecated in 0.5: ..." for things that change in the next release. On the downside, this can potentially be a bit of maintenance work.

Way to much maintenance to keep up with this imo.

> I have written a little script that doctests all the .rst files in selected folders under doc/source. That can help a lot in keeping the examples there up to date.

Great script, but it should be in the `odl/test` folder and have a proper `pytest --documentation` command.

**Comment by kohr-h** [comment]
> Great script, but it should be in the odl/test folder and have a proper pytest --documentation command.

I actually tried to convince `pytest` first to do the job, but there it didn't seem to want to bother with files other than `.py`. I tried adding to the `testpaths` config variable and hack the `python_files` option, but that didn't do the deal. Maybe you have an idea.

Or: do you mean adding a pytest command line option that invokes it? That would make sense.

**Comment by adler-j** [comment]
Closing this, we'll go by holgers suggestion and possibly open this in some far future (perhaps after 1.0)
