### ISSUE TITLE
Bug in test generation for product spaces

### ISSUE THREAD

**Issue by aringh** [odlgroup/odl#66]
I'll just make a short summary (@adler-j should know what I'm talking about since we found it when we worked together ;) ).

There seems to be a bug in the generation of test examples for product spaces, in the diagnostics. If one adds a return statement on [line 88](https://github.com/odlgroup/odl/blob/a606d9c987b80139ebe7965dda45ca3914f81ab3/odl/diagnostics/examples.py#L88), in order to not generate more tests than necessary, and then run the minimal working example
```
import odl

r3 = odl.Rn(3)
l2 = odl.uniform_discr(odl.FunctionSpace(odl.Interval(0, 1)), 10)
X = odl.ProductSpace(l2, r3)

for ex in odl.diagnostics.samples(X, X):
    print(ex)
```
it seems to generate a test for `zero times zero -> zero times one`, however it should generate a test for `zero times zero -> zero times zero`.

**Comment by adler-j** [comment]
Attempt at solution given in the commit, can you please try it on your problem and report back?

**Comment by aringh** [comment]
It works. With that I close this issue.
