### ISSUE TITLE
Improving the readme

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#666]
"now" that we have a very nice installation documentation, I suggest we simplify the README.

Removing the "Optional Dependencies" and "Compatibility" headings, moving perhaps the second one to the installation instructions. We could leave the "ODL is compatible to Python 2 and 3 through the future library. It is intended to work on all major platforms (GNU/Linux / Mac / Windows)." comment under installation, if we want.

Adding a "Code example" heading that does something truly amazing and mind blowing that shows the strength of ODL, input @ozanoktem, @aringh etc on this would be great.

Optionally, we could also want to remove the contributors list from the README and move it to a separate file, but I'd leave it for now.

**Comment by adler-j** [comment]
Some of this has been done, but we still need to discuss if we want a code example or not. If we don't thats totally fine and we cna close this.

**Comment by kohr-h** [comment]
If we can come up with a short but non-trivial example, that would be good. I can't think of anything mind-blowing from the top of my head. If there are no inputs in the near future I say we close this.

**Comment by kohr-h** [comment]
Seems no-one has a killer example for the README. Shall we close?

**Comment by adler-j** [comment]
I agree, perhaps it is hard to give one.
