### ISSUE TITLE
Remove RegularGrid

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#670]
We have a distinction `RegularGrid` vs `TensorGrid`, but no such distinction for `RectPartition`. I propose we scrap `RegularGrid` and rename `TensorGrid` to `RectGrid`. Any opinions?

**Comment by kohr-h** [comment]
This is related to the old issue/question #286, just in a broader sense. I would agree here and add a property like `uniform_axes` that returns the boolean sequence telling in which axes the grid is uniform. We just need to be careful with numerical errors that may ruin the property.

**Comment by kohr-h** [comment]
I'll get this done.
