### ISSUE TITLE
Some operators too picky about uniformity of domain discretization

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#671]
The fourier transform fails to work with tensor-domains even if the `axes` parameter is given and the domain is in fact a `RegularGrid` along the axes where the fourier transform is taken. This could likely be fixed if #670 is implemented.

**Comment by kohr-h** [comment]
Makes sense.

**Comment by adler-j** [comment]
This can now be fixed since #670 is closed.

**Comment by kohr-h** [comment]
Updated the title, `ResizingOperator` is also affected.
