### ISSUE TITLE
Conda TLDR fails (on windows)

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#674]
If i simply run the command as stated I get this following:

```
(odl51) E:\virtualenvs> conda create -c odlgroup -n odl-py35 python=3.5 odl odlcuda matplotlib pytest scikit-image spyder
Fetching package metadata ...........
Solving package specifications: .
PackageNotFoundError: Package not found: '' Packages/dependencies missing in current win-64 channels:
  - odl -> nomkl
  - odlcuda

Close matches found; did you mean one of these?

    nomkl: mkl

You can search for packages on anaconda.org with

    anaconda search -t conda odlcuda
```

I guess we need to state the channel somewhere? Also I'd probably remove odlcuda from that one.

**Comment by kohr-h** [comment]
Oh, so that means on Windows you *have to* use MKL. Interesting. That should be an OS-dependent dependency then.

**Comment by adler-j** [comment]
Additional error found when doing this during the presentation. Spyder does not properly use the conda env, so we need to tell the users to actually use the env interpreter.

**Comment by adler-j** [comment]
Isn't this fixed now?

**Comment by kohr-h** [comment]
Yes.
