### ISSUE TITLE
Indexing partitions by dimension

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#676]
Indexing of partitions is currently done on a cell basis, but is often of interest to do indexing by dimension, i.e. `partition.bydimension[0]` would be the sub-partition along dimension 0.

**Comment by kohr-h** [comment]
You can do that with lists: `partition[[0]]`.

**Comment by adler-j** [comment]
Wait what? How does that even work?

**Comment by kohr-h** [comment]
It's NumPy style indexing. Lists refer to axes, tuples to... something else.

**Comment by adler-j** [comment]
I feel like you are missunderstanding the question then, there is no numpy equivalent of what I want to do here. I'll give an example.

Suppose I have the partition

```
>>> p = odl.uniform_partition([0, 0], [1, 2], [3, 4])
```

The partition can be seen as the product of sub-partitions

```
>>> p1 = odl.uniform_partition(0, 1, 3)
>>> p2 = odl.uniform_partition(0, 2, 4)
>>> p_alt = p1.append(p2)
```

I want to extract these sub-partitions, i.e.

```
>>> p.bydimension[0] == p1
True
>>> p.bydimension[1] == p2
True
```

your syntax does not do this:

```
>>> p[[0]]
uniform_partition([0.0, 0.0], [0.33333333333333331, 2.0], [1, 4])
>>> p[[0]] == p1
False
```

In fact,

```
>>> p[[0]] == p[0]
True
>>> p[[1]] == p[1]
True
```

**Comment by kohr-h** [comment]
Right, I was too quick. Then we need an extra method.
The alternative is to not do the Numpy style indexing for single integers (or other "incomplete" slices) and let `p[0]` do what you want to do. But on the other hand, the list indexing thing could be very handy at some point.
