### ISSUE TITLE
Moving pytest.ini to odl folder caused bugs

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#679]
This move basically made the tests un-runable on my machine, any "usual" thing fails:

```
$pytest
$pytest odl
$python -c "import odl; odl.test()"
```

The only way to fix this for me is by moving the `pytest.ini` file back into the root folder and creating a `conftest.py` file that points to the pytest plugins:

``` python
# in conftest.py
pytest_plugins = "odl.util.pytest_plugins"
```

With this, all of the above works perfectly.

**Comment by adler-j** [comment]
Did some more work on this, the above does not solve the problem either, problems still linger. For example, the `collect_ignore` variable is not used. This should be fixed rather asap.

**Comment by adler-j** [comment]
Does it even work on linux?

**Comment by adler-j** [comment]
Only way I've found that actually work is moving conftest.py and pytest.ini back into the root

**Comment by kohr-h** [comment]
For me just copying pytest.ini back to the surface works, except for the collect_ignore thing. Need to investigate.

**Comment by kohr-h** [comment]
It seems like `collect_ignore` is not used properly, although defined in the plugin file. To me this is a pytest bug, but we can try working around it by putting a minimal `conftest.py` only containing `collect_ignore` at top level, together with a `pytest.ini`.
