### ISSUE TITLE
DART algorithm

### ISSUE THREAD

**Issue by aringh** [odlgroup/odl#681]
Implement the DART reconstruction, as given in [this article](http://ieeexplore.ieee.org/document/5738333/)

**Comment by aringh** [comment]
An open question is where to put a solver like this? In `solvers.iterative`? A `solvers.misc`? In the `tomo`-part?

**Comment by adler-j** [comment]
Not 100% sure we want it in ODL core, perhaps it should be in som ancillary library.

**Comment by adler-j** [comment]
So my suggestion:

Create a repo for this yourself and add it there. Can we agree on that @aringh? In that case we close this.

**Comment by aringh** [comment]
Done. Just forgot to close the issue :)

**Comment by adler-j** [comment]
Link to the repo in case anyone finds this issue?

**Comment by aringh** [comment]
It is put in a private repo for now.
