### ISSUE TITLE
Add nuclear norm

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#690]
The nuclear norm is a norm on spaces of the form 

```
ProductSpace(ProductSpace(space, n), m)
```

See article:

[Collaborative Total Variation: A General Framework for Vectorial TV Models](http://epubs.siam.org/doi/abs/10.1137/15M102873X?journalCode=sjisbi)

for more information.

**Comment by chongchenmath** [comment]
The nuclear norm is a norm of a matrix, which is the sum of singular values of the matrix. So here we need a matrix space.
