### ISSUE TITLE
Implement ADMM solver

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#695]
Even if we currently have a set of very competent solvers for convex optimization, the ADMM solvers is by many considered as an important reference. In addition to that, it is rather easy to implement, so we should add it to the library.

**Comment by ozanoktem** [comment]
A nice reference for ADMM is [Distributed Optimization and Statistical Learning via the Alternating Direction Method of Multipliers](http://www.nowpublishers.com/article/Details/MAL-016).

**Comment by kohr-h** [comment]
Closed by #1198
