### ISSUE TITLE
dot as alias for inner and/or call

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#7]
Just a thought, currently many numpy users do things like:

```python
a = x.dot(A.dot(x))
```

In odl this would be

```python
a = x.inner(A(x))
```

or using the `Vector.T` syntax

```python
a = x.T(A(x))
```

do we want to somehow support the `numpy` syntax? This could also allow `odl` to be used with duck-typing in cases where a code expects a numpy array.

**Comment by adler-j** [comment]
Do we want to do this?

**Comment by kohr-h** [comment]
Depends on how useful this can be and if the potential usefulness outweighs the slight confusion with complex inner product vs. dot product. But actually we already have gone a bit along that path with the `vector.T` syntax, so IMO we can actually do the analogous thing for operators.

Just for linear ones?

**Comment by adler-j** [comment]
I suggest we close this since, second thought, it would be "un-odlic". Ok?

**Comment by kohr-h** [comment]
Agree. If some beautiful day, somebody asks for this feature or why that doesn't work, we can rethink.
