### ISSUE TITLE
About the specific definition of Fourier transform

### ISSUE THREAD

**Issue by chongchenmath** [odlgroup/odl#705]
The convolution theorem states that
F{f * g} = k F{f} F{g}
where F{f} denotes the Fourier transform of f, and k is a constant that depends on the specific normalization of the Fourier transform. [https://en.wikipedia.org/wiki/Convolution](url)

Based on that the convolution of f and g is
f * g = F^{-1}{ k F{f} F{g} }.

Note that we need to consider what the constant k is.
 
So the specific definition of Fourier transform has impact on the result of convolution. Now I encounter this problem: for 2D problem, the k = 2 np.pi  in ODL. Right?

Question: What is the specific definition formula of Fourier transform in ODL?

**Comment by kohr-h** [comment]
https://odlgroup.github.io/odl/math/trafos/fourier_transform.html

**Comment by chongchenmath** [comment]
It seems that we has a scale factor for convolution in ODL. For 2D problem, the k = 2 np.pi.

**Comment by kohr-h** [comment]
Yes, it's `(2 * np.pi) ** (ndim / 2)`
