### ISSUE TITLE
Make LinearSpace.Vector a non-member

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#71]
I propse the simple change of:

```python
class SomeSpace(odl.LinearSpace):
    class Vector(odl.LinearSpace.Vector):
        pass
```

to

```python
class SomeSpace(odl.LinearSpace):
    @property
    def vector_type:
        return SomeSpaceVector

class SomeSpaceVector(odl.LinearSpaceVector):
    pass
```

The main reason is that sphinx and other tools really dont support nested classes, and with this approach each vector class gets a unique name. Any use of `SomeSpace.Vector` could still be replaced to `SomeSpace.vector_type`.

This also ties in nicely with issue #70.

**Comment by kohr-h** [comment]
This is good. Python internally handles nested classes anyway this way (sort of) without giving them proper names. With the suggested change, things become explicit. I like that.
