### ISSUE TITLE
collect_ignore is ignored

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#714]
Our collect ignore looks something like

```
dir/odl/odl/trafos/backends/pywt_backend.py
```

while the method `pytest_collect_ignore` is called with only the path:

```
dir/odl/odl/trafos/backends
```

We need to fix this.

**Comment by kohr-h** [comment]
Is this the conclusion from a failure or a guess? Note the definition of `pytest_collect_ignore`:
```python
def pytest_ignore_collect(path, config):
    return str(path) in collect_ignore
```
It returns everything that is in `collect_ignore`, which is full paths with file names, as you write above.

Further, I tested installing only PyFFTW but not PyWavelets in a fresh environment, and the PyFFTW doctests are run while the PyWavelets doctests are skipped, just as they should.

**Comment by adler-j** [comment]
I found it. It seems that `os.path.abspath` returns the path in non-capital letters, where the `path` argument can contain capital letters. Calling `os.path.normcase` on path before the `path in collect_ignore` solves it.

Seems it was windows specific.
