### ISSUE TITLE
About the uniform_partition

### ISSUE THREAD

**Issue by chongchenmath** [odlgroup/odl#715]
Give the number of directions
````num_angles = 6````

Create the uniformly distributed directions
````angle_partition = odl.uniform_partition(0, np.pi, num_angles)````
or
````angle_partition = odl.uniform_partition(0, np.pi, num_angles, nodes_on_bdry=[(True, False)])````
or
````angle_partition = odl.uniform_partition(0, np.pi, num_angles, nodes_on_bdry=[(False, True)])````
or
````angle_partition = odl.uniform_partition(0, np.pi, num_angles, nodes_on_bdry=[(True, True)])````

Create 2-D projection domain
````detector_partition = odl.uniform_partition(-24, 24, 182)````

Create 2-D parallel projection geometry
````geometry = odl.tomo.Parallel2dGeometry(angle_partition, detector_partition)````

(Stupid) questions:
1. How many angles we use in ``geometry``?
2. what are the angles we use in ``geometry``?
3. How to check the concrete angles in ODL we use in ``geometry``?

**Comment by kohr-h** [comment]
Hm, perhaps this property should be more accessible. To answer your questions:

1. 6
2. and 3. Check with `angle_partition.grid` or, to get the array of angles, `angle_partition.grid.coord_vectors`.

**Comment by adler-j** [comment]
To ellaborate:

1. `len(geometry.angles) == 6`
2. and 3. `geometry.angles`

**Comment by chongchenmath** [comment]
It is not so clear here what on earth the angles we use for the customized scanning geometry just from the ``angle_partition``.
