### ISSUE TITLE
ASTRA Grid checks with absolute tolerance bad for small scales

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#720]
As seen in #719, very small grid scales will have much less forgiving checks compared to checks on large-scale grids. We should use relative tolerance checks.

**Comment by adler-j** [comment]
Updated title to make it clear that we're talking about astra check.

**Comment by kohr-h** [comment]
I actually thought this was a more general problem, but with grids it's up to the user to set reasonable tolerances, so that should be fine.

**Comment by adler-j** [comment]
See #721
