### ISSUE TITLE
Scaling in ASTRA 3d geometries

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#724]
In recent changes in the ASTRA code, scalings in the 3d cases were changed. I suspect [this pull request](https://github.com/astra-toolbox/astra-toolbox/pull/41). We need to test this explicitly, but I guess the changes fix the scaling inconsistencies that were there before and that we [fix on our side](https://github.com/odlgroup/odl/blob/master/odl/tomo/backends/astra_cuda.py#L235-L262). As it seems, there is nothing to fix any more, and I see failures in tests with current ASTRA versions due to this.

So how are we going to fix this issue? We cannot check (yet) "astra version before this: fix scaling else: don't" because the fixed scaling code is on master and not in a released version. Also, master internally works with the same version number as the last release so we cannot use that either.

**Comment by adler-j** [comment]
Well, first question, which is becoming bad, is that astra really needs to solve [astra issue 68](https://github.com/astra-toolbox/astra-toolbox/issues/68). Without it, we cannot check what version of astra we're interfacing with and any fix to stuff like this would be moot. Perhaps you can talk to someone over there.

Other than that, we obviously can only support released versions of ASTRA, so they need to make a new release for us to start supporting it.

**Comment by ozanoktem** [comment]
I suggest we keep support for older versions of ASTRA by simply let a user refer to those using a  different back-end tag.

**Comment by adler-j** [comment]
> I suggest we keep support for older versions of ASTRA by simply let a user refer to those using a different back-end tag.

If at all possible we do not want code that only works with new/old ASTRA, I mean, which would we use in our examples? If we can handle this internally we really should, and it seems we can.

**Comment by kohr-h** [comment]
As I wrote over there, you can do the obvious
```python
>>> astra.astra.version(printToScreen=True)
1.7.1
```
but as I wrote, `master` has the same version as the latest release.

I think this is an issue for us, too. We should consider increasing the version number immediately after a releas on master. Best to something that evaluates higher than the release, but not as high as any next release.

**Comment by ozanoktem** [comment]
Examples can be migrated, if necessary, to the latest version of external software that we support. But if we took the pain and effort to support an older, perhaps widespread, version of ASTRA, why remove support for it? I suggest it is supported simply with a different back-end label.

**Comment by kohr-h** [comment]
> Examples can be migrated, if necessary, to the latest version of external software that we support.

There shouldn't be a need to migrate example code, that would really show that we did a bad job abstracting away that stuff.



> But if we took the pain and effort to support an older, perhaps widespread, version of ASTRA, why remove support for it? I suggest it is supported simply with a different back-end label.

Nobody wants to discontinue support for older ASTRA. The only thing that should be necessary **internally** is a check like
```python
if parse_version(astra.__version__) <= parse_version('1.7.1'):
    # Rescale
else:
    # Do nothing, issue was fixed upstream
```
The problem is that there is only `<= 1.7.1` at the moment, even in the code on master.

**Comment by adler-j** [comment]
> Examples can be migrated, if necessary, to the latest version of external software that we support. But if we took the pain and effort to support an older, perhaps widespread, version of ASTRA, why remove support for it? I suggest it is supported simply with a different back-end label.

This is simply a scaling issue, the solution is clearly to put a `if astra.__version__ < (something):` around the scaling part in ODL, there should be no need to introduce new labels.

>As I wrote over there, you can do the obvious
    ```
    >>> astra.astra.version(printToScreen=True)
    1.7.1
    ```
    but as I wrote, `master` has the same version as the latest release.

Again, we cannot support experimental code from other packages, we can only support actually released code, which would then have a release nr. The solution here is that ASTRA creates a release. If we start supporting experimental code we'll get into a really hard dependency situation in the long run.

> I think this is an issue for us, too. We should consider increasing the version number immediately after a releas on master. Best to something that evaluates higher than the release, but not as high as any next release.

Well `0.5.c3` or something like it works for that. [PEP440](https://www.python.org/dev/peps/pep-0440/) has some discussion on this and it seems something like that would be the preferred naming.

**Comment by adler-j** [comment]
> The problem is that there is only <= 1.7.1 at the moment, even in the code on master.

Agree, but the latest astra release, even minor, was a year ago. Perhaps we can get them to make a new one?

**Comment by kohr-h** [comment]
> Well 0.5.c3 or something like it works for that. PEP440 has some discussion on this and it seems something like that would be the preferred naming.

That's possible, or a `.dev` tag with the next likely version, currently `0.5.3.dev0`. For comparison we use established tools, in particular `parse_version` from `pkg_resources`:
```python
>>> parse_version('0.5.2.dev')
<Version('0.5.2.dev0')>
>>> parse_version('0.5.2.dev') >= parse_version('0.5.2')
False
>> parse_version('0.5.3.dev') > parse_version('0.5.2')
True
```
All tags like `a, b, c, dev` actually make the version *smaller* than the one without tag, so we need to be careful. We could also go with the next major version + tag, nothing keeps us from making intermediate minor releases. I mean `0.6.dev0` as the current master version.

**Comment by kohr-h** [comment]
> The problem is that there is only <= 1.7.1 at the moment, even in the code on master.
> 
> Agree, but the latest astra release, even minor, was a year ago. Perhaps we can get them to make a new one?

Actually, @wjp is redoing the Python packaging for ASTRA right now, I'm pretty sure this will lead to a new release^^

**Comment by ozanoktem** [comment]
>> The problem is that there is only <= 1.7.1 at the moment, even in the code on master.
>> 
>> Agree, but the latest astra release, even minor, was a year ago. Perhaps we can get them to make a new one?
>
> Actually, @wjp is redoing the Python packaging for ASTRA right now, I'm pretty sure this will lead to a new release^^

Does that also include the refactoring for providing pointers to the GPU memory in ASTRA?

**Comment by kohr-h** [comment]
> For comparison we use established tools, in particular parse_version from pkg_resources

See also [this page](https://setuptools.readthedocs.io/en/latest/pkg_resources.html#parsing-utilities).

**Comment by kohr-h** [comment]
> Does that also include the refactoring for providing pointers to the GPU memory in ASTRA?

Well... still work in progress, I guess.

**Comment by adler-j** [comment]
So this seems to be causing some rather nasty errors for our users and should get fixed asap.

**Comment by kohr-h** [comment]
It's going to be taken care of in ASTRA 1.8, scheduled "asap". Until then it's probably best to go back to the released 1.7.1 version.

**Comment by adler-j** [comment]
So @davlars, do you see this?

**Comment by adler-j** [comment]
Also can we have a branch in waiting for astra 1.8, so we can basically release when they do?

**Comment by kohr-h** [comment]
I have a working branch where I started testing, just pushed it (`issue-724...`).

**Comment by adler-j** [comment]
Great work!

**Comment by davlars** [comment]
I am getting the ray transform error (issue [#732](https://github.com/odlgroup/odl/issues/732)) even when working on astra 1.7.1. (I'm working from the `python_site_packages` branch). 

I'm a bit confused: is this the version where you're encountering errors as well? Meaning that we need to go back further in the astra releases to overcome this (until an astra 1.8-release)?

**Comment by kohr-h** [comment]
> (I'm working from the python_site_packages branch).

That was pointing to a commit later than the relevant changes that broke our tests. Try the version on the conda channel, or go back to the upstream repo, tag `v1.7.1` or so and build ASTRA based on that state. The `python_site_packages` branch is obsolete, you can reach the same effect by invoking `make python-root-install`, which I wasn't aware of at that time. 
That whole part will be redone and simplified in 1.8 by the way.
