### ISSUE TITLE
Migrate simple pytest fixtures to `simple_fixture`

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#725]
The [`simple_fixture`](https://github.com/odlgroup/odl/blob/master/odl/util/testutils.py#L238-L272) helper function should be used for all fixtures that don't do anything non-trivial.

**Comment by adler-j** [comment]
I did this in the proximal_operator_slow_tests, while doing other stuff and oh god yes it is so great. Basically cleans up like 50 unreadable lines per test.

**Comment by kohr-h** [comment]
Seems like my best contribution ever :-)

**Comment by adler-j** [comment]
I'll get this done

**Comment by adler-j** [comment]
Closed by #823
