### ISSUE TITLE
uncompr_bin_test fails on windows

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#726]
it seems the file opened by tempfile is not an actual file, to quote the doc:

> The returned object is a true file object on POSIX platforms. On other platforms, it is a file-like object whose file attribute is the underlying true file object. This file-like object can be used in a with statement, just like a normal file.

This causes the call `data.tofile(self.file)` to misfire badly, basically failing all the tests.

I'm quite sure this is a windows only situation, I'll look into it.

**Comment by kohr-h** [comment]
This is done.
