### ISSUE TITLE
MRC tests take too much time for basic test suite

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#727]
The tests currently take 1.98 seconds on my system, comparable to the `RayTransform` tests. A such peripheral feature shouldn't take about 10-20% of the total testing time. I suggest we reduce some numbers and possibly test with smaller fixtures. Another option is to extend it, but move it to largescale, or check if largescale is running and then run the larger tests.

**Comment by kohr-h** [comment]
What machine are you working on? For me all tests in `odl/tomo/data` run in 0.7 seconds.

**Comment by adler-j** [comment]
Relatively old, but still a decent stationary. How long does the full suite take on yours?

**Comment by kohr-h** [comment]
14.94 seconds, but with some of the ASTRA tests currently failing, so probably more around 13 or 14.

**Comment by kohr-h** [comment]
But the code is on and SSD, so data IO costs less.

**Comment by adler-j** [comment]
Still, this tests currently open like 300 files, I feel that is excessive for a basic test suite. We will very quickly get a test runtime creep if features like this are allowed to take several seconds. Before we know it we have like 4 file formats and some others and runtime of `pytest` is over a minute -> people run them less.

**Comment by kohr-h** [comment]
It's a lot, agreed. I don't know what takes most time there, opening and closing the files or the actual I/O. If the former is the bottleneck, one could try opening a temporary file globally and keep it open during this suite.

**Comment by adler-j** [comment]
MRC is now in contrib and this is hence solved.
