### ISSUE TITLE
Tensors with libgpuarray

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#731]
I started work on the integration of [libgpuarray]() as a GPU alternative for Numpy arrays as discussed a while ago. The code is in a [branch in my fork](https://github.com/kohr-h/odl/tree/gpuarray) to keep it out of the way here. I'm writing the code in-tree for convenience, but in the long run it's intended to use the entry point plugin mechanism as the current `odlcuda`.

Regarding design, I have a couple of questions that may be worth discussing, in part because I'm not really all that familiar with GPGPU concepts. I'll start making a list, but this is probably going to grow once I hit more issues.

### Multi-indexing
We have disabled multi-indexing for ODL vectors or space elements because we have data containers that don't support it (`odlcuda`). I guess we won't scrap that package until we have a full-fledged, well-tested and known-to-be-fast replacement, so the restriction stays. And it makes sense also in view of the otherwise huge extra burden on implementers of new spaces.

On the other hand, operations involving vector- or tensor-valued functions become all the more prevalent, so being able to perform operations on multi-indexing-capable data containers would make many use cases much simpler (for example the `NuclearNorm` operator, #691.

So the question here is: Does it make sense to allow multi-indexing, using e.g. a flag `multi_indexing` exported by the plugin that implements a space?

That may potentially lead to a significant amount of `if ... else ...` constructs. A more lightweight approach would be an `impl` flag to `as_writable_array` which is mostly used to have a multi-indexing capability.

### How to handle GPU contexts
This may be a silly question, but I'm not sure whether the context should be a property of the space. It seems to make sense to consider two spaces with vectors in different contexts to be different.

### "Nice" initialization
This depends a lot on the backend, of course, but right now users of `libgpuarray` still need to manually create a context and use it in vector initialization directly, or, alternatively, set it as default context. Since we don't know what will be available on a given machine, what would be a viable approach to have a "default environment"? I'm thinking mostly of (doc)tests. I'm currently thinking of defaulting to `pygpu.set_default_context(pygpu.init('opencl0:0'))` (would work even without GPU?).

### How to handle numerical methods that need migration
Of course, everything we have now will "just work" because of the `__array__` interface implemented by GPU arrays. But to get speed benefits in, e.g., solvers, functionals, operators etc. quite a bit of code needs to be changed, basically from Numpy functions to dedicated kernels where it makes sense regarding effort vs. gain.
What I think is nicely coming along in `libgpuarray` is the capability to define [elementwise](https://github.com/Theano/libgpuarray/blob/6e1e5c4a68ae5fd1655fd631d43f5832c1bd7f35/pygpu/_elemwise.pyx#L86) and [reduction](https://github.com/Theano/libgpuarray/blob/6e1e5c4a68ae5fd1655fd631d43f5832c1bd7f35/pygpu/reduction.py#L130) kernels (including map) on the fly in Python. That should make life substantially simpler. What I don't really know is how much there is to gain.

### Data pointers
I removed the capability of creating an element directly from a pointer, at least for now. It gave me consistent crashes, but that may have been my machine also, since I got the same crashes with any CUDA context after that :-). However, the [documentation](http://deeplearning.net/software/libgpuarray/pyapi.html#pygpu.gpuarray.from_gpudata) or the function needed for this array creation from pointer is marked "advanced" (nothing wrong with that) but also "may be deprecated later". I did once manage to create arrays that way, though.

Edit: add data pointers part

**Comment by kohr-h** [comment]
> The code is in a branch in my fork to keep it out of the way here.

Of course, if anybody (not looking at anyone specific) is interested in helping out I can move the development to this repo.

**Comment by adler-j** [comment]
Excellent initiative, short answers about what I think about the questions rased:

> Multi-indexing

This is a real problem, with the underlying problem of adding multi-indexing resulting in `FnBase` needing a rewrite since it currently assumes linear storage.

My suggestion, if we start adding this is to force all implementations of `FnBase` to "support" multi-indexing. This would need some rewriting of odlcuda, but I guess we can live with that given all the gains we can have

> How to handle GPU contexts

GPU context should be part of the space, I'm quite sure. Unless you have an "intelligent" space which can handle this additions smartly. I think CUDA supports stuff like this, i.e. that you dont need GPU -> CPU -> GPU data transfer. In that case, you may want to leave the option open, in which case data is stored on a specific GPU.

> "Nice" initialization

Yes we need a default. We may even want an option to select the default when installing the plugin, i.e. `pip install odllibgpuarray --use-cuda`

> How to handle numerical methods that need migration

Should be straightforward, from what I know about libgpuarray. We certainly want these on the GPU.

Regarding deeper functionality (like functionals etc) I feel that this will mostly need to wait for `__numpy_ufunc__` when this will come for free. If you have a specific case you need optimized, please add it.

For some things you may even want to implement optimized versions like `L2DistLibGPUARRAY` or whatever.

> Data pointers

Creating from data pointers is not critical, but accessing them for reading is.

**Comment by kohr-h** [comment]
> This is a real problem, with the underlying problem of adding multi-indexing resulting in FnBase needing a rewrite since it currently assumes linear storage.
> 
> My suggestion, if we start adding this is to force all implementations of FnBase to "support" multi-indexing. This would need some rewriting of odlcuda, but I guess we can live with that given all the gains we can have

Okay, fair enough. There is a [somewhat outdated branch](https://github.com/odlgroup/odl/tree/issue-342__tensor) which goes that way, but unfinished. So probably I'll port the changes from that branch to this working branch and implement the transition in one go.

> GPU context should be part of the space, I'm quite sure. Unless you have an "intelligent" space which can handle this additions smartly. I think CUDA supports stuff like this, i.e. that you dont need GPU -> CPU -> GPU data transfer. In that case, you may want to leave the option open, in which case data is stored on a specific GPU.

That's what I did so far. I'm tied to what libgpuarray supports, and so far there's no dynamic context switching available.

> Yes we need a default. We may even want an option to select the default when installing the plugin, i.e. pip install odllibgpuarray --use-cuda

Good suggestion, I'll look into ways of specifying this at install time.

> Should be straightforward, from what I know about libgpuarray. We certainly want these on the GPU.
> 
> Regarding deeper functionality (like functionals etc) I feel that this will mostly need to wait for __numpy_ufunc__ when this will come for free. If you have a specific case you need optimized, please add it.
> 
> For some things you may even want to implement optimized versions like L2DistLibGPUARRAY or whatever.

Yes, I figured that would be the least painful transition. Will `__numpy_ufunc__` ever come?



> Creating from data pointers is not critical, but accessing them for reading is.

Well output is trivial and still there, input is on the FIXME list.

**Comment by ozanoktem** [comment]
Hi, I don't want to make things complicated and I know this suggestion comes way late, but I wonder why we can't consider using an existing infrastructure for multi-dimensional fields, like [Theano](http://deeplearning.net/software/theano/index.html) or [TensorFlow](https://www.tensorflow.org)?

**Comment by adler-j** [comment]
Theano **is** basically a wrapper for libgpuarray, for our intents. Easier to go to the "root".

TensorFlow may be an option, but it seems you you'd get lots of unwanted extras just to access the container.

**Comment by kohr-h** [comment]
See [here](https://github.com/Theano/libgpuarray). `libgpuarray` is the next-generation backend for Theano data handling on the GPU. We can bet on strong incentives from the machine learning people to push this.

**Comment by adler-j** [comment]
A short comment here. It seems [pytorch](https://github.com/pytorch/pytorch) also aims to be a "numpy drop in", so that would certainly be an alternative backend as well.

**Comment by kohr-h** [comment]
Certainly, the more, the better. In some sense, when one is done, additional backends become much easier to integrate.

**Comment by kohr-h** [comment]
> A short comment here. It seems pytorch also aims to be a "numpy drop in", so that would certainly be an alternative backend as well.

Now more than ever since [the latest version](https://github.com/pytorch/pytorch/releases/tag/v0.2.0) adds support for Numpy broadcasting, among other niceties. Will definitely check it out.

**Comment by adler-j** [comment]
Yoshua Bengio just announced the "death" of Theano so to say:

https://groups.google.com/forum/#!topic/theano-users/7Poq8BZutbY

I guess we'll have to wait and see what this means for libgpuarray.

**Comment by kohr-h** [comment]
I read it this morning. Maybe they'll write something on GH.

**Comment by kohr-h** [comment]
Not gonna happen
