### ISSUE TITLE
Functionals for approximate data matching

### ISSUE THREAD

**Issue by aringh** [odlgroup/odl#737]
For exact data matching the convex conjugate of the Zero Functional is actually of interest (see issue #657). Normal ways of doing data matching is also expressions of the form
```
||Ax - b||_2^2 <= epsilon.
```
The convex conjugate of this functional, being defined as a infinity outside "the tolerance region" and zero inside, can be derived and also the proximal operator of this.

My suggestions is to implement this as a separate functional, since this opens up for using this kind of expressions in the Douglas-Rachford and primal-dual forward-backward solver.

**Comment by adler-j** [comment]
Example of how to do this via the convjex conjugate of l2 or using IndicatorLpUnitBall:

```python
import odl
import numpy as np

r2 = odl.rn(2)
A = odl.IdentityOperator(r2)
b = r2.one()

epsilon = 0.5

func = ((1 / np.sqrt(epsilon)) * odl.solvers.L2Norm(A.domain) ).convex_conj.translated(b)
func2 = odl.solvers.IndicatorLpUnitBall(r2, 2).translated(b) * (1 / np.sqrt(epsilon))  # note right multiplication
```
