### ISSUE TITLE
Continuous version of broadcasting

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#75]
A requirement that is very likely to emerge is the possibility to perform calculations with functions of different dimensionality by simple constant continuation along the missing axis. The usual pattern is that there is a 2D function `f: A --> R` and a 1D function `g: B --> R`, and one wants to e.g. multiply the two functions, where `g` is interpreted as constant along either the first or second axis, whatever is needed. This can be regarded as the continuum version of NumPy's broadcasting (or a subset thereof). More precisely, I want to be able to calculate expressions like `f(x, y) * g(x)` by regarding `g` as constant in `y`, i.e. calculate `f(x,y) * G(x, y)` with `G(x, y) = g(x)`. And all that, of course, without having to *actually* do the constant continuation.

Conditions for that to be possible are that

- they live in the same "type" of space
- their domains are compatible, i.e. there is some interval `[a, b]` such that `A = [a, b] x B` or `A = B x [a, b]` (we don't want it more complicated than that)
- they map to the same set

Since this is going to be useful beyond simple arithmetics, I think it would be best to write some `ConstExtensionOperator` or extend the semantics of `Embedding` to get this working. For functions defined on `IntervalProd`, the conditions are going to be easy to check.

The only thing which needs to be figured out is the handling of the data manipulation, which should work without actually having to blow up the data beforehand. In the NumPy backend, this should work out of the box by the broadcasting rules - provided the operators are all implemented properly - but on the CUDA side it's not going to fly immediately.

**Comment by kohr-h** [comment]
For all functionality using the `asarray()` result, this behavior would be simple to implement. Given an axis along which to extend, say `ax`, one does

```python
slc = [np.s_[:]] * self.ndim
slc[ax] = None
# Get array and reshape
return array[slc]
```

and broadcasting will do the rest. Could easily be generalized for several axes or slices.

**Comment by adler-j** [comment]
Is this functionality we're still interested in? I feel this would be done as part of adding slicing, if it is done.

**Comment by kohr-h** [comment]
Slicing in the sense of "give me the slice at z=0" I guess. This is in some way the opposite direction. Maybe it's the adjoint operator? :-)
Actually, I cannot quite think of an application of this, and in one way or another, it could be replaced by a functionality that adds a size-1 axis, composed with a `ResizingOperator`.
