### ISSUE TITLE
Data pre-scaling in tomography

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#751]
We should think about a flag in the ray transform operators that would skip the [output scaling](https://github.com/odlgroup/odl/blob/4e264b7a252d6aeb6664605303cae70829b5e3a4/odl/tomo/backends/astra_cuda.py#L229-L262) in each call to the backprojector. These factors are the same in each call anyway and they could be applied once to the data instead.

A helper function would make sense IMO since it can become quite involved. For example, the angle weights can actually vary if the angle distribution is not equidistant, or the magnification factors (determined by source and detector distances) could vary from projection to projection. We don't have a (simple) geometry for the latter case yet, but non-equidistant angles are definitely a thing and could be handled better than currently.

**Comment by adler-j** [comment]
I agree that this should be done since it is so simple (basically factor out the function and add a flag, should take like 5 minutes). But i think the "big" gains are from issue #152, so we can skip the data reordering etc.

**Comment by adler-j** [comment]
Lots of profiling done during #802, and this is not a big issue (i.m.o.), is it something you want to do regardless? perhaps it is big in some special case?

**Comment by kohr-h** [comment]
> Lots of profiling done during #802, and this is not a big issue (i.m.o.), is it something you want to do regardless? perhaps it is big in some special case?

It could be relevant when trying to go real-time in single slices, but I haven't profiled anything. If it pops up, we can reopen. No time to do this now.
