### ISSUE TITLE
Add Total Generalized Variation (TGV)

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#760]
TGV is one of the "standard" regularization methods that go beyond mere TV. We need to add it to ODL rather soon since we are now starting to solve actual problems.

The implementation would preferably be done in a similar manner to the [NuclearNorm](https://github.com/odlgroup/odl/blob/d5cb9f225c59f955c2cea269e9206c86e5830679/odl/solvers/functional/default_functionals.py#L1782), i.e. by implementing a functional that does not explicitly need to work on the derivative. This would imply a slight generalization of the TGV framework, but I think it would be rather obvious in what sense.

@kohr-h did you have a collegue at CWI who had implemented TGV before? Would this person be interested in doing this?

Sources (please contribute with more):
[It was introduced in this article](http://epubs.siam.org/doi/abs/10.1137/090769521)
[Articles referring to the original paper](https://scholar.google.com/scholar?cites=13429931524816703782&as_sdt=5,39&sciodt=0,39&hl=en)
[Adding Bregman to it](https://link.springer.com/article/10.1007/s10915-012-9650-3)

Edit @kohr-h: Added two more links.

**Comment by kohr-h** [comment]
> @kohr-h did you have a collegue at CWI who had implemented TGV before? Would this person be interested in doing this?

No, you probably think of TVR-DART. Apart from that, I'm not aware of an acronym anyone has implemented here that sounds similar.



> The implementation would preferably be done in a similar manner to the NuclearNorm, i.e. by implementing a functional that does not explicitly need to work on the derivative. This would imply a slight generalization of the TGV framework, but I think it would be rather obvious in what sense.

It would become so much easier with #738, and probably the first GPU version with #739. I'll push that stuff a bit more.

**Comment by ozanoktem** [comment]
Two good publications regarding TGV, covering both theory and numerics, are 

[A TGV-Based Framework for Variational Image Decompression, Zooming, and Reconstruction. Part I: Analytics](http://epubs.siam.org/doi/abs/10.1137/15M1023865)
[A TGV-Based Framework for Variational Image Decompression, Zooming, and Reconstruction. Part II: Numerics](http://epubs.siam.org/doi/abs/10.1137/15M1023877)

**Comment by adler-j** [comment]
Closing this. In truth, I only did the TGV-2 case, but generalizing it is somewhat trivial and should be doable by users.
