### ISSUE TITLE
Add Non-Local Means (NLM) regularizer

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#761]
Non-Local Means is perhaps the most famous nonlocal regularizer around today, and it can actually be used as a regularizer in inverse problems. I suggest we add a NLM functional to ODL, with corresponding proximal etc.

See the [FlexISP paper](http://www.cs.ubc.ca/labs/imager/tr/2014/FlexISP/FlexISP_Heide2014_lowres.pdf) for some information, but we may want a better reference.

See the [ProxImaL implementation](https://github.com/comp-imaging/ProxImaL/blob/cdf3044c08e65ba6c8cfa9c1203d44755deab599/proximal/prox_fns/patch_NLM.py) for some inspiration.

**Comment by chongchenmath** [comment]
A non-local algorithm for image denoising: [http://ieeexplore.ieee.org/document/1467423/?arnumber=1467423&tag=1](url)
Bregmanized Nonlocal Regularization for Deconvolution and Sparse Reconstruction: [http://epubs.siam.org/doi/abs/10.1137/090746379](url)

**Comment by adler-j** [comment]
This is merged.
