### ISSUE TITLE
Why is `ProductSpaceElement` mutable?

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#767]
While doing stuff on tensors, I saw that entries in a `ProductSpaceElement` are [stored in a list](https://github.com/odlgroup/odl/blob/0a609ea89e2000d1dfbdad1622c959ee9d575a43/odl/space/pspace.py#L605). Didn't make much sense to me, so I changed it to a tuple. That apparently blew the hat off a couple of tests, e.g. [this line](https://github.com/odlgroup/odl/blob/0a609ea89e2000d1dfbdad1622c959ee9d575a43/odl/test/space/pspace_test.py#L571) that assumes the storage is mutable. 
I don't get it. Why? Why would it ever be a good idea to make the storage mutable? Actually, in this same test, one could insert arbitrary garbage into the list, and [the code](https://github.com/odlgroup/odl/blob/0a609ea89e2000d1dfbdad1622c959ee9d575a43/odl/space/pspace.py#L651-L657) would just happily run.

So either I'm retarded or we should change this and re-implement `__setitem__` to assign *in-place* instead of replacing the whole element in the list.

**Comment by adler-j** [comment]
You are totally correct in that this is bad design. It should be changed to assigning in place.

**Comment by kohr-h** [comment]
Absolutely, we shouldn't require users to add the extra `[:]`. They should think of `x[i]` as a view of the i-th part, which is itself mutable, but not replaceable by something else.
