### ISSUE TITLE
Latex doc fails

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#77]
See [build](https://readthedocs.org/projects/odl/builds/3512257/)

**Comment by kohr-h** [comment]
What the?? `Undefined control sequence [...] \mathbb`? Apparently that's part of the AMS math package which is not loaded.

**Comment by kohr-h** [comment]
First attempt: add
```python
latex_elements = {
    'preamble': '''
\usepackage{amsmath}
\usepackage{amssymb}
'''
}
```
to `doc/source/conf.py`, but it seems to stop at the `\tableofcontents` command when I run `make latexpdf`.

**Comment by kohr-h** [comment]
One major reason for the failure is [here](https://github.com/odlgroup/odl/blob/master/doc/source/conf.py#L207-L210):
```python
latex_documents = [
    (master_doc, 'odl.tex', u'odl Documentation',
     u'Jonas Adler, Holger Kohr & Ozan Öktem', 'manual'),
]
```
Guess what? LaTex interprets the `&`.
