### ISSUE TITLE
Angles and offsets not consistent between projectors

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#772]
As title says, I discovered this when changing the angle test example to no longer have symmetry. It seems the rotation is simply according to -theta. I'll upload a branch that shows this.

**Comment by adler-j** [comment]
This is obviously related to our lack of documentation of these things, see #183. Perhaps we need a larger look at that.

**Comment by kohr-h** [comment]
I'm not at all surprised. It struck me back then (#295, #296, #297, #298, #299) when I finished up the monster PR #178 that we basically don't test anything related to geometries and aren't very consistent either in our definitions. My almost-sure guess is that the more tests we write for corner cases, the more failures and code atrocities we'll uncover. But :+1: for exploring in #773.
