### ISSUE TITLE
DiscreteLpVector.show in 3d

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#78]
Currently `show` only supports 1d or 2d vectors, we should also support 3d (and possibly n-d). Some options on how to do this:

* Show a slice (default to middle one)
* Show some sort of quad-view ![example](https://lh6.googleusercontent.com/i7FRBojVCWTBUIMS-IIz5Zhng5kL1khexj0xa19qB0sNVjvS0kBc2GSozLZg01YzSqvp676ojUAk8DY2yjK5SDyv9MREVaqkUo7bNVeqZXbJrf9dyFQWOpZM2-QNNQKkuQ)
* Some 3d rendering

**Comment by kohr-h** [comment]
This is definitely cool shit, but there is at least [a basic slicing capability](https://github.com/odlgroup/odl/blob/master/odl/discr/lp_discr.py#L330-L334) already implemented.

**Comment by adler-j** [comment]
Any chance for that to have a default value so this doesn't happen:

```python
>>> X = odl.uniform_discr(odl.FunctionSpace(odl.Cuboid([0,0,0],[1,1,1])), [10, 10, 10])
>>> X.zero().show()
Traceback (most recent call last):

  File "<ipython-input-3-8f84471491f6>", line 2, in <module>
    X.zero().show()

  File "e:\github\odl\odl\discr\lp_discr.py", line 361, in show
    indices=indices, **kwargs)

  File "e:\github\odl\odl\util\graphics.py", line 184, in show_discrete_function
    ''.format(dfunc.ndim))

NotImplementedError: no method for 3d display implemented.
```

**Comment by kohr-h** [comment]
Perhaps something like `np.s_[..., shape[2:] // 2]` semantically?

**Comment by adler-j** [comment]
Yes!

**Comment by kohr-h** [comment]
Added this.

**Comment by kohr-h** [comment]
I think I'll read up a bit on visualization soon, so regarding the quad view thing and other 3d visualization techniques, I may get some ideas.
