### ISSUE TITLE
Test & release for Python 3.6

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#787]
Python 3.6 is officially out and available on mainline conda. We should add it to our Travis CI test cases and build conda packages for it.

**Comment by adler-j** [comment]
I agree with this, should be rather straightforward, no?

**Comment by kohr-h** [comment]
I tried it with a new conda environment using Python 3.6. A few packages are missing, for example matplotlib and numpy with nomkl. Takes another week maybe.

**Comment by adler-j** [comment]
Ok lets wait then.

**Comment by kohr-h** [comment]
Only waiting for matplotlib now, rest seems fixed.
