### ISSUE TITLE
CallbackSleep

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#792]
Some examples run too fast after #789 is in. For better "observability" we need some way to sleep in each iteration. That can be easily done with 
```python
from time import sleep
callback = odl.solvers.CallbackApply(lambda _: sleep(0.2))
```
but perhaps it's good to have a separate class such that it's obvious such a function exists.

**Comment by adler-j** [comment]
An alternative is to bake this into CallbackShow, but I guess it has it uses as another separate callback.
