### ISSUE TITLE
UFuncs for FnBase elements

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#80]
It is possible (using the `__array_wrap__` interface) to define ufuncs for any `FnBaseVector`. How about we do this, and optionally allow overloading? Then users could write `my_vector.sin()` and it always works, but it COULD be overloaded. Specifically this would help with cuda.

**Comment by kohr-h** [comment]
Hm, this doesn't immediately make sense to me, so I have to think about it properly. I guess you want to be able to use the same interface for NumPy and CUDA implementations and get rid of the module-level ufuncs in `cu_ntuples.py`?

**Comment by adler-j** [comment]
Yes that is the idea. Basically only allow member ufuncs:

```python
>>> x = CudaRn(5)
>>> x = X.element([1, 2, 3, 4, 5])
>>> y = x.sin()
>>> z = X.element()
>>> x.sin(out=z)
```
