### ISSUE TITLE
Add 'K' order property to spaces

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#807]
While working on the tensors I realized that the `space.order` property really stopped to make sense. 

## Problem
When slicing into an array, the result can very well be non-contiguous. So far we just ignored that to make sure views are preserved:
```python
>>> space = odl.rn((2, 3), order='F')
>>> x = space.zero()
>>> x_part = x[:, ::2]
>>> x_part[:] = 1
>>> x
rn((2, 3), order='F').element(
[[1.0, 0.0, 1.0],
 [1.0, 0.0, 1.0]]
)
```
At the same time we have this:
```python
>>> x_part.space.order
'F'
>>> x_part.data.flags.f_contiguous
False
```
That can lead to certain WTF moments...

## Suggestion
In my view it would make most sense to
- remove `space.order`,
- add `order` to `element` methods where enforcing ordering makes sense.

**Comment by adler-j** [comment]
I don't see the technical issue with this, fortran order does not imply fortran order and contiguous storage. With that said, I agree that it is un-pedagogical and with tensors rather unnecessary in most cases.

With that said, we still occasionally require spaces to store their data in a specific way for compatibility with external libraries. My suggestion would be that we add the `'A'` option to order which is "any" in numpy, i.e. we don't care. And then we let the current `'C'` and `'F'` be "strong" assumptions, i.e. require that storage order (and continuity). In your example, this would mean that `x_part.space` would have order `'A'`. 

In a longer term, we would actually want to be able to specify the specific strides to use, but that is likely not needed right now.

See [numpy.copy](https://docs.scipy.org/doc/numpy/reference/generated/numpy.copy.html) for an example of using this labeling of orders.

**Comment by kohr-h** [comment]
> I don't see the technical issue with this, fortran order does not imply fortran order and contiguous storage. With that said, I agree that it is un-pedagogical and with tensors rather unnecessary in most cases.

Hm, so you're saying that an object created in a space with `'F'` ordering should not be assumed to be F-contiguous. In other words, `'F'` is merely an "if-possible" or "in-the-beginning" guarantee, not a lifetime guarantee.

I'm not quite sure I like that. Belonging to a space with that property would IMO mean that this property should also hold for a particular element.

On the other hand, if the space hadn't such a property but only the element factory, it would be totally fine. Basically then the code would make the same kind of promise as Numpy.



> With that said, we still occasionally require spaces to store their data in a specific way for compatibility with external libraries. My suggestion would be that we add the 'A' option to order which is "any" in numpy, i.e. we don't care. And then we let the current 'C' and 'F' be "strong" assumptions, i.e. require that storage order (and continuity). In your example, this would mean that x_part.space would have order 'A'.

> Edit: It seems my 'A' should perhaps be 'K'

Yes, that's a good suggestion.

But regarding guarantee of order in interaction with external libraries: wouldn't it be better (and easier to maintain / reason about) if the specific methods intended for this interaction would have an option to enforce contiguousness?
Typical candidates for that would be
- element
- asarray
- writable array

**Comment by adler-j** [comment]
>Hm, so you're saying that an object created in a space with 'F' ordering should not be assumed to be F-contiguous. In other words, 'F' is merely an "if-possible" or "in-the-beginning" guarantee, not a lifetime guarantee.

No, what I mean is that an object in a space with `'F'` ordering should be in column major order, not guarantee that it is also continguous. At least thats how I interpret the word "ordering".

> I'm not quite sure I like that. Belonging to a space with that property would IMO mean that this property should also hold for a particular element.

Certainly agree that properties like this should be lifelong guarantees.

> On the other hand, if the space hadn't such a property but only the element factory, it would be totally fine. Basically then the code would make the same kind of promise as Numpy.

Agree, but then binary combatibility with some libraries (notably GPUMCI, but I'm sure when we add deep astra integration they will need it as well) would be impossible on a space level, i.e. we wouldn't be able to accept an arbitrary element in the space as input.

> But regarding guarantee of order in interaction with external libraries: wouldn't it be better (and easier to maintain / reason about) if the specific methods intended for this interaction would have an option to enforce contiguousness?

Well the specific method intended for that interaction is in general `data_ptr`, in which case we cant really do much. For the others, use might as well use whatever method is available in the returning object (i.e. just call np.asfortran after calling `vec.asarray()`.

**Comment by kohr-h** [comment]
Looking into this now. I'm still a bit confused about what to do best, here are some thoughts in random order.

- Regarding labels, I think it should be 'A' for "any".
- What shall we do when comparing spaces? Strict regarding order? Probably the only sensible way to go.
- `__getitem__` needs to check `out_arr.flags[self.order + '_CONTIGUOUS']` (for C or F) and create a new space accordingly. If the flag is `False`, ouput order will be `'A'`.
- `'A'` means `'C'` for new elements, as in Numpy.
- What should be the default for spaces? If we use `'C'`, which means "enforce C contiguousness", we potentially copy a lot by default. Probably `'A'` should be the default, and if some external code needs a certain ordering, it has to be explicitly given.

**Comment by adler-j** [comment]
> Regarding labels, I think it should be 'A' for "any".

Sadly I'd follow numpy strictly here and they seem to distinguish A from K, and I think we want K here, no?

> What shall we do when comparing spaces? Strict regarding order? Probably the only sensible way to go.

Strict.

> `__getitem__` needs to check `out_arr.flags[self.order + '_CONTIGUOUS']` (for C or F) and create a new space accordingly. If the flag is `False`, ouput order will be `'A'`.

I don't quite follow here, but yes, output needs to have the correct order.

> `'A'` means `'C'` for new elements, as in Numpy.

It should mean whatever the backend picks, i.e. no guarantee to users. Or is that too weak?

> What should be the default for spaces? If we use `'C'`, which means "enforce C contiguousness", we potentially copy a lot by default. Probably `'A'` should be the default, and if some external code needs a certain ordering, it has to be explicitly given.

I'd say "`A`" by default.

**Comment by kohr-h** [comment]
>> Regarding labels, I think it should be 'A' for "any".
> 
> Sadly I'd follow numpy strictly here and they seem to distinguish A from K, and I think we want K here, no?

So this is the docstring of `numpy.ravel`, the interesting part:
> order : {‘C’,’F’, ‘A’, ‘K’}, optional 
The elements of a are read using this index order. ‘C’ means to index the elements in row-major, C-style order, with the last axis index changing fastest, back to the first axis index changing slowest. ‘F’ means to index the elements in column-major, Fortran-style order, with the first index changing fastest, and the last index changing slowest. Note that the ‘C’ and ‘F’ options take no account of the memory layout of the underlying array, and only refer to the order of axis indexing. ‘A’ means to read the elements in Fortran-like index order if a is Fortran contiguous in memory, C-like order otherwise. ‘K’ means to read the elements in the order they occur in memory, except for reversing the data when strides are negative. By default, ‘C’ index order is used.

K seems to exist only for a few functions, basically reshaping and related. For constructors like `np.array` you have only `'C', 'F', 'A'`, and here `'A'` means anything if no copy is required, otherwise `'C'`.

So I guess you're right, we want `'K'` for the space, which means "as in memory", and the order for new elements will have to be determined by hand.

> I don't quite follow here, but yes, output needs to have the correct order.

I mean that we have to fall back to `'K'` when we take a slice like `x[1:3, ::2]` that results in discontiguous memory layout, but not for `x[...]`.



> It should mean whatever the backend picks, i.e. no guarantee to users. Or is that too weak?

Right, there's no claim about contiguousness in `'A'` (or let's say `'K'`) anyway, so we can just use whatever we get. I don't think that's too weak, we don't really make any promise there.



> I'd say "A" by default.

Sounds good. There's even another aspect, namely that often times, views are not preserved when enforcing contiguous ordering, but we usually want views.

**Comment by kohr-h** [comment]
In light of the fact that we have to use `'A'` for reshaping, *and* that libgpuarray uses `'A'` for anything, the letter ´'K'` is largely useless. I'd say we change it to `'A'` and scrap the `view_order` property, even if technically we have `'K'`.

**Comment by kohr-h** [comment]
Not going to happen.
