### ISSUE TITLE
Tensor ops should be unrelated to discr

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#811]
The submodule `odl/discr/tensor_ops` is for some reason put under `odl/discr`, but all of the functionality should work on arbitrary `ProductSpace`s. So they should be moved to `odl/operator`. We also need to do a slight fix to some code that explicitly verifies that the base space is a `DiscreteLp`.

The reson for fixing this is that one would want to have `PointwiseInner` and related ops over arbitrary spaces and not only for `DiscreteLp` spaces. The canonical example is "matrix spaces", e.g. `ProductSpace`s of `ProductSpace`s of `DiscreteLp`, which is currently disallowed.

@kohr-h who wrote these classes initially could perhaps shine some light on why it is in `odl/discr`?

**Comment by kohr-h** [comment]
> @kohr-h who wrote these classes initially could perhaps shine some light on why it is in odl/discr?

Yeah I'm the culprit...

The likely reason for the placement is that I had a different implementation in mind when I started out. I planned to ensure contiguous storage if possible, but let go of that idea when it became too hard to realize.
But when I think of it, that didn't make for a good reason in `odl/discr` either.

Anyway, fine with me to move this and relax the conditions.
