### ISSUE TITLE
Update tutorial

### ISSUE THREAD

**Issue by ozanoktem** [odlgroup/odl#812]
We need to update the [tutorial](https://github.com/odlgroup/odl/blob/971f31f6d196e63b49b2071bcfb12b8f3b31d59f/doc/source/guide/introduction/getting_started.rst) so that it reflects the changes that have come with the introduction of functionals. We should also link to the tutorial already at the **Documents** section in the [ODL front page at GItHub](https://github.com/odlgroup/odl), perhaps right after mentioning the link to the documentation page.

**Comment by adler-j** [comment]
I'll fix this.

**Comment by adler-j** [comment]
Second thought, it seems you were looking at some age old version of that code. The file you reference was removed [about 4 months ago](https://github.com/odlgroup/odl/commit/eea32ef4800f0fe6b2132911ea64151f86b5ff48).

The new version is here:

https://github.com/odlgroup/odl/blob/master/doc/source/getting_started/first_steps.rst

But you should always be using the ODL documentation page, i.e. here:

https://odlgroup.github.io/odl/getting_started/first_steps.html

Anyway, I'll add it to the readme.

**Comment by adler-j** [comment]
Second thought, I wont add it. It is already on the front page of the documentation, as should be: 

https://odlgroup.github.io/odl/

I say close this.

**Comment by kohr-h** [comment]
What we *could* do is to change the front page title "Documentation" to "Resources" (a quite common header) and list some more links in an item list. For example

- [Documentation](https://odlgroup.github.io/odl/)
- Getting started (has no subpage currently)
- Tutorials (see #814)
- [Code examples](https://github.com/odlgroup/odl/blob/master/examples)
- [API reference](https://odlgroup.github.io/odl/odl.html)

**Comment by adler-j** [comment]
Excellent suggestion @kohr-h, do you want ot fix it?

**Comment by kohr-h** [comment]
Ok, give me a minute.
