### ISSUE TITLE
Change RayTransform impl default

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#822]
The default of `RayTransform`s `impl` argument is currently `'astra_cpu'`, for some reason. A much more reasonable choice would be to set it to `None`, and then pick "the best available one", if no specific one is given. My proposal is to prioritize:

`'astra_cuda'` > `'astra_cpu'` > `'scikit'`

In cases where one is not available, for a given geometry, ignore it.

This would simplify all examples with lines like

```
# The implementation of the ray transform to use, options:
# 'scikit'                    Requires scikit-image (can be installed by
#                             running ``pip install scikit-image``).
# 'astra_cpu', 'astra_cuda'   Requires astra tomography to be installed.
#                             Astra is much faster than scikit. Webpage:
#                             https://github.com/astra-toolbox/astra-toolbox
impl = 'astra_cuda'
```

Since we could just remove them (perhaps with a note that users may want to install ASTRA anyway.)

**Comment by kohr-h** [comment]
Reasonable suggestion.
