### ISSUE TITLE
Clean up the main repo

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#829]
We currently have [29 branches](https://github.com/odlgroup/odl/branches) in the repo which I think is rather ridiculous. Even if most of them are feature or work-in-progress branches it looks to a visitor like the devs are all over the place and everything is pure chaos.

I suggest that we do the following:
- Stop pushing our branches here.
- Make PRs always from our own forks where things can be dirty as hell.
- Use PRs aggressively also when working collaboratively on a feature, i.e., make a PR into a branch rather than pushing to the same branch (that issue resolves itself when PRs are made from own forks exclusively).
- Clean up this repo by pushing all "own" branches to our forks and removing them here.

I'll start by pulling over my old stuff.

**Comment by adler-j** [comment]
Certainly agree with this idea, which would also solve stuff like #786.

Suggestions for branches that we should have:

* Larger features, i.e. tensors. Basically anything that will have sub-branches.
* Version branches. I.e. we shold have made a 0.5.3 branch, that way we get a clear separation in what features should go in there.

I am personally against a dev branch for now, simply because it overcomplicates things.

I'll clean up my branches.

**Comment by kohr-h** [comment]
> Larger features, i.e. tensors. Basically anything that will have sub-branches.

Definitely, I wanted to add that, too. Making PRs into feature branches that should be publicly visible in the main repo only works if the feature branch is in the main repo, so there it makes sense.



> Version branches. I.e. we shold have made a 0.5.3 branch, that way we get a clear separation in what features should go in there.

How do you mean? At which time point?



> I am personally against a dev branch for now, simply because it overcomplicates things.

Me, too. So far we have always had a working master branch, and that's a big plus. I think we should always be able to tell people that using latest master is a valid option, not a risk.
No need for a dev branch so far.

**Comment by adler-j** [comment]
Related to #786

**Comment by adler-j** [comment]
The general idea is this, but simplified (cut the develop branch, replace it with master)

http://nvie.com/posts/a-successful-git-branching-model/

This seems to sum up my thoughts rather well:

http://endoflineblog.com/gitflow-considered-harmful

> Here it is:
> * There is only one eternal branch - you can call it master, develop, current, next - whatever. I personally like "master", and that's the name I'll use in the rest of the description, as it's convention by now in the Git world and immediately conveys its purpose.
> * All other branches (feature, release, hotfix, and whatever else you need) are temporary and only used as a convenience to share code with other developers and as a backup measure. They are always removed once the changes present on them land on master.
> * Features are integrated onto the master branch primarily in a way which keeps the history linear. You have a lot of leeway in how you want to enforce this. You can make it simply a convention that developers are encouraged, but not forced, to follow. On the other side of the spectrum, if you use something like Gerrit to manage your Git repositories (which I recommend, even if you don't practice code reviews - the permission system is fantastic, and if you ever decide you want code reviews, it'll be very easy to start doing them), you can set up permissions in such a way that actually forbids pushing merge commits to master, and that way ensure linear history.
> * Releases are done similarly to in GitFlow. You create a new branch for the release, branching off at the point in master that you decide has all the necessary features. From then on new work, aimed for the next release, is pushed to master as always, and any necessary changes are pushed to the release branch (in my opinion, it's an anti-pattern and a huge red flag if your release requires separate commits to work, but that's a topic for another article - for simplicity, let's assume you can't or don't want to change that). Finally, once the release is ready, you tag the top of the release branch. Then, because there is one eternal branch, there is only one way to get your release to be versioned permanently - and that is to merge the release branch into master and push that changed master. After that, all the changes that were made during the release are now part of master, and the release branch is deleted.
> * Hotfixes are very similar to releases, except you don't branch from an arbitrary commit on master, but from the release tag that you want to make the fix in. Again, work on master continues as always, and the necessary fixes are pushed to the hotfix branch. Once the fix is ready, the procedure is exactly the same as for a release - tag the top of the branch creating a new release, merge it into master, then delete the hotfix branch.

**Comment by kohr-h** [comment]
Boy, that's some complicated development model. I'm totally against it, here's why:
- Looking at the first image in the article arouses strong WTF feelings. I actually thought that image has to be the development anti-pattern the author debunks as utter BS. But no, that's the model he proposes.
- IMO it tries to solve a non-existing problem, at least in our case, while creating a bunch of new ones. Why all the hassle? My first impression of this approach is "We do it because we can." or "Look at what complex dev model we can handle here, we're so smart."
- This will certainly cast away any potential contributors. If we add a text like this (even a stripped-down version) to `CONTRIBUTING.md` we can be very sure that our number of external contributors stays exactly constant.
  For example, when I choose to contribute to a project, my first (and in 99 % of the cases correct) guess is that I should branch off master, make the feature and then put in a pull request. With the above model, I'd be told by the maintainers "No, you did it wrong, you should have branched off `develop`. Now go back and rebase all of your stuff." And in that case, if it wasn't a big bunch of work, I would just say "screw you and your stupid model" and leave forever.
- What's wrong with creating a release tag off `master`? We're only two people who have to coordinate actions, how hard can it be? We don't need a release branch, and I also don't believe in milestones, they just add arbitrary goals that either not met 50 % of the time, or delays releases in an unreasonable manner.
   I'm actually totally fine with making releases the moment we "feel like it". Create an issue, define which branches should go in before tagging, and then go. What I can agree on is that we should probably release more often, but that's an orthogonal issue and won't get any easier from putting in extra burdens.
- And `hotfix`, boy, give me a break. We're not selling a product. If people are not happy with a release, they should use `master` because it's stable and may already contain the fix. If not, users can file a bug report and somebody will fix it, then `master` has the fix.
- The remark on usage of tools for code review is kind of valid, but slightly outdated. I'm actually quite happy with the way you can control access in GitHub directly.
  Some time ago I checked out a bunch of the review tools in GH integrations, don't quite remember the names, but each one basically said "Code review done right.". Another property of all those tools, besides being right, is that they're so ridiculously complex that you just get sick of using them. I concluded that I can very well live with the limitations of code review on GitHub in exchange for the relatively simple interface and usage.

So I have to disagree on the notion of "sane model" and conclude that the model proposed in the article is roughly the opposite of what I consider reasonable.

**Comment by kohr-h** [comment]
Okay, maybe I overreacted a little bit, but I would very much keep things as simple as possible. And as long as we haven't clearly identified a *practically relevant* flaw in the current model, I'm very reluctant to put additional complexity into it.

**Comment by adler-j** [comment]
My only suggested change is that we actually create release branches. That way we can perform a feature freeze without freezing the whole repository.

We only need to do this for larger branches, but stuff like 0.5.3. could perhaps have used a throrough review, i.e. make sure everything runs on all platforms, all examples run etc before the final release.

**Comment by kohr-h** [comment]
> My only suggested change is that we actually create release branches. That way we can perform a feature freeze without freezing the whole repository.

Makes sense.

> make sure everything runs on all platforms

Kind of makes my case for #618, or?



> all examples run etc before the final release.

With that in mind, it would be good to write up a short `HOWTO_RELEASE.md` somewhere since it's easy to forget things. Also some parts of the process are quite hacky at the moment, for example the horrible manual editing of the conda packages for windows.

**Comment by adler-j** [comment]
I'd say this has been implemented now, no?

**Comment by kohr-h** [comment]
Sure
