### ISSUE TITLE
Rename `TensorGrid` -> `RectGrid` and `RegularGrid` -> `UniformGrid`?

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#836]
Suggestions for renames of grid classes so they better match the partition names and the names we use for properties, e.g. `is_uniform`.

**Comment by adler-j** [comment]
Related to "Remove RegularGrid" #670, which I prefer to this solution.

**Comment by kohr-h** [comment]
I knew there was an old issue about that but couldn't find it for some unknown reason.
