### ISSUE TITLE
Bug in derivative of quadratic functional

### ISSUE THREAD

**Issue by aringh** [odlgroup/odl#837]
There is a bug in the derivative of the quadratic functional, when only the linear term is used. Fix exists in my fork: e486361d9bb192949e30eed95b1ee43290b21652. I can try to cherry-pick it later (if no one else wants to do it ;-)) to get into master. But right now I need to run.

**Comment by adler-j** [comment]
It's not an emergency, just make a pull request when you can. If possible, also add a test so this can't happen again.

**Comment by adler-j** [comment]
I suppose this is fixed.
