### ISSUE TITLE
Make installation instructions less mixed

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#839]
Currently we have a single file with all installation instructions, this seems to cause confusion (given that I've seen a few people do it), so my suggestion would be that we split the installation instruction into the following parts that live in separate files:

* **Installing ODL**: The current start of the text, should contain what it does not, but with a short TLDR up top and make links.
* **Installing a release using conda**: Same as now, but with tests added.
* **Installing a release using pip**: Same as now, but with tests added.
* **Installation from source**: Same as now, but with tests added. Here we should mention astra from source, among others.
* **Compiled extensions**: This should contain the "hard to install parts", easily installed packages should go into their respective guide.

What do we think?

**Comment by kohr-h** [comment]
I think that makes a lot of sense. The text is admittedly quite long and intimidating, having more but shorter files for specific cases would be good.
