### ISSUE TITLE
Vector creation utility

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#84]
As discussed in #82, we should maybe add a utility to create vectors (with all default options). In pseudocode the suggestion is to add

```python
def vector(inp, dtype=None, impl=None):
    if impl == 'numpy':
         return Rn(len(inp), dtype=dtype).element(inp)
    elif impl == 'cuda':
         return CudaRn(len(inp), dtype=dtype).element(inp)
```

to some part of `odl/space`. Discussed options are `__init__.py` and a new file.

**Comment by kohr-h** [comment]
I admit that `__init__.py` is far from optimal. Probably better to have an own file, `space_util.py` sounded okay. This version is obviously only for real data types, an analogon for complex would make sense, too. And then, names like `real_vector` and `complex_vector` would be good.

**Comment by adler-j** [comment]
> I admit that __init__.py is far from optimal. Probably better to have an own file, space_util.py sounded okay.

Agree

> This version is obviously only for real data types, an analogon for complex would make sense, too. And then, names like real_vector and complex_vector would be good.

I think that is making it to complicated (it should be doable with the `dtype` parameter). How about:

```python
def vector(inp, dtype=None, impl=None):
    array = np.asarray(inp, dtype=dtype)
    if impl == 'numpy':
         return Fn(len(inp), dtype=array.dtype).element(array)
    elif impl == 'cuda':
         return CudaFn(len(inp), dtype=array.dtype).element(array)
```

with this, the vector will be complex if the input is complex

```python
>>> vector([1, 2])
Rn(2).element([1, 2])
>>> vector([1, 1+2i])
Cn(2).element([1, 1+2i])
```

**Comment by adler-j** [comment]
Nice addition, added a few comments. Will be useful in demos and short tests.
