### ISSUE TITLE
Copyright in examples

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#842]
I've noticed this when introducing the examples to new users, that they start reading the disclaimer and read a line or two before they notice that they should skip it. And this is problematic since it hinders the new user experience.

I personally feel that we should remove the copyright notice in the examples for a few reasons:

1. Do we really care if someone takes the examples? They are basically not usable without ODL anyway.
2. They distract from the code.
3. Legally, we still own the code and the licence still applies. It is merely "recommended" that we attach it to each file.

**Comment by kohr-h** [comment]
I agree.
