### ISSUE TITLE
Update numpydoc submodule

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#845]
The upstream repo has advanced a bit since we branched off. Doesn't look like too much has happened, but one thing they added is a section duplication check that caught an error in #841.
```
reading sources... [  7%] generated/odl.discr.grid.uniform_sampling_fromintv                         
Exception occurred:
  File "/home/hkohr/git/odl/doc/sphinxext/numpydoc/docscrape.py", line 336, in _parse
    raise ValueError(msg)
ValueError: The section See Also appears twice in the docstring.
```
This is nice, and we should rebase on the current master.

**Comment by adler-j** [comment]
Sounds nice, please go ahead, should basically mean rebasing our repo to numpys.
