### ISSUE TITLE
Change reflective isinstance(self, type(other)) to type equality check

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#848]
We currently have lots of equality checks that begin with:

```python
return isinstance(other, type(self)) and isinstance(self, type(other)
```

this could easily be changed to the more easily read 

```python
return type(self) == type(other)
```

which should also somewhat improve performance.

**Comment by kohr-h** [comment]
The correct way would be
```python
return type(self) is type(other)
```
with which I agree.

**Comment by adler-j** [comment]
Are we sure that does not break in some really weird corner case (e.g. a metaclass generating classes on the fly or something)?

**Comment by kohr-h** [comment]
Hm, could be. For those cases `is` would always return `False` 😞 
I guess `==` is the best way after all.

**Comment by adler-j** [comment]
I searched the code and there is none of these left. Closing.
