### ISSUE TITLE
niter should not be optional

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#849]
The parameter `niter`, when used to give a fixed number of iterations (as compared to `maxiter`, which gives an upper limit) currently has defaults set to 1. I feel this is a source of confusion in some cases, and provides very little improved simplicitly in other cases (who runs 1 iteration of landweber?)

My suggestion is to make the variable mandatory across the board.

**Comment by kohr-h** [comment]
Agreed, default 1 hardly makes sense.
