### ISSUE TITLE
Import ODL much slower

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#85]
It occurred to me that `import odl` has become much slower lately. [A short profiling gives the the answer](https://github.com/odlgroup/odl/blob/cfd3149611ce92bc8652c599ac07661e4f789006/odl/util/graphics.py#L33)

Basically this takes forever (a whole 2.4 seconds, enough for me to notice). Compare this to the whole of `odl` taking about 2.8 second to load, the second highest being the cuda test (which initializes cuda), taking ~0.1s.

There are two suggestions to solve issues like this:

* Lazy importing, for example by using [Importing](https://pypi.python.org/pypi/Importing) package or homebrewing.
* More stringence in having these imports inside the function that uses them.

**Comment by kohr-h** [comment]
Well if it's only matplotlib that causes the delay, I'd say we put it into the function that needs it rather than adding an external dependency.

**Comment by adler-j** [comment]
Ok great. We should keep an eye on this and actually have a benchmark for the program `import odl` as part of the CI.

**Comment by adler-j** [comment]
Fixed the worst culprit, now down to 0.29 seconds. Numpy by comparison takes 0.029 seconds. We may want to investigate this further.
