### ISSUE TITLE
Add product of spaces

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#859]
A rather obvious syntax that we have not started using is the product of spaces, i.e. one could easily envision

```python
>>> r2 = odl.rn(2)
>>> r3 = odl.rn(3)
>>> r2 * r3
ProductSpace(rn(2), r3)
>>> r2 ** 4
ProductSpace(rn(2), 4)
```

sub-classes could then overload this syntax to provide more advanced storage and functionality, i.e. in #857.

```python
>>> space = odl.uniform_discr(0, 1, 100)
>>> space ** 3
uniform_discr(0, 1, 100, shape=3)  # or w/e syntax we pick
```

**Comment by kohr-h** [comment]
How about
```python
>>> space = odl.uniform_discr(0, 1, 100)
>>> space ** 3
uniform_discr([0.0, 0.0, 0.0], [1.0, 1.0, 1.0], (100, 100, 100))
```
?
There could be an internal (or public) property like `pspace_shape`, which gives the shape that is not part of the base space but added to the "left".

**Comment by adler-j** [comment]
Well your suggestion is strictly different from mine and frankly doesn't really make sense in how you usually write notation. You are taking the power as a power of a domain, while I take it as a power of the range. Your suggestion is hence *not* compatible with this suggestion, since it has no obvious equivalent in the case of non-`uniform_discr` spaces.

Example, my proposal:

```python
>>> space = odl.uniform_discr(0, 1, 100)
>>> (space ** 3)[0]
uniform_discr(0, 1, 100)
```

your proposal would, if it is to be consistent with slicing, give

```python
>>> space = odl.uniform_discr(0, 1, 100)
>>> (space ** 3)[0]
uniform_discr([0, 0], [1, 1], [100, 100])
```

Mathematically it doesn't make much sense either. If I write F({1, 2, 3}, R) to mean the set of functions from {1, 2, 3} to R, then F({1, 2, 3}, R)^2 should be the set of ordered 2-tuples of such functions. I.e. 

    F({1, 2, 3}, R)^2 = (F({1, 2, 3}, R), F({1, 2, 3}, R))

this can be identified with

    F({1, 2, 3}, R)^2 = F({1, 2, 3}, R^2)

but doesn't have an isomorphism to what you propose, i.e.

    F({1, 2, 3}, R)^2 != F({1, 2, 3}^2, R)

**Comment by kohr-h** [comment]
Oh never mind, what I wrote was obviously BS. That kind of stuff would only work for tensor spaces, where you would add a 3 to the shape on the left, obviously not adding 2 axes as I wrote above.

**Comment by adler-j** [comment]
Well what you wrote could be given the syntax

```python
>>> space = odl.uniform_discr(0, 1, 100)
>>> 3 ** space
uniform_discr([0.0, 0.0, 0.0], [1.0, 1.0, 1.0], (100, 100, 100))
```

which I *think* would make sense?

**Comment by kohr-h** [comment]
Haha, not quite sure about that.. I just know `2^X` as the power set of `X`, which has `2^n` elements if `X` has `n`. That analogy doesn't really hold, does it?
Perhaps `space * 3` instead? No, seriously, I think it's okay to type that one out.
