### ISSUE TITLE
Scrap FunctionSet, DiscretizedSet and similar

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#860]
We currently make a hard distinction between what is considered a space and what is not, by using two separate classes for each such case. 

That distinction could as well be made in a duck-typing way, i.e. if `isinstance(space, FunctionSpace) == True`, then `space.element() + space.element()` should be possible as long as `space` has a `field` (or one that is not `None`). The same goes with other vector space properties.

This would likely have rather far-reaching changes, but IMO it would be worth it since it would remove quite a bit of code, flatten the inheritance structure, and behave more "pythonic" in general.

One immediate consequence I see would be that `LinearSpace` would have to allow `field=None` or something, because the alternative would be that we don't call `LinearSpace.__init__` in subclasses when we don't have a reasonable `field` to provide. I prefer the first variant, since the latter is actually a rather bad code smell.

**Comment by adler-j** [comment]
Agree with everything you said. Duck type all the things.

**Comment by kohr-h** [comment]
Quick question here: how should be react when a `LinearSpace` with a non-field is created? Should we error-check anything that requires a field or should we just lean back and let errors propagate? For example, by using something like a `UniversalField` that never complains?

**Comment by adler-j** [comment]
Well, I say lean back and let errors propagate, I'd stay out of a `UniversalField`, at least for now.

**Comment by kohr-h** [comment]
Okay, I'll try a bit of stuff to see what happens. My concern is that there will immediately be the `NoneType is not iterable` type of error all over. Then probably access to `space.field` needs a bit more care to produce reasonable error messages.

**Comment by kohr-h** [comment]
(I write here not to litter #861 so that page stays alive a bit longer)

Wow, that was much easier than I thought. Basically a couple of hours of shuffling code around, deleting lots of stuff and adding a few checks, fixing the tests, that's it.

I basically took the logic from the `*Set` classes over to the `*Space` classes an adapted the checks. Some details:
- `FunctionSpace` does the `out_dtype` vs. `range` checking slightly differently now. It infers `field` and sets it to `None` if the data type is neither real nor complex.
- `DiscretizedSpace` basically just checks less strict.
- `TensorSpace` is also being more liberal and checks during `init` if `weighting`, `norm` etc. make sense or not.
- `LinearSpace` allows `field=None`. To avoid lots of `NoneType is not iterable` type errors, there is an additional `has_field` property that allows checking if stuff related to `field` make sense. I don't think I have propagated it to all relevant places yet.
- The tests were basically fixable by text search-and-replace and in one or two places removal of `pytest.raises` that didn't raise any more. I suspect that some of the cases that we now just silently allow are a bit under-tested since I didn't get a single substantial failure. I may have to look closer into that.
