### ISSUE TITLE
DiscreteLp.real_space does not conserve axis labels

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#862]
As this example shows, the labels are lost

```python
>>> spc = odl.uniform_discr(0, 1, 10, axis_labels=['label'], dtype=complex)
>>> real_spc = spc.real_space
>>> real_spc.axis_labels
('$x$',)
```

**Comment by kohr-h** [comment]
Whoopsey!

**Comment by adler-j** [comment]
Can you fix this in the monster branch, since I'm sure merges right now are getting out of hand.

**Comment by kohr-h** [comment]
Can do. It's not that bad currently, I try to keep rebasing the branch roughly every or every second day. But I agree, why unnecessary pain?
