### ISSUE TITLE
Implement cone beam geometries

### ISSUE THREAD

**Issue by moosmann** [odlgroup/odl#87]
Create branch implementing cone beam geometries, corresponding ASTRA backends, and others features:
* Add cone beam geometry
* Specify unit of angle parameter in docstring
* Add optional offset parameter for motion parameters
* Add rotation about arbitrary axis for 3D geometries
* Add ASTRA backend for relevant geometries
* Correct swapping of axis and/or angle offset in ASTRA
* Correct inconsistent scaling of ASTRA projector with pixel size
* Add corresponding tests

**Comment by kohr-h** [comment]
Moved from [the old repo](https://github.com/odlgroup/odl-tomo/issues/6).
