### ISSUE TITLE
Doctest fails in RectPartition with Python 3.6

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#874]
[This doctest](https://github.com/odlgroup/odl/blob/559290fde436cd4ed785416385de52fea8007499/odl/discr/partition.py#L969-L974) fails since for some reason unclear to me, the value 3 for the max point is not used. Instead, the default is used. It only affects Python 3.6, which to my knowledge introduced internal changes to dictionaries. But this code should still work. Maybe it's a bug in the `doctest` module, or in `pytest`?

**Comment by adler-j** [comment]
Can you try to produce a minimal working example? Perhaps it is actually a python bug?
