### ISSUE TITLE
Bug in ProductSpaceOperator?

### ISSUE THREAD

**Issue by aringh** [odlgroup/odl#88]
In my endless search to solve the issue #49 (:p) I am now writing tests for the code. In order to do this efficiently I use the `ProductSpaceOperator`. However, the operator seems to only take instances of `ProductSpace` as range (and probably also domain): is this on purpose?

Minimal working example: I want to create an operator `C: R3 times R2 -> R3`, `Cx = Ax + By`, where A is a 3x3 matrix, x lives in R3, B is a 3x2 matrix, and y lives in R2. If this is done with the code
```python
    n = 3
    rn = odl.Rn(n)
    A = np.random.rand(n, n)
    Aop = MatVecOperator(rn, rn, A)

    m = 2
    rm = odl.Rn(m)
    B = np.random.rand(n, m)
    Bop = MatVecOperator(rm, rn, B)

    ran = rn
    dom = ProductSpace(rn, rm)

    A_plus_B_op = ProductSpaceOperator([Aop, Bop], dom, ran)
```
one gets the error
`TypeError: space ProductSpace(Rn(3), Rn(2)) not a ProductSpace instance.`
First of all: looking at [these lines](https://github.com/odlgroup/odl/blob/master/odl/operator/pspace_ops.py#L131-L133), it should probably say `Rn(3) not a ProductSpace instance`.

Second: why is a call like this not allowed? Changing the line `ran = rn` in the example to `ran = ProductSpace(rn, 1)` this works fine. Also changing the initiation of the operator to `ProductSpaceOperator([Aop, Bop])` goes through. However, there is no difference in the end between these two and the first way.

**Comment by adler-j** [comment]
*  It should clearly be `format(ran)`, thats a error in the docstring.

* The reason it does not work is that the function is defined `ProductSpace -> ProductSpace`. I can certainly see why you would want it to also work for the cases `ProductSpace -> LinearSpace` and `LinearSpace -> ProductSpace`, but these are currently not supported. If you want to add them it would be useful I suppose.

**Comment by adler-j** [comment]
Bug part fixed in f3e0129cc0e815c073872e4e51eb4386c88d61f5

**Comment by adler-j** [comment]
Some further information on why this is not allowed. Basically it is the same reason as in #49, It causes much more code and testing complexity. If it is a requested feature I'm sure we could implement it.

**Comment by aringh** [comment]
Since it is not hard to work around, by simply doing something like `ProductSpace(rn, 1)`, it could be fine this way. But maybe this "work-around" could be added in the documentation or in the example somehow?

**Comment by adler-j** [comment]
Sure, feel free to add it under `Notes` in the documentation.

**Comment by adler-j** [comment]
Once more the coercion (embedding) operator issue #59 would come in handy here, with it, one could:

```python
ProductSpaceOperator([...]) * embed(ProductSpace(x.space), x.space)
```

**Comment by adler-j** [comment]
Doc updated in 79ffcca07756d9806f19ac8a8511b420a6a1d8fc, closing this issue now. Please open a new one if you want the option to project on a `LinearSpace`.

**Comment by aringh** [comment]
Looks good to me.

**Comment by aringh** [comment]
Or should the `close?` label be kept?

**Comment by adler-j** [comment]
Ehrm, never thought abot it, I suppose not.

**Comment by kohr-h** [comment]
No, when it's closed, it's closed. No more questions :-)
