### ISSUE TITLE
x.min() and x.max() for ODL elements

### ISSUE THREAD

**Issue by MatthiasJE** [odlgroup/odl#896]
I am trying to use ODL together with some code I wrote for another purpose and I came across the problem that my code does not know about ODL's structures (and I also don't want it to know to not be 100% dependent). In my code I wrote something like

```
>>> x.min()
>>> x.max()
```

which works fine on numpy arrays but is not supported on ODL structures. My idea was to extent ODL to this feature by extending `DiscretizedSetVector` like below. Is this a good choice or would you do this differently? The code (extended by the snippet below) works fine and to me it would be great if ODL was supporting all kind of numpy functionality like reshape, flatten, etc. Of course the output is then not necessarily an element of a function space any more.

```python
class DiscretizedSetVector(NtuplesBaseVector):
    ....
    def min(self):
        return self.ntuple.asarray().min()
    def max(self):
        return self.ntuple.asarray().max()
    ... 
```

Edit: @adler-j improved formatting.

**Comment by adler-j** [comment]
Great to hear that you are trying out ODL!

Regarding `min()` and `max()`, the best way is to use the free numpy functions "np.min(x)" and "np.max(x)", ODL knows how to work with them, so there is practically 0 overhead. This also allows your code to work with arbitrary data, not only ODL. See e.g. `[1, 2, 3].max()` vs `np.max([1, 2, 3])`. I would personally find doing this easier than your suggestion.

Regarding other numpy functionality, we do support some of it, but in general that is mostly done by calling the respective numpy function. I.e. the following works:

```python
>>> spc = odl.uniform_discr([0, 0], [1, 1], [2, 5])
>>> x = spc.zero()
>>> np.ravel(x)
array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])
```

If you truly want to work with a ODL vector as an array, you can always simply cast it to an array and then do what you want:

```python
>>> arr = np.asarray(x)  # no overhead, arr is the actual data container of x
>>> do_stuff_to_array(arr)  # x is modified in place
```

For a specific subset of numpy functions, the so called universal functions, we actually have built in support. For you, that likely makes only a minor difference, but in some cases it is needed (e.g. on product spaces, which numpy cannot support properly). To do that, you need to use the "ufuncs" functionality

```python
>>> minv = x.ufuncs.min()
0.0
```

You can read more here: https://odlgroup.github.io/odl/guide/numpy_guide.html#using-odl-vectors-with-numpy-functions. There is an effort to make any ODL vector (e.g. ProductSpaces, CUDA vectors, etc) work fully optimized with the free numpy functions, but sadly this has been delayed in numpy. You can read more here:  https://docs.scipy.org/doc/numpy-dev/neps/ufunc-overrides.html. Current status: https://github.com/numpy/numpy/pull/8247. See also ODL issue #225.
