### ISSUE TITLE
Diagnostics extremely slow on large data

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#90]
It seems the examples are not vectorized anymore, possibly related to the bug in issue #89. This causes the generation of realistic size example to take way to long. We need to fix this vectorization.

**Comment by kohr-h** [comment]
Yes, it's on my extended agenda until the beginning of December. I noticed that vectorization is completely off currently, but I didn't bother to make a quick fix for now. The large overhaul lags a bit behind, but I'll take it up asap.

**Comment by adler-j** [comment]
This would be quite nice to have since this bug renders the whole diagnostics package moot untill fixed.

**Comment by kohr-h** [comment]
Closed by #116
