### ISSUE TITLE
adding ODL elements with numpy arrays

### ISSUE THREAD

**Issue by MatthiasJE** [odlgroup/odl#900]
I am trying to add ODL elements with numpy arrays. Sometimes this works and sometimes is does not. I have not figured out when it should work and when it should not. From a computational point of view I would say it should always work if the dimensions match!

An example that does not work is:

```python
A = odl.BroadcastOperator(*listOps)
data = A(phantom)

for i in range(nSamples):
    data[i] += .1*np.random.randn(*data[i].shape)

```

which results in 

```
Traceback (most recent call last):

  File "<ipython-input-22-4c10ffba52cc>", line 6, in <module>
    data[i] += .1*np.random.randn(*data[i].shape)

  File "/home/ehrhardt/repositories/git_ODL/odl/set/space.py", line 523, in __iadd__
    ''.format(self, other))

TypeError: cannot add uniform_discr([0.0, 0.0], [1.0, 1.0], (128, 128), weighting='none').element([[0.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0],
 ...,
 [0.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0]]) and array([[-0.08350407, -0.02737384, -0.03786369, ...,  0.03008707,
         0.06871137,  0.02027193],
       [-0.07882959,  0.06028557, -0.10612426, ...,  0.031921  ,
         0.05032298,  0.14929735],
       [-0.11079299,  0.09026181, -0.15664159, ..., -0.05561518,
         0.03036444, -0.03668191],
       ..., 
       [-0.08704358, -0.15688478, -0.03112204, ...,  0.03760074,
        -0.03157461, -0.18668979],
       [ 0.06773552, -0.08604943, -0.03066653, ..., -0.03339932,
        -0.16292931, -0.05387972],
       [-0.09577363,  0.09608238, -0.00291216, ..., -0.1573153 ,
        -0.17913628, -0.13699507]]) in place
```

However, by changing it slightly to 

```python
A = odl.BroadcastOperator(*listOps)
data = A(phantom)

for i in range(nSamples):
    data[i] = data[i] + .1*np.random.randn(*data[i].shape)

```
I can make it work. 

In this example I would be fine with the second option, however, in some cases there might not be an easy workaround. Any ideas?

**Comment by adler-j** [comment]
In general we do not currently intend to support `array + vector`/`vector + array`, and actually already have a bug regarding this here #272 and further discussion here #319.

What you want to do in your case would be to do this

```python
for i in range(nSamples):
    data[i] += .1*data.space.element(np.random.randn(*data[i].shape))
```

Another option is to use the built in noise features

```python
for i in range(nSamples):
    data[i] += .1 * odl.phantom.white_noise(data[i].space)
```

**Comment by MatthiasJE** [comment]
To convince people of ODL it would be great if ODL was as compatible as possible with other code. Therefore, it is OK to have ODL outside of some other coded algorithms and convert there things into the right spaces, inside those algorithms you may not want to make changes such as x = data.space.element(x) just to be able to add two arrays. Wouldn't it be possible to define an addition of a space element x and a numpy array y as
    x + y := x + x.space.element(y)
This would allow my code to be run either with or without ODL. What do you think about this?

In case you don't like it, it might be worth thinking to create a space that is more flexible and allows this?

**Comment by adler-j** [comment]
It certainly would be possible to do what you say, and in fact @kohr-h has already proposed it here #319.

Making a more flexible space would not really be an option since it would cause a maintenance nightmare with two slightly different spaces (see the blunder with array vs matrix that numpy did long ago and still suffer from).

I'll get this done.

**Comment by adler-j** [comment]
There is now a PR that solves this #902, waiting for review.

**Comment by adler-j** [comment]
Fixed this, please try it out @MatthiasJE and see how you like it!

**Comment by MatthiasJE** [comment]
Works fine! No problems whatsoever. Thanks!
