### ISSUE TITLE
Future.str crashes with py.test

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#91]
If we do `from builtins import str`, which we now seem to do pretty much everywhere, the following crashes:

```python
if __name__ == '__main__':
    pytest.main(str(__file__.replace('\\', '/') + ' -v'))
```

this stops us from running our tests individually in a simple way.

**Comment by kohr-h** [comment]
Simply remove `str`? (and the import)

**Comment by adler-j** [comment]
`str` is needed for some reason on some platforms.
