### ISSUE TITLE
About the MRC read_extended_header

### ISSUE THREAD

**Issue by chongchenmath** [odlgroup/odl#913]
If use

```extended_header = reader.read_extended_header(force_type='FEI1')```,

we can read the FEI type MRC data successfully. 

But there exists a problem as follows: each key has the same size (1024) array, and using zero to pad the surplus elements. This is not right. For example, the 'a_tilt' should be a 151 size array.

```
for key, value in extended_header.items():
    print(key, value)

('a_tilt', array([[-74.99828339],
       [-73.99934387],
       [-72.99943542],
       ..., 
       [  0.        ],
       [  0.        ],
       [  0.        ]], dtype=float32))
('b_tilt', array([[ 0.],
       [ 0.],
       [ 0.],
       ..., 
       [ 0.],
       [ 0.],
       [ 0.]], dtype=float32))
('x_stage', array([[ 0.],
       [ 0.],
       [ 0.],
       ..., 
       [ 0.],
       [ 0.],
       [ 0.]], dtype=float32))
('y_stage', array([[ 0.],
       [ 0.],
       [ 0.],
       ..., 
       [ 0.],
       [ 0.],
       [ 0.]], dtype=float32))
('z_stage', array([[ 0.],
       [ 0.],
       [ 0.],
       ..., 
       [ 0.],
       [ 0.],
       [ 0.]], dtype=float32))
('x_shift', array([[ 0.],
       [ 0.],
       [ 0.],
       ..., 
       [ 0.],
       [ 0.],
       [ 0.]], dtype=float32))
('y_shift', array([[ 0.],
       [ 0.],
       [ 0.],
       ..., 
       [ 0.],
       [ 0.],
       [ 0.]], dtype=float32))
('defocus', array([[  1.54988993e-06],
       [  1.53229155e-06],
       [  1.68305257e-06],
       ..., 
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  0.00000000e+00]], dtype=float32))
('exp_time', array([[ 6.],
       [ 6.],
       [ 6.],
       ..., 
       [ 0.],
       [ 0.],
       [ 0.]], dtype=float32))
('mean_int', array([[ 4807.84960938],
       [ 4837.09033203],
       [ 4885.26855469],
       ..., 
       [    0.        ],
       [    0.        ],
       [    0.        ]], dtype=float32))
('tilt_axis', array([[ 0.],
       [ 0.],
       [ 0.],
       ..., 
       [ 0.],
       [ 0.],
       [ 0.]], dtype=float32))
('pixel_size', array([[  5.20956445e-10],
       [  5.20956445e-10],
       [  5.20956445e-10],
       ..., 
       [  0.00000000e+00],
       [  0.00000000e+00],
       [  0.00000000e+00]], dtype=float32))
('magnification', array([[ 225000.],
       [ 225000.],
       [ 225000.],
       ..., 
       [      0.],
       [      0.],
       [      0.]], dtype=float32))
('ht', array([[ 200000.],
       [ 200000.],
       [ 200000.],
       ..., 
       [      0.],
       [      0.],
       [      0.]], dtype=float32))
('binning', array([[ 2.],
       [ 2.],
       [ 2.],
       ..., 
       [ 0.],
       [ 0.],
       [ 0.]], dtype=float32))
('applied_defocus', array([[ 0.],
       [ 0.],
       [ 0.],
       ..., 
       [ 0.],
       [ 0.],
       [ 0.]], dtype=float32))
```

**Comment by adler-j** [comment]
As usual, this is very hard to debug without further information, including a minimal working example. Thus we need access to the data that causes this bug.

Anyway, with the disclaimer that I've never worked with any of this, it seems the current behaviour is in line with the standard. Specifically [it says](http://www.2dx.unibas.ch/documentation/mrc-software/fei-extended-mrc-format-not-used-by-2dx):

> The extended header is thus 1024 * 128 bytes (always the same length, regardless of how many images are present.)

We could ofc try to be more intelligent here and only return the exact number of angles that were actually used, but that is more of a design question. What do you think @kohr-h?

**Comment by kohr-h** [comment]
I think we should stick to the specification since it explicitly says it. I'd go for a helper that crops the arrays to the number of tilt angles.
That helper would look roughly like this:
```python
def trimmed_ext_header(ext_header, num_tilts):
    trimmed = {}
    for k, v in ext_header.items():
        trimmed[k] = v[:num_tilts]
    return trimmed
```
Or simply trim the arrays that you need, e.g., `magnifications = extended_header['magnification'][:num_tilts]`.

**Comment by adler-j** [comment]
My suggestion would be to instead add a utility that takes mrc data as input and gives an odl geometry as output. That would save regular users from having to deal with stuff like this.

**Comment by kohr-h** [comment]
That's not doable using MRC data only, since it doesn't have enough information to create the geometry. There you see how crappy the file format really is.

**Comment by adler-j** [comment]
How about with the extended header?

**Comment by kohr-h** [comment]
There it's possible I guess. Not sure about the tilt axis, perhaps it's hard-coded.

**Comment by adler-j** [comment]
Well to put my question this way: What the \*f\* is the format for then? Do we have a single example of using it somewhere? How would that look?

**Comment by kohr-h** [comment]
Looking at the spec, the extended header actually has a field `TILT_AXIS` but it's defined with respect to the projections. Should be sufficient anyway.



> Well to put my question this way: What the *f* is the format for then? Do we have a single example of using it somewhere? How would that look?

The best answer I can come up with is that it's the standard format in EM/ET, which says a lot. Anyway, given the above I think it would actually be doable to make an example/function that takes an MRC file and outputs a geometry (and data).

**Comment by adler-j** [comment]
Ok, so this highlights the need for #914 even more. Except for that, I suggest we close this issue with the comment that the current behaviour is according to the standard, regardless if we disagree with it.

OK?

**Comment by ozanoktem** [comment]
> That's not doable using MRC data only, since it doesn't have enough information to create the geometry. There you see how crappy the file format really is.

I think the [FEI extended MRC](http://www.2dx.unibas.ch/documentation/mrc-software/fei-extended-mrc-format-not-used-by-2dx) and the [MRC 2014](http://www.sciencedirect.com/science/article/pii/S104784771500074X) formats are complete enough so that one may uniquely generate the parallel beam geometry in question. The older version, such as [this one](http://www.2dx.unibas.ch/documentation/mrc-software/mrc-file-format-specifications), is not complete enough.

**Comment by kohr-h** [comment]
MRC2014 in itself doesn't explicitly define all geometry parameters, that's what the extended header adds, among other parameters.

Anyway, I'll close this.
