### ISSUE TITLE
Unused variables in mrc_header_from_params

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#916]
A quick look with Spyder shows this:

![mrc](https://cloud.githubusercontent.com/assets/2202312/23024602/4a540a88-f45b-11e6-97e2-f7d17b17d6a1.png)

where all the yellow lines are unused variables. This clearly has to be an error on our side and should be fixed.

**Comment by kohr-h** [comment]
It's not an error. Spyder doesn't understand the `eval` thing coming later.

**Comment by adler-j** [comment]
Oh god, eval :/

**Comment by adler-j** [comment]
Well then the issue is to get rid of eval :D

**Comment by kohr-h** [comment]
We had that discussion in the PR for this stuff. To some extent I agree that `eval` is not great, but it saves about 20 lines of totally annoying code [here](https://github.com/odlgroup/odl/blob/05873fdc6e1bd8769135608ce871ef46b19cf8a4/odl/tomo/data/mrc.py#L816-L818).

**Comment by adler-j** [comment]
Frankly I'd prefer those 20 annoying lines since the current code is very error prone and breaks the style guide quite miserably. Not an emergency however.

**Comment by adler-j** [comment]
Closing this for now then, but still a bit grumpy.
