### ISSUE TITLE
More specific exceptions

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#92]
Currently we almost only use `TypeError` (a bit too much IMO, we have to check) and `ValueError` (for anything else). We should create our own exceptions (not too many) and be more specific. That way, we could also cut down on the length of error messages. I suggest (parentheses mean parent)

- `ODLImportError(ImportError)` - see [this usage example](https://github.com/odlgroup/odl/commit/3c3e00f6ee2b0de8bdd33eb1bcc2f91b1adfbe7f#commitcomment-14636076)
- `OpDomainError(ValueError)` - when an argument is not in the domain  of an operator
- `OpRangeError(ValueError)` - when an argument is not in the range  of an operator
- `OpAttrError(NotImplementedError)` - when derivative, adjoint etc. are not defined. Not sure about that, could interfere with methods being recognized as "sort of abstract"
- ...

**Comment by adler-j** [comment]
I'm OK with this. By inheriting from the standard library we can ensure that things work as before with old code. All your examples are OK.

**Comment by kohr-h** [comment]
I would also add something like an `ElementError` which is specifically raised by the `element()` methods of spaces so it becomes easier to catch in the duck-typed operator call pattern, see #100. Currently it's hard to catch errors in `element()` without catching too much.

Alternatively we could just let the exception in `element()` pass through at the expense of exactness in the error messages on `Operator.__call__()`.

**Comment by adler-j** [comment]
`ElementError` could be hard since we'd need to require users to use it aswel. I'd simply let it pass through.

**Comment by kohr-h** [comment]
That was my second thought, too, when I wrote this. Better to let it propagate then.

**Comment by adler-j** [comment]
Adding a branch on this, just one thing: `ODLImportError(ImportError)`. I dont see any place to use this (we don't propagate errors anymore). So we drop it?

**Comment by kohr-h** [comment]
That's right. We handle missing imports differently now, so we don't need a specific exception there.
