### ISSUE TITLE
uniform_discr() missing 3 required positional arguments

### ISSUE THREAD

**Issue by rshpeley** [odlgroup/odl#932]
I'm trying to get this [code example](https://gist.github.com/adler-j/e9eddcf4ef919042a72178e523429142) working like [this one](https://github.com/astra-toolbox/astra-toolbox/issues/38), but I get an error from reco_space = odl.uniform_discr()

    TypeError: uniform_discr() missing 3 required positional arguments: 'min_pt', 'max_pt', and 'shape'

I'm on an ubuntu server with gpu, jupyter notebook, python 3.6.0 and recently installed odl and astra from conda.

**Comment by adler-j** [comment]
The example in question has been updated, we did some renames with issue issue #452 that broke this example. Thank you for informing us.

I'm posting the new code here for your convenience:

```python
import odl
import numpy as np

# Discrete reconstruction space: discretized functions on the rectangle
# [-20, 20]^2 with 300 samples per dimension.
reco_space = odl.uniform_discr(
    min_pt=[-1, -1], max_pt=[1, 1], shape=[256, 256])

# Make a parallel beam geometry with flat detector

# Angles: uniformly spaced, n = 180, min = 0, max = pi
angle_partition = odl.uniform_partition(0, np.pi, 180)

# Detector: uniformly sampled, n = 256, min = -1.152, max = 1.152
detector_partition = odl.uniform_partition(-1.152, 1.152, 256)
geometry = odl.tomo.Parallel2dGeometry(angle_partition, detector_partition)

# Create a discrete Shepp-Logan phantom (modified version)
phantom = odl.phantom.shepp_logan(reco_space, modified=True)

# ray transform aka forward projection. We use ASTRA CUDA/CPU backend.
ray_trafo = odl.tomo.RayTransform(reco_space, geometry, impl='astra_cuda')
ray_trafo_cpu = odl.tomo.RayTransform(reco_space, geometry, impl='astra_cpu')

# Create projection data by calling the ray transform on the phantom
proj_data = ray_trafo(phantom)
proj_data_cpu = ray_trafo_cpu(phantom)

# Back-projection can be done by simply calling the adjoint operator on the
# projection data (or any element in the projection space).
backproj = ray_trafo.adjoint(proj_data)
backproj_cpu = ray_trafo_cpu.adjoint(proj_data_cpu)

# Shows a slice of the phantom, projections, and reconstruction
phantom.show(title='Phantom')
proj_data.show(title='cuda sinogram')
backproj.show(title='cuda backprojection')
proj_data_cpu.show(title='cpu sinogram')
backproj_cpu.show(title='cpu backprojection')
(proj_data_cpu - proj_data).show(title='diff sinogram')
(backproj_cpu - backproj).show(title='diff backprojection')
```

This runs on my machine. Please inform us when you have tried the example so we can close this issue, and please ask if you have further questions.

**Comment by rshpeley** [comment]
I tried it, and `reco_space = odl.uniform_discr()` now completes. But now I get only the `diff backprojection` plot. There are no other errors so this is a silent failure.

I'm pretty sure astra gpu code is working, but I'll recheck that.

**Comment by rshpeley** [comment]
I tried `s003_gpu_reconstruction.py` from astra-toolbox/samples/python and the gpu code is working...

**Comment by kohr-h** [comment]
> I tried it, and reco_space = odl.uniform_discr() now completes. But now I get only the diff backprojection plot. There are no other errors so this is a silent failure.

That could be a matplotlib thing. Are you running in an IDE (Spyder) or on the terminal? Depending on that, figures may not be shown instantly. You can force that by adding the `force_show=True` option to the `show` calls.

**Comment by rshpeley** [comment]
Ok. I just tried separating out each `show` line in the notebook. This picks up all of the plots, so it appears as though the plots are overwritten in a jupyter notebook. I'd say this issue is closed, but probably the last problem should be addressed in another issue?

I use a jupyter notebook mostly because I run remotely from a gpu server instance.

Thanks for your quick response!

**Comment by kohr-h** [comment]
> I'd say this issue is closed, but probably the last problem should be addressed in another issue?

What other issue are you referring to?

> I use a jupyter notebook mostly because I run remotely from a gpu server instance.

Ah yes, I think there is some matplotlib manipulation going on there as well.

**Comment by rshpeley** [comment]
Yeah, `force_show=True` did it. Thanks!

btw, any options to save the images to files, or better yet break out the image data? I need to compose my own images and save them to files.

**Comment by kohr-h** [comment]
> btw, any options to save the images to files

That's possible: You can use the `saveto='filename'`, it will work just as the matplotlib option. In general, any keyword argument that is not consumed by the `show` method itself is passed on to the matplotlib drawing function, so for images you can use things like `clim` and `cmap` transparently.



> or better yet break out the image data

Also yes: `np.asarray(x)` gives you the Numpy array corresponding to the ODL object. Most of the time (when Numpy is used as array storage, which is the default), this operation is basically for free since it just returns the raw Numpy array.


I'll close this, but don't feel forced to stop asking questions ;-)

**Comment by rshpeley** [comment]
To be clear, all the plots showed up on the notebook after `force_show=True`, but the aspect ratio of the images are off. The phantoms are more circular than the plots [here](https://github.com/astra-toolbox/astra-toolbox/issues/38).

```python
# Shows a slice of the phantom, projections, and reconstruction
phantom.show(title='Phantom', force_show=True)
proj_data.show(title='cuda sinogram', force_show=True)
backproj.show(title='cuda backprojection', force_show=True)
proj_data_cpu.show(title='cpu sinogram', force_show=True)
backproj_cpu.show(title='cpu backprojection', force_show=True)
(proj_data_cpu - proj_data).show(title='diff sinogram', force_show=True)
(backproj_cpu - backproj).show(title='diff backprojection')
```
The last one repeats if the `force_show=True` option is set.

**Comment by rshpeley** [comment]
Thanks for the info! I'll start a new issue for another question I have.

**Comment by kohr-h** [comment]
Cool. As an answer to your comment above about aspect ratios, the `show` method uses `aspect='auto'` because (at the time of writing) it was the only way to get matplotlib to respect the actual sizes of the axes, which are given by the "physical" sizes of the space. It's possible that notebooks manipulate that setting, but that's only a guess.

In the end, if you really want fully customized plots, it's better to use matplotlib directly. The ODL `show` method is just convenience and some real-time plotting during iteration, but it doesn't solve all problems equally well.
