### ISSUE TITLE
.adjoint creates an object every time?

### ISSUE THREAD

**Issue by MatthiasJE** [odlgroup/odl#939]
Does op.adjoint create an object every time? In most cases this is not an issue because creating the object is cheap. However, sometimes the constructor should do some extra work that only needs to happen once. Is there an easy way how to do this without breaking the principles of ODL (adjoint is a property etc)

**Comment by kohr-h** [comment]
If this becomes a bottleneck, which is not unlikely, you can also compute the adjoint at initialization time and store it, then in `adjoint` just return the stored value.
```python
# in operator
def __init__(self, ...):
    # other stuff
    self.__adjoint = ExpensiveToComputeAdjoint(...)

@property
def adjoint(self):
    return self.__adjoint
```
In some sense it's not nice either that creating an operator is expensive, but it's still better than having an expensive property, since the syntax `obj.property` in some way indicates that it's cheap to get the property.

**Comment by MatthiasJE** [comment]
Yes, this is what I would do, too. I thought this breaks a bit with the syntax as now "adjoint" is both private and public?

**Comment by kohr-h** [comment]
> Yes, this is what I would do, too. I thought this breaks a bit with the syntax as now "adjoint" is both private and public?

Well, from the outside it looks identical, so I wouldn't say it's more private necessarily. The purely public alternative would be to directly store `self.adjoint = ...`. But this has 1 1/2 drawbacks:
1. There is no way to document `adjoint`.
2. (depends on taste) `adjoint` can be overwritten in instances, i.e. you could do `op.adjoint = None`, which is forbidden with the current implementation.

**Comment by adler-j** [comment]
Well, the problem with adjoint being both public and private is mostly fine, given that Operators in ODL are (at least supposed to be) immutable. Hence, even if you "share" an instance of your operator to someone else, that person shouldn't be able to ruin the operator for you, and hence there is no risk.

For an example of where we do this, see [RayTransform.adjoint](https://github.com/odlgroup/odl/blob/bd9e4c5c78057407e6189af90fc050d62c7f3175/odl/tomo/operators/ray_trafo.py#L230-L247).

**Comment by adler-j** [comment]
Are we happy with this issue and can close it, or did you have any more questions?

**Comment by MatthiasJE** [comment]
Happy :)
