### ISSUE TITLE
all_equal causes infinite recursions with strings

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#94]
Since each element of a string is itself a lenght-1 string, the recursion in `all_equal` never stops. These functions need a break point for strings.

**Comment by adler-j** [comment]
Dislike the current fix, it has quite heavy overhead (tries to stringify in each sub-step). Is there not faster way?

**Comment by kohr-h** [comment]
Instance checks don't work, they also recurse indefinitely.

**Comment by kohr-h** [comment]
Hm, maybe they do.

**Comment by kohr-h** [comment]
Okay, one can use `isinstance(iter1, basestring)`, done in 781381058fc596a7dcf161f4229585f2d662c1eb. But we have to keep an eye on this, seems quite fragile with respect to the differences in Py2 and Py3. Not the instance check, but the truth value at the end.
