### ISSUE TITLE
save and load ODL objects

### ISSUE THREAD

**Issue by MatthiasJE** [odlgroup/odl#945]
How are ODL objects to be stored and loaded? I tried the following which does not work:

```
import numpy as np
import odl

X = odl.uniform_discr(min_pt=[-1, -1], max_pt=[1, 1], shape=[128, 128])
phantom = odl.phantom.shepp_logan(X, modified=True)
np.save("data.npy", phantom )
phantom = np.load("data.npy")
```

phantom before loading:
```
Out[2]: 
uniform_discr([-1.0, -1.0], [1.0, 1.0], (128, 128)).element([[0.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0],
 ...,
 [0.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0]])
```
phantom after loading
```
Out[4]: 
array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

```
Any ideas?

**Comment by kohr-h** [comment]
Well, the `np.save` function extracts the array and stores it, no matter what implementation ODL uses under the hood. So when loading again, you get the array. The simplest approach here would be to just call `X.element()` on the loaded array again.

In the long run, we want to be able to pickle the object using `pickle.dump()` and `pickle.load()`, which is the standard Python way of storing objects on disk and loading them again. You could try them as-is, but for better efficiency we need to implement the `__getstate__` and `__setstate__` methods.
See [here](https://docs.python.org/3.5/library/pickle.html) for the documentation of `pickle`.

**Comment by kohr-h** [comment]
I'll close this, since the "proper" solution requires more work and will probably pop up sometime in the future, with a dedicated issue then.
