### ISSUE TITLE
GroupL1Norm gradient not implemented for product spaces

### ISSUE THREAD

**Issue by aringh** [odlgroup/odl#950]
I get the following error when I want to take the gradient of the `GroupL1Norm`.
```
>>> import numpy as np
>>> import odl
>>> reco_space = odl.uniform_discr(0,1,10)
>>> grad = odl.Gradient(reco_space)
>>> l1 = odl.solvers.GroupL1Norm(grad.range)
>>> x = reco_space.element(lambda x: x**2)
>>> (l1 * grad).gradient(x)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/aringh/git/odl/odl/operator/operator.py", line 695, in __call__
    out = self._call_out_of_place(x, **kwargs)
  File "/home/aringh/git/odl/odl/solvers/functional/functional.py", line 577, in _call
    return op.derivative(x).adjoint(func.gradient(op(x)))
  File "/home/aringh/git/odl/odl/operator/operator.py", line 695, in __call__
    out = self._call_out_of_place(x, **kwargs)
  File "/home/aringh/git/odl/odl/solvers/functional/default_functionals.py", line 305, in _call
    np.divide(x, result, out=result, where=result != 0)
TypeError: return arrays must be of ArrayType
```
Is this a bug, or am I making a logical mistake here?

Trying to make the example somewhat smaller still produces the error:
```
>>> y = grad(x)
>>> l1.gradient(y)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/aringh/git/odl/odl/operator/operator.py", line 695, in __call__
    out = self._call_out_of_place(x, **kwargs)
  File "/home/aringh/git/odl/odl/solvers/functional/default_functionals.py", line 305, in _call
    np.divide(x, result, out=result, where=result != 0)
TypeError: return arrays must be of ArrayType
```

**Comment by kohr-h** [comment]
That's an actual bug: `result` is an ODL vector also after taking `np.abs` or whatever, and it's not valid as `out` parameter in a Numpy ufunc.
The lines that use `out=result` must be changed to
```python
with writable_array(result) as result_arr:
    np.something(..., out=result_arr)
```
The `writable_array` comes from `odl.util`.
Can you go fix that @aringh? Apparently we have no test for it, can you do that, too? Seems like you have already done it in some sense.

**Comment by aringh** [comment]
I can fix it :-) But I'm currently not in the office, so it will probably take a little more than a week before I can get it done.

**Comment by kohr-h** [comment]
No problem, you're assigned now :-)

**Comment by aringh** [comment]
Am I wrong if I think that the group L1 norm is the same as composing the pointwise norm and the L1 norm? For `exponent = 2` I get the same result, but not for any other exponent.

I changed the last of the three cases in the [last of the three cases](https://github.com/odlgroup/odl/blob/master/odl/solvers/functional/default_functionals.py#L307-L312) to
```
                    to_return = self.domain.element()
                    dividend = np.power(np.abs(x), p - 2) * x
                    divisor = np.power(functional.pointwise_norm(x), p - 1)
                    for i in range(x.size):
                        with writable_array(to_return[i]) as ret_arr:
                            np.divide(dividend[i], divisor, out=ret_arr,
                                      where=divisor != 0)
                    return to_return
```
which seems to do the job when it comes to not crashing. However the output from the following lines of code is note the same for the two gradients. What am I doing wrong?

```
import odl
import numpy as np
space = odl.uniform_discr(0,1,10)
prod_space = odl.ProductSpace(space, 3)

l1 = odl.solvers.L1Norm(space)
pnorm = odl.PointwiseNorm(prod_space, exponent=2.4)
func_to_compare = l1 * pnorm

group_l1 = odl.solvers.GroupL1Norm(prod_space, exponent=2.4)

x = odl.util.testutils.noise_element(prod_space)
func_to_compare(x)
group_l1(x)

func_to_compare.gradient(x)
group_l1.gradient(x)
```
 Moreover, I guess that the [derivative of the Pointwise norm](https://github.com/odlgroup/odl/blob/master/odl/operator/tensor_ops.py#L351-L352) should be safe-guarded in a similar manner, no? Change for something like this? Or is this the root of the problem?
```
        for gi in inner_vf:
            tmp = vf_pwnorm_fac * gi ** (self.exponent - 2)
            gi = np.divide(gi, tmp, where=tmp != 0)
```

**Comment by kohr-h** [comment]
One apparent problem with the current code is that it's safeguarded only in one of the two places where it can fail. The other part that gives invalid values is already encountered in the line
```python
dividend = np.power(np.abs(x), p - 2) * x
```

Generally, I'm skeptical towards safeguarding all these calls. As @adler-j reported, using the `where` parameter of ufuncs makes them very slow compared to the unguarded version. It's probably faster to just run the code, silence the warnings and fix the mess afterwards by replacing the NaN values with something (e.g. 0):
```python
with np.errstate(invalid='ignore', divide='ignore'):
    # do invalid stuff
    # divide by zero
# fix result by replacing NaNs
```

With that said, I think the code you posted @aringh *should* yield the same result, given they both implement the same functionality.
Have you tried running both derivatives through diagnostics? Perhaps one of the implementations is simply wrong?

**Comment by adler-j** [comment]
Any update on this?

**Comment by aringh** [comment]
No... this has been "dormant" since my previous comment on this

**Comment by aringh** [comment]
There is a [branch](https://github.com/aringh/odl/branches) on my fork now. I thought I had pushed it earlier, but apparently not

**Comment by aringh** [comment]
The group L1-norm is basically `L1Norm * pnorm`, which is more or less also how [it is implemented](https://github.com/odlgroup/odl/blob/master/odl/solvers/functional/default_functionals.py#L242-L249). Moreover, to the best of my knowledge the gradient, evaluated in a point `f`, of a functional `F` composed with an operator `A`  is

```(F * A)'(f) = A.derivative(f).adjoint(F.gradient(A(f)))```.

Is there a good reason why the gradient of the `GroupL1Norm` should not just be implemented in this way?

**Comment by adler-j** [comment]
> Is there a good reason why the gradient of the GroupL1Norm should not just be implemented in this way?

Performance, I guess. But I'd have to look at it further to determine if it is actually the case.

I'd be much more in favor of simply changing to that implementation if it is faster for you to do. I much prefer correctness over performance.
