### ISSUE TITLE
Submodule for "non-optimal code"

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#951]
Several libraries have a core library, and some place where external contributors can place their code for sharing, but not for maintanance by the core crew.

* Eigen does this with [Eigen.unsupported](https://eigen.tuxfamily.org/dox/unsupported/index.html)
* Tensorflow does it with [Tensorflow.contrib](https://www.tensorflow.org/api_docs/python/tf/contrib)

I feel by doing this has two big uppsides:

* We reduce the threshold for community contributions (E.g. not everyone is as brave as @MatthiasJE and @aringh in braving our 100 comment+ reviews).
* We can let this module "swell" with application specific stuff, without clogging the main library.

How do we feel about this?

**Comment by MatthiasJE** [comment]
I like this idea a lot. However, one should consider from time to time to maybe put some of the "unsupported" code into the main library if it is well written, documented and useful to many others.

**Comment by adler-j** [comment]
> I like this idea a lot. However, one should consider from time to time to maybe put some of the "unsupported" code into the main library if it is well written, documented and useful to many others.

Agree, hence we could aim for a structure that is parallel to the main library structure, e.g. if you add a solver, it would go under `odl.contrib.solvers.YourFancySolver`, that way, moving it into the main library would be very simple and intuitive for users.

I also agree with @kohr-h:s suggestions.

So any idea bout what such a package would be named? `contrib`?

**Comment by kohr-h** [comment]
`contrib` sounds good to me.

**Comment by kohr-h** [comment]
> Agree, hence we could aim for a structure that is parallel to the main library structure, e.g. if you add a solver, it would go under odl.contrib.solvers.YourFancySolver, that way, moving it into the main library would be very simple and intuitive for users.

I'm not so sure about this part. It basically means that somebody has to maintain the whole thing again. In particular, when we get a PR and want to "just merge", we want to be sure that the new addition doesn't break everything else in `contrib`, e.g. by not being importable.

So IF we mirror the main package structure in some sense, i.e., make a parallel package where people put their experimental code, we cannot do that without a maintainer.
The other solution is to have everything compartmentalized, either per contributor or into small sub-packages, I don't care. Just that people don't step on each others' toes. That would be very close to making a separate repository, with main differences being (1) things are more visible in main and (2) we get to see each contribution - although that could also be done with a separate repo.

**Comment by kohr-h** [comment]
> So IF we mirror the main package structure in some sense, i.e., make a parallel package where people put their experimental code, we cannot do that without a maintainer.

Hm, on the other hand, that can easily be checked by Travis.

**Comment by adler-j** [comment]
This is done.
