### ISSUE TITLE
Show slice of 3D volume using CallbackShow

### ISSUE THREAD

**Issue by chongchenmath** [odlgroup/odl#953]
It seems that the ``CallbackShow`` cannot show the slice of 3D volume that we want to see.

**Comment by adler-j** [comment]
We need much more detail here. What do we want to see? Please provide a [minimal working example](http://stackoverflow.com/help/mcve).

**Comment by chongchenmath** [comment]
It is not easy for me to give an example. 

For 3D case, the default ``CallbackShow`` is to show the middle slice orthogonal to Z axis . For instance, if I want to show any slice orthogonal to X axis, how to set it?

**Comment by adler-j** [comment]
You use the `coords` argument to show, i.e.

```python
space = odl.uniform_discr([-20, -20, -20], [20, 20, 20], shape=(256, 256, 256))
callback = odl.solvers.CallbackShow(coords=[0, None, None])
callback(space.zero())
```

**Comment by chongchenmath** [comment]
Solved! Thank you.
