### ISSUE TITLE
Change ODL licence to Mozilla Public License, version 2.0

### ISSUE THREAD

**Issue by ozanoktem** [odlgroup/odl#967]
Bearing in mind the discussions we have had with partners, we should change the ODL licence from the current one, which is [GNU General Public License v3.0](http://www.gnu.org/licenses/gpl-3.0.en.html), to [Mozilla Public License, version 2.0](http://www.mozilla.org/en-US/MPL/2.0/). The motivation for choosing such a weak copyleft license are the following:

- We welcome commercial usage of ODL and want to minimize obstacles for such usage.
- We appreciate others forking and improving our work.
- We want to prevent license-incompatible forks of ODL, be it proprietary versions or versions under a stronger copyleft license.

Due to the last point, permissive licenses are of less interest, and the first point excludes strong copyleft licenses like GPL.

**Comment by MatthiasJE** [comment]
I am OK with the change of license.

**Comment by aringh** [comment]
I am Ok with this change of licence under which ODL is distributed.

**Comment by kohr-h** [comment]
For the record, I'm OK, too.

**Comment by chongchenmath** [comment]
Okay for me, too.

**Comment by niinimaki** [comment]
The license change is OK for me too.

**Comment by moosmann** [comment]
I'm OK with the license change, too.

**Comment by adler-j** [comment]
Fine with me

**Comment by wjp** [comment]
OK for me.

**Comment by kohr-h** [comment]
Missing @hilding79 here

**Comment by hilding79** [comment]
Ok for me.

**Comment by kohr-h** [comment]
Yay!
