### ISSUE TITLE
Using the latest numpy

### ISSUE THREAD

**Issue by adler-j** [odlgroup/odl#98]
I found out that we require numpy 1.9 (requirements said 1.8, not updated). This issue is two parted:

* We should be carefull in always using the latest, forcing users to install "the latest sexy" will cause quite some trubble since many users want to simply use "whats out of the box". My recommendation is that we try to not use things later than whats available in `aptitude` and other binary distributions.

* Second, we should add a FAQ post on how to install the require python libs.

**Comment by kohr-h** [comment]
> I found out that we require numpy 1.9 (requirements said 1.8, not updated).

Where do we do that? This is a mistake. I think, on the contrary, that we should require the oldest version which works and switch only if we desperately need new functionality and the version we need has hit the mainstream package repos.

> Second, we should add a FAQ post on how to install the require python libs.

This and write a general advice how to handle `pip` installs. I can write a small `virtualenv` tutorial on how to safely install all requirements by `pip`.

**Comment by adler-j** [comment]
>Where do we do that? This is a mistake. I think, on the contrary, that we should require the oldest version which works and switch only if we desperately need new functionality and the version we need has hit the mainstream package repos.

We apparently use `linspace` with the `dtype` option. If you remove that I suppose we could (somehow) try with that version. perhaps we can configure travis to use a specfic version.

>This and write a general advice how to handle pip installs. I can write a small virtualenv tutorial on how to safely install all requirements by pip.

Please do a short text on that. It would be useful.
