### ISSUE TITLE
Stochastic version of the Chambolle-Pock method

### ISSUE THREAD

**Issue by ozanoktem** [odlgroup/odl#985]
We should consider implementing a recently proposed Stochastic Primal-Dual Hybrid Gradient Method (SPDHG) outlined [here](http://arxiv.org/abs/1706.04957), which would be a stochastic version of the [ODL Primal-Dual Hybrid Gradient (PDHG) algorithm](https://github.com/odlgroup/odl/blob/f58dfedc323d8c4219dfe25d7eecb595009a8930/odl/solvers/nonsmooth/chambolle_pock.py). 

SPDHG combines the PDHG method with a randomized dual decomposition strategy (somewhat reminiscent of ART, Kaczmarz, and OSEM, which operate in the primal) and PDHG arises as a special (and suboptimal) case of SPDHG. Authors prove convergence for a wide range of random samplings and they prove  rigorous iteration complexity bounds for standard and accelerated variants.

**Comment by adler-j** [comment]
Reference available here: https://arxiv.org/abs/1706.04957

**Comment by adler-j** [comment]
@MatthiasJE are you doing this right now? Because I could really use this when working on my 3D data!

**Comment by MatthiasJE** [comment]
It is on my to-do list for the next two weeks. I hope you don't need it really urgently?

**Comment by adler-j** [comment]
No-no it's not that bad, but it sure would help :)
