### ISSUE TITLE
Restrict uniformity requirement of operators to affected axes

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#993]
A  bunch of operators, most significantly `FourierTransform` and `ResizingOperator`, require that their domains be uniformly discretized throughout. However, they should also work if the domain is uniformly discretized only in the axes where something happens. For the above two examples, the FT has an `axes` argument where it's easily determined, and for resizing, one can simply check the shapes that remain the same.
There are probably other operators with the same issue.

**Comment by adler-j** [comment]
This is a partial duplicate of #671, I propose we close it and use this instead to coordinate.

**Comment by kohr-h** [comment]
Okay
