### ISSUE TITLE
Allow empty grids and partitions

### ISSUE THREAD

**Issue by kohr-h** [odlgroup/odl#994]
Currently it's not possible to create grids or partitions with 0 dimensions. That would be useful for cases where they are built up axis by axis, e.g. when mixing uniform and non-uniform axes. Then one should be able to start from something empty and append to it.

**Comment by adler-j** [comment]
I agree. An obvious followup is if we want to allow it as the domain of `uniform_discr` etc?

**Comment by kohr-h** [comment]
> An obvious followup is if we want to allow it as the domain of uniform_discr etc?

That gives problems with the weights, assuming that `cell_volume` should be `0.0` for empty partitions. We could just set the weight to 1 in that case.
